python/peps

.hgignore
Was this really such a low-hanging fruit or did I miss something? I'm not a mercurial expert so I can't really tell but couldn't resist to not do it also.
Refs. #6 
:beers:
=> Remove hgignore and hgtags file

pep-0006.txt
I had to tweak this one by hand a bit.
=> Restify PEP-6

pep-0003.txt
Similar to #16:
You can use `git diff origin/master --word-diff --ignore-all-space` to see the differences.
=> Restify PEP-3

pep-0005.txt
Like #16 and #20, as usual `git diff origin/master --word-diff --ignore-all-space`.
=> Restify PEP-5

pep-0001.txt
Please review @berkerpeksag  / @brettcannon.
=> Update PEP VCS References. Point to the github repository.

pep-0252.txt, pep-0253.txt, pep-0367.txt, pep-3135.txt
Just as the title, while reading these PEPs, find a few typos, fix them.
=> fix a few typos of PEP 252, 253, 367, 3135

pep-0299.txt
As usual, the diff is not that big, but the rewrap of lines make it hard to vien on GitHub.
=> Convert pep-299 to rst.

pep-0487.txt
This adds the changes proposed by Guido at 
https://mail.python.org/pipermail/python-dev/2016-July/145606.html
=> Update PEP 487

pep-0487.txt
This clarifies PEP 487 and makes it more readable.
=> Clarify PEP487

pep-0514.txt
=> PEP-514 acceptance

pep-0520.txt
=> PEP 520: Remove duplicate word 'namespace'

pep-0008.txt, pep-0484.txt
@gvanrossum please review.
Since it is proposed to also add something to PEP 8 @warsaw is also invited to review.
=> [WIP] Semantics of variance in type variables and notation conventions

pep-0526.txt
This PR is a work in progress, but we may want to merge it just to reserve the PEP number.
=> PEP 0526 -- variable declarations

pep-0526.txt
Not ready for general review!!! Use this PR for minor textual nits; for comments on substance, use https://github.com/python/typing/issues/258.
=> PEP 0526 next round of edits

pep-0526.txt
Attn @gvanrossum 
In this PR:
* Additions proposed on python-dev
* Replaced word "declaration" with "annotation" everywhere (and added a note in non-goals), it seems that some people are really annoyed by this word.
=> [WIP] Minor additions to PEP 526 following discussions on python-dev

pep-0526.txt
@gvanrossum 
See also http://bugs.python.org/issue28076
=> Mention that private variable annotations are mangled

pep-0505.txt
The ✊🍆 emoji has an offensive connotation that would not be very welcoming to new developers.
=> Change emoji used in PEP 505

pep-0484.txt
Fixes https://github.com/python/typing/issues/292
@gvanrossum Please take a look.
=> Tweak the scope of type: ignore comment

pep-0484.txt
An update for the example with generic type alias following the discussion in https://github.com/python/mypy/issues/606
@gvanrossum Please take a look.
=> Update the type alias example in PEP 484

pep-0202.txt
as per #4 
Let me know if this works.
Thanks 😃
=> Convert PEP 202 to reST

pep-0484.txt
@gvanrossum Please take a look at this.
I mark this as WIP because I am not sure this is exactly what you wanted.
=> [WIP] Add Coroutine ABC to PEP 484

pep-0533.txt
This is the version I originally sent to python-ideas. It already needs
some revision based on the discussion so far, but I'd like to get a
number now to make it easier to refer/link to.
=> Add PEP for deterministic iterator cleanup

pep-0521.txt
Mostly textual cleanup; no change in actual proposal.
=> Various edits to PEP 521

pep-0512.txt
Detect shorter commit hashes and building the docs from git.
=> Add some TODOs

pep-3107.txt
Fixes https://github.com/python/peps/issues/168
=> Update outdated links in PEP 3107 with archived pages

pep-0512.txt
Also clearly delineate what issues are blocker, post-migration things to do, and non-blockers.
=> Update migration status

pep-0160.txt, pep-0210.txt, pep-0217.txt, pep-0220.txt, pep-0233.txt, pep-0251.txt, pep-0254.txt, pep-0260.txt, pep-0270.txt, pep-0271.txt
PEP 160
PEP 210
PEP 217
PEP 220
PEP 233
PEP 251
PEP 254
PEP 260
PEP 270
PEP 271
Continuing work on https://github.com/python/peps/issues/4 :)
=> reSTify 10 PEPs

pep-0215.txt, pep-0226.txt, pep-0239.txt, pep-0250.txt, pep-0259.txt, pep-0264.txt, pep-0274.txt, pep-0313.txt, pep-0336.txt, pep-3142.txt
🎉 
PEP 215
PEP 226
PEP 239
PEP 250
PEP 259
PEP 264
PEP 274
PEP 313
PEP 336
PEP 3142
https://github.com/python/peps/issues/4
=> Another batch of 10 PEPs converted :)

pep-0263.txt
- convert the content to text/x-rst
- update http://python.org/sf/* url
with https://bugs.python.org/issue*
This PEP could be a good reference for the purpose of this ticket:
https://bugs.python.org/issue29381
=> Convert PEP 263 to reST

pep-0213.txt, pep-0241.txt, pep-0291.txt, pep-0298.txt, pep-0311.txt
PEP 213:
- Fix typo in the word miniscule -> minuscule
PEP 241
PEP 291
PEP 298
PEP 311
=> Convert PEPs 213, 241, 291, 298, 311

pep-0222.txt, pep-0224.txt, pep-0281.txt, pep-0284.txt, pep-0310.txt
Some more progress for https://github.com/python/peps/issues/4
60 more to go.
=> Convert PEPs 222, 224, 281, 284, 310

Makefile
=> Fix the 'venv' target by using Python 3

pep-0008.txt
I realized I have some opinions and guidance around trailing commas. Here they are. I guess the next flake8 can add some rules around this.
=> Clarify my preferences around trailing commas

pep-0542.txt
Hi, this was originally suggested and discussed in the Python ideas mailing list: https://mail.python.org/pipermail/python-ideas/2017-February/044551.html
So I've now created a PEP for it. This is my first PEP ever, so it probably has flaws and things I've forgotten.
=> PEP-542: Dot Notation Assignment In Function Header

pep-0204.txt, pep-0248.txt, pep-0283.txt, pep-0314.txt, pep-3115.txt
For https://github.com/python/peps/issues/4
=> Convert PEPs 204, 248, 283, 314, 3115

pep-0440.txt
=> Provide examples regular expression for pep 440.

pep-0545.txt
Fixes a number of issues (typos, structuring, etc) with PEP 545.
=> Polish wording in PEP-0545

pep-0540.txt
Fixes a couple of issues I found while reading PEP 540.
=> Polish up PEP-540

pep-0506.txt
Fix indentation in PEP 506
Closes https://github.com/python/peps/issues/259
=> Fix indentation and wrapping.

pep-0526.txt
I also fix some reST formatting.
=> PEP 526: Add using ClassAttr instead of ClassVar to rejected ideas

pep-0526.txt
Fixes https://github.com/python/peps/pull/239#issuecomment-301079259.
=> Prohibit type variables inside ClassVar

pep-0266.txt
=> reSTify PEP266

pep-0484.txt
See discussion in https://github.com/python/mypy/pull/3465
=> PEP 484: Allow deriving NewType from another unique type

pep-0546.txt
=> Grammatical and minor content changes to PEP 546.

pep-0547.rst, pep-9999.rst
This idea was discussed on import-sig: https://mail.python.org/pipermail/import-sig/2017-May/001072.html
=> PEP for -m switch for extension modules

pep-0225.txt, pep-0234.txt, pep-0255.txt, pep-0450.txt
=> reSTify PEP225, PEP234, PEP255, PEP450

pep-0544.txt
Here are few (minor) updates based on a recent discussion on python-dev. Most notable change is the change of title.
Attn: @JukkaL @ambv @gvanrossum
=> Updates to PEP 544

pep-0495.txt
=> Mark PEP 495 as Final

pep-0517.txt
=> 517: Add note about fresh subprocess per build

pep-0214.txt
=> reSTify PEP 214

pep-0363.txt
=> reSTify PEP 363

pep-0280.txt
=> reSTify PEP 280

pep-0340.txt
=> reSTify PEP 340

pep-0537.txt
Fix 3.7 release schedule version number typo
=> Add PEP 538 to 3.7 release schedule

pep-0343.txt
=> reSTify PEP 343

pep-0511.txt
Just a tiny typo fix to test my CLA/github status.
=> typo: extra space

pep-0242.txt
=> reSTify PEP 242

pep-0355.txt
=> reSTify PEP 355

pep-0371.txt
=> reSTify PEP 371

pep-0397.txt
=> reSTify PEP 397

pep-0452.txt
=> reSTify PEP 452

pep-3101.txt
=> reSTify PEP 3101

pep-0319.txt
=> reSTify PEP 319

pep-0323.txt
=> reSTify PEP 323

pep-0296.txt
=> reSTify PEP 296

pep-0293.txt
=> reSTify PEP 293

pep-0276.txt
=> reSTify PEP 276

pep-0282.txt
=> reSTify PEP 282

pep-0551.rst
Captures some early feedback and updates the post history.
=> PEP 551 v2

pep-0550.rst
=> PEP-550: Mention why threading.local()-like interface was rejected

pep-0275.txt
=> reSTify PEP 275

pep-0324.txt
=> reSTify PEP 324

pep-0262.txt
=> reSTify PEP 262

pep-0551.rst
Rewrap PEP to 72 columns
Remove unnecessary hook for type.__setattr__
Separate API code into C and Python
Minor word tweaks
=> PEP 551 updates

pep-0253.txt
=> reSTify PEP 253

pep-0555.rst
=> PEP 555: Context-local variables (contextvars)

pep-0512.txt
Moved to completed:
- Link web content back to files that it is generated from: https://bugs.python.org/issue28929
- Handling Misc/NEWS: https://pypi.org/project/blurb/
- Bot to generate cherry-pick pull requests: https://github.com/python/miss-islington
- Write `.github/CONTRIBUTING.md`  - .github/CONTRIBUTING.rst exists
=> PEP 512: Move some optional features from `not started` to `completed`

pep-0551.rst
Add userdata parameter to C API
Remove recursion limit and switch interval hooks
=> PEP 551: updates

pep-0554.rst
This change also enumerates some of the concerns discussed on the mailing list.
=> Add an object passing mechanism to PEP 554.

pep-0558.rst
=> Clarify bullets for Function scope

pep-0554.rst
Raymond gave me some good feedback.  Thanks, Raymond!
=> PEP 554: minor cleanup and renames.

pep-0560.rst
=> Fix typo in PEP 560

pep-0561.rst
These changes are in response to @JelleZijlstra's review of PEP 561.
=> Updates for PEP 561

pep-0246.txt
=> reSTify PEP 246

pep-0231.txt
=> reSTify PEP 231

pep-0245.txt
=> reSTify PEP 245

pep-0209.txt
=> reSTify PEP 209

pep-0252.txt
=> reSTify PEP 252

pep-0227.txt
=> reSTify PEP 227

pep-0102.txt
=> reSTify PEP 102

pep-0207.txt
=> reSTify PEP 207

pep-0205.txt
=> reSTify PEP 205

pep-0484.txt
Not sure if this is the way to suggest fixes, let me know. Reading through the pep, I found a few places where the wording/grammar is quite hard to understand at first sight; I tried to suggest a few minor changes that should improve readability while not affecting the substance of the text.
=> A few wording fixes to pep-0484

pep-0004.txt
=> DOC: correct typo in PEP 4

pep-0545.txt
=> Fix typo in PEP 545

pep-0100.txt
=> reSTify PEP 100

pep-0009.txt
=> Make PEP 9 one massive literal block

pep-3115.txt
=> Fix dead link to implementation of PEP 3115

pep-0560.rst
This is based on discussion on python-ideas list.
Reference implementation will be updated soon.
cc: @gvanrossum
=> Updates to PEP 560

pep-0561.rst
=> PEP 561: Add note about module only distributions

pep-0560.rst
I have also updated the reference implementation. It is however still a bit "rough": all tests pass (``test_types``, ``test_typing``, and newly added ``test_genericclass``), but there is a refleak that I can't catch and I am not yet happy with he overall code style.
=> PEP 560: Updates following recent disscussions

pep-0484.txt
cc @gvanrossum You suggested I make a PR about this a bit over a week ago.
=> Add suggestion about multiple comment syntax

pep-0560.rst
This is a minor comment, but Mark Shannon insisted on it, maybe it is indeed worth adding this comment.
=> PEP 560: Additional comment proposed on python-dev

pep-0012.rst
=> Post-History should include dates of postings to python-ideas

pep-0554.rst
I've finally gotten around to dealing with feedback I've gotten on the PEP, as well as addressing the open questions.  I've also cleaned it up a little.
=> PEP 554: Address Feedback.

pep-0566.txt
Address comments from https://mail.python.org/pipermail/distutils-sig/2017-December/031788.html
(cc @ncoghlan)
=> PEP 566: Address RFC feedback, typos

pep-0567.rst
=> More uncontroversial updates to PEP 567

pep-0567.rst
=> pep-567: Add a Token section to the Specification

pep-0567.rst
* Add Token.MISSING and Token.old_value
* Change the signature of PyContextVar_Reset
cc @gvanrossum
=> pep-567: More additions

pep-0567.rst
=> pep-567: Rejected Ideas, Token usability, fixes

pep-0485.txt
Correction for a minor typo that tripped me up today.
=> pep-485: Fix function name typo

pep-0443.txt
Suggesting correction of a typo.
=> Correction of typo: resultion → resolution

pep-0101.txt
See: https://github.com/python/cpython/commit/dff9b5f9d62aa0b23f8a255867d09d11890efd1b#diff-8f5971460bde8339206e3973186a649f
=> FIX: Renamed version_switcher.js

pep-0101.txt
=> Doc is served by nginx, not apache.

pep-0567.rst
=> pep-567: V3.

pep-0567.rst
=> pep-567: Update the Rejected Ideas section

pep-0567.rst
=> pep-567: Add two more subsections to Rejected Ideas

pep-0562.rst
=> Update status of PEP 562 to Final

pep-0537.txt
@ned-deily I've updated the list of final PEPs.  Maybe there's a few that are still missing though.
=> pep-537: Update the list of final peps

pep-0227.txt
=> PEP 227: remove placeholder comments.

pep-0342.txt
https://bugs.python.org/issue32744
=> bpo-32744: Fix double colons typos in code

pep-0484.txt
=> Fix syntax error

pep-0541.txt
Prose improvements from
https://mail.python.org/pipermail/distutils-sig/2017-September/031517.html
=> Copyedit for PEP 541

pep-0484.txt
=> PEP 484: Fix a typo in code example

pep-0541.txt
Adding text for Packaging Workgroup role.
=> Cleaning up text - role of the PSF

pep-0571.rst
Resolves #592 in the simplest possible way.
=> PEP 571: Remove Continuum Analytics reference

pep-0541.txt
voted by the packaging-wg 10-0-0
https://mail.python.org/pipermail/distutils-sig/2018-March/032089.html
=> change status to final

pep-0571.rst
@geofft provided critical feedback on the `vsyscall` workaround and also helped refine my thinking visa-vi
=> 571: @geofft is an author; mention manylinux2007; cite CalVer.org.

pep-0449.txt, pep-0464.txt, pep-0470.txt
@dstufft this is per our conversation on Friday. Will you double-check that the Resolutions and Statuses on these are appropriate?
=> Update 469, 464, 470 to Final

pep-0526.txt
Fixed format so that both Yes//No bullet points display consistently with bullet points.
=>  #433 Update pep-0526.txt - Typo

pep-0571.rst
Extra backquote/backtick removed
=> Fix formatting in PEP 571

pep-0554.rst
After actually writing the implementation and writing tests, I found a number of minor usability issues that I'm addressing here.
=> PEP 554: Updates post-implementation.

pep-0008.txt
https://english.stackexchange.com/questions/2426/backward-versus-backwards-is-there-any-difference
=> Use consistent "backwards" adverb and case for heads

pep-0561.rst
@ethanhs Hope you have time to look at this.
=> Small tweaks to PEP 561

pep-0518.txt
=> PEP 518: Reword paragraphs describing defined tables

pep-0551.rst, pep-0578.rst
Improves PEP 578 rejected ideas
Starts PEP 551 rejected recommendations
Clarifies relationship between PEPs
=> PEP 551/578 work

pep-0505.txt
Add myself as PEP 505 coauthor (with Mark's permission), and prepare for the rewrite!
=> PEP 505: prepare for 3.8

pep-0505.rst
* make it Draft
* fix grammar
* add augmented assignment `??=`
* clarify use in assignment targets
=> Updates to PEP 505

pep-0572.rst
(Forked from #695, mostly to remove the redundant parentheses that Victor added.)
=> Add PEP 572 examples from stdlib

pep-0572.rst
I think "bur" should be "but".
=> Fix trivial typo in pep-0572.rst

pep-0576.rst
Attempting to maintain this PEP in its own repo just lead to confusion and didn't reduce the amount of email traffic on python-dev. So I'm making this the sole version.
=> Update PEP-0576 to reflect latest design.

pep-0561.rst
=> PEP 561: Add link to sample stub packages

pep-0572.rst
See https://twitter.com/asmeurer/status/1016522016160022528
@Rosuav This was your paragraph IIRC -- do you mind if we delete it?
=> PEP 572: Delete objection about ugly code

pep2rss.py
=> Fix pep2rss to specify output encoding

pep-0572.rst
=> PEP 572 occurrs -> occurs typo

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst
Mention about signing the CLA, and additional steps before writing up a PEP.
I copied over text from
https://github.com/python/peps/issues/158#issuecomment-349126312
and
https://github.com/python/peps/issues/158#issue-195613178
Closes https://github.com/python/peps/issues/158
=> Update the PR template and Contributing Guidelines

pep-0505.rst, pep-0505/find-pep505.py
Improves readability and examples of PEP 505
=> PEP 505 updates

pep-0580.rst
=> PEP 580: minor update

pep-0580.rst
=> PEP 580: update

pep0/pep.py
=> Fix rendering abbreviated two-part surnames

pep-0554.rst
There were a few typos and minor updates.  Mostly the PEP is still up-to-date.
=> PEP 554: minor corrections.

pep-8002.rst
This broke python.org's PEP builder.
=> PEP 8002: Fix markup

pep-8013.rst
Feel free to add review comments at this point - I am interested in additional thoughts.
However, please bear in mind that this proposal _deliberately_ leaves much process unspecified. The examples section will cover the things you are likely concerned about.
=> PEP 8013: The External Council Governance Model

pep-0567.rst
=> Fix PEP 567 to reflect changes in 3.7.1 (see bpo-34762)

pep-0527.txt
=> PEP 527: Fix typo "Chocalatey" to "Chocolatey"

pep-8011.rst
Just showing my intent to claim this PEP.
=> (wip) PEP 8011

pep-0580.rst
Here is a proposed update about ``cc_parent``.
@jdemeyer, do you agree?
=> PEP 580: Reword section on cc_parent

pep-0544.txt
See recent thread "PEP 544 status (forked off "Petr Viktorin as BDFL-Delegate for PEP 580")" in python-dev.
=> PEP 544: Make Guido the BDFL-Delegate (Protocols)

pep-8012.rst
Clarifies some benefits of this governance model and challenges/risks of other models
=> PEP 8012: Add text for clarity

pep-0574.rst
* Fix example
* Mention Numpy implementation and benchmark
=> PEP 574: minor updates

pep-0581.rst
PEP 581: Add mapping issues and read-only mode for the migrated issues.
=> PEP 581: Mapping issues, read-only mode for migrated issues

pep-8010.rst
If the release cadence changes, the term of the GUIDO will change as well.  Include language on how this should be done.
=> Update term length

pep-8001.rst
Hopefully only briefly. Rationale:
https://discuss.python.org/t/python-governance-electoral-system/290/21
=> PEP 8001: back to draft status

pep-8015.rst
* Explain how a Python team is created
* Clarify the special case when a Steering Committee member
proposes a PEP
=> Update PEP 815

pep-8015.rst
* Steering Committee: move Roles before Election
* Use Schulze method
* Change required majority
* Add also a "Annex: Summary on votes" section.
=> PEP 8015: Adjust votes

pep-8000.rst, pep-8001.rst, pep-8016.rst
Incomplete – please don't merge yet. For discussion, see:
https://discuss.python.org/t/working-discussion-for-pep-8016-the-boringest-possible-steering-council-model/
=> PEP 8016 - initial draft

pep-8016.rst
=> PEP 8016: add more details about how emeritus members work

pep-8014.rst
Added procedures for initial CoE selection, vote of no confidence. Ad…ded clarifications. Made some choices on implementation. Added 50%+1 rule.
=> PEP 8014: Procedures, implementation.

pep-8014.rst
=> PEP 8014: added timeout for deferred PEPs and minor clarifications

pep-8010.rst
Also fix the column width for two lines.
=> PEP 8010: Fix typo

pep-0160.txt, pep-0205.txt
The old email address hasn't worked for a good while.
=> PEPs 160, 205: Update email address for fdrake

pep-8100.rst
Adds information on the Voter Roll, which was updated in https://github.com/python/voters/pull/3
Adds information on the Election Implementation.
=> PEP 8100: Election logistics

pep-8100.rst
=> PEP 8100: Nominate Victor Stinner

pep-0008.txt
Going through the pep, please do not merge for at least 24 hours:
I might propose more improvements 👍
=> PEP 8: Comment clarification

pep-8100.rst
=> List myself in PEP-8100

pep-8100.rst
The URL will be added when his post clears moderation.
=> PEP-8100: Add Peter Wang's nomination

pep-8100.rst
=> PEP 8100: Add Myself to Nominees

pep-8100.rst
=> PEP 8100: Fixed link to Peter Wang's nomination post

pep-0571.rst
=> PEP 571: remove duplicated word

pep-0483.txt
=> PEP 483: fix typo

pep-0219.txt
=> PEP 219: Fix grammatical mistakes

pep-0584.rst
=> PEP 584: Fix typo

pep-0012.rst
To help people not to forget something.
=> PEP 12: provide templates for the header and sections

pep-0581.rst
Posted to Python-dev on March 7, 2019.
=> PEP 581: Add Post-history

pep-0570.rst
After an offline conversation with @vstinner, add some further content and links to existing conversations and further examples of the use of the PEP.
=> pep-0570: Add further rationale and related work

.travis.yml
=> Remove deprecated travis ci option

pep-0491.txt
This isn't be actively pursued right now, but may be revisited later.
=> PEP 491: Mark as Deferred

pep-0584.rst
(Inspired by patch in PR #937, by @EmilStenstrom.)
=> PEP 584: Fix dict difference example

pep-0418.txt, pep-0418/clockutils.py, pep-0499.txt
This separate PR was requested by Guido. He reverted my updated email in PR 939 to make the test suite pass and requested a separate PR to updte my email address in all affected files.
Here it is.
=> PEP 499: update the email address of Cameron Simpson from cs@zip.com.au to cs@cskk.id.au

pep-0554.rst
Most notably, this PR adds an "Implementation" section.  Honestly, nothing has changed in the proposal since it was last posted to python-dev (May 2018).
=> PEP 554: Seasonal Updates.

pep-0447.txt
=> Defer PEP 447

pep-0570.rst
=> PEP 570: Fix broken link and quote formatting

pep-0452.txt
All relevant modules implement this and future changes will go into a v3 version of the spec.
=> Mark PEP 452 as final

pep-0578.rst
=> PEP 578: Updated text

pep-0533.txt
CC: @1st1 @njsmith @brettcannon
=> PEP 533: Make Guido BDFL-Delegate

pep-0533.txt
Correct https://github.com/python/peps/pull/969
=> PEP 533: Correction: Make Yury BDFL-Delegate

pep-0544.txt
is it really necessary to sign the CLA for a 1-character (uncopyrightable?) change? i don't exactly feel like entering my physical address online.
=> PEP 544: Fix typo in code block

pep-0570.rst
Also fix various style/capitalization/markup nits that I found during review.
=> PEP 570: Accept

pep-0590.rst
Fix typos, bad formatting. Remove one false sentence about PEP 580.
=> PEP 590: minor edits

pep-0336.txt
Change semicolons to colons at function definitions
=> PEP 336: Change semicolons to colons at function definitions

Makefile
The PR https://github.com/python/peps/pull/898 make the issue https://github.com/python/peps/issues/431 come back again. This PR will fix that.
Ref python/pythondotorg#1394
=> Package all pep files. Fixes python/pythondotorg#1394

pep-0578.rst
=> PEP 578: Add Post History

pep-0581.rst
Small fixes such as: added a missing word, simplified a long sentence, and (hopefully) fixed a misused word with it's intended meaning.
=> PEP 581: Minor text edits

pep-0484.txt
Per discussion in python/typing#597.
=> PEP 484: Add @type_check_only

pep-0589.rst
=> PEP 589: Minor typo/grammar/wording/markup fixes

pep-0591.rst
- Fix some typos
- Clarify that @final can't be used on non-method functions
=> PEP 591: some minor cleanups

pep-0586.rst
CLA is signed, but not yet confirmed, probably tomorrow.
=> PEP 586: typo (MAy -> May)

pep-0586.rst, pep-0589.rst, pep-0591.rst
The Steering Council has approved this in its meeting on 4/16/2019.
=> PEP 586, PEP 589, PEP 591: Make Guido BDFL-Delegate of typing PEPs

pep-0467.txt
=> PEP 467: Defer, and update open questions

pep-0557.rst
=> PEP 557: Data Classes - Mark as Final

pep-0558.rst
- SC asked Nathaniel to be BDFL-Delegate and he accepted
- added a link to the draft reference implementation
- made the dynamic "frame.f_locals" behaviour an open question based on
both discussion with Nathaniel and further development on the reference
implementation
=> PEP 558: Appoint BDFL-Delegate and other updates

pep-0573.rst
=> PEP 573: Stefan Behnel has accepted the BDFL-Delegate role

pep-0574.rst
Reconcile the PEP contents with the current implementation.
=> PEP 574: Final updates

pep-0482.txt
=> Mark PEP 482 final

pep-0013.rst
This should not be merged unless 2/3 of core devs approve the changes.
=> Specify how long votes should be held

pep-0588.rst
All in title. 
--
cc @Mariatta (Thanks for today's presentation)
=> stray backquote in pep 588

pep-0581.rst, pep-0588.rst, pep-8001.rst, pep-8011.rst, pep-8100.rst
@Mariatta told me she wants to go by just "Mariatta".
- https://twitter.com/mariatta/status/1083136575754493953
- https://twitter.com/mariatta
=> Various PEPs: Mariatta prefers to be just Mariatta

pep-0572.rst
I'm not 100% sure exactly the process to update a PEP.
This is based off of the comments here:
* https://bugs.python.org/issue36798
This update specifies the interplay between f-strings and
the assignment operator. Specifically, it attempts to
clarify how to use assignment operators inside of f-strings.
=> Update PEP-572 for f-strings (see bpo-36798)

pep-0578.rst
=> PEP 578: Update with feedback

pep-0578.rst
Signed-off-by: Christian Heimes <christian@python.org>
=> PEP 578: mark as accepted

pep-0574.rst
=> PEP 574: Mark accepted

pep-0503.txt
=> PEP 503: Update PyPI's base URL for Warehouse

pep-0592.rst
=> 592 Clarifications

pep-0592.rst
=> PEP 592: Typo fixes & restructuring

pep-0591.rst
=> PEP 591: Discuss (not doing) runtime final enforcement

pep-0592.rst
=> Mark PEP 592 as Accepted

pep-0569.rst
=> PEP 569: Move release PEP to correct index section

pep-0587.rst
Minor textual edits of PEP 587.
=> PEP 587: Minor textual edits.

pep-0589.rst
These are the updates I promised in https://github.com/python/peps/pull/991.
=> PEP 589: Small updates based on feedback from @gvanrossum

pep-0594.rst
First public draft of PEP 594 *Removing dead batteries from the standard library*
=> PEP 594: Removing dead batteries from stdlib

pep-0594.rst
=> PEP 594: Fix header (status and type)

pep-0594.rst
=> PEP 594: Add argparse as substitute of getopt

pep-0594.rst
=> PEP 594: Update 1.5

pep-0594.rst
=> PEP 594: discussion to discuss.python.org

pep-0544.txt, pep-0586.rst, pep-0589.rst, pep-0591.rst
cc @gvanrossum @ambv @JukkaL @msullivan @Michael0x2a
=> Mark PEPs 544, 586, 589, and 591 as accepted for Python 3.8

pep-0574.rst
=> PEP 574: Mark final

pep-0594.rst
List legacycrypt as replacement for crypt.
=> PEP-594: add legacycrypt

pep-0590.rst
See https://mail.python.org/pipermail/python-dev/2019-May/157753.html
=> PEP 590: Mark as accepted

pep-0595.rst
=> PEP 595: add python-dev feedback and expand the "migration considerations" section.

pep-0526.txt
See https://bugs.python.org/issue35814
cc @gvanrossum @phouse512 @lisroach @refi64
=> PEP 526: Add another example of tuple packing

pep-0594.rst
Double backticks are needed for reST (single is for Markdown).
=> PEP 594: Typos, formatting and consistency

pep-0484.txt
=> PEP 484: Add missing words

pep-0557.rst
Hi there,
This PR just eventually fixes a small typo.
Related PR: #1110
cc @Rosuav
=> PEP 557: Fix typo (expicitly -> explicitly)

pep-0581.rst
- include recent changes to bpo
- clarify the downsides of GitHub
=> PEP 581 Updates

pep-0600.rst, pep-9999.rst
Adding this here at @pfmoore's request.
I am going on holiday next week, without a laptop. When I come back there will undoubtedly be a pile of things to catch up on. @njsmith et al: please do not wait for me if you want to make changes.
=> PEP 600: Perennial manylinux proposal

.travis.yml
https://travis-ci.community/t/potential-problem-with-the-python-3-7-xenial-environment/4341/5?u=native-api
=> Prevent the highly parallel workload from overloading a worker

pep-0423.txt
=> PEP 0423: Correct typo

pep-0588.rst
- hire a professional project manager
- create playground issue tracker for experiment
- test repo for labels
- python triage team has been created
- devguide update
=> PEP 588 Updates

pep-0588.rst
Also mention that discussions can happen in Discourse.
=> PEP 588: add how to nosy the expert

pep-0425.txt
=> PEP 425: Fix misspelled name (Marc Abramowitz)

pep-0518.txt
=> PEP 518: .e.g => e.g.

pep-0601.txt
Adds discuss.python.org link to #1151
=> PEP 601: Discussions-To

pep-0603.rst
=> [PEP 603] Fix one reference to frozenmap

pep-0601.txt
=> PEP601: Add rejection notice

pep-0603.rst
PEP 0603: Fixed code sample's indentation
=> Fix PEP-0603 code sample indentation

pep-0373.txt
cc @benjaminp per our conversation [on python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/APWHFYQDKNVYQAK3HZMBGQIZHAVRHCV2/). Thank you.
=> PEP 373: Add 2.7.18 release details and reference

pep-0604.rst
=> Pep 0604: Remove __revert__ operator

pep-0604.rst
=> Pep 0604 : Change title

pep-0604.rst
Approved by Steering Council, agreed to by Ivan.
=> PEP 604: Make Ivan BDFL-Delegate

pep-0605.rst
* example What's New subsection
* example alpha, beta, and rc announcements
* fix Python-Requires recommendation
* add rationale for allowing mid-stream alpha releases
=> PEP 605: Add example user-facing docs

pep-0440.txt
Avoid suggesting versions that will raise warnings in build tools such as pypa/setuptools#302
=> PEP 440: Normalize date version examples

pep-0606.rst
=> Add PEP 606: Python Compatibility Version

pep-0607.rst
Also moves a couple of paragraphs to the correct section.
=> PEP 607: Update Discussions-To header

pep-0584.rst
=> PEP 584: Fix formatting and update copyright notice.

pep-0602.rst
=> Assign a BDFL-Delegate for PEP 602

pep-0544.txt
=> PEP 544: Corrected import in sample code

pep-0609.rst, pep-9999.rst
Discussion: https://discuss.python.org/t/closing-the-loop-on-pypa-governance-bdfrn/
=> PEP 609: PyPA Governance

pep-0606.rst
=> Grammatical improvements for PEP 606

pep-0457.txt
@larryhastings Is there anything else you wanted to do here? If I don't hear from you by Friday I'll merge this as-is.
=> PEP 457: Mark as Final -- there's nothing left to do here now PEP 570 is accepted

pep-0558.rst
@ncoghlan @njsmith This PR is also a ping: what needs to happen for this PEP to actually land in 3.9?
=> PEP 558: Move target version to 3.9

pep-0589.rst
=> PEP 589: Fix typos

pep-0480.txt
=> PEP 480: Fix typos

pep-8101.rst
per https://discuss.python.org/t/steering-council-nomination-guido-van-rossum-2020-term/2657/11
=> PEP 8101: Update nominees

pep-8101.rst
=> PEP 8101: Fix typo.

pep-0611.rst
=> PEP 611: Correct typo

pep-0612.rst
This PR implements the @gvanrossum 's requested formatting changes from his review of https://github.com/python/peps/pull/1259
=> PEP 612: Formatting changes

pep-0458.txt
Heads-up @dstufft @ewdurbin @ncoghlan and @mnm678.
=> PEP 458: Add sponsor and update status

pep-0484.txt
=> PEP 484: Remove square brackets around ellipsis

pep-0458.txt
I updated the abstract of PEP 458 per the discussion here: https://discuss.python.org/t/pep-458-surviving-a-compromise-of-pypi/2648/52.
=> PEP 458: Update abstract

pep-0458.txt
cc @ncoghlan @mnm678 @dstufft 
Per [this python-dev post today](https://mail.python.org/archives/list/python-dev@python.org/thread/ARJLCFBZJYTDXHRMK6YP5SNAHD34HNR5/).
=> PEP 458: Add Post-History header

pep-0405.txt
=> PEP 405: Removed dead links to Google Code Search

pep-0610.rst
Second draft following comments collected in the discuss thread.
=> PEP 610: 2nd draft

pep-0610.rst
As suggested by @ncoghlan at https://discuss.python.org/t/draft-pep-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/41?u=sbidoul
=> PEP 610: third draft

pep-0610.rst
From https://github.com/pypa/packaging.python.org/pull/690#issuecomment-578499201
=> PEP 610: add canonical URL and minor clarification

pep-0611.rst
Also remove comment about Jython, as it is incorrect.
=> PEP 611: relax hard limits and make 1 million a soft limit. Include recursion depth in limits.

pep-0610.rst
- support well-known users in URLs
- correction wrt `resolved_revision` and `resolved_revision_type`
cc/ @ncoghlan
=> PEP 610: support well-known users in URLs

pep-0597.rst
I chose utilizing exiting UTF8 mode instead of adding more options.
=> PEP 597: Rewrite the whole PEP.

pep-0458.txt, pep-0480.txt
=> PEP 458: update list of authors

pep-0584.rst
Just a few things I noticed on the published build. This also includes a link to the newest discussion on python-dev.
=> PEP 584: Assorted cleanup.

pep-0614.rst, pep-9999.rst
Here's a first draft. Thanks @gvanrossum for sponsoring.
=> PEP 614: Relaxing Grammar Restrictions On Decorators

pep-0614.rst
=> PEP 614: Remove matmul section and clarify the current restrictions.

pep-0373.txt
Updating per [conversation on Discourse](https://discuss.python.org/t/petition-abandon-plans-to-ship-a-2-7-18-in-april/2946/).
=> PEP 373: Use past tense since sunset date has passed

pep-0584.rst
These are just a collection of clarifications that were requested on- and off-list.
=> PEP 584: Apply feedback from the Python-Dev discussion.

pep-0596.rst
Since PEP 602 ("Annual Release Cycle for Python") has been accepted, update the note.
=> PEP 596: Update note now that PEP 602 is accepted

pep-0020.txt
@tim-one sent me a link to the original posting containing the PEP 20 text.  I thought it would be historically interesting to include this in the PEP
=> PEP 20: Add the original Zen (Way) of Python link

pep-0376.txt
Minimal changes to address https://discuss.python.org/t/does-pep-376-need-a-review/3269
=> PEP 376: clarify status of implementation notes

pep-0584.rst
Guido just informed us that the Steering Council accepted his [recommendation](https://mail.python.org/archives/list/python-dev@python.org/thread/6KT2KIOTYXMDCD2CCAOLOI7LUGTN6MBS)!
=> PEP 584: Mark as Accepted.

pep-0013.rst
=> PEP 13: update for the latest steering council

pep-0615.rst
This is in response to further feedback and further reflection, as well as playing around more with the reference implementation.
=> PEP 615: Changes to TZPATH and str, plus minor tweaks

pep-0458.txt
=> PEP 458: correct spelling of 'infrastucture'

pep-0610.rst
From https://discuss.python.org/t/1535/56?u=pradyunsg
=> PEP 610: Provisional Acceptance

pep-0616.rst, pep-9999.rst
=> PEP 616: String methods to remove prefixes and suffixes

pep-0616.rst, pep-9999.rst
- Shorten the abstract
- Clarify ``return self`` behavior.
- Add support for a tuple of affixes.
=> PEP 616 Revisions

pep-0616.rst
=> PEP 616: Add references to past discussion threads, fix formatting and typos

pep-0616.rst
=> PEP 616: Rename the methods and restrict to one affix

pep-0616.rst
=> PEP 616: Remove obsolete names; consistently quote strings

pep-0616.rst
=> PEP 616: Make the specification more concise

pep-0616.rst
=> PEP 616: Add revision history

pep-0617.rst
A few wording issues I noticed while reading.
=> PEP 617: minor edits

pep-0617.rst
=> PEP 617: Expand the section about actions to cover Python-based actions

pep-0617.rst
Closes https://github.com/we-like-parsers/cpython/issues/34
=> PEP 617: Add section on rejected alternatives

pep-0518.txt
For https://discuss.python.org/t/mark-pep-518-as-final/3820 basically.
/cc @brettcannon @ncoghlan
=> PEP 518: Mark as Final

pep-0505.rst
=> PEP 505: Fix rst error

pep-0373.txt
Toward https://github.com/python/steering-council/issues/3#issuecomment-613135126 .
=> PEP 373: Move 2.7.18rc1 to past

pep-0373.txt
Regarding https://github.com/python/steering-council/issues/3 .
=> PEP 373: Link to Python 2 sunsetting FAQ

pep-0617.rst
=> PEP-617: Mark as accepted

pep-0615.rst
Per [the steering council's decision](https://mail.python.org/archives/list/python-dev@python.org/thread/MDR2FL66R4T4VSLUI5XRFFUTKD43FMK4/). :smile:
=> PEP 615: Mark as accepted

pep-0373.txt
Fix grammar and add one reference link.
=> PEP 373 grammar fix

pep-0616.rst
=> PEP 616: How to teach this

pep-0599.rst
Per https://github.com/pypa/manylinux/issues/338 , manylinux2014 is
now implemented in its entirety. Per PEP 1, since the reference
implementation is now complete and incorporated into the main source
code repository, this commit changes the status to "Final".
=> PEP 599: Update status to Final

pep-0349.txt
=> Reject PEP 349: Outdated by Python 3

pep-0581.rst, pep-0588.rst
=> PEP 581/588: Discussions to: core-workflow on Discourse

pep-0618.rst
This contains some minor changes based on feedback gathered from Ideas.
CC @python/pep-editors @pitrou @cool-RR
=> PEP 618: Second Draft

pep-0617.rst
Fixes #1400 (citation fix courtesy Michael Wayne Goodman).
=> PEP 617: Fix citation for Medeiros ([2])

pep-0431.txt
=> PEP 431: Mention PEP 615

pep-0584.rst
=> Specify pep-0584 order guarantee

pep-0318.txt
=> PEP 318: Replace dead link with Internet Archive version

pep-0619.rst
=> PEP 619: Fix creation date

pep-0619.rst
There is no Tuesday, 2021-05-03:
* https://clndr.org/2021/May
Could be either of:
* Monday, 2021-05-03
* Tuesday, 2021-05-04
=> PEP 619: Fix version number and date of beta 1

pep-0596.rst
=> PEP 596: Add the list of PEPs implemented in Python 3.9.0b1

pep-0570.rst
According to
https://docs.python.org/3/whatsnew/3.8.html#positional-only-parameters
=> PEP 570: add Python version

pep-0570.rst, pep-0617.rst, pep-0619.rst, pep-8001.rst
=> Update Pablo Galindo's email

pep-0618.rst
CC: @pitrou
Thanks @cool-RR and @gvanrossum for pushing me to finish this after the feature-freeze passed!
I feel the PEP is ready, and ~I'll be seeking a BDFL-Delegate after it is published~ (thanks, Guido, for agreeing to fill this role). If any of you see anything you think should be changed, just comment here or email me.
=> PEP 618: Third Draft

pep-0004.txt
See: https://github.com/python/cpython/pull/12707
See: https://bugs.python.org/issue36543
Signed-off-by: Christian Heimes <christian@python.org>
=> Update PEP 4 with xml.etree.cElementTree removal

pep-0527.txt
Fully implemented via https://github.com/pypa/warehouse/issues/6792
cc @di @ncoghlan
=> PEP 527: Update status to Final

pep-0618.rst
=> PEP 618: Accepted!

pep-0609.rst
Per @ewdurbin's [suggestion](https://discuss.python.org/t/pep-609-pypa-governance/2619/22).
=> PEP 609: Disambiguate from Packaging WG

pep-0614.rst
- Change status to "Final".
- Update post history.
- Add resolution link.
- Link to PR instead of branch.
- Remove trailing whitespace.
=> PEP 614: Final

pep-0584.rst
=> PEP 584: Final

pep-0620.rst
=> PEP 620: Hide implementation details from the C API

pep-0622.rst
I am about to post about this to python-dev.
=> PEP 622: Structural Pattern Matching (Bucher, Kohn, Levkivskyi, GvR, Talin)

pep-0622.rst
There is really not much to say about it - it's a typo and I fixed it :)
=> PEP 622: minor typo and grammar fixes

pep-0618.rst
=> PEP 618: Final

pep-0621.rst
Typo fixes, and change email in example to a functional one.
=> PEP 621: Cosmetic updates

pep-0387.txt
=> Mention that C compiler warnings are acceptable notice for removal

pep-0543.rst, pep-0550.rst, pep-0553.rst, pep-0614.rst, pep-0622.rst, pep-8013.rst
=> PEP 622: Fix Typo

pep-0609.rst
Title says it all. :)
/cc @di as the co-author on this PEP
=> PEP 609: Clarify expectations around PEP sponsors

pep-0623.rst
=> PEP 623: Set the BDFL-Delegate

pep-0622.rst
Changes to the treatment of `__match_args__`, and a few other fixes.
=> PEP 622: Updates from Python-Dev

pep-0558.rst
Leaving as Draft as I'm still intending to work on it in the coming
months, it just isn't going to be ready in time for the 3.9 beta 1
deadline.
=> PEP 558: Postpone to 3.10

pep-0622.rst
See https://github.com/gvanrossum/patma/issues/93#issuecomment-650723402
=> PEP 622: Strengthen the argument for _ as wildcard

pep-0622.rst
See https://github.com/gvanrossum/patma/issues/89#issuecomment-652782965
=> PEP 622: Add argumentation against 'else'

pep-0623.rst
=> Rephrase the PEP 623

pep-0617.rst
=> PEP 617: Fix typo

pep-0622.rst
=> PEP 622: Ditch leading dots for name loads

pep-0622.rst
Daniel Moisset and I rewrote the Abstract and "Rationale and Goals"
and inserted a new Overview section in between.
Includes a few minor updates elsewhere, such as a better link to the
reference implementation.
Co-Authored-By: Daniel F Moisset <dfmoisset@gmail.com>
=> PEP 622: New intro

pep-0622.rst
Explain why the PEP proposes this and only this construct.
=> PEP 622: Why the match statement is the correct feature right now

pep-0620.rst
=> Update PEP 620

pep-0625.rst
Noticed some minor typos while reading #1505. cc @pfmoore @uranusjr
=> PEP 625: Typo fixes

pep-0629.rst
=> PEP 629: Add versioning to PyPI's Simple API

pep-0626.rst
=> PEP 626: Add version and post date.

pep-0629.rst
=> Make Brett Cannon the PEP delegate for PEP 629

pep-0604.rst
Here I'm also retargeting this to Python 3.10 and proposing various
small changes to clarify the PEP. In addition, we have a new reference
implementation in the works.
=> PEP 604: I've been asked to take over as PEP-Delegate

pep-0604.rst
"Change only PEP 484" is not sub idea of "Add a new operator ".
=> PEP 604: Reformat section

pep-0612.rst
=> PEP 612: Updating PEP metadata

pep-0624.rst
=> PEP 624: nitpicks

pep-0620.rst
=> PEP 620: Fix typos

pep-0612.rst
=> PEP 612: Fix indentation in code example

pep-0627.rst
=> PEP 627: Typo

pep-0604.rst
- Added additional examples and details to the specification section.
cc: @gvanrossum @pprados
=> PEP 604 - Updates and Edits

pep-0604.rst
Forgot to push this commit on the last branch. Apologies!
cc: @gvanrossum @pprados
=> Update authors for PEP604

pep-0432.txt
=> PEP 432: Withdraw to make way for future subproposals

pep-0631.rst
See: https://discuss.python.org/t/5018/23
=> PEP 631: Allow future extension of the spec in a backward compatible way

pep-0632.rst
=> PEP 632: Update metadata

pep-0597.rst
See discussion in https://discuss.python.org/t/3880/16 .
=> PEP 597: Add io.LOCALE_ENCODING constant

pep-0631.rst
=> Correct backward compatible update logic

pep-0533.txt
=> fix PEP 533 typo

pep-0604.rst
=> PEP 604: Fix minor typo

pep-0631.rst
Addresses part of https://discuss.python.org/t/how-to-specify-dependencies-pep-508-strings-or-a-table-in-toml/5243/2
=> PEP 631: Add reference implementation

pep-0633.rst
=> PEP 633: Reference implementation fixes

pep-0544.txt
=> fix that/than typo

pep-0637.txt
There are other ways to resolve the ambiguity/awkwardness:
- rename the variable
- put the variable name in quote
but I think this looks best?
=> PEP 637: Clarify phrasing in example

pep-0637.rst
Integrates feedback from GvR. 
Note: this PR is built on top of #1619
=> PEP 637: Integrate feedback from GvR

pep-0637.rst
Added discussion on the sentinel value when nothing is passed as an index.
=> PEP 637 Default sentinel value for no value passed as index

pep-0626.rst
The Steering Council have asked Pablo to be the PEP delegate for PEP 626, and he's agreed.
=> Record Pablo as the PEP delegate for PEP 626.

pep-0639.rst
=> PEP 639: edits from review

pep-0609.rst
(cc @pganssle @pfmoore @takluyver)
=> PEP 609: Clarify conditions for a successful vote

pep-0484.txt
See
https://mail.python.org/archives/list/typing-sig@python.org/thread/YLJPWECBNPD2K4TRIBRIPISNUZJCRREY/
esp.
https://mail.python.org/archives/list/typing-sig@python.org/message/RDJECZOIFRLU2IQZWU276MZDWVJQZOAY/
=> PEP 484: Clarify that 'import ... as ...' means 'X as X'

pep-0623.rst
=> fix typo: extensiom -> extension

pep-0635.rst
=> PEP 635: Added guards and walrus patterns

pep-0621.rst, pep-0631.rst
=> PEP 621 & 631: pull in details from PEP 631 into PEP 621

pep-0637.rst
Hi Jonathan
Thank you for accepting my invitation to be a co-author of PEP 637. I regret that because of disagreeing direction for the PEP I think it best for the community that I ask you to resign as co-author.
Thank you for your help
=> PEP 637 I've asked Jonathan Fine to resign as PEP author, and he's agreed to do so. Details in the pull request.

pep-0634.rst
=> PEP 634: Define irrefutable and add requirements around it

pep-0621.rst
=> PEP 621: data specified is canonical

pep-0636.rst
Fixed a little typo on line 357
=> PEP 636: Fixed typo

pep-0639.rst
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
=> PEP-639: Minor typo fixes 

pep-0621.rst
=> PEP 621: update post history

pep-0635.rst
=> PEP 635:  many improvements

pep-0635.rst
=> PEP-635: Spelling fixes for

pep-0636.rst
Some rearranging of sections to connect the story more
linearly after adding the new sections.
Minor editorial updates
=> PEP-636: Add section on built-in class patterns and qualified names

pep2rss.py
=> Use HTTPS for RSS links

pep-0634.rst
=> PEP 634: Fix code block markup

pep-0642.rst
=> PEP 642: Add notes on reference implementation status

pep-0643.rst
=> PEP 643: Metadata for Package Source Distributions

pep-0643.rst
=> PEP 643: Add Discussions-To and clarify handling of Python-Requires

pep-0635.rst
=> PEP 635: Add a rebuttal of PEP 642

pep-0644.rst
Signed-off-by: Christian Heimes <christian@python.org>
=> PEP-644: Require OpenSSL 1.1 or newer

pep-0642.rst
* add explicit syntax for identity constraints
* reject literal patterns (with rationale)
* reorder rejected ideas to put unpublished ideas last
* add containment constraints as a deferred idea
* misc ReST formatting fixes and other text fixes
=> PEP 642: Add identity constraints

pep-8102.rst
This will be updated as we progress through the election on the timeline announced via [python-committers](https://mail.python.org/archives/list/python-committers@python.org/thread/JHYSU6FEYM3A5AZXSICO5OE3VAWDPGEJ/)
=> PEP-8102 -- 2021 Term steering council election

pep-0643.rst
=> PEP 643: Further updates

pep-0643.rst
=> PEP 643: Update Post-History and clarify permitted tool behaviour

pep-0636.rst
=> PEP 636: Fix incorrect wording.

pep-0621.rst
=> PEP 621: reviewer feedback

pep-0641.rst
=> PEP 641: open issue for the idea of standardizing on double digit minor  version numbers

pep-0593.rst
=> PEP 593: Remove repeated word

pep-8102.rst
Nominations have closed. Add nominees and links to the discuss.python.org nomination topic for each.
=> PEP 8102: Update Nominees list

pep-0635.rst
=> PEP 635: Add link to Guido's copy of DLS '20 paper.

pep-0643.rst
=> PEP 643: Clarify wording of rejected item about Requires-Python

pep-0626.rst
=> PEP 626: Clarify which keywords are considered to be executable code.

pep-8102.rst
See https://github.com/python/voters/pull/33
=> PEP 8102: add voter roll for 2021 term steering council election

pep-0643.rst
As BDFL-Delegate, I am happy to accept PEP 643: https://discuss.python.org/t/pep-643-metadata-for-package-source-distributions/5577/53
=> PEP 643: Mark as accepted

pep-0458.txt, pep-0588.rst, pep-8001.rst, pep-8100.rst, pep-8101.rst, pep-8102.rst
=> PEP-0: new name <3

pep-0601.txt
=> PEP 601: Add my email

pep-0635.rst
=> fix typos in PEP 635

pep-0647.rst, pep-9999.rst
I've signed the CLA
bugs.python.org username: erictr
=> PEP 647: User-defined Type Guards

pep-0648.rst
=> PEP 0648: Extensible customizations of the interpreter at startup

pep-0612.rst
=> PEP 612: Fix typo

pep-0648.rst
Moving away from namespace packages after receiving feedback.
=> PEP-648: Change implementation to folder with scripts

pep-0648.rst
Please approve to acknowledge the copyright change: @pablogsal, @JelleZijlstra
Thanks @Rosuav for raising this.
=> PEP 648: Add copyright notice

pep-0646.rst
=> PEP 646: Fix minor typos

pep-0651.rst
@markshannon When I first saw your email I thought it was about numeric overflow.
=> PEP 651: Change title to clarify topic

pep-0650.rst
=> Update PEP 650 based on reviewer comments

pep-0610.rst
=> PEP 610: Mark as Final

pep-0629.rst
=> Accept PEP 629

pep-0648.rst
=> PEP 648: Add entry_points as rejected alternative

pep-0637.rst
=> PEP 637: Fix case of "Python"

pep-0634.rst, pep-0635.rst, pep-0636.rst
CC @gvanrossum.
Informational PEPs go straight to "Final", right?
=> PEP 634/635/636: Accept!

pep-0648.rst
Some clarifications from discussions in the discourse thread.
=> PEP648: Updates from discourse thread

pep-3333.txt
=> PEP 3333: Clairify HTTP_HOST as superior source for SERVER_PORT (#1816)

pep-0653.rst
New PEP providing precise semantics for pattern matching.
=> PEP 653: Precise Semantics for Pattern Matching

pep-0653.rst
Improvements suggested by @brandtbucher
* Clarify description of __match_kind__
* Drop tenuous claim of improved security
=> Minor improvements to PEP 653

pep-0653.rst
=> PEP 653: Make it clearer that MATCH_DEFAULT is the default.

pep-0646.rst
=> Fixed several omissions and errors in sample code in PEP 646.

pep-9999.rst
=> Initial version of Exception Groups and except* PEP

pep-0654.rst
=> "This PEP" -->  " this document"

pep-0654.rst
=> pep 654: Fix indentation to use consistent 4 spaces in all snippets

pep-0654.rst
=> PEP-654: fix level of subsection headings

pep-0654.rst
=> Add Post-History date

pep-0427.txt
Counterpart to https://github.com/pypa/packaging.python.org/pull/839 - cc @pfmoore
=> PEP 427: Point to spec on packaging.python.org

pep-0654.rst
=> PEP-654: remove cause, context from traverse()

pep-0654.rst
=> PEP-654: added explanation why we did not extend except to handle ExceptionGroups

pep-0655.rst
=> PEP 655: Revise Post-History

pep-0654.rst
Just fixing a couple small typos
=> PEP 654: fix typos

pep-0646.rst
No semantic changes - just readability improvements, some minor clarifications, and cleanup of references.
=> (Hopefully) final readability tweaks to PEP 646

pep-0651.rst
=> PEP 651 rejected by the SC

pep-0601.txt
Apparently 2 authors are lexed just if it were 1 person so let's try whether it works in this way
=> PEP 601: try to fix lexing

pep-0654.rst
=> PEP-654: errors --> exceptions

pep-0644.rst
=> PEP 644: OpenSSL 1.1.1, CI proviers, Debian, SHA-3 (GH-1875)

pep-0654.rst
=> PEP-654: add post history date

pep-0597.rst
https://mail.python.org/archives/list/python-committers@python.org/message/YIZGJBMDQAOZHD6MXQCLEXIAKGUQFMQM/
=> PEP-597: Update status as accepted

pep-0654.rst
=> PEP-654: fix bug in leaf_generator example

.github/CODEOWNERS
=> CODEOWNERS: fix Pablo's name for PEP 619

pep-0636.rst
=> PEP 636: Convert __match_args__ to tuple

pep-0647.rst
=> PEP 647: Mark as accepted

pep-0644.rst
PEP was implemented in merged PR https://github.com/python/cpython/pull/23014
=> PEP 644: Added accepted mail and mark as final (GH-1927)

pep-0652.rst
See https://mail.python.org/archives/list/python-dev@python.org/message/IN4XMFLQJ6D6V67EXU27GV3QWSEHHNNH/
=> Mark PEP 652 accepted & add a note from the SC and link to bpo

pep-0654.rst
=> add acknowledgements

pep-0648.rst
=> PEP648: Rework wording based on feedback from SC

pep-0624.rst
Implemented in https://github.com/python/cpython/pull/25881
=> PEP 624: Change status to Final

pep-0657.rst
=> PEP 657: Include fine grained error locations in tracebacks

.github/CODEOWNERS
=> PEP 657: add codeowners

pep-0657.rst
This should help people get to the right place for discussion if they get linked to the PEP directly.
=> PEP 657: Add Discussions-To linking to discourse thread

pep-0657.rst
=> PEP 657: Update the public API and the opt-out mechanism

pep-0657.rst
=> PEP 657: Add a new rejected idea section for single-caret errors

pep-0101.txt
Same for the `/dev/` symlinks, it's now updated automatically.
=> pep-101: /3/ symlink is handled by the build server now.

pep-0661.rst
=> Fix reference implementation

.github/workflows/deploy-gh-pages.yaml
As per @pablogsal in https://github.com/python/peps/pull/1931#pullrequestreview-679083858
=> Update to only deploy Sphinx on pushing to `master`

pep-0619.rst
=> PEP 619: Mark 3.10.0b2 as relased.

pep-0635.rst
=> Fix typo: swap node and match in the example

pep-3104.txt
Resolves: python/peps#897 issue
=> PEP 3104: Fix broken link

pep-0657.rst
As per Barry on behalf of the steering council: https://mail.python.org/archives/list/python-dev@python.org/thread/3WDJNOW2SPTPCKUGLG2ANBWZZEYTT6F6/
=> Mark PEP 657 as accepted

pep-0002.txt
=> PEP 2:  This PEP is superseded

pep-0662.rst
https://discuss.python.org/t/pronouncement-on-peps-660-and-662-editable-installs/9450/1
=> PEP-662: C'est la vie

pep-0663.txt
=> PEP 663: Fix SyntaxError

pep-0664.rst
=> PEP 664: Python 3.11 Release Schedule

pep-0658.rst
Based on https://discuss.python.org/t/8651/48
/cc @uranusjr @dstufft
=> PEP 658: Mark as Accepted

pep-0654.rst
=> PEP-654: mark as accepted
