python/peps

pep-0626.rst

I noticed this because the typo even found its way to the [What's new listing in CPython](https://github.com/python/cpython/blame/master/Doc/whatsnew/3.10.rst#L176)

PEP 626: typo: should be f_lineno, not f_lineo.

---

pep-0653.rst

* Make 0 the defualt for `__match_class__` and drop ability to not match class patterns
* Use equality not bitwise ands to check for matches
* Add to rejected and deferred sections, explaining the above

PEP 653: Simplifications

---

.github/CODEOWNERS

Bisect CODEOWNERS to try and figure out why it isn't working

---

pep-0656.rst

https://discuss.python.org/t/pep-656-platform-tag-for-linux-distributions-using-musl/7165/32

PEP 656: Accepted

---

pep-0646.rst

These sections were requested in some feedback we got when talking to NumPy and JAX folks. OK, this does make an already-long PEP even longer, but I do think this context is important - especially for folks who don't have strong intuitions for how parametric typing works in Python.
This is just a draft right now, but I'll submit a PR to get some early feedback from Python folks while I also check with external folks whether this makes sense.

PEP 646: Add some broader context

---

pep-0634.rst

This PR makes the behavior of matching sequences and mappings more robust in unusual circumstances.
For example:
* Pattern matching can be used before `collections.abc` is imported. This might be important for coverage and profiling tools
* Registering `dict` as a `collections.abc.Sequence` will not make `{}` match `[]`.
* Pattern matching cannot fail as a result of `collections.abc` failing to import.
This change keeps the door open for PEP 653, but is a worthwhile improvement even if PEP 653 is withdrawn or rejected.

PEP 634: Reword sequence and mapping patterns sections to be more robust.

---

pep-3141.txt

Was - 404 (discovered while working on https://github.com/python/cpython/pull/25552).
Not sure, perhaps it would be better add the web archive link:
https://web.archive.org/web/20161115045107/http://code.haskell.org/numeric-prelude/docs/html/index.html
or https://archives.haskell.org/code.haskell.org/numeric-prelude/docs/html/index.html
The current package version is different.

PEP 3141: fix link for the Haskell numeric prelude

---

pep-0626.rst

Allows line tables that are not sentinel terminated and makes the extent of the line table explicit.
See https://bugs.python.org/issue42739 and https://github.com/python/cpython/pull/25657

PEP 626: Add length parameter to PyLineTable_InitAddressRange

---

pep-0634.rst

Also, slightly rework the note to be less wordy.

PEP 634: Fix markup for sequence pattern note

---

README.rst

No PEP, just updating the links, which are being redirected to HTTPS anyway 0:-)
CLA should be signed.

Update two links in README.rst to use HTTPS

---

pep-0101.txt

Update references to master to point to main

---

pep-0657.rst

Looks like we accidentally retained the old estimated percentage increase, let's update this to the real number.
(Point out by `/u/velit` in https://www.reddit.com/r/Python/comments/n89r40/pep_657_include_fine_grained_error_locations_in/gxhihrk/)

PEP 657: Fix incorrect percentage for standard library pyc size increase

---

.github/CODEOWNERS
pep-0658.rst

Spawned from pypa/warehouse#8254. Missing fields to be filled later after a number is assigned.

PEP 658: Static Distribution Metadata in the Simple Repository API

---

pep-0659.rst

Fix a minor typo in the compatibility section.

PEP 659: fix a typo

---

README.rst

Seems the instructions are old (?) in this README and deviates from [PEP-0012](https://www.python.org/dev/peps/pep-0012).

Update instructions to use pep-9999.rst

---

pep-0659.rst

Make it a draft PEP, as it is still being debated.

Make PEP 659: Make it draft, not active.

---

pep-0658.rst

Based on feedback https://discuss.python.org/t/8651/35

PEP 658: Rationale edits

---

pep-0515.txt

While working on https://bugs.python.org/issue44267 I've noticed some broken links (first commit).  The second one fix links with redirects.
BTW, the stdlib implementation doesn't follow PEP.  Is it ok?

PEP 515: fix links

---

pep-0101.txt

As it's no longer mandatory to merge, some false positives can sneak in.
It's a burden for RMs, and it's slowly been handled in:
https://bugs.python.org/issue42238

Release: drop 'make suspicious' from release process.

---

build.py
conf.py
pep_sphinx_extensions/__init__.py
pep_sphinx_extensions/config.py
pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
pep_sphinx_extensions/pep_processor/parsing/pep_parser.py
pep_sphinx_extensions/pep_processor/parsing/pep_role.py
pep_sphinx_extensions/pep_processor/transforms/pep_contents.py
pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
pep_sphinx_extensions/pep_processor/transforms/pep_title.py
pep_sphinx_extensions/pep_processor/transforms/pep_zero.py

See #2, #1385 for context. Superseeds #1566.
This is the docutils parsing, transforms and writing part, building on PR #1930. It contains a pseudo-package, `sphinx_pep_extensions`, which itself contains:
- `PEPParser` - collates transforms and interfaces with Sphinx core
- `PEPRole` - deals with :PEP:`blah` in RST source
- `PEPContents` (Creates table of contents without page title)
- `PEPFooter` (Dels with footnotes, link to source, last modified commit)
- `PEPHeaders` (Parses RFC2822 headers)
- `PEPTitle` - Creates document title from PEP headers
- `PEPZero` - Masks email addresses and creates links to PEP numbers from tables in `pep-0000.rst`
- `PEPTranslator` - Overrides to the default HTML translator to enable better matching of the current PEP styles

Sphinx - docutils

---

Makefile
build.py

xref discussion in #1931, https://github.com/python/peps/pull/1931#issuecomment-857283694
Two questions left - what to put as the default (directories or files), and whether to add a make target (I don't know if make passes args through? If so this Q is irrelevant)

Add config option in `build.py` for Sphinx builders

---

.github/CODEOWNERS
pep-0662.rst
pep-9999.rst

Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

PEP 662: Editable installs via virtual wheels

---

Makefile
pep_rss_gen.py
requirements.txt

See #2, #1385 for context.
This is the RSS generation part, building on PR #1930. It contains the logic for generating RSS
- This was originally in #1385 and #1565, split out for ease of review

Sphinx - RSS

---

pep-0517.txt

It currently looks kinda odd. 
Though I'm not sure of the original intention. Which part does the author want to be linked?

PEP 517: Fix odd url markup

---

pep-0660.rst

A few updates to PEP 660 following ongoing discussions.

Updates to PEP 660

---

pep-0582.rst

According to https://github.com/python/peps/issues/1796, it looks like the desired discussion forum is Discourse.
Closes https://github.com/python/peps/issues/1796

PEP 582: Add Discussions To

---

.github/CODEOWNERS
pep-0634.rst

...as requested by @markshannon in https://github.com/python/cpython/pull/26864.
Also, add myself as a CODEOWNER of PEPs 635 and 636.

PEP 634: Clarify late-registration edge-case

---

pep-0662.rst

This provides full symetry with build_wheel and allows
a fast path for the frontend to validate the backend metadata,
without needing to build the wheel.
Signed-off-by: Bernát Gábor <gaborjbernat@gmail.com>

PEP-662: Add prepare_metadata_for_build_editable

---

pep-0600.rst

- Add a link to PEP 599
- Add a mention to manylinux2014 aliases
c.f. [discussion](https://discuss.python.org/t/pep-600-future-manylinux-platform-tags-for-portable-linux-built-distributions/2414/34) for more details

PEP 600: add manylinux2014 compatibility

---

pep-0513.txt
pep-0571.rst
pep-0599.rst
pep-0600.rst

Per PEP 600:
```
When this PEP is accepted, the previous manylinux PEPs will receive a final update noting that they are no longer maintained and referring to this PEP.
```

PEP 600 supersedes PEP 513, PEP 571, PEP 599

---

pep-0563.rst

The "Backward Compatibility" section in PEP-563 contains an example which
violates Python scoping rules. This PR updates the PEP to say that the example
is not OK and should fail.
See discussion in typing-sig for details [*].
[*]: https://mail.python.org/archives/list/typing-sig@python.org/thread/F2ERQCGB6W6VADR7G6NN4TLMFJECD6EW/

PEP-563: Fixed a nested class example in 

---

pep-0563.rst

This PR fixes the wording in the comments for failing examples in the  "Backwads Compatibility" section as suggested by Guido in #2007.

PEP-563: Fixed the comments for a few examples

---

pep-0517.txt

Make PEP 517 final. It's implemented in most tools now, and has plenty of real-world usage, so I think it's time for it to be made final.
/cc @ncoghlan as BDFL-Delegate for the original PEP, do you agree?

PEP 517: Make final

---

pep-0657.rst

PEP 657: Update the env variable name and the C-API and add some clarifications

---

README.rst

Closes #2014 
Didn't add any notes on the process of how Sphinx & `pep_sphinx_extensions` actually works but added brief instructions on how to build locally and a reference to `build.py`
cc: @pablogsal

Add build process notes to README.rst

---

pep-0657.rst

Consistent with the other existing APIs, e.g `int PyCode_Addr2Line(PyCodeObject *co, int addrq)`.

PEP 657: addr => addrq

---

.github/workflows/deploy-gh-pages.yaml

Fixes last-modified dates in PEP footers by fetching the entire repo when cloning
See for example https://python.github.io/peps/pep-0801/ (2021-07-04) vs https://aa-turner.github.io/peps/pep-0801/ (2018-06-21)
A
cc: @pablogsal

Sphinx - fix last modified dates for PEPs

---

pep-0657.rst

For the background of this change, see the discussion on: https://github.com/python/cpython/pull/26958#issuecomment-873480427

PEP 657: use 0-indexed offsets

---

pep-0657.rst

Added underscores between the words for consistency with flags like:
* [`-X warn_default_encoding`](https://www.python.org/dev/peps/pep-0597/#abstract)
* [`-X pycache_prefix`](https://docs.python.org/3/library/sys.html#sys.pycache_prefix)

PEP 657: Rename opt out command line flag

---

pep-3104.txt

While reading PEP 3104 to understand the ``nonlocal`` keyword, I found the explanation for why an alternative was not chosen to be vague. Further digging revealed an example for why there was a concern that ``.x`` and ``x`` could be used interchangeably. I linked this example as a footnote to save future readers time from digging to find an example. I hope this will increase comprehension of the PEP for future learners.

PEP 3104: Add footnote to give example

---

pep-0101.txt

Per the announcement on the python-dev mailing list:
https://mail.python.org/archives/list/python-dev@python.org/thread/FQW44V4DZFX4GAGOAMAZAN5KDQXCASDU/

PEP 101: #python-dev channel is now on Libera Chat

---

pep-0558.rst

* `pdb` stores `__return__` and `__exception__`` entries on
arbitrary frames, so that feature needs to be preserved
* Some fast locals proxy operations will implicitly update the
underlying shared mapping on the frame
* Anyone explicitly calling `LocalsToFast` is going to want the
read/write proxy, not any of the read-only options (plus it's
hard to fit an essay in an error message)
* Remove lingering reference to the removed `PyLocals_RefreshViews()`

PEP 558: adjustments after updating implementation

---

pep-0617.rst

PEP 617: missing word and grammar

---

pep-0554.rst

new threads are not allowed (including daemon threads) implies that the opposite
is true in isolated=False subinterpreters: that new threads are allowed (*excluding* daemon threads)

PEP 0554: drop wording about daemon threads in isolated subinterpreters

---

.github/workflows/build.yml
pep2rss.py

Fixes https://github.com/python/peps/issues/1085.
This uses docutils to fetch the first paragraph of the PEP abstract and uses that as the `<description>`, and move the PEP author to `<author>`.
Also run the script on the CI to make sure it runs without errors, fix some Flake8 things, and corrects the usage comment.
Check individual commits to see Flake8 stuff separate from new stuff.
Here's for before and after `peps.rss`, including a pair put through an XML tidy to ease comparison.
* [peps-rss.zip](https://github.com/python/peps/files/5429707/peps-rss.zip)
<details>
<summary>before, raw</summary>
```rss
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"><channel><title>Newest Python PEPs</title><link>http://www.python.org/dev/peps</link><description>Newest Python Enhancement …
```

Add PEP abstract to the RSS feed

---

pep-0478.txt

Re: 
* https://www.python.org/downloads/release/python-358/
* https://github.com/python/cpython/releases/tag/v3.5.8

PEP 478: Add release date of 3.5.8 final

---

pep-0621.rst

Under `Entry points` it says:
> The [project.scripts] table corresponds to the console_scripts group in the core metadata.
But the entry points aren't part of the core metadata; they're a separate spec.
I have removed the "in the core metadata" passage, as I can't see a clear way of adding a link to the entry points specification in its place.
There's already a link on line 353, so the user should be able to find the spec.

PEP 621: Remove mentions of core metadata from `Entry points`

---

pep-0533.txt

Inline code is not permitted within links in reStructuredText, and produces malformed output:

PEP 533: Fix links containing inline code.

---

pep-0211.txt
pep-0543.rst
pep-0642.rst
pep-0647.rst
pep-0660.rst
pep-3100.txt

Unbalanced backticks appear in the rendered HTML, as do any additional backticks if there are more than two.
For example:

Remove additional backticks from inline code

---

pep-0657.rst

As per PEP1:
> Once a PEP has been accepted, the reference implementation must be completed. When the reference implementation is complete and incorporated into the main source code repository, the status will be changed to "Final". 
To be pulled in after https://github.com/python/cpython/pull/27047
🎉

Mark PEP657 as Final

---

pep-0558.rst

Further implementation work on the fast locals proxy resulted
in treating the "f_locals" frame storage as an implicitly
updated cache, moreso than treating it as a dynamic snapshot.

PEP 558: Update for fast locals proxy caching design changes

---

pep-0558.rst

* Propose a PyLocals_Kind enum rather than PyLocals_GetReturnsCopy
* Reference python-dev threads from early 2021
* Remove an outdated mention of possibly dropping support for storing
extra f_locals keys in optimised scopes
* Make it more explicit that accessing frame.f_locals in Python
refreshes the f_locals cache on that frame
* Note that read-only views on optimised frames have the same cache
consistency limitations as the read/write proxy
* Fix miscellaneous typos

PEP 558: Incorporate review comments from python-dev posting

---

pep-0008.txt

Two paragraphs in the [Programming Recommendations](https://www.python.org/dev/peps/pep-0008/) section of PEP 8 seem to have the wrong indentation. It is the bullet point regarding usage of `isinstance()`, and it seems to me they are supposed to be a part of that bullet point.

PEP 8: Fix indentation of two paragraphs in list

---

pep-0646.rst

PEP 646: Add section on grammar changes

---

pep-0667.rst
pep-06xx.rst

PEP 667:  Alternative to PEP to 558 for frame.f_locals and locals().

---

pep-0658.rst

During the PEP's evoltion, the data-dist-info-metadata attribute was changed from indicating the metadata's location to merely indicating the file's existence. The exact location should be inferred elsewhere. But we forgot to update the description in the abstract to reflect this.
This was mentioned by @dstufft in the [resolution message](https://discuss.python.org/t/8651/48):
> I will mention there’s one bit of wording that you might want to clean up. It doesn’t really affect the contents of the PEP, but the Abstract still references `data-dist-info-metadata` as the pointer for the location of the metadata file.

PEP 658: Fix attribute description in abstract

---

pep-0646.rst

As suggested by @gvanrossum.
@pradeep90 @fylux

PEP 646: Add additional motivation for why *Ts over Unpack[Ts]

---

pep-0667.rst

Also, some minor fixes to examples, and other edits for clarity.

PEP 667: Update PyEval_GetLocals() to return a borrowed reference.

---

pep-0467.txt

Also make it clearer that memoryview isn't an open issue for the PEP,
it's explicitly outside the PEP's scope.

PEP 467: Drop the bchr builtin proposal

---

pep-0619.rst

> Release Date: Sept. 7, 2021
https://www.python.org/downloads/release/python-3100rc2/
https://discuss.python.org/t/python-3-10-0rc2-is-now-available/10496
cc @pablogsal

PEP 619: Update date for Python3.10rc2

---

pep-0569.rst

PEP 569: Include Python 3.8.12 in 3.8 release schedule

---

pep-0646.rst

As suggested by @gvanrossum.
@fylux Anything else to add here - should we ask the JAX folks you talked to whether they want to contribute a statement for the PEP? And any word from Bas?
@pradeep90 too.

PEP 646: Add explicit section on endorsements

---

pep-0649.rst

one code-block added, and a couple places where URLs were formatted at quotations.
no changes to the text.
I signed the CLA years ago :-)

PEP 649 Cleaning up a bit of formatting.

---

pep-0418/clockutils.py

Normal methods should have at least one parameter (the first of which should be '`self`').
Fixes some of these LGTM.com recommendations:
https://lgtm.com/projects/g/python/peps/?severity=recommendation

PEP 0418: Fix LGTM.com recommendation: First parameter of a method is not named 'self'

---

pep2html.py

Fixes a couple LGTM.com recommendations:
https://lgtm.com/projects/g/python/peps/?severity=recommendation
The "Testing equality to None" commit relates to [PEP 0290](https://github.com/python/peps/blob/master/pep-0290.txt) (_Code Migration and Modernization_):
> Since there is only one None object, equality can be tested with identity. Identity tests are slightly faster than equality tests. Also, some object types may overload comparison, so equality testing may be much slower.
> 
> Pattern::
> ```
> if v == None  -->  if v is None:
> if v != None  -->  if v is not None:
> ```
Anyway, the existing code runs without errors, there is no need to fix this other than "modernization" of the code.

A couple pep2html.py issues

---

pep-0563.rst

Edited two sentences to reflect that PEP 563 won't be default until at least 3.11 if ever.
Resolves python/peps#2084

PEP 563: Correct references to 3.10 default adoption

---

pep-0654.rst

This fixes a small typo on line 61; it changes 'to reraised' to 'to reraise'.

Fixed typo: 'to reraised -> to reraise'

---

pep-0654.rst

Fixed a small error on line 157; 'distunction' to 'distinction'.

Fixed typo: 'distunction -> distinction'

---

pep0/constants.py

pep 1 does not indicate that pep numbers will never be changed
(though I agree that not changing them is a good idea)
closes #2087

PEP 0: changed location of reference to pep 1

---

pep-0013.rst
pep-8103.rst

Updating PEP 13 to include a reference to the 2020 SC election (i.e. PEP 8102).
Also created a draft of PEP 8103.

PEP 13: updated and draft PEP 8103 created

---

pep-0619.rst

https://www.python.org/downloads/release/python-3100/
https://discuss.python.org/t/python-3-10-0-is-now-available/10955
@pablogsal Thanks for the release and the release stream yesterday!

PEP 619: Python 3.10.0 was released on schedule

---

pep-0636.rst

Seen originally at (https://bugs.python.org/issue45370).
Fixing typo `have being doing` to `have been doing`. 
Fixes https://github.com/python/peps/issues/2100

PEP 636: Fix typo: being --> been

---

pep-0654.rst

PEP-654: except *T --> except* T

---

pep-0654.rst

PEP-654: warn that leaf_generator recycles tracebacks

---

pep-0654.rst

Joe Gottman alerted us to an error in this example. Thanks Joe!

[PEP-654] add None check in subgroup example

---

pep-0654.rst

The examples that don't involve except* I generated from the main branch, the ones that do I edited myself.

[PEP-654] update traceback formatting in examples

---

pep-0636.rst

The current example allows the reader to wonder whether the __match_args__ names must match the __init__ args or the class members.  This change explicitly shows that class member names are searched for the __match_args__ items (admittedly at the cost of some clutter).

PEP 636: clarify __match_args__ naming

---

pep-3119.txt

re: sets, "subclass/superclass" should be "subset/superset" when referring to the inequality operations on sets.

PEP 3119: re: sets, "subclass/superclass" should be "subset/superset"

---

pep-0563.rst
pep-0665.rst
pep-0670.rst
pep-0672.rst

Fixes a handful typos detected by [codespell](https://github.com/codespell-project/codespell) in a handful PEPs.
See #2073, #1144, #1113, #294 for similar previous PRs.

Typos found by codespell

---

pep-0670.rst

* Elaborate the performance aspect of a debug build
* Rephrase some sections

Complete PEP 670

---

.github/workflows/build.yml
requirements.txt

See: https://github.com/python/peps/pull/1571#discussion_r478701944
> Fine to try it in another PR, but looks like all that really is needed is to install pygments:
> 
> 1. The `script` step calls `make` to turn plaintext PEPs into HTML, and I assume pygments is only needed here to add colour to the generated HTML files (I'm afk this week so cannot verify this assumption.now).
> 2. Then the `deploy` step calls `deploy.bash` which does `make package` to `tar.gz` the plaintext and generated files and images, and then calls `aws` to actually deploy the `tar.gz` to AWS.

Support code highlighting

---

pep-0670.rst

PEP 670 amendments

---

pep-0670.rst

* Don't convert l-value macros
* Add "Examples of duplication of side effects" section
* Remove the gcc -O0 versus gcc -Og benchmark: it's not relevent for
this PEP.

PEP 670: LTO+PGO benchmark

---

pep-0670.rst

* Elaborate the Abstract
* Add "Misnesting" example
* The return value has already been removed in the public C API macros
* Clarify that converting Py_TYPE() macro was an incompatible change

PEP 670: more examples

---

.github/CODEOWNERS
pep-0674.rst

PEP 674: add myself to CODEOWNERS

---

.github/CODEOWNERS
pep-0675.rst

+ Move in draft from the Google Doc.
+ Turn unicode to ASCII.
cc @gbleaney @JelleZijlstra

PEP 675: Arbitrary Literal Strings

---

pep-0670.rst

PEP 670: fix typo

---

pep-0001.txt
pep-0426.txt
pep-0512.txt
pep-0545.txt
pep-8001.rst
pep-8002.rst
pep-8016.rst

Follow on for https://github.com/python/peps/issues/1956, similar to #2178.
Renames `master` to `main` in some PEPs, for this repo and some references. I've not attempted to rename all, and skipped older ones especially rejected or withdrawn.

PEPs 1, 426, 512, 545, 8001, 8002, 8016: rename master to main

---

pep-0667.rst

PEP 667: Update to account for changes to PEP 558 and feedback from Nick.

---

pep-0646.rst

Our specification implicitly treated it as legal to replace a `TypeVarTuple` with a tuple such as `Tuple[int, str]`. However, we did not mention the natural implications for `*args` or `Callable`. We also did not address the behavior of unbounded tuples.
This led to artificial restrictions (such as "type variable tuples must be of known length").
This PR specifies that, wherever a `Ts` is used, we can legally replace it with `Tuple[int, str]` or `Tuple[int, ...]` or `Tuple[int, *Ts, str]`. Concretely, the following are valid:
+ `*args: *Tuple[int, *Ts, str]`, etc.
+ `Callable[[int, *Ts, str], None]`, etc.
+ `Tuple[int, *Tuple[str, ...]]`, etc.
This replaces #2125 .
cc @mrahtz @gvanrossum

[PEP 646] Allow cleanly substituting any tuple type for a TypeVarTuple

---

pep-0007.txt

PEP7: add PyAPI_DATA() macro, see details #2182

PEP7: add PyAPI_DATA() macro

---

pep-0669.rst

From suggestion from @vstinner: put all the events into an enum and namespace the whole thing.

PEP 669: Add an enum and namespace the interface.

---

pep-0646.rst

@pradeep90 @gvanrossum @stroxler
I'm still not entirely sure that having the compiler emit the equivalent of `next(iter(Ts))` for `*args: *Ts` is the best solution. The alternatives I can think of are:
1. `[*Ts][0]` (uglier, but the bytecode ends up being a little simpler)
2. Directly accessing the property `Ts._unpacked` (less ugly, but less consistent with other uses of the star operator)
Having said that, I also think `next(iter(Ts))` is Good Enough (tm) - and in the first place (I think?) it's not too critical an issue because it's an implementation detail. So happy to discuss this, but also happy not to discuss this :)

PEP 646: Explain the results of the new grammar/compiler change

---

.github/CODEOWNERS
pep-0677.rst
pep-XXXX.rst

The draft of our Callable Type Syntax PEP is in a complete enough state that it is worth moving discussion to github so we have a history of major revisions going forward.
There are still many edits coming and we do not yet have a PEP number, hence keeping this as a draft PR.
Currently open problems (as of December 9) that I plan to get to soon:
- inline references
- add more to the motivation section
- add more to the section comparing to other languages, and possibly touch on possible lambda syntax

PEP 677: Callable Type Syntax

---

pep-0677.rst

Almost nothing material to the proposal itself is changing, the only specification tweak is that we updated the grammar snippet for supporting PEP 646 to include a guard against `'...'`.
All other edits are just for readability:
- fixes for typos and markup issues
- clarifying examples and/or wording
- moving subsections between sections (mainly shrinking "Motivation" and expanding "Rationale")
This closes all open suggestions from review of the initial PR except that:
- I still have a ParamSpec example in Rationale, which may be worth removing
- There's a suggestion to add a `Statistics` subsection to the `Resources` section and I haven't gotten to that yet

PEP 677: Readability and organizational edits

---

pep-0673.rst

Thanks to Eric Traut who tested all the code examples in Pyright and
raised implementation concerns about ``Self`` type in aliases.
I ran into implementation issues in Pyre too. This is because Pyre
preprocesses things like ``Self`` in an early phase and does alias
resolution in a later phase. Mixing the two would lead to a lot of
hacks.
@JelleZijlstra I believe you had some concerns about using `Tuple` this way at runtime. Do we need to include them too?
@gobot1234 What do you think? Do you have any workarounds or strong objections? 
Here is our [prior discussion](https://docs.google.com/document/d/1ujuSMXDmSIOJpiZyV7mvBEC8P-y55AgSzXcvhrZciuI/edit?disco=AAAARP_cNZ4) about aliases on the Google Doc. A user had brought up a concern there too that `Self` outside a class would be confusing. …

PEP 673: forbid Self in type aliases.

---

pep-0639.rst

As requested and discussed at length on the [Discourse thread](https://discuss.python.org/t/pep-639-improving-license-clarity-with-better-package-metadata/2154/170), this is a thorough rewrite of PEP 639, to reflect the numerous additions (PEP 621 metadata, deprecation guidance), changes (use ``License-Expression`` field instead of ``License``, license file handling), updates (to many tools, specs, links, best practices and docs it references in the two+ years since its creation) and reformatting (as a standalone PEP rather than a spec update, inline links per #2130 , headings, various formatting/PEP 12 issues).
Additionally, adds examples, user scenarios and a terminology section (as mentioned there), comprehensively documents the many ultimately rejected ideas suggested during the …

PEP 639: Make requested additions and changes, add additional helpful info, reformat, update and copyedit

---

pep-0677.rst

Thanks to Eric Traut for pointing out that we should be clearer
about our intent here and not just give a grammar snippet.

Clarify our intent to support PEP 646 Unpack in type checking, not just grammar

---

pep2html.py
pep_sphinx_extensions/pep_processor/transforms/pep_footer.py

First step to implementing #2130 , as agreed with @gvanrossum and the PEP editor team.
When building, don't add redundant footnotes and references entries for URLs that are already directly linked inline. This avoids an unnecessary, potentially confusing footnote for each link, and taking up additional space in the references section for no real benefit, plus simplifies the build code and should improve build time, especially for Sphinx. Furthermore, if the references section is empty (not including now-invisible link targets), remove it, as we did before (but in a more robust manner). This allows past and future PEPs to still use inline references with targets stored in the references section, while avoiding showing a now-empty references section.
These are both implemented for Sphinx …

Don't auto-add inline links to ref section & rm if empty, per #2130

---

pep-0007.txt

The removed sentence is sort of a repetition of this previous text:
> * Python versions greater than or equal to 3.6 use C89 with several select C99 features:
>   [...]
>    * C++-style line comments
Versions of Python earlier than 3.6 are EOL'd. Therefore this piece of information has lost its importance, and doesn't warrant repetition.
I explain why I find this sentence is ambiguous in https://github.com/python/peps/pull/2072#issuecomment-921197784.

PEP 0007: C++ style // one-line comments

---

pep-0558.rst

* fast locals proxy never assumes the value cache is already up to date
* operations become O(n) as required to avoid that assumption
* remove `*View()` APIs from proposal due to algorithmic complexity issue
* add Python pseudo-code to the PEP 667 comparison section
* reword PEP 667 comparison section to focus on the remaining differences
in the C API proposal

PEP 558: Adopt Python level semantics from PEP 667

---

pep-0440.txt

>>> from packaging.version import Version
>>> Version("1.dev0") > Version("1.0.15")
False
The way to do version check is suggested by @hugovk.

PEP 440: Extend example to clarify 1.dev0 < 1.0.15

---

pep-0011.txt
pep-0498.txt
pep-0558.rst
pep-0639.rst
pep-0665.rst
pep-0674.rst
pep-0676.rst
pep-0677.rst
pep-3104.txt

Various PEPs: fix typos

---

pep-0677.rst

I'd intended to make this update everywhere in an earlier PR, but missed this line.

PEP 677: Use PEP 646 syntax when discussing unpack

---

pep-0676.rst

xref #2200 
This is the consolidated version I suggested I would write. 
I couldn't work out how to keep @CAM-Gerlach as the 'author' of the formatting commit whilst re-writing history, so I added him as co-author on the commits with the `Co-authored-by:` syntax.
This keeps all the formatting and spelling fixes (two line breaks before a section, all references to use `` `link`_``), and merges the prose updates.
I would like to have this resolved before posting the PEP to `python-dev`, so if anyone (esp @CAM-Gerlach / @hugovk ) has any comments, please would you let me know sharpish!
I also have a 2 part implementation updates PR I'm preparing in a few moments, will link that here when I send it.
A

PEP 676: Formatting and prose updates

---

.github/workflows/deploy-gh-pages.yaml
Makefile
build.py
conf.py
generate_rss.py
pep-0456.txt
pep_sphinx_extensions/__init__.py
pep_sphinx_extensions/config.py
pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
pep_sphinx_extensions/pep_processor/html/pep_html_translator.py
pep_sphinx_extensions/pep_processor/parsing/pep_role.py
pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
pep_sphinx_extensions/pep_processor/transforms/pep_zero.py
pep_sphinx_extensions/pep_theme/static/doctools.js
pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/templates/page.html
pep_sphinx_extensions/pep_zero_generator/writer.py

This PR has implementation updates for PEP 676.
- Cache pip in github actions
- Simplyify parts of `generate_rss.py`, and remove the dependency on `python-dateutil`
- Cache last modified times of each file, speeds up building by 28% on windows (less on unix as subprocess is faster there)
- Remove `pep_sphinx_extensions.config`, add the properties to the document object
- More speed ups with a custom builder, allows removing some patches
- Remove all uses of javascript
- Updated PEP 0 lead to inline links (xref #2130)
- Fix a false positive for the Docutils inliner in PEP 456
A

PEP 676: Implementation updates

---

.python-version
pep-0677.rst

Adding more options that came up in typing-sig and python-dev discussion.

PEP 677: Include more rejected alternatives

---

pep-0677.rst

It isn't entirely clear whether Discussions-To should be typing-sig or python-dev, but PEPs 604 and 585 have a similar purpose and both say typing-sig so I went with that (especially since neither Pradeep nor I generally follow python-dev)

PEP 677: Add Discussions-To and Post-History headers

---

pep-0677.rst

We're getting ready for a final request for comments to python-dev,
so I did one more pass through the PEP to catch remaining readability
issues (I was especially looking for things easier to see on the actual
PEP page with formatting than the rst doc), e.g.:
- found an incorrectly formatted hyperlink
- reworded sentences that seemed ambiguous (e.g. ambiguous pronouns)
- adjusted wording to better match the order of sections

PEP 677: Minor wording and formatting fixes.

---

pep2html.py

As a followup to #2155 (and thus related to #2130 ), this sets a low priority to removing the references section, to fix link references not resolving for some cases on the legacy build system (`pep2html.py`) where the references section gets removed if it would render empty, as apparently otherwise it is removed before it is needed to resolve the refs. Not sure how I didn't catch those cases in testing, but this simple tweak fixes it. Since this breaks proper link resolution on certain PEPs (at least those using multi-layer reference indirection, like [PEP 639](https://www.python.org/dev/peps/pep-0639/)) and fixes a regression, it would be appreciated to merge this promptly. Sorry for not spotting this earlier!
CC: @AA-Turner

Set low priority for rm-ing refs section so refs still resolve correctly

---

pep_sphinx_extensions/pep_processor/transforms/pep_footer.py

Followup to #2227 to fix #2155 for the new Sphinx build; I'd previously attempted to reproduce the issue locally on the same PEP and it apparently didn't occur, but I didn't realize I was looking at a stale built file, and it turns out that in fact the same fix is needed. Sorry for the double PR!

Fix refs section removal breaking external links on Sphinx build too

---

pep-0677.rst

When Pradeep reread the PEP yesterday he noticed that all of `Callable[...]` based versions of `flat_map` are spread across several lines, whereas our demonstration of the new syntax is a one-liner.
Keeping the formatting consistent helps make comparisons apples-to-apples.

PEP 677: Format the flat_map example consistently

---

pep-0673.rst

@JelleZijlstra RFC on the wording and any other links you think we should add.

PEP 673: Mention user requests for the feature.

---

pep-0613.rst

Per discussion on typing-sig
https://mail.python.org/archives/list/typing-sig@python.org/thread/CGOO7GPPECGMLFDUDXSSXTRADI4BXYCS/

PEP 613: Loosen class scope restriction of explicit TypeAlias

---

pep-0677.rst

Thanks to Eric Niewland for catching this!

PEP 677: fix typo in example

---

pep-0458.txt

In [preparation for the 1.0.0 release](https://github.com/theupdateframework/python-tuf/blob/059bfda391893a7e502ed3da5a185ab174e977dc/docs/1.0.0-ANNOUNCEMENT.md) of the TUF reference implementation `python-tuf` documentation referenced in this PEP is being moved. This patch updates the corresponding links in the PEP.
More specifically, the following link changes are performed:
- METADATA.md
to: metadata format section in TUF spec
Note: alternatively this could link to the new location of METADATA.md (see theupdateframework/python-tuf#1769), but the spec seems like a better resource
- TUTORIAL.md#repo-management
to: new metadata API doc on readthedocs and new repo  example/tutorial
- TUTORIAL.md#lazy-bin-walk
to: new hashed bin delegation example/tutorial
- client implementation
to: new …

PEP 458: update references to python-tuf repo

---

pep-0673.rst

- Use `...` instead of a unicode ellipsis
- Fix dataclass definition with defaulted before non-defaulted field

PEP 673: minor fixes to the code samples

---

pep-0008.txt

Parentheses are allowed in 3.10, so I did the minimal change to be accurate.

PEP 8: update example of backslash usage for with statements

---

pep-0677.rst

The `flat_map` function is passing the function first in its calls, so the definition should reflect the same.

Fix function signatures in PEP 677 

---

pep-0674.rst

PEP 674: Relationship with the HPy project

---

pep-0677.rst

I had forgotten to port the detailed spec from
https://docs.google.com/document/d/15nmTDA_39Lo-EULQQwdwYx_Q1IYX4dD5WPnHbFG71Lk/edit
(It was originally separate because I was concerned there might be too much debate and thrash to put it in the PEP, but that did not turn out to be true).

PEP 677: Runtime Behavior Specification

---

pep2html.py

This patches Docutils in `pep2html` to allow the syntax of `` :pep:`title <3000#section>` ``. Users of Sphinx will be familiar with this, and e.g. in #2248 there is no clean way to express the author's intent without this. 
Passing test run at https://github.com/AA-Turner/peps/runs/4872058326 -- from this commit https://github.com/AA-Turner/peps/commit/54499146b8d9e5252b3eb7a0c57054ab238be77c
cc @JelleZijlstra (you've merged a few of my recent ones so sorry for taking advantage of your good nature!)
A

Allow title and fragments in PEP and RFC references

---

.github/CODEOWNERS

Add Adam Turner as the default reviewer for PEP infrastructure

---

AUTHOR_OVERRIDES.csv

While all the other rows had them, the line for `python-dev` in `AUTHOR-OVERRIDES.csv` was missing quotes around `Surname First`, which resulted in the author for the relevant PEPs being displayed as `and Community` instead of `python-dev`, as intended. This PR fixes that, which (confirmed by testing) solves the bug.

Fix missing quotes around python-dev in overrides causing display bug

---

.github/CODEOWNERS
pep-0639.rst

Update the PEP delegate for PEP 639, pending an approving outcome of [the relevant PyPA committers discussion](https://mail.python.org/archives/list/pypa-committers@python.org/thread/TJXEXQHP7XXYC33I5EXCD3KTHWHX2VVO/). Also updates the post history.

PEP 639: Update PEP delegate, post history and CODEOWNERS

---

pep-0655.rst

This branch is easiest to review either:
1. a commit at a time, or 
2. as a sequence of commits together but excluding the last commit "Eliminate many uses of '...' to decrease typographic noise".
CC sponsor @gvanrossum

PEP 655: Integrate feedback from circa Feb 2021

---

pep-0001.txt

This PR is a revision of the closed PR #1445.

PEP 1: Update language on PEP-Delegate field

---

.github/workflows/deploy-gh-pages.yml

cc: @pablogsal 
Relaxes restriction from #1987, builds on PRs from forks.

Only restrict to deploying on pushes to `master` in the python/peps repo

---

pep-0311.txt
pep-0355.txt
pep-0381.txt
pep-0458.txt
pep-3119.txt
pep-3127.txt

Cleanup grating unmodern gender wording text in old PEPs that were pointed out
in #855.

Remove needless gender specific terms. #855

---

pep-0001.txt

Further refine the PEP 1 phrasing around PEP-delegates, as originally opened as #1445 and further reviewed and merged in #2256 . See my review on #2256 for the rationale behind the specific copyedits (which I've further refined since then).
Also, fixes a related instance where `python-dev` instead of the Steering Council was specified as the final approve of PEPs (I plan to open another issue to discuss also mentioning/linking the PEPs category of the Python Discourse, as well as a few related changes).

PEP 1: Further refine phrasing and organization of PEP-Delegate description

---

pep-0001.txt

Prep for [PEP 676](https://python.github.io/peps/pep-0676/), which will give syntax highlighting. By default Python formatting is used:
https://python.github.io/peps/pep-0001/#pep-header-preamble
But we want plain text formatting here.
---
Also update some links to their newly redirected location.
And delete this one:
```
* `Frequently Asked Questions for Developers
<http://docs.python.org/devguide/faq.html>`_
```
Because it redirects to 404 https://devguide.python.org/faq/
Checking the Internet Archive (https://web.archive.org/web/20120301112706/http://docs.python.org/devguide/faq.html#how-do-i-tell-who-is-and-isn-t-a-core-developer) I don't see a matching page on the new devguide?

PEP 1: Use plain text formatting and fix links

---

.github/CODEOWNERS
pep-0676.rst

From discourse. Minor update.
The build might fail due to the `:doc:` role. I wait with bated breath.
A

PEP 676: Mention additional enhacements

---

pep-0646.rst

This is what I meant in https://mail.python.org/archives/list/python-dev@python.org/message/OR5RKV7GAVSGLVH3JAGQ6OXFAXIP5XDX/
Is it OK with you, PEP authors?

PEP 646: Add acceptance note, bump Python version

---

.codespell/exclude-file.txt
.codespell/ignore-words.txt
.codespellrc
.pre-commit-config.yaml
Makefile
requirements.txt

Merely add codespell configuration files, following https://github.com/python/peps/pull/2075#issuecomment-968744828:
* `.codespellrc` is the root configuration file
* `.codespell/ignore-words.txt` list of words that are false positives
* `.codespell/exclude-file.txt` list of lines that contain false positives
Unlike the initial PR #2075, this PR focuses on configuration and does not attempt to add a spelling check to the CI.
A few notes:
* Codespell checks the current directory for a file named [`setup.cfg` or `.codespellrc`](https://github.com/codespell-project/codespell/blob/master/README.rst#using-a-config-file). I have opened https://github.com/codespell-project/codespell/pull/2087, but the request hasn't been accepted yet. In the meantime, in the absence of a `setup.cfg` file, I have …

Add configuration for running `codespell` locally

---

conf.py

RE #2151; fixes Sphinx build.
A

Exclude `.codespell` from Sphinx

---

pep-0013.rst
pep-0245.txt

PEP 13 and PEP 245: Fix incorrect PEP references

---

pep-0008.txt

The document contained two occurrences of `print` used as a statement.
I changed those to functions so that the examples work in modern Python environments.

PEP 0008: Replaced outdated usages of `print` as a statement

---

pep-0013.rst

Fixes https://github.com/python/peps/issues/2268.
Add results from https://python.github.io/peps/pep-8103/#results in simple alphabetical order (as it was before 991815f9367170c0c3bbb3122231cc5c448d38ac).

PEP 13: Update 2022 Steering Council per PEP 8103 results

---

pep-0007.txt

Tweaks the wording of PEP 7 slightly, per @encukou 's suggestion on @erikjanss 's issue, to clarify that compiler extensions are prohibited in general, mentioning GCC and MSVC as specific offenders and retaining the existing GCC example, rather than just only GCC extensions specifically.
Fixes #758

PEP 7: Clarify that compiler extensions are prohibited in general, not just GCC

---

pep-0678.rst

I've added a few sections addressing rejected ideas from [this discussion on Reddit](https://www.reddit.com/r/Python/comments/rmrvxv/pep_678_enriching_exceptions_with_notes/), and laid out my position about non-`str` notes in response to @warsaw's https://github.com/python/peps/pull/2201#issuecomment-1001252610.
My own design intuition is pretty clearly against non-string notes... but my respect for the voice of experience is also strong.  This draft of the PEP therefore describes the current implementation (string-or-None), but I'm open to revising that based on python-dev discussion (planning to post early in the new year).

PEP 678: more rejected ideas

---

pep-0674.rst

PEP 674: Leave PyDescr_TYPE() unchanged

---

pep-0674.rst

PEP 674: only 9 projects are affected

---

pep-0675.rst

Mostly just nits.
+ Ease into the Motivation section for people who are unfamiliar with security stuff.
+ Forward-reference the Other Uses section at the end of Motivation
Remaining: Add an exhaustive list of `str` methods that we will modify. I'm making that a separate PR for ease of review.
cc @gbleaney

PEP 675: Clarify wording in various sections

---

pep-0680.rst

On the discuss thread, questions were brought up about the binary file type: https://discuss.python.org/t/pep-680-tomllib-support-for-parsing-toml-in-the-standard-library/13040/43
Ensuring that it's easy to correctly parse TOML files containing non-ASCII characters on Windows is a good reason to use binary files. This PR adds some words to highlight this reason for using binary files.
cc @hukkin

PEP 680: Further explain why files are read as binary

---

pep-0680.rst

PEP 680: Note that double precision float is a recommendation not requirement

---

pep-0655.rst

PEP 655: Integrate feedback circa Jan 2022

---

pep_sphinx_extensions/__init__.py

Fail the build on warnings or above from the Docutils reporter.
Prompted by Cam in https://github.com/python/peps/pull/2285#issuecomment-1024719088
A

Fail on Docutils warning

---

pep-0675.rst

cc @gbleaney
@JelleZijlstra 
Mostly looking for feedback on the two design choices we need to make:
1. Do we restrict literal-preserving str methods to (a) just the four mentioned in "Type Inference" or (b) to the full set of str methods?
2. Do we (a) overload the typeshed stubs for those methods or (b) leave the str stub as is and ask type checkers to hardcode literal behavior?
We are leaning towards 1b and 2a. Let us know your thoughts. We have also offered to change it if the Steering Council feels strongly.
Also, I recall that, as a typeshed maintainer, you wanted us to give clear recommendations for future typeshed changes. Could you clarify the questions we need to address?
Finally, we'll change the name from `Literal[str]` in a PR after the above stuff is resolved.

PEP 675: List the `str` methods that preserve literal types

---

pep-0675.rst

We discussed a lot of alternatives on typing-sig over the last couple of months. 
`Literal[str]` was pretty strongly rejected. Every candidate had some objection, but `StringLiteral`/`LiteralString` seemed to have quite a lot of support. 
So, we decided to go in favor of `LiteralString`.
cc @gbleaney

PEP 675: Switch to the name `LiteralString`

---

pep-0001.txt

Followup to #1430 and PRs #2256 and #2257 , and discussed on python/steering-council#97 , to ensure the description of how PEP delegates should notify and request approval of the Steering Council is clear and consistent, and matches actual established practice, based on the descrepencies with the current merged language identified by @AA-Turner and discussed further with @willingc .

PEP 1: Further clarify PEP-Delegate notification & acceptance process

---

pep-0594.rst

Per the consensus of the discussion in #2262 , it doesn't really make sense to mention the EOL date of Python 3.11 with the retargetting of PEP-0594 for Python 3.11-3.13, as opposed to Python 3.10 (last version without the warning) and/or Python 3.12 (last version with the deprecated modules). This revises that PEP to add both useful dates; I can revise this to eliminate one or the other can be eliminated if the PEP author desires, but I included both here for completeness. Thanks.

PEP 594: Revise EOL dates mentioned to reflect relevant Python versions

---

pep-0675.rst

Minor formatting and wording fixes.

PEP 675: Minor formatting and wording fixes

---

pep-0681.rst

Fix field_descriptors type annotation to match in-use alternate form.

PEP 681: Fix type annotation of field_descriptors param

---

pep-0675.rst

We don't strictly rely on Self type PEP and people on typing-sig asked that we mention it in the "Requires" field. Better to just remove the dependency.
Also link to Perl's taint (runtime taint-checking) and thank David and Arie.
cc @gbleaney

PEP 675: remove unnecessary reference to Self type PEP

---

.pre-commit-config.yaml
pep-0012.rst
pep-0340.txt
pep-0427.txt
pep-0491.txt

In #2209 , @AA-Turner removed the legacy implicit PEP/RFC link logic, and batch-converted existing PEPs to use explicit `:pep:` and `:rfc::` roles to reference other PEPs and RFCs, rather than relying on hacky, fragile and limited implicit links, or hardcoding URLs (often in footnotes). However, PEP 12 has not been updated accordingly to reflect this, still containing a substantial quantity of outdated language on this point.
Therefore, it was updated to update these now-misleading descriptions and examples, describe the new practice and explain and give examples of its use. This also, as a necessary side effect, addresses the most straightforward and obvious aspects of #2130 , though I will address the remaining parts of it not directly concerned with PEP/RFC links and footnotes thereof …

PEP 12: Update guidance on linking PEPs/RFCs per recent changes, and add check for it

---

.github/CODEOWNERS

The `.pre-commit-config` filename was mistakenly listed with the `yml` extension rather than the correct (and standards-conforming) `yaml` extension. Thus, it wasn't actually working correctly. Also, fixes a couple trivial sorting issues.

Fix pre-commit-config filename in codeowners and re-sort

---

pep-0678.rst

Following [the post on python-dev](https://mail.python.org/archives/list/python-dev@python.org/thread/IMNZE4HN7VNWS5SROMFOLHQQVYHUYT77/) which requested [comments to this Discuss thread](https://discuss.python.org/t/pep-678-enriching-exceptions-with-notes/13374), I've updated PEP 678 with Post-History and some minor clarifications following that discussion.
I believe that after this PR is merged, the PEP is ready for consideration by the Steering Council.
My deep thanks again to everyone who has helped me through this, especially the many thoughtful commenters, those who proof-read and contributed fixes, and to Irit for her support and sponsorship throughout :pray:

PEP 678: add post-history, minor tweaks following discussion

---

pep-0680.rst

If I'm not mistaken, the link pointed to a comment from a flake8 user/contributor. I changed it to point to a comment by a maintainer.

PEP 680: Fix link

---

pep-0639.rst

Following @pfmoore and @brettcannon 's feedback, I've revised some of the `License-File` text to state that it represents a record of the license file relative paths in the project source tree, and in the PyPA-specified distribution and installed projects formats to the file paths relative to the defined license root directory, with its meaning in unspecified legacy, new and non-standard distribution, installation and metadata formats defined by the needs of the particular format. I've also clarified a bit of terminology elsewhere.
Also, as another incremental step toward reducing the length of the PEP, I've eliminated the superfluous "Future PEPs" section, since none of those speculated PEPs are directly germane to this one, and also greatly slimmed down the terminology section, …

PEP 639: Clarify License-File field, slim down terminology & remove future PEPs

---

pep-0517.txt

PEP 517 was made final in https://github.com/python/peps/pull/1712, so the section is outdated and can be removed.

PEP 517: Remove "Provisional acceptance" section now the PEP is Final

---

pep-0594.rst

While it was removed from the prose, the table still mentions `lib2to3` as being a module to keep. This removes it from the table as well, along with fixing a few RST syntax issues.

PEP 594: Remove old lib2to3 keep table entry and fix RST syntax issues

---

pep-0675.rst

They were top-level sections.
I also moved up the Runtime Behavior section to answer the question of
where LiteralString lives, since right now it's buried in the PEP.
cc @gbleaney

PEP 675: nest sections under Specification

---

pep-0678.rst

Per https://github.com/python/peps/pull/2294#issuecomment-1028848346

PEP 678: convert footnotes to inline links and hard wrap to 79 cols

---

pep-0682.rst

PEP 682: Fix pre-commit issue with backticks

---

pep-0007.txt

PEP 7: prefer static inline functions

---

pep-0682.rst

* fill in `Discussions-To`
* fix wording of Rationale forward references
* remove use of `code-block:: pycon`, since it applies a proportional font to `>>>` and `...`, which looks odd and misaligns indents

PEP 682: Discussions-To and minor fixes

---

pep-0682.rst

* clarify supported presentation types
* cite Rust survey
* note C99 use of `z`

PEP 682: small additions

---

pep-0630.rst

- Make it clear that it's not necessary to convert all static types to heap ones
- Make it clear that this is a generic guide, and doesn't cover stdlib-specific issues
- Add PyType_GetModuleByDef, closing the `#1` open issue
- Add an open isssue re. converting “losslessly” to heap types
I'd like to apologize to everyone who was misled by the previous version of this PEP.
When I wrote it, I thought heap types were definitely the correct direction, and wrote the text with that in mind. But it turns out that this PEP could be used as the *only* rationale for converting to heap types. That wasn't my intention.
I still think heap types are good, especially in third-party modules, all else being equal. But  in the stdlib, there should be a specific reason for each heap type conversion.
I hope …

PEP 630: add disclaimers re. heap types & conversion, add PyType_GetModuleByDef

---

pep-0675.rst

The document was drafted and discussed on typing-sig, which is perfectly acceptable for this PEP.
But as a general PEP, it should briefly establish its context.
(The PR just adds `Using static type annotations,`, splits a  sentence that becomes too long, and adjusts capitalization.)

PEP 675: Establish typing context in the Abstract

---

pep-0675.rst

The new title makes it much clearer that this PEP is about types rather than string values.
Also adjusted the wording of the first line of the Abstract. I changed
"static type annotations" to "type annotations" since the "static" part
is redundant.
cc @gbleaney

PEP 675: add "Type" to title and add post history

---

.github/CODEOWNERS
pep-0683.rst
pep-06XX-immortal-objects.rst

I plan on merging/posting this as soon as I get a review from my co-author.

PEP 683: Add a PEP for immortal objects.

---

pep-0675.rst

+ Add newlines to make code samples easier to read.
+ s/argument/parameter/.
cc @gbleaney

PEP 675: fix wording in a couple of places

---

pep-0675.rst

See this [FAQ](https://www.chicagomanualofstyle.org/qanda/data/faq/topics/Punctuation/faq0036.html).

PEP 675: use semicolon instead of comma

---

pep-0594.rst

Just a few things I noticed on my read-through.

PEP 594: Apply typofixes & language tweaks

---

pep-0594.rst

A [new discussion thread](https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508) was opened for this PEP on Discourse following the last round of updates; this updates the PEP headers to reflect that.
First noticed by @hugovk in #2334

PEP 594: Update Discussions-To link and date with posting of new thread

---

pep-0683.rst

These are extensive changes in response to the [python-dev thread](https://mail.python.org/archives/list/python-dev@python.org/thread/TPLEYDCXFQ4AMTW6F6OQFINSIFYBRFCR/#EPH3PGNKUBUZK26Z2M4SQSPUVIGXZUNB).

[PEP 683] Immortal objects v2

---

pep-0655.rst

Did add syntax-highlighting syntax as requested by {@AA-Turner , @hugovk , @CAM-Gerlach }.
However when I try to regenerate the PEP and view it locally, the marked block doesn't actually appear with any syntax-highlighted colors. Seems strange to use a notation that has no effect on the generated output.
Am I missing something? Is there a setting needed to actually enable syntax highlighting?

PEP 655: Highlight TypeScript code snippet correctly

---

pep-0668.rst

See https://discuss.python.org/t/graceful-cooperation-between-external-and-python-package-managers-pep-668/10302/26?u=pradyunsg

PEP 668: Change title to better summarise the content

---

pep-0678.rst

Without recapping the diff, [further discussion of translating messages](https://discuss.python.org/t/pep-678-enriching-exceptions-with-notes/13374) on discuss.python.org prompted this updated design, which handles multiple notes by way of representing a sequence, rather than concatenating strings.
It is also, while I do anticipate further expansion, high time for an acknowledgements section.

PEP 678: Update proposal with `.add_note()` and acknowledgements section

---

pep-0654.rst

I just ran the examples in the PEP and found two that have a stale output.
Quite a while back we decided that we won't add an implicit wrap by an ExceptionGroup when propagating only one exception from an except*.

PEP 654: Fix output of two examples

---

pep-0001.txt

Presently, PEP 1 states that PEPs will be checked via Travis CI a couple places, which this PR updates to refer to generic "CI" (in case we change from GHA in the future, since such implementation details have no business being in a governance PEP). Also, it updates a few related outdated references referring to the legacy plain-text format in new/active PEPs.

PEP 1: Update outdated language referring to Travis CI and plain-text PEPs

---

pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
pep_sphinx_extensions/pep_processor/transforms/pep_zero.py

xref https://github.com/python/peps/pull/2344#issuecomment-1046438174
A

PEP 676: Display mailing list names for thread links in Discussions-To

---

pep-0683.rst

PEP 683: Fix some typos

---

pep-0655.rst

A followup to the issue just raised on [Discourse](https://discuss.python.org/t/pep-655-required-and-notrequired-for-typeddict/13817) and #2266 . Currently, PEP 655 doesn't actually link the canonical discussion thread, requiring community members interesting in reading or contributing to the discussion to Google and guess to find the official discussion, or fragmenting it into multiple different threads, making following and reviewing it more difficult for both SC members/PEP-delegates and the community alike. This PR links what I believe is the correct thread, resolving this issue.
As an enhancement to the previous approach, and tested and confirmed with both build systems and our linting suite, it uses an inline link, which keeps the conciseness and human-readability of just stating …

PEP 655: Add Discussions-To link to the actual thread

---

pep-0675.rst

It looks like PEP 675 hasn't yet been updated with the link to the latest official discussion thread (potentially contributing to the uncertainty of the community member on #2282 as to where to submit substantive feedback), which I believe I found after a fair amount of digging and a bit of guesswork. As such, this PR does just that.
CC: @pradeep90

PEP 675: Add link to official discussion thread

---

.github/CODEOWNERS
CONTRIBUTING.rst
Makefile
README.rst

Adds a description of how to run the linting and spellcheck locally to the README and Contributing Guide and an admonition against mass spellcheck PRs, as well as updates the codeowners for the linting-related infra.
The contents of the README vs. Contributing Guide are a touch disjointed, and the content in the former pertaining to the Sphinx builds is somewhat out of date and duplicated/redundant to that in the docs directory (and in the ``--help`` of ``build.py``), but I didn't touch that here for now.
Fixes #2265

Describe running lint and spellcheck locally in README/Contributing guide

---

pep0/output.py

PEP 0 has an empty references section at the bottom in the old docutils builder on Python.org (it renders as expected via PEP 676)...my fault, again. Apparently, despite my local testing previously, it doesn't actually get removed, at least when run via the Python.org system. Yet one more thing PEP 676 will fix, but for now, this removes that vestigial invisible section heading at the source. Tested to produce the expected results with `genpepindex.py` and `pep2html.py` (has no effect on the new build system).

PEP 0: Don't add title for empty references section

---

pep-0670.rst

* Clarify how arguments are cast
* Limited C API 3.11 no longer cast arguments
* No longer remove return value
* Require to not change the return type
* Don't change macros having multiple return types

PEP 670: clarify cast; don't change return type

---

pep-0654.rst

PEP-654: add number of sub-exceptions to BaseException.__str__

---

README.rst

As noted in #2265 and #2352 , the Readme still has some redundant and somewhat outdated/out of sync information versus what is currently in the build docs (`doc/build`) and the ``build.py`` script, including detailed description of setting up, building and viewing the docs with Sphinx that is now covered in updated form in `doc/build.rst`, and listing the `build.py` options, which are now in the script ``--help``, and are redundant and will drift out of sync here, and which we removed from `build.rst` for that reason. Therefore, for each, we refer the reader to the respective canonical sources for this information, while leaving a concise high-level summary remaining in the Readme.

Replace old Sphinx build info/options in Readme with summary & doc link

---

pep-0001.txt
pep-0012.rst
pep-0012/pep-NNNN.rst

This updates PEP 1 (and a few small relevant parts of PEP 12 and the template) to reflect present real-world practice by the SC , as well as the recommendations we agreed on in #2266 , in order to clarify the current process for official discussion, announcement and resolution of PEPs, and improve the experience for PEP authors, the SC/delegates and the community, and avoid confusion, uncertainty and mistakes around these points, and update/remove related out of date content that no longer accurately reflects the _de jure_ or _de facto_ process.
As part of this change, it re-organizes the various scattered, sometimes duplicative or even contradictory paragraphs discussing PEP discussion, announcement and similar into one coherent section, with a clearer, more sequential and logical …

PEP 1: Update to reflect best practices in PEP annoucement/discussion

---

pep-0544.txt

I've been reading through some PEPs to better educate myself about Python, and I found some room for improvement in PEP 544 "Protocols: Structural subtyping (static duck typing)". I made three separate commits to make it easier to accept/reject them individually:
- ~`PEP 544: Fix errors in class object example`~: While reading through the PEP, I noticed that the comments for type errors were reversed in the third code block in the "`Type[]` and class objects vs protocols" section. I ran the example through mypy 0.931 using Python 3.10.2 to verify I was correct, and it found some other errors that I needed to fix before I could get the expected error:
```console
$ mypy example.py
example.py:11: error: Incompatible types in assignment (expression has type "Type[C]", variable has type …
```

PEP 544: Replace broken link to Zope documentation

---

pep-0001.txt
pep-0012/pep-NNNN.rst
pep2html.py

As mentioned in #2352 , despite every single PEP in the repo, even PEP-0009, using `Content-Type: text/x-rst`, the obsolete plain text format described in said PEP, with `Content-Type: text/plain`, is still the default (at least in the old docutils-based system; this is fixed in the new PEP 676 Sphinx-based one).
Therefore, this flips the default to `text/x-rst`, and updates PEP 1 and the reST PEP template accordingly (which up until now, lacked a Content-Type header entirely, meaning that PEPs would in fact render as plain-text). This makes the Sphinx and docutils build systems consistent, allows simplifying the Readme, Contributing Guide, PEP 1 and the template, and sets the stage for eliminating this now-redundant field entirely in the future (e.g. if/when acceptance of PEP 676).

PEP 1: Make text/x-rst officially the default and update accordingly

---

pep-0007.txt

PEP 7: Python 3.11 uses C99 and C11

---

pep-0678.rst

Final (🤞) update to the PEP, before I ask the steering council to consider it 🙂

PEP 678: `del err.__notes__`, and why we're not just using a list

---

pep-0655.rst

Thanks for the related feedback @JelleZijlstra and Mehdi Drissi!

PEP 655: Motivation: Enables mixed key requiredness in the TypedDict alternative syntax

---

pep-0541.txt

Noticed when checking through the changed files in #2361, simple enough to fix.
reST is very pernickety about nested lists -- the two extra spaces here created a block-quote with a list inside it, which I don't expect was intended.
A

PEP 541: Fix markup in nested lists

---

generate_rss.py
pep_sphinx_extensions/pep_processor/html/pep_html_builder.py

PEP 676: Use `docutils.nodes.Node.findall`

---

CONTRIBUTING.rst
README.rst

Some of the content in the Readme and Contributing guide is somewhat out of date. Furthermore, a number of PEPs and other resources are mentioned but not linked directly, it doesn't fully conform with the guidance in PEP 1 and PEP 12 (particularly recent changes), and there are some grammar, copyediting and reST formatting issues. 
This PR fixes all that, aside from the linting additions in #2338 , the follow-up to add a section describing what edits to existing PEPs are generally considered helpful, and the removal of the outdated PEP 676 information now discussed in the `docs/` subdir and/or `build.py --help`.
Also, it contains a section that discusses in some detail steps to take before writing a PEP, which duplicates and is somewhat out of sync from PEP 1. Instead, I made the …

Update, copyedit and format Readme and Contributing Guide

---

pep-0012.rst

Presently, PEP 12's guidance on including and describing images is thoroughly outdated and does not reflect the present reality, well-established best practices nor accessibility standards. This PR updates it to do so, by:

PEP 12: Update outdated image and comment formatting guidance

---

pep_sphinx_extensions/__init__.py
pep_sphinx_extensions/pep_processor/parsing/pep_role.py
pep_sphinx_extensions/pep_processor/transforms/pep_references.py

This adds the PEP number, title, and section target title to the title text of the link element.
A

Add PEP titles and sections as reference title text

---

pep-0572.rst

Changing typo from "parenthesize" to "parentheses".

PEP 572: Typo, parenthesize -> parentheses

---

pep-0683.rst

This is mostly changes in response to https://mail.python.org/archives/list/python-dev@python.org/thread/KDAR6CCMPOX36GQJUDWHQBKRD5USNV3B/.  Also, we increase the focus on the immutability of per-object runtime state.

PEP 683: Immortal Objects v3

---

pep-0678.rst

Following https://github.com/python/steering-council/issues/105#issuecomment-1056023519.

PEP 678: Clarify how the notes tuple is updated and when it is copied

---

pep-0012.rst
pep-0012/pep-NNNN.rst

As proposed by @JelleZijlstra in [this comment](https://discuss.python.org/t/one-sentence-per-line-for-peps-and-more/13920/13) and widely agreed on there.

PEP 12: Update spacing/breaking conventions to match current practice

---

.pre-commit-config.yaml
pep-8100.rst
pep-8101.rst
pep-8102.rst
pep-8103.rst

In [a comment](https://github.com/python/peps/pull/2374#discussion_r818033566) on #2374 , @hugovk mentioned that while PEP 12 unequivocally specifies that tabs should not be used in PEPs and spaces used instead, we don't currently have a linting check for this (which I thought we did). This allowed tabs to slip into list of core developers present in PEPs 8100-8103. Therefore, we convert them to spaces, in conformance with PEP 12 and the rest of the PEPs, and implement a simple linting check in case any sneak by in the future.

Lint: Implement check for spaces, not tabs per PEP 12

---

pep-0681.rst

@NeilGirdhar noticed that having a `kw_only` field descriptor parameter was called out as a rejected idea, but it is supported by `dataclasses.field` as of Python 3.10. This section of the spec was not properly updated after https://bugs.python.org/issue43532 was fixed.
- Removed the corresponding "Rejected Ideas" subsection
- Added `kw_only` in the "Field descriptor parameters" section
- Mentioned `match_args` (also added in Python 3.10) in the "Decorator function and class/metaclass parameters" section. We already mentioned `slots` (the last "new in 3.10" parameter) there.
- Clarified that field descriptors support all `dataclasses.field` parameters except those that do not have an impact on type checking. For example, `hash` is not supported since it only changes the code within the …

PEP 681: kw_only field descriptor parameter is supported

---

pep-0681.rst

Removed the "Alternate form" section and the mention of the alternate form in the "Reference Implementation" section.
Now that the `dataclass_transform` decorator is available in `typing_extensions`, the fact that Pyright supports the dundered alternate form (`__dataclass_transform__`) is not particularly interesting and has caused some reader confusion.
This needed to be removed before requesting PEP approval anyway.
cc: @davidfstr

PEP 681: Remove discussion of alternate form

---

pep-0681.rst

Please see individual commit messages for explanation of each change made.

PEP 681: Fix minor formatting and typographical issues

---

.github/CODEOWNERS

All entries here must be for people who have push access to the repo.
@pjeby left the core dev team in 2020 according to https://devguide.python.org/developers/
@erlend-aasland is not a core dev (yet)

Meta: fix CODEOWNERS

---

pep-0681.rst

Responding to @encukou's feedback on Typing SIG
- Added sentence in abstract explaining the PEP's impact on CPython
- Added link in abstract to dataclasses documentation

PEP 681: Describe CPython changes and include docs link

---

pep-0619.rst

Remove duplicated expected Python 3.10.8 release date.
This probably doesn't require the CLA.

PEP 619: Remove duplicated expected release date

---

pep-0001.txt
pep-0012.rst
pep-0012/pep-NNNN.rst

As requested on #2335 by multiple people, [discussed and documented](https://github.com/python/peps/issues/2266#issuecomment-1045676523) in #2266 and as a followup to PR #2346 , where it was also independently requested by another reviewer.
The `Discussions-To` link, while helpful in providing the latest/current thread (which is hopefully cross-linked to any previous threads) is currently transient, and does not preserve the history of previous discussion threads. This is useful to retain for most of the same reasons linking the current thread is, to document and allow readers to explore and learn from the discussions that led to a PEP, enable the Steering Council, PEP-Delegate and other reviewers to examine the full discussion history, and track such threads for authors and other …

PEP 1 & 12: Have Post-History link posts to preserve Discussions-To history

---

pep-0684.rst

In #2393 , the ``Discussions-To`` header of PEP 684 was updated to an invalid format, per the initial discussion in #2266  documentation in #2346 , initial processing implementation in #2351 , final implementation and full conform in #2361 , and as stated in PEP 1 (PEP-0001) and PEP 12 (PEP-0012) and approved by the Steering Council in python/steering-council#113 . This PR fixes that.
To note, I've already implemented and tested updates to the validators to catch regressions like this and hopefully avoid this incident in the future, so that the headers can be easily parsed programmatically (which allows us to do all sorts of nice things without having to touch existing PEPs or ask anything more of PEP authors), and PEP authors are given immediate and specific feedback in case of mistakes. …

PEP 684: Fix invalid format for Discussions-To header

---

pep-0685.rst

I corrected a handful of technical, syntax and PEP 12-conformance issues, including with links, mistakenly-retained template text, reST syntax and code block formatting. Furthermore, I proofread for a few apparent typos, spelling mistakes, missing punctuation and grammar errors. Finally, I copyedited it to use clearer phrasing, appropriate diction, avoid distracting repetition, and add a few small clarifications.
Also, should @pfmoore be added as PEP-Delegate, given his standing delegation for packaging metadata and related PEPs?
There was one much more significant issue with the contact that affected a number of areas in the PEP, including some consequentially not accurate statements, but I don't address that anywhere here as its obviously much more appropriate for the discussion thread.

PEP 685: Conform to PEP 12, address textual errors and improve clarity and phrasing

---

.github/workflows/lint.yml
.github/workflows/render.yml

Similar to https://github.com/python/cpython/pull/30419.
Whilst we're deciding whether to use something like Read the Docs that builds [hosted previews of PRs](https://docs.readthedocs.io/en/stable/pull-requests.html), we can use https://github.com/actions/upload-artifact to create a zip of the rendered PEPs built on the CI.
This makes testing/reviewing a bit easier: no need to checkout the branch and build locally. Also reviewable on mobile.

Infra: Upload rendered PEPs as GitHub artifact

---

build.py
pep_sphinx_extensions/__init__.py
readthedocs.yaml

See #2, https://github.com/python/docs-community/issues/10 for context.
Adds support for building PEPs with Read the Docs (or any external documentation builder).
A

PRS: Enable PR previews

---

pep-0001.txt
pep-0458.txt
pep-0480.txt
pep-0495.txt
pep-0525.txt
pep-0532.txt
pep-0550.rst
pep-0603.rst
pep-3147.txt
pep_sphinx_extensions/pep_theme/static/dark.css

As detailed at https://discuss.python.org/t/styling-of-peps/13270/25?u=hugovk and https://discuss.python.org/t/styling-of-peps/13270/26?u=hugovk, a number of images need adapting to display in dark mode.
Use CSS to invert those images in PEP-0001 and marked :arrows_counterclockwise: above.

Dark mode: invert some images

---

pep-0594.rst

The SC announcement:
> We are accepting [PEP-594 2](https://peps.python.org/pep-0594/) _Removing dead batteries from the standard library_.
> 
> It removes a non-controversial set of very old unmaintained or obsolete libraries from the Python standard library. We expect this PEP to be a one time event, and for future deprecations to be handled differently.
> 
> One thing we’d like to see happen while implementing it: Document the status of the modules being deprecated and removed and backport those deprecation updates to older CPython branch documentation (at least back to 3.9). That gets the notices in front of more people who may use the docs for their specific Python version.
> 
> Particular care should also be taken during the pre-release cycles that remove deprecated modules. If it …

PEP 594: Mark as accepted

---

pep-0594.rst

Resolution: https://discuss.python.org/t/13508/22
Follow on from https://github.com/python/peps/pull/2414.

PEP 594: Set Resolution header

---

pep-0659.rst

PEP 659: Link to final version of Brunthaler paper

---

pep-0673.rst

Changes:
- Name protocol to match usage
It would have been possible here to change the bound of the `TypeVar` on line 495 to 'Shape', however I've opted to change the names of the definitions so that they match the later (similar) definitions of this protocol.
- Fix example generic class name
I'm guessing this was just a copy/pasta error or similar; there is no generic class named 'Foo' which is in scope here, however there is a 'Bar' that has just been defined and isn't yet used.

PEP 673: Fix a couple of typos

---

Makefile

For https://github.com/python/peps/issues/2402.
Fixes https://github.com/python/peps/issues/2403.
The pre-commit tool can be called as a module as `pre_commit`: https://github.com/pre-commit/pre-commit/issues/1627#issuecomment-704373290
This allows us to choose which Python version to use:
```sh
make lint
make PYTHON=python3.7 lint
make PYTHON=/Users/huvankem/.pyenv/shims/python3.8 lint
```
And the tools are installed inside a venv using the given Python version.
This is based on the CPython docs [`makefile`](https://github.com/python/cpython/blob/main/Doc/Makefile) and devguide [`makefile`](https://github.com/python/devguide/blob/main/Makefile), so should follow a familiar pattern.

Lint: call tools inside venv using make's PYTHON

---

pep-0440.txt

PEP 440: note that setuptools comparison is historical

---

pep-8001.rst
pep_sphinx_extensions/pep_zero_generator/writer.py

Currently, `Accepted` but not yet implemented (`Active`) PEPs of the `Process` types are getting dumped into the "Historical" category, which isn't accurate and makes them much less visible, despite being in the process of implementation. Both PEP 581 (PEP-0581), the GitHub issue migration, and PEP 676 (PEP-0676), outlining the new PEP build system, fall into this category, despite both being actively in the process of being implemented and certainly not "historical".
Also, I noted PEP 8001 (PEP-8001) on the governance model vote is still listed as "Accepted", despite said vote having concluded (and the resulting decided-upon SC governance model fully implemented) years ago, so it _does_ belong in the "historical" category.
As such, I've tweaked the classification logic to sort `Accepted` …

Meta: Classify Accepted Process PEPs as non-historical & mark PEP 8001 Final

---

conf.py
pep_sphinx_extensions/__init__.py

Closes #2405, closes #2404
This PR specifies a whitelist of files to include in the rendering. It currently monkeypatches Sphinx, although I hope to add support upstream for this in general (specifiable via `conf.py` etc)
A

PRS: Explicitly list files to render

---

pep_sphinx_extensions/pep_theme/static/style.css

Styling: Remove field block highlights and restore definition list indent

---

pep-0339.txt

I stumbled upon this broken link while trying to find another obsolete link to this paper on www.python.org. I realize it's old news, but the fix seems trivial, and should stay unbroken as long as legacy.python.org is running.

PEP 339: Fix broken link

---

pep_sphinx_extensions/pep_theme/templates/page.html

1. Go to https://web.dev/measure/
2. Enter https://peps.python.org/ and RUN AUDIT
(Alternatively, Chrome devtools has a Lighthouse tab to run the same thing.)
https://peps.python.org/
> **Buttons do not have an accessible name**
When a button doesn't have an accessible name, screen readers announce it as "button", making it unusable for users who rely on screen readers. Learn more.
https://web.dev/button-name/?utm_source=lighthouse&utm_medium=lr says:
> For buttons without visible labels, like icon buttons, use the `aria-label` attribute to clearly describe the action to anyone using an assistive technology [...]
https://pep-previews--2426.org.readthedocs.build/
(There are of course further manual accessibility things that can be checked.)

Accessibility: Add aria-label to clearly describe the dark mode button

---

pep-0020.txt

As reported by @brettcannon in #2430 , PEP 20 (PEP-0020), the Zen of Python, has some quirks under the new build system, particularly strangely-displayed syntax highlighting. This is due to the assumed default of `python` for code blocks, when they are actually just text here. As such, this PR converts the code blocks to the explicit ``.. code-block`` syntax with language declarations, plus updates/removes a few other out of date bits of the old format in the process.
Now that PEP 676 is accepted and live, I will update PEP 12 to explain this for current and future authors, and ensure the other active core/meta-PEPs also reflect it. Following that, I'll also go through and check the other old PEPs for similar issues, and fix those I find in as low-impact manner as practical (i.e. adding a …

PEP 20: Fix syntax highlighting and other minor syntax/formatting issues

---

pep-0673.rst

PEP 673: Fix syntax highlighting

---

pep-0537.txt
pep-0569.rst
pep-0596.rst

This week's security releases for 3.7-3.10 went out today:
https://discuss.python.org/t/python-3-10-3-3-9-11-3-8-13-and-3-7-13-are-now-available-with-security-content/14353
Pablo already updated the 3.10 PEP: https://github.com/python/peps/commit/9beb2bee45de33fcdf51d5397a4ff16be14c16be
This PR updates the 3.7-3.9 PEPs.

PEP 537, 569, 596: Update bugfix release date

---

pep-0685.rst

Clarifications:
* Refine description of PEP 503 substitution to avoid implying that only the substitution character (`-`) is replaced or that only collapsing is done, and slightly expand examples.
* Add that a critical distinction between `safe_extra()` and PEP 503 is normalizing non-PEP 508 characters, avoid implying that only collapsing (as opposed to both collapsing and replacement) is not done for `-` and `.`, and briefly mention the further inconsistency with the function's docstring.
* Tweak discussion of PyPI results to explicitly make clear that potential "clashes" were global, not project-specifc
* Clarify what specifically was being followed in Setuptools and that a key factor in going with PEP 503 instead was a lack of real-world backward compat issues
Copyedits:
* Fix some …

PEP 685: Copyedit and fix various minor issues following further changes

---

pep_sphinx_extensions/pep_theme/static/style.css

In #2300 , it was reported that the vertical margin varies substantially between entries with multiple paragraphs (i.e, another `<p>` element) and those that only have one (i.e. just text, no `<p>`). Furthermore, the margins are still pretty tight as @pradyunsg reported, making them uncomfortable to read; they should be at least equivalent to the normal margin between paragraph-level elements. 
PEP 639 is a canonical example [without](https://peps.python.org/pep-0639/#terminology) and [with](https://pep-previews--2427.org.readthedocs.build/pep-0639/#terminology) this PR.
----
----
This resolves both of those concerns by just ensuring that `dl dd` (except headers and footnotes, which are already overridden) have the same `0.5rem` bottom vertical margin as paragraphs do:
----
---- …

Style: Fix vertical margins of def lists w/o <p>s to match those with

---

pep-0594.rst

It looks like 3.8 was the targeted version in the [first draft](https://github.com/python/peps/blob/7799178afdf53a2a681a3ed1bf85fd6303355348/pep-0594.rst), that was missed when updating 3.8 to 3.11 in the [recent revival](https://github.com/python/peps/commit/9906d568766862be269534468fcd4b9e1a8deaa6)?
At least there are no existing deprecations for it (yet).

PEP 594: Fix typo: deprecate nis in 3.11 not 3.8

---

pep-0668.rst

This preserves the protections afforded by these changes, in container
images.
See [this comment](https://discuss.python.org/t/graceful-cooperation-between-external-and-python-package-managers-pep-668/10302/15?u=pradyunsg) for context.

PEP 668: Keep the marker file in container images

---

.github/CODEOWNERS
pep-0686.rst

Technical-only updates to PEP 686 (PEP-0686) per PEP 12 (PEP-0012):
* Use the `:pep:` role instead of hardcoded PEP URLs (the checkers are supposed to catch this, but I was still in the process of updating it to check for the new URL format; I'll have that very shortly)
* Use links instead of footnotes for references (see #2130)
* Add the `Discussions-To` and `Post-History` headers now that the [thread](https://discuss.python.org/t/14435) is live (it should be updated whenever a new discussion thread for the PEP is posted, so people know where to go to give feedback)
* Add @methane as the owner of PEP 686 in `CODEOWNERS`
@methane in the process, I also noticed some grammar issues in the PEP, but I refrained from changing the text here. If you'd like me to follow up with another PR for …

PEP 686: Update URLs, PEP references, Discussions-To and CODEOWNERS per PEP 12

---

pep-0630.rst

Two more things to watch out for.
I'm almost ready to convert this PEP into a HOWTO page in the CPython docs. I'd welcome any copy-editing you can throw at it (preferably as a separate PR, which could be rebased onto the docs if the document moves there quickly).
If you don't speak C but want to copyedit, I'd be happy to explain the details.

PEP 630: Add sections for 2 more gotchas

---

pep-0685.rst

PEP 685: Minor wording changes

---

pep-0659.rst

Also, change "deoptimize" to "de-optimize".
No changes to text or meaning, otherwise.

PEP 659: Reformat to obey 80 column limit

---

pep-0655.rst

cc @davidfstr. Also, I opened https://bugs.python.org/issue47087 to track the CPython implementation, but couldn't find you there

PEP 655: Mark as accepted

---

pep_sphinx_extensions/pep_theme/static/mq.css
pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/static/wrap_tables.js
pep_sphinx_extensions/pep_theme/templates/page.html

Right now, the code font is much larger than the prose font, which varies by platform (due to the former using a system font stack, while the latter uses a web font). As a stopgap solution, to ensure 79 characters fit on a line under all but the most constrained screen resolutions, and reduce the perceptible size difference between the prose and code fonts while making it more motivated, this PR follows @pradyunsg 's suggestion reduce the code font size to something similar to what Furo uses, 0.875rem/14px as was suggested and discussed there, until we decide on a final resolution to the font stack issue.
Furthermore, as also suggested by @methane on #2347 , it allows code blocks to break by letter than than by word, resolving formatting issues at narrow screen widths and matching the …

Style: Reduce size of code font and improve responsiveness at narrow screen widths

---

pep-0681.rst

@davidfstr pointed out that having a `hash` alias for `unsafe_hash` is disguising a potentially unsafe feature as safe.
We don't remember why we added a `hash` alias. It may have been a mistake. Or it may have been added because attrs uses hash instead of unsafe_hash. However, [the attrs documentation](https://www.attrs.org/en/stable/hashing.html) recommends against setting hash, so this should be unusual. Attrs can add an `unsafe_hash` alias on their side if needed.
cc: @hynek

PEP 681: Remove hash alias for unsafe_hash

---

pep-0686.rst

https://discuss.python.org/t/pep-686-make-utf-8-mode-default/14435/25?u=methane

PEP 686: Change target version to 3.13

---

pep-0001.txt
pep-0012.rst

Presently, PEP 12 doesn't mention how to ensure that the automatic syntax highlighting added in the new Sphinx/PEP 676 build system gives the intended rendered output. Therefore, this PR adds a passage to the Literal Blocks section mentioning when and how to do this for specific blocks or entire PEPs. In the process, it also updates and simplifies the existing text.
Additionally, it updates PEP 1 and PEP 12 to follow those practices themselves, so they render as intended and serve as a good example for PEP authors. A future PR will fix the other existing PEPs where the default `python` syntax highlighting is not giving the rendered result the original author intended, to proactively solve existing issues like #2430 ; in most cases, it can be accomplished merely by adding a single ``.. …

PEP 1, 12: Update to reflect guidance for correct syntax highlighting

---

pep-0678.rst

Following further discussion (a running theme), the pendulum has swung back towards a simpler and less-tightly-specified interface.  Loosely, `__notes__` will be a list, created on the first call to `add_note()`, and if it's been messed up by the user we'll raise errors (in `add_note()`) or print a placeholder message (at display time) as appropriate.  This mirrors the existing handling of maybe-not-stringifiable exception instances, and permits all kinds of advanced shennanigans from users (or alternative implementations) who wish to push the system.
In the last few minutes I've also seen new messages about prior art in Tensorflow (a `utils.reraise()` helper) and circa-2013 discussions on BPO and python-dev, but it's late enough here that I'll push further updates in tomorrow.

PEP 678: simplify specification to use a list

---

pep-0596.rst

https://discuss.python.org/t/python-3-10-4-and-3-9-12-are-now-available-out-of-schedule/14568
https://docs.python.org/release/3.9.12/whatsnew/changelog.html

PEP 596: Add 3.9.12 release

---

.pre-commit-config.yaml
README.rst
contents.rst
pep-0001.txt
pep-0012.rst
pep-0685.rst

Followup to PR #2399 , which officially moved us over to the new Sphinx-based rendering system proposed in PEP 676.
Updates PEP 1 and 12 to update outdated references to Docutils and the Docutils-based rendering system to refer to Sphinx, ensure the guidance related to the rendering workflow is up to date with current practice, improve the description of and links to help resources. Also, fixes a few minor issues in the Readme introduced by that PR and updates the hardcoded PEP link checker to detect the new URL as well as the old (avoiding it missing them like in #2444, and even I myself not noticing in #2428).

PEP 1, 12: Update for adoption of PEP 676, and fix a few related items

---

pep_sphinx_extensions/pep_theme/static/style.css

As reported by @encukou and confirmed by @hugovk in #2439 , the current approach of wrapping code/literal blocks at narrow viewport widths makes them difficult to read, especially if they are particularly wide, include multiple columns of text, and are not correct syntax-highlighted, all of which is the case for, e.g., at least [one example block](https://peps.python.org/pep-0678/#raise-wrapper-explanation-from-err) in PEP 678.
A better approach, as discussed there, is to simply allow scrolling overly-wide code blocks instead of wrapping them, which is what GitHub and other sites do (as well as most editors by default, if soft-wrap is not enabled). This PR implements that approach, resolving the issue.
Before and after on a simulated iPhone SE (2nd gen), a particularly narrow device:

Style: Scroll code blocks instead of wrapping them

---

pep_sphinx_extensions/pep_processor/transforms/pep_zero.py

As requested by @gvanrossum in #2364 ,
> FWIW the one usability improvement you could make in PEP 0 with the biggest effect would be to make PEP titles clickable. Having to aim at the little number in front of e.g. PEP 1 is awkward for someone with as clumsy a mouse as myself.
This PR does exactly that.

PEP 0: Make PEP titles in table clickable links

---

Makefile
generate_rss.py

https://peps.python.org/peps.rss includes links like:
```rss
<guid isPermaLink="true">https://peps.python.org/pep-0686</guid>
```
Without the trailing `/`, there's an extra HTTP 301 redirect to add the slash, which adds a small but unnecessary delay which can vary between 20ms and 335ms.
See https://github.com/sphinx-doc/sphinx/pull/10288 for some network waterfall diagrams with and without the extra request.
So let's include it:
```rss
<guid isPermaLink="true">https://peps.python.org/pep-0686/</guid>
```
Also update pip and include wheel in virtualenv creation to remove a couple of warnings, noticeable during `make rss`.

Infra: Include trailing slash in RSS URLs to avoid 301 redirect

---

pep-0396.txt

Fix reference to `importlib.metadata.version()` in PEP 396.

PEP 396: Fix `importlib.metadata.version` reference

---

pep-0570.rst

As discussed in #2479 , PEP 570 (positional-only parameters) was implemented and documented in Python 3.8 but not marked Final, likely as an oversight. This fixes that.
Fixes #2479

PEP 570: Mark as Final

---

pep-0681.rst

1. Remove line about `dataclass_transform` likely not working well for Django since Django users have told us the opposite.
2. Move `converter` Open Issue to Rejected Ideas.

PEP 681: Rejected Ideas cleanup

---

pep_sphinx_extensions/pep_theme/static/mq.css

As originally reported by @pradyunsg on #2476 , PEP 440 (PEP-0440, namely [this section](https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions)) and possibly other specific PEPs that contain very long `<span>`s (i.e. syntax-highlighted text with the same color) inside scrolling literal blocks overflow the viewport at wider screen width, causing the rest of the page to overflow as well.
To make a long story short, after some investigation and testing, setting an appropriately-bounded `max-width` on the page content for the widest breakpoint (where it was previously unbounded) avoided this problem and ensured the page displayed identically to other PEPs with more typical content, while not affecting anything else.
Additionally, I noticed that …

Style: Fix unbounded max width causing very wide spans to overflow

---

pep-0686.rst

New post is here:
https://discuss.python.org/t/pep-686-make-utf-8-mode-default-round-2/14737

PEP 686: Update Post-History

---

pep-0681.rst

Removed support for `transform_descriptor_types` and added Rejected Ideas section about descriptor-typed fields.
cc: @carljm, @zzzeek

PEP 681: Move descriptor-field support to Rejected Ideas

---

pep-0686.rst

#2489 updated the `Post-History` to add the new thread (thanks for the quick update, @methane !). The `Discussions-To` was not updated, though, which this PR does (as well as a formatting fix). In the future, I'd like to generate `Discussions-To` automatically if it is not provided from the latest `Post-History` entry, so PEP authors only need to update it one place, but that's not implemented quite yet and there was some disagreement about the idea. (To note, the checks in #2484 actually caught this automatically)

PEP 686: Update Discussions-To to match Post-History

---

pep-0681.rst

1. Specify that when `dataclass_transform` is applied to functions, it can be on any one of the overloads or the implementation. The behavior when `dataclass_transform` is applied in more than one of those overloads/implementation is undefined.
2. Mention that in the future we may add additional `dataclass_transform` parameters based on consensus in typing-sig, without a PEP.
3. Clarify in Dataclass Semantics section that the list of semantics in the PEP is not complete, but just the ones that we felt needed to be called out. In particular the PEP doesn't list behaviors related to descriptor-typed fields which will hopefully be documented soon on the `dataclass` side -- https://bugs.python.org/issue47174

PEP 681: Decorator placement, future params, unstated semantics

---

pep_sphinx_extensions/pep_zero_generator/parser.py
pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py

[PEP 0](https://peps.python.org/pep-0000/) is a human-readable PEP index.
It would be useful to create a machine-readable version for, well, machines to read and process. This PR creates a `peps.json` of the key fields.
Preview:
```json
[
{
"number": 1,
"title": "PEP Purpose and Guidelines",
"authors": "Warsaw, Hylton, Goodger, Coghlan",
"status": "Active",
"type": "Process",
"url": "https://peps.python.org/pep-0001/"
},
{
"number": 2,
"title": "Procedure for Adding New Modules",
"authors": "Faassen",
"status": "Superseded",
"type": "Process",
"url": "https://peps.python.org/pep-0002/"
},
{
"number": 3,
"title": "Guidelines for Handling Bug Reports",
"authors": "Hylton",
"status": "Withdrawn",
"type": "Process",
"url": "https://peps.python.org/pep-0003/"
},
...
``` …

Infra: generate machine-readable PEP index

---

pep-0687.rst

From recent discussions around “what should have a PEP”, it's clear that this should have been a PEP long ago. Better late than never, I guess!
We submit this PEP to explain the changes, seek consensus on whether they are good,  propose the remaining changes, and set best practices for new modules.
(We wrote this over several months, sorry if it doesn't follow all the new PEP guidelines.)

PEP 687: Isolating modules in the standard library

---

pep-0681.rst

@carljm pointed out that the term "field descriptor" was confusing given that "descriptor" already has a strong meaning in Python and while "field descriptors" can be descriptors they are not required to be.
Renamed "field descriptor" to "field specifier".

PEP 681: Rename "field descriptor" to "field specifier"

---

pep-0681.rst

Added **kwargs on dataclass_transform so type checkers can experiment with new parameters without waiting for a corresponding change in typing.py.

PEP 681: Add kwargs on dataclass_transform

---

CONTRIBUTING.rst
pep-0001.txt

As has come up on many issues and PRs submitted here (e.g. #2151, #2199. #2265, #2318. #2332 being but a few recent examples off the top of my head), it would be of benefit to provide clear unambiguous up-front guidance on whether, when and where to propose changes to existing PEPs. Therefore, this PR adds this near the top of the Contributing Guide (which is exposed fairly prominently by the GitHub UI), to explictly explain the established, mostly unwritten practice here.
Specifically, it:
Also, I added a sentence to the "Commit messages and PR titles" section clarifying prefix usage for non-PEP PR titles/commit messages, as that has been the source of some confusion lately by multiple PEP editors (e.g. on  #2364 and #2375 )

Meta: Clearly document current guidance for changing existing PEPs

---

pep_sphinx_extensions/pep_theme/static/style.css

As written up in detail at https://github.com/python/peps/issues/2511, this rule breaks the rendering of 199 inline literals across all the PEPs, and appears to have no reason to exist. I therefore propose to remove it.
Resolves #2511.

Remove pre-wrap CSS rule that breaks multi-line inline literals

---

pep-0678.rst

Per the `Resolution` link, the SC has accepted PEP-678.  As I understand it the status is therefore updated to `Accepted`, and will reach `Final` after https://github.com/python/cpython/pull/31317 is merged.
(🥳)

PEP 678: update status to Accepted

---

pep-0427.txt

This is a typo according to the PEP author. https://github.com/pypa/pip/issues/9616#issuecomment-780699010
See also https://github.com/pypa/packaging.python.org/pull/1072

PEP 427: Fix typo in file contents keys

---

.github/workflows/render.yml

issues a purge all to the Fastly service that fronts peps.python.org to make new changes appear fast..... lier.
otherwise this would have led to up to 1 hour delay for changes.

purge CDN cache on deploy

---

pep_sphinx_extensions/pep_theme/templates/page.html

For https://github.com/python/peps/issues/2508.
Previously title was "Python Enhancement Proposals", changing it here to "Latest PEPs" on @encukou's suggestion. I agree: it's both more descriptive and concise, and if you're visiting this PEPs site, you know what a PEP is.
The old PEPs site, by virtue of being part of python.org, also had these three RSS feeds:
```html
<link rel="alternate" type="application/rss+xml" title="Python Job Opportunities"
href="https://www.python.org/jobs/feed/rss/">
<link rel="alternate" type="application/rss+xml" title="Python Software Foundation News"
href="https://feeds.feedburner.com/PythonSoftwareFoundationNews">
<link rel="alternate" type="application/rss+xml" title="Python Insider"
href="https://feeds.feedburner.com/PythonInsider">
```
Do we want to …

Infra: Restore PEPs RSS feed in <head>

---

pep-0671.rst

I've linked what appears to be the latest discussion thread for this PEP.

PEP 671: Add Discussions-To header

---

pep-0645.rst

Also, this PR supercedes https://github.com/python/peps/pull/2483 .
Approver for this is @gvanrossum (Sponsor of PEP 645). (The Author of PEP 645 has not been responsive in the past several weeks.)

PEP 645: Mark as Withdrawn (and as Standards Track)

---

pep-0631.rst

As [discussed on Discourse](https://discuss.python.org/t/updating-the-status-of-completed-peps/14853), PEP 631 is marked as accepted, but was later merged into PEP 621. As [I suggest there](https://discuss.python.org/t/updating-the-status-of-completed-peps/14853/5?u=cam-gerlach), it would make sense to mark it `Superseded` by PEP 621, to avoid any duplication or confusion over it still needing to be implemented independently, especially since PEP 621 in turn refers to the canonical PyPA specification. In addition, I also updated the note to make clear the merge happened.
As a minor note, I didn't add a `Replaces: 631` header on PEP 621 since it didn't seem conceptually appropriate here (and if there must always be a 1:1 relationship between these headers, we could just generate them …

PEP 631: Update status to clarify incorperation into PEP 621

---

pep-0670.rst

PEP 670: Mark as Accepted

---

pep-0687.rst

PEP 687: amendments after feedback

---

pep-0681.rst

#2481 didn't like the hashes in the URLs

PEP 681: Fix header links

---

docs/build.rst

Please note that I did not test the Windows-specific instructions I added, since I do not have quick access to a Windows box.

Build Instructions: Fix to work with the latest Makefile

---

pep-0595.rst

Fixes https://github.com/python/peps/issues/1098.
The autonumbered `[#]` footnotes got out-of-sync starting with the Zulip link.
To fix, replaced with preferred inline URLs (see https://github.com/python/peps/issues/2130).
Also fixed a couple of typos: "easiers" -> "easier" and "be use to" to "be used to".
Finally, whilst we're here and to avoid touching this file later, replace the coloured Python formatting for two literal blocks with more appropriate plaintext.
https://peps.python.org/pep-0595/
https://pep-previews--2534.org.readthedocs.build/pep-0595/

PEP 595: replace mismatched references with inline links

---

pep-0011.txt

PEP 11: define tiered platform support

---

pep_sphinx_extensions/pep_processor/transforms/pep_title.py
pep_sphinx_extensions/pep_theme/static/style.css

As discussed on #2514 , the headers at the top consume excessive vertical space, particularly on mobile which some style tweaks could dramatically improve with no loss of information. Furthermore, there are some odd gaps and spacing between the various elements that could be fixed, and the title and PEP number is redundant and can be removed, as it is present no less than four other places (the main title, the breadcrumbs, the sidebar [as addressed by #2532], and the tab title).
To note, while it is included in the comparisons below, this PR defers the implementation of removing or `abbr`-ing the email address to a followup PR, as it may require a bit more discussion and is better done after #2484 is merged.
**Desktop (Before/After)**
**Mobile (Before/Previous/Latest)**
Fixes #2514

Style: Reduce space consumed by headers and improve alignment

---

pep-0009.txt
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py

After some time reading, writing and interacting with the recently-added automatic formatting of links in the Discussions-To, Post-History and Resolution headers originally added in #2351 and improved in #2361, I've implemented a number of improvements and fixes that make both the URL and the link text more useful, handle many additional common cases, include the Post-History field as well, and prepare for other potential future enhancements. In particular, they now:
* Link to the relevant main page of python.org and googlegroups.com mailing lists for non-thread links, where users can subscribe to the list, browse relevant threads and post a reply (via mailto or web), as well as view more information about the venue
* Support Discourse, with the link title "Discourse thread" for threads …

Infra: Improve email and link processing and rendering in headers

---

.github/CODEOWNERS
pep-0639.rst

This is part 1 in (finally) updating PEP 639 (again). This first part just makes straightforward technical changes to update the headers in line with the current guidance, take advantage of the new syntax allowed by PEP 676's implementation, prepare for moving most of the ancillary/appendix material elsewhere, and fix a handful of technical and textual issues discovered during the process.
Specifically, it uses the recommended `:ref:` role for internal links, so that links (particularly cross-document ones) still work after renaming things and moving them around (among other benefits), ensures the external links are all uniformly anonymous to avoid conflicts, and strips the `#` from the target names to avoid confusion with footnotes or with URI fragments, and ensures the proper syntax …

PEP 639: Update header, footer, link, reference and code block syntax

---

pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/templates/page.html

We currently have the PEP title shown four times at the top of each page:
https://peps.python.org/8
* https://github.com/python/peps/issues/2514#issuecomment-1100505799 will remove the one from the table
* the main title should stay
* the one at the top line is questionable, should that go?
* but the one on the left the top of the contents is unnecessary
This PR removes the contents title on the left:

Infra: remove two of the five instances of title at top of pages

---

pep-0630.rst

As originally requested by @encukou in #2450 .
Overall, the base prose quality of the document was very good, so there weren't that many changes necessary to begin with, without doing a major rewrite (when there are certainly bigger fish to fry in that department).
In general, I attempted to keep my changes fairly unobtrusive. There were only a few non-purely-copyediting additions that affect content/meaning, the only really significant was was adding a mention of PEP 683 (PEP-0683), which relates directly to the note on immutable objects not being truly immutable due to the refcount.

PEP 630: Format and copyedit prior to conversion into a docs HOWTO guide

---

pep-0517.txt

All the other example hooks have a `def` so this looks like a typo.

PEP 517: add missing def for the mandatory hook build_wheel signature

---

pep_sphinx_extensions/pep_processor/html/pep_html_translator.py

This simply changes the title of the inline dropdown table of contents from `Contents` to `Table of Contents`, to be more clear and avoid confusion. I just changed it in the output HTML translator, so it shouldn't require touching anything else.
Fixes #2540

Style: Retitle inline 'Contents' to 'Table of Contents' for clarity

---

pep-0011.txt

PEP 11: Add Discussions section

---

pep-0642.rst

PEP 588, "GitHub Issues Migration Plan", is made Final since the
migration is done now.
PEP 642, "Explicit Pattern Syntax for Structural Pattern Matching",
has been rejected.

PEP 642: Update status to Rejected

---

pep-0688.rst

Link to current documentation of the protocol first and make the
PEP secondary (it might still be useful for the original motivation/rationale).

PEP 688: Link to current docs

---

pep-0681.rst

- Changed wording of Rejected Ideas to avoid recommending changes in libraries or dictating how users respond to these limitations. @encukou 
- Added language in Rationale indicating that we will consider extending `dataclass_transform` in the future with features commonly used in libraries but not supported by `dataclass`. @AlexWaygood

PEP 681: Address Steering Council feedback

---

pep-0594.rst

This received SC approval at their 2022-04-25 meeting.

PEP 11: add mailcap to the deprecation list

---

pep-0686.rst

This change is based on SC feedback.
https://github.com/python/steering-council/issues/118#issuecomment-1108833536

PEP 686: Postpone target version to 3.15

---

pep-0480.txt

This pr removes references to key sharing in the automated signing section, and proposes a small modification that allows multiple maintainers to upload a package without sharing keys.

PEP 480: Clarify automated signing solution to remove key sharing

---

.github/workflows/render.yml
.github/workflows/test.yml
.gitignore
.pre-commit-config.yaml
Makefile
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
pep_sphinx_extensions/pep_zero_generator/author.py
pep_sphinx_extensions/tests/pep_processor/transform/test_pep_footer.py
pep_sphinx_extensions/tests/pep_processor/transform/test_pep_headers.py
pep_sphinx_extensions/tests/pep_processor/transform/test_pep_zero.py
pep_sphinx_extensions/tests/pep_zero_generator/test_author.py
pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
pep_sphinx_extensions/tests/pep_zero_generator/test_pep_index_generator.py
pep_sphinx_extensions/tests/pep_zero_generator/test_writer.py
pep_sphinx_extensions/tests/peps/pep-9000.rst
pep_sphinx_extensions/tests/peps/pep-9001.rst
pep_sphinx_extensions/tests/utils.py
pytest.ini
requirements.txt
tox.ini

As [suggested earlier](https://github.com/python/peps/pull/2467#issuecomment-1084169702), let's test our infra code at `pep_sphinx_extensions/`.
I mainly aimed at testing standalone functions, and skipped the harder to test things involving Sphinx. I think this is fine, it's more important to test the more logic-based things than the whole rendering process by Sphinx and distutils. And we can extract bits of logic to make them easier to test. Still, 55% coverage isn't bad.
I found some bugs :)
1. `pep_sphinx_extensions/pep_processor/transforms/pep_headers.py` had an f-string missing the `f` prefix
2. `pep_sphinx_extensions/pep_zero_generator/author.py` had an `AttributeError: can't set attribute` on `name_parts.surname = f"\\{name_parts.surname}"`
3. Same file, I couldn't reach `raise …

Infra: add tests

---

.github/CODEOWNERS
pep-0689.rst

A PEP for https://github.com/python/cpython/issues/91744

PEP 689: Semi-stable C API tier

---

pep-0011.txt

Restores and updates the `Post-History` header removed in #2544 , including the direct thread links that PR helpfully added.
@brettcannon should we also link the Python-Dev thread? That wasn't listed below, though it was indirectly linked via the OP of your March 2022 Python-Committers thread.

PEP 11: Add back and update Post-History header with direct links

---

pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py

pep 0 is a bit different from other peps given that it's autogenerated, but I still think it makes sense to include it in the `api/peps.json` endpoint.
Page in build preview: https://pep-previews--2567.org.readthedocs.build/api/peps.json

Include the PEP index in `peps.json`

---

pep-0001.txt

with all the issues migrated to GitHub Issues, it makes sense now for PEP-1 to point to GitHub Issues over BPO

PEP 1: Update "issue tracker" to link to GitHub Issues

---

.github/CODEOWNERS
AUTHOR_OVERRIDES.csv
pep-0690.rst
pep-9999.rst

This is the PEP proposal for Lazy Imports in Python

PEP 690: Lazy Imports

---

pep-0690.rst

PEP 690: Add "per-module opt-in" to "rejected ideas" section

---

pep-0690.rst

PEP 690: Added Post-History

---

pep-0689.rst

Also includes a [change proposed in the initial review](https://github.com/python/peps/pull/2559#discussion_r858895879).

PEP 689: Rename to "Unstable C API tier"

---

pep-0690.rst

Requested in https://discuss.python.org/t/pep-690-lazy-imports/15474/14?u=carljm

PEP 690: Add a simple example of the behavior

---

pep-0690.rst

This adds a callback to the proposed `importlib.set_eager_imports()`.

PEP 690: Add flexibility to set_eager_imports()

---

.github/CODEOWNERS

PEP 670, 687: Update CODEOWNERS

---

pep-0362.txt

PEP 362: Fix formatting of colons in field descriptions

---

pep-0691.rst

- Reorganize the content so we introduce things in a more gradual approach, first pulling in versioning, then the JSON serialization, then our content types, then finally tying it all together with content negotiation.
- Expand a number of the sections with more detail.
- Add ``?format=<content-type>`` as an optional, alternative mechanism to using HTTP's conneg.
- Explicitly mention that the decisions made here enable repositories to do an endpoint per content-type if they desire.
- Add a recommendations section, to guide implementors on the best "default" choices.
- Add FAQ entries for a number of questions:
- Implications for static file servers
- Does this mean that PyPI is dropping support for PEP 503.
- Why TUF doesn't force us to have a single URL per TUF target.
- Why we haven't …

PEP 691: Refactor based on Feedback

---

pep-0691.rst

- ~~Adds the Post History for Today~~
- Adds a Copyright to the PEP
To merge this, we'll need permission from all the existing authors to copyright their work under the included license.

PEP 691: Copyright

---

pep-0008.txt

PEP 8: Fix typos

---

pep-0691.rst

Seems like most of the issues originally brought up in #2578 post-merge were fixed in the meantime, but there were a few remaining minor header/syntax/formatting nits I've fixed here.
@dstufft @di @cooperlees @pradyunsg

PEP 691: Fix minor nits with headers and reST syntax

---

pep-0007.txt

Based on post-merge feedback, it was decided to revert this change.
See the original PR (GH-2605), the proposed PR for PEP 8 (GH-2606), and
the issue (GH-2604) for the discussions.
This reverts commit c7877394784070af2db09e162007c828dc831f99.

PEP 7: Revert "Add note about greppable exception messages (#2605)"

---

pep-0690.rst

the example describes the behavior under lazy imports, so it should use `-L`

PEP 690: Fix omission of `-L` in example

---

pep-0673.rst

Not adding a `radius` attribute, because the Circle class needs to be
instantiable from just the `scale` config value. So, I'm going with a
method.
cc @JelleZijlstra  @Gobot1234
Closes #2617

PEP 675: Add explicit `circumference` method

---

pep-0681.rst

Clarify that decorating an overload with `dataclass_transform` impacts the function as a whole, not just usage of that one overload. The current language was reported as ambiguous in https://github.com/python/typing/discussions/1187.
cc: @zzzeek

PEP 681: Clarify impact of decorating an overload

---

pep-0621.rst

PyPI seems to reject these as-is (probably expectedly).

PEP 621: Fix missing schemes in example project.urls

---

pep-0257.txt

In python3, sys.maxint changed to sys.maxsize.

PEP 257: Use `sys.maxsize`

---

pep_sphinx_extensions/pep_processor/transforms/pep_zero.py
pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_zero_generator/parser.py
pep_sphinx_extensions/pep_zero_generator/writer.py
pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py

Change in support of subindices.
A

Infra: Use Docutils' `list-table` syntax for PEP 0

---

pep-0520.txt

```
peps/pep-0520.txt:416: WARNING: Citation [nick_concern] is not referenced.
```
The [nick_concern_] reference source was deleted in a9ed29c (#35).
Let's delete this orhpan to fix a Sphinx warning.
---
```
peps/pep-0520.txt:419: WARNING: Citation [orig] is not referenced.
peps/pep-0520.txt:422: WARNING: Citation [followup1] is not referenced.
peps/pep-0520.txt:425: WARNING: Citation [followup2] is not referenced.
```
These were added in the very first commit (https://github.com/python/peps/commit/9a5e309b5da79d9749369a63911b1db2ae042b9d) and were orphans from the start.
Let's convert them into a bullet list.
---
The final reference (to the implementation on BPO) doesn't cause a warning, but let's switch it into a direct hyperlink to GH (re: https://github.com/python/peps/issues/2130).

PEP 520: Fix citation references

---

pep-0484.txt

Fix some Sphinx build warnings.
(for readability, paths trimmed in warnings shown here)
---
```
pep-0484.txt:2490: WARNING: Citation [peps] is not referenced.
```
This was a misplaced underscore, now fixed.
---
```
pep-0484.txt:2463: WARNING: duplicate citation mypy, other instance in pep-0482.txt
```
The exact same citation is already defined in `pep-482.txt`, Sphinx uses that one.
---
```
pep-0484.txt:2475: WARNING: duplicate citation pyflakes, other instance in pep-0482.txt
pep-0484.txt:2478: WARNING: duplicate citation pylint, other instance in pep-0482.txt
```
These aren't actually used in this file, we can delete them.
---
Also remove the redundant emacs metadata from the end of the file.

PEP 484: Fix citation references

---

pep-0619.rst
pep-0664.rst

* 3.10 was planned for the _start_ of October 2021.
* 3.11 is planned for the _start_ of October _2022_.
For both, I think we can just say October [YYYY].

PEP 619, 664: Fix release date in comment

---

pep-0670.rst

PEP 670: Set Status to Final

---

pep-0554.rst

```
pep-0554.rst:1709: WARNING: Citation [nathaniel-asyncio] is not referenced.
pep-0554.rst:1712: WARNING: Citation [extension-docs] is not referenced.
```
Fixed by converting to inline links.
---
```
pep-0554.rst:1645: WARNING: Citation [CSP] is not referenced.
```
This citation was added in https://github.com/python/peps/pull/419.
The text uses:
```rst
`Communicating Sequential Processes`_ (CSP)
```
and:
```rst
.. _Communicating Sequential Processes:
.. [CSP]
https://en.wikipedia.org/wiki/Communicating_sequential_processes
https://github.com/futurecore/python-csp
```
So let's change this to a single citation:
```rst
Communicating Sequential Processes [CSP]_
```
and:
```rst
.. [CSP]
https://en.wikipedia.org/wiki/Communicating_sequential_processes
https://github.com/futurecore/python-csp …
```

PEP 554: Fix citation references

---

pep-0609.rst

This makes it clearer what the acronym stands for, by presenting the
full form in addition to the acronym.

PEP 609: Rename to Python Packaging Authority (PyPA) Governance

---

pep-0671.rst

This has been a point of some confusion, so I'm just writing in some defaults explicitly.

PEP 671: Add section on evaluation order

---

pep-0691.rst

* Switches to a list for serializing the project index.
* Drops URL from project index, adds name.
* Calls out a few non obvious notes about underlying data.
* Add a FAQ for why v1.0
* Add an appendix for the conceptual data models

PEP691: Switch to a List for Project, Address more Feedback

---

pep-0693.rst

Add the tentative release schedule PEP for Python 3.12.

PEP 693: Python 3.12 Release Schedule

---

pep-0553.rst

The section that once referred to the `envar` citation was deleted in bede39a536b5afe42fdc3bec63b6c83fa9db3957, so let's remove the orphan citation to fix this warning:
```
pep-0553.rst:283: WARNING: Citation [envar] is not referenced.
```
Let's also remove redundant emacs metadata from the end of the file.

PEP 553: Fix citation references

---

pep-0593.rst

Fix Sphinx build warnings.
---
```
pep-0593.rst:265: WARNING: Citation [struct-doc] is not referenced.
```
It was added as an orphan citation in the first commit: https://github.com/python/peps/pull/1014/commits/2756e1996fe6c8a71b214064681a92ef75bebac7 (PR https://github.com/python/peps/pull/1014).
Let's remove it.
---
```
pep-0593.rst:265: WARNING: duplicate citation mypy, other instance in pep-0484.txt
pep-0593.rst:271: WARNING: duplicate citation pycharm, other instance in pep-0482.txt
```
To fix these, let's convert the remaining references to inline links, per https://github.com/python/peps/issues/2130.

PEP 593: Fix citation references

---

pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/templates/page.html

1. Run Lighthouse audit from Chrome devtools or using https://web.dev/
> Buttons do not have an accessible name
https://web.dev/measure/?url=https%3A%2F%2Fpeps.python.org
https://web.dev/measure/?url=https%3A%2F%2Fpep-previews--2619.org.readthedocs.build%2F
Fixed following advice from https://kittygiraudel.com/2020/12/10/accessible-icon-links/
* Add `<span class="visually-hidden">Toggle light / dark / auto colour theme</span>` to the button
* Visible to screenreaders, but visually hidden
* Using the `visually-hidden` CSS class from [Furo](https://github.com/pradyunsg/furo/blob/0c2acbbd23f8146dd0ae50a2ba57258c1f63ea9f/src/furo/assets/styles/base/_screen-readers.sass) which is pretty similar to the one [from the blog](https://kittygiraudel.com/snippets/sr-only-class/)
* Conversely, add …

Infra: Make colour theme cycler button accessible

---

pep-0632.rst

This removes the header, as requested by the author in https://github.com/python/peps/pull/2636#discussion_r898173875.

PEP 632: Remove `Topic: Packaging` header

---

pep_sphinx_extensions/__init__.py

Fixes #2655 
Not sure how strongly people care about being able to reach the other PEPs from the filesystem HTML files opened as-is, since that'd be broken with this. On the other hand, viewing the files from an HTTP server run with `python -m http.server build` works still -- and so does the preview rendered by RTD + URLs that would be used with peps.python.org. :)

Tweak PEP references to work on topic sub-index pages

---

pep-0440.txt
pep-0503.txt
pep-0508.txt
pep-0600.rst
pep-0627.rst
pep-0656.rst

These all introduce or update existing Python Packaging Specifications,
and should follow the PyPA Specification processes. These are expected
to be Standards Track PEPs and are not informational.
This change also ensures that they get listed under the correct section
on the Packaging topic index.
See https://discuss.python.org/t/splitting-out-the-packaging-peps-on-the-pep-site/14111/33?u=pradyunsg for details and motivation.

Multiple PEPs: Move Packaging PEPs to Standards Track and mark as Final

---

pep-0615.rst

PEP 615 "Support for the IANA Time Zone Database in the Standard Library" contains the following text:
> there are IETF RFCs both for the maintenance procedures ([RFC 6557](https://datatracker.ietf.org/doc/html/rfc6557.html)) and for the compiled binary (TZif) format ([RFC 8636](https://datatracker.ietf.org/doc/html/rfc8636.html))
The second RFC is titled "Public Key Cryptography for Initial Authentication in Kerberos (PKINIT) Algorithm Agility", so I don't think it's what was intended. The author likely intended to include [RFC 8**5**36](https://datatracker.ietf.org/doc/html/rfc8536.html), titled "The Time Zone Information Format (TZif)". This PR fixes the link so it points to the correct RFC.

PEP 615: Fix incorrect RFC link

---

pep-0660.rst

This PEP has been implemented across multiple tools now.
This is motivated by trimming the list of “may not be implemented yet” PEPs on the Packaging subindex up to date / relevant.

PEP 660: Mark as Final

---

pep-0561.rst

This PEP has been implemented across multiple tools.
Mostly filing this to trim the number of “may not be implemented” PEPs on the Packaging sub index. This is motivated by trimming the list of “may not be implemented yet” PEPs on the Packaging subindex up to date / relevant.

PEP 561: Mark as final

---

pep-0650.rst

The discussion and interest in this PEP has died down.
Moving to Standards Track in line with the packaging specification process.
This should probably wait for approval from at least one of the authors.

PEP 650: Withdraw and move to Standards Track

---

pep-0691.rst

PEP 691: touch up

---

pep-0691.rst

Some minor grammatical changes, to make it a bit more pleasant to read.
And under Project List, I added the `meta` key that was forgotten in the description (not in the example code).

PEP-0691 Gramatical changes + `meta` key description under Project List

---

pep_sphinx_extensions/pep_processor/transforms/pep_headers.py

This makes the topic(s) listed in the Topic header in the rendered PEPs into actual links to the index page of the specified topic(s), which is very useful.
Fixes #2688

Infra: Link topic index pages in rendered PEP topic headers

---

pep-0694.rst

Some small grammar changes, and added mention of HTTP2 having deprecated the HTTP status reason phrase.

PEP 694: Grammar changes + reason phrase deprecation mention

---

.pre-commit-config.yaml

See #2673 for an example of where this existing description was insufficient.

Remove the requirement for Resolution to be the final header

---

pep-0683.rst

This covers typos, tweaks in wording, and some adjustments in response to [the last email thread](https://mail.python.org/archives/list/python-dev@python.org/thread/MI22URMVKC63OFMZTALHFZKAKVGAT4UF/).
@eduardo-elizondo will be making an update with additional technical details before we post the PEP for another round of discussion.

PEP 683: Small Updates

---

pep-0661.rst

```
pep-0661.rst:323: WARNING: Footnote [5] is not referenced.
pep-0661.rst:324: WARNING: Footnote [6] is not referenced.
pep-0661.rst:325: WARNING: Footnote [7] is not referenced.
pep-0661.rst:326: WARNING: Footnote [8] is not referenced.
```
These are not referenced in the text. Let's fix by converting to a bullet list (like in https://github.com/python/peps/pull/2644).
Let's also convert the remaining references to inline links, per https://github.com/python/peps/issues/2130, and remove the redundant emacs metadata.
https://pep-previews--2698.org.readthedocs.build/pep-0661/

PEP 661: Fix citation references

---

pep_sphinx_extensions/pep_theme/static/style.css

Since the basic admonition admonition styles are just applied to a couple individual admonitions, rather than admonitions in general, those other than "warning" and "note" won't display as admonitions at all. In addition to fixing that, this PR adds appropriate, standard colors for each of the additional admonition types in both light and dark mode.
Discovered in and required by #2690 .
<details>
<summary>Slightly outdated screenshots also showing status quo</summary>
</details>

Style: Fix colors and style for all admonitions

---

pep-0625.rst

Change the proposed naming conventions based on the latest discussions on Discourse.

PEP 625: Update following discussions

---

pep_sphinx_extensions/pep_theme/static/colour_scheme.js
pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/templates/page.html

This fixes the issue with the link rel canonical tag pointing to the wrong path. It was apparently using the undocumented `pageurl` template variable; this correctly constructs the path to the canonical dirhtml URL (and will also work to point to the canonical page even on local builds, PR previews and other people's deploys, so it can be accurately tested to point to the real page and these non-canonical copies don't get picked up independently in search results).
Also, I took the opportunity to clean up a few other minor HTML, CSS and JS validation issues:
* Conformed the self-closing tags and inconsistent whitespace from the HTML template, the former of which [superfluous and not recommended in HTML5](https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-ht …

Infra: Fix canonical link tag to point to correct PEP URL

---

.gitignore
Makefile

Infra: gitignore generated `/topic` and wipe via `make clean`

---

pep-0695.rst

* Someone pointed out that rust does include a way to specify default type arguments, something I missed when compiling the survey in Appendix A.
* Updated the "Rejected Ideas" section to address a couple of questions that were raised, including the use of angle brackets and the use of decorator-style syntax.

PEP 695: Incorporated recent feedback from python-dev.

---

pep-0642.rst

```
pep-0642.rst:1835: WARNING: Footnote [1] is not referenced.
pep-0642.rst:1838: WARNING: Footnote [2] is not referenced.
pep-0642.rst:1841: WARNING: Footnote [3] is not referenced.
pep-0642.rst:1844: WARNING: Footnote [4] is not referenced.
pep-0642.rst:1847: WARNING: Footnote [5] is not referenced.
pep-0642.rst:1850: WARNING: Footnote [6] is not referenced.
pep-0642.rst:1853: WARNING: Footnote [7] is not referenced.
pep-0642.rst:1856: WARNING: Footnote [8] is not referenced.
pep-0642.rst:1859: WARNING: Footnote [9] is not referenced.
```
Like https://github.com/python/peps/pull/2714, the footnotes in the text should be of the form `[1]_` not `[1_]`.
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#footnotes
---
And fix this:
``` …
```

PEP 642: Fix footnotes

---

pep-0538.txt

```
pep-0538.txt:1181: WARNING: Footnote [1] is not referenced.
pep-0538.txt:1184: WARNING: Footnote [2] is not referenced.
pep-0538.txt:1187: WARNING: Footnote [3] is not referenced.
pep-0538.txt:1190: WARNING: Footnote [4] is not referenced.
pep-0538.txt:1193: WARNING: Footnote [5] is not referenced.
pep-0538.txt:1196: WARNING: Footnote [6] is not referenced.
pep-0538.txt:1199: WARNING: Footnote [7] is not referenced.
pep-0538.txt:1202: WARNING: Footnote [8] is not referenced.
pep-0538.txt:1205: WARNING: Footnote [9] is not referenced.
pep-0538.txt:1208: WARNING: Footnote [10] is not referenced.
pep-0538.txt:1211: WARNING: Footnote [11] is not referenced.
pep-0538.txt:1214: WARNING: Footnote [12] is not referenced.
pep-0538.txt:1217: WARNING: Footnote [13] is not …
```

PEP 538: Fix footnotes

---

pep-0601.txt

```
pep-0601.txt:223: WARNING: Footnote [1] is not referenced.
pep-0601.txt:225: WARNING: Footnote [2] is not referenced.
pep-0601.txt:227: WARNING: Footnote [3] is not referenced.
pep-0601.txt:229: WARNING: Footnote [4] is not referenced.
pep-0601.txt:231: WARNING: Footnote [5] is not referenced.
pep-0601.txt:233: WARNING: Footnote [6] is not referenced.
pep-0601.txt:235: WARNING: Footnote [7] is not referenced.
pep-0601.txt:237: WARNING: Footnote [8] is not referenced.
pep-0601.txt:239: WARNING: Footnote [9] is not referenced.
```
It was using `[1]` instead of `[1]_`.
Also:
* Remove redundant emacs metadata
* Fix footnote links
* Add some inline code formatting

PEP 601: Fix footnotes

---

pep-0634.rst

Fix these warnings (like we did in https://github.com/python/peps/pull/2718):
```
pep-0634.rst:140: WARNING: duplicate label guards, other instance in pep-0622.rst
pep-0634.rst:175: WARNING: duplicate label patterns, other instance in pep-0622.rst
pep-0634.rst:231: WARNING: duplicate label literal_pattern, other instance in pep-0622.rst
pep-0634.rst:267: WARNING: duplicate label capture_pattern, other instance in pep-0622.rst
pep-0634.rst:290: WARNING: duplicate label wildcard_pattern, other instance in pep-0622.rst
pep-0634.rst:337: WARNING: duplicate label sequence_pattern, other instance in pep-0622.rst
pep-0634.rst:417: WARNING: duplicate label mapping_pattern, other instance in pep-0622.rst
pep-0634.rst:472: WARNING: duplicate label class_pattern, other instance in pep-0622.rst …
```

PEP 634: Fix duplicate labels

---

pep-0613.rst

Fix issue 2737 - Missing Python-Version in [PEP 613](https://peps.python.org/pep-0613/).

Fix issue 2737 - Missing Python-Version in PEP 613

---

pep-0635.rst

```
pep-0635.rst:403: WARNING: duplicate label patterns, other instance in pep-0634.rst
pep-0635.rst:592: WARNING: duplicate label literal_pattern, other instance in pep-0634.rst
pep-0635.rst:681: WARNING: duplicate label capture_pattern, other instance in pep-0634.rst
pep-0635.rst:740: WARNING: duplicate label wildcard_pattern, other instance in pep-0634.rst
pep-0635.rst:907: WARNING: duplicate label sequence_pattern, other instance in pep-0634.rst
pep-0635.rst:967: WARNING: duplicate label mapping_pattern, other instance in pep-0634.rst
pep-0635.rst:1014: WARNING: duplicate label class_pattern, other instance in pep-0634.rst
```
Like https://github.com/python/peps/pull/2735, we still get the same anchors in both:
* https://peps.python.org/pep-0635/#sequence-pattern
* …

PEP 635: fix duplicate labels

---

pep-0605.rst

```
pep-0605.rst:1346: WARNING: Footnote [1] is not referenced.
pep-0605.rst:1349: WARNING: Footnote [2] is not referenced.
pep-0605.rst:1352: WARNING: Footnote [3] is not referenced.
pep-0605.rst:1355: WARNING: Footnote [4] is not referenced.
pep-0605.rst:1358: WARNING: Footnote [5] is not referenced.
pep-0605.rst:1361: WARNING: Footnote [6] is not referenced.
```
References should be like `[5]_` not `[5_]`.
Also remove redundant emacs metadata.

PEP 605: fix footnotes

---

.github/workflows/render.yml
Makefile
build.py
readthedocs.yaml

ReadTheDocs now has a beta feature to override the build commands:
* https://twitter.com/readthedocs/status/1549145303801946112
* https://docs.readthedocs.io/en/latest/build-customization.html#override-the-build-process
Right now, a whole bunch of dependencies are installed that we don't use.
This can be slow especially as some old dependencies are built from source because they don't support modern Python and don't have wheels available (e.g. https://github.com/readthedocs/readthedocs.org/issues/9118).
Instead, we can just `make pages` and only install the stuff we need.
This speeds up the build "command" time ~2.5 mins to ~2 mins (uploading following build takes ~100s in both cases).
---
Each build step took:
1. Command time: 2s
2. Command time: 0s
3. Command time: 0s
4. Command time: …

Infra: override RTD build commands

---

.github/workflows/lint.yml
.github/workflows/render.yml
.github/workflows/test.yml
.gitignore
pytest.ini

Due to the recent delays in the 3.11 beta, it's very important to test it as widely as possible to help find issues before RC1.
https://discuss.python.org/t/the-cursed-release-of-python-3-11-0b4-is-now-available/17274?u=hugovk
---
Because we have test warnings turned into errors, temporarily ignore these in dependencies:
* Awaiting release of https://github.com/python-babel/babel/issues/873 in Babel 2.11, due 2022-08-01 https://github.com/python-babel/babel/milestone/6?closed=1
* Awaiting https://github.com/sphinx-doc/sphinx/issues/10440
Also skip testing 3.11 on Windows because lxml isn't yet available.

Infra: Test Python 3.11 beta

---

generate_rss.py
requirements.txt

```
.venv/bin/python3 generate_rss.py
/home/runner/work/peps/peps/generate_rss.py:134: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
settings = frontend.OptionParser((rst.Parser,)).get_default_values()
/home/runner/work/peps/peps/generate_rss.py:134: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
settings = frontend.OptionParser((rst.Parser,)).get_default_values()
/home/runner/work/peps/peps/generate_rss.py:134: DeprecationWarning: The frontend.OptionParser class will be replaced by a subclass of argparse.ArgumentParser in Docutils 0.21 or later.
settings = …
```

Infra: Fix docutils deprecation warning when generating RSS

---

pep-0639.rst

At long last, the next (and hopefully final) round of substantive PEP 639 (PEP-639) updates has arrived, based on the consensus of recent (and by now, not so recent) community discussions.
[See the preview here](https://pep-previews--2705.org.readthedocs.build/pep-0639/)
I was initially going to make the Terminology section into a Sphinx `glossary` and link the terms on first and prominient uses for clarity, but to speed things up and avoid scope creep I've deferred that to an immediate followup.
In a final followup PR, I'll reduce the length of the PEP by a further ≈two thirds (on top of substantial earlier reductions and modest further trimming here) by moving all the appendices, the "Mapping License Classifiers to SPDX Identifiers" section (previously normative) and the full rejected …

PEP 639: Further update per discussion, w/flat license key, etc.

---

pep-0282.txt

Syntax highligting interprets ' as start of a string and colors the following text differently.
Also this change makes the text fragment better readable for non-English native speakers.

PEP 282: Improve upon colloquial phrasing

---

pep-0501.txt

```
pep-0501.txt:557: WARNING: Footnote [#] is not referenced.
pep-0501.txt:560: WARNING: Footnote [#] is not referenced.
pep-0501.txt:563: WARNING: Footnote [#] is not referenced.
pep-0501.txt:566: WARNING: Footnote [#] is not referenced.
pep-0501.txt:568: WARNING: Footnote [#] is not referenced.
pep-0501.txt:570: WARNING: Footnote [#] is not referenced.
pep-0501.txt:572: WARNING: Footnote [#] is not referenced.
pep-0501.txt:574: WARNING: Footnote [#] is not referenced.
pep-0501.txt:577: WARNING: Footnote [#] is not referenced.
pep-0501.txt:580: WARNING: Footnote [#] is not referenced.
```
These aren't referenced in the body text so let's convert them to bullet points (like in https://github.com/python/peps/pull/2644 and others).
Plus update/fix some links and remove …

PEP 501: Fix footnotes

---

pep-0565.rst

```
pep-0565.rst:337: WARNING: Footnote [1] is not referenced.
pep-0565.rst:340: WARNING: Footnote [2] is not referenced.
pep-0565.rst:343: WARNING: Footnote [3] is not referenced.
pep-0565.rst:346: WARNING: Footnote [4] is not referenced.
pep-0565.rst:349: WARNING: Footnote [5] is not referenced.
pep-0565.rst:352: WARNING: Footnote [6] is not referenced.
pep-0565.rst:355: WARNING: Footnote [7] is not referenced.
pep-0565.rst:358: WARNING: Footnote [8] is not referenced.
pep-0565.rst:361: WARNING: Footnote [9] is not referenced.
```
1-5 and 8-9 were of the format `[1_]` instead of `[1]_`.
6-7 are not referred to, so changed those to bullet points.
And then renumbered 8-9 to 6-7.
---
Also:
* Consistently format DeprecationWarning as `DeprecationWarning` to match the …

PEP 565: Fix footnotes

---

pep-0582.rst

Includes the latest update in the internal structure of `__pypackages__` directory. Also points to a working example to enable the same in both `Cpython` & in `PyPy`.

PEP 582: Updates to internal directory structure

---

pep-0654.rst

PEP 654 was [implemented in Python 3.11](https://docs.python.org/3.12/whatsnew/3.11.html#exceptions-can-be-enriched-with-notes-pep-678) but is missing a Python-Version header, which resulted in it not showing up in my search for 3.11 PEPs while helping with the What's New. This adds it.

PEP 654: Add missing Python-Version header

---

pep-0550.rst

Fix these warnings by removing the orphaned references:
```
pep-0550.rst:1704: WARNING: Footnote [4] is not referenced.
pep-0550.rst:1718: WARNING: Footnote [11] is not referenced.
pep-0550.rst:1720: WARNING: Footnote [13] is not referenced.
pep-0550.rst:1722: WARNING: Footnote [14] is not referenced.
pep-0550.rst:1724: WARNING: Footnote [15] is not referenced.
pep-0550.rst:1726: WARNING: Footnote [16] is not referenced.
```
[4] was removed in https://github.com/python/peps/commit/1b8728ded7cde9df0f9a24268574907fafec6d5e ("PEP-0550 V4" #375)
And the others were removed in https://github.com/python/peps/commit/09c05c8740785fb1987d6b2162b927cccea58818 ("pep-550: Full rewrite: v2." #344)
---
Also:
* Remove redundant emacs metadata
* Use plaintext literal block for ASCII diagram
* Update link …

PEP 550: Fix footnotes

---

pep-0467.txt

```
pep-0467.txt:239: WARNING: Footnote [1] is not referenced.
pep-0467.txt:241: WARNING: Footnote [2] is not referenced.
pep-0467.txt:243: WARNING: Footnote [3] is not referenced.
pep-0467.txt:245: WARNING: Footnote [4] is not referenced.
pep-0467.txt:247: WARNING: Footnote [5] is not referenced.
pep-0467.txt:249: WARNING: Footnote [6] is not referenced.
```
They're not really footnotes, so like in https://github.com/python/peps/pull/2644 and others, let's convert them to regular links.
Plus update a couple of redirects.
https://pep-previews--2752.org.readthedocs.build/pep-0467/

PEP 467: Fix footnotes

---

pep-0558.rst

Fix these footnotes:
```
pep-0558.rst:1299: WARNING: Footnote [2] is not referenced.
pep-0558.rst:1323: WARNING: Footnote [10] is not referenced.
pep-0558.rst:1326: WARNING: Footnote [11] is not referenced.
pep-0558.rst:1329: WARNING: Footnote [12] is not referenced.
pep-0558.rst:1332: WARNING: Footnote [13] is not referenced.
```
`[2]` was removed in https://github.com/python/peps/pull/1008/commits/f0576753e45b6877d4e68df7d63cd386b110af03
The others were written like `[8,13]_` and `[10,11,12]_` instead of `[8]_ [13]_` and `[10]_ [11]_ [12]_`
Also:
* Remove redundant emacs metadata
* Fix code formatting (e.g. `.. code-block:: c`)
* Fix a couple of typos
* Update BPO links to GH
* Convert the references to regular links
https://pep-previews--2754.org.readthedocs.build/pep-0558/

PEP 558: fix footnote references

---

pep-0467.txt
pep-0554.rst
pep-0558.rst
pep-0603.rst
pep-0619.rst
pep-0620.rst
pep-0664.rst
pep-0671.rst
pep-0674.rst
pep-0679.rst
pep-0684.rst
pep-0689.rst

Now that Python 3.11 is in its RC phase, the still-Draft PEPs targeting it or an earlier version can't make the cut, so I've checked each PEP carefully, as well as their associated discussion threads and the Steering Council repo, and bumped/dropped their `Python-Version`s accordingly.
Authors, please either let us know that a version bump is okay, or otherwise let us know what you'd like to do about your PEP (e.g. a later target version, removing the version entirely and Deferring/Withdrawing it, etc.); I'll leave this open for ≈two weeks, unless we hear from everyone before then, to ensure everyone has a chance to see this. Thanks!
Two PEPs were exceptions to just bumping the version:
* ~~PEP 603 (PEP-603) appears to be inactive, as there haven't been meaningful changes or much …

Lint: Update outdated Python-Version on still-Draft PEPs

---

pep-0229.txt
pep-0305.txt
pep-0307.txt
pep-0308.txt
pep-0311.txt
pep-0341.txt
pep-0352.txt
pep-0353.txt
pep-0397.txt
pep-0409.txt
pep-0414.txt
pep-0421.txt
pep-0436.txt
pep-0441.txt
pep-0443.txt
pep-0476.txt
pep-0523.txt
pep-3106.txt
pep-3119.txt
pep-3138.txt
pep-3141.txt
pep-3156.txt

As originally discussed in #2755 , a number of older non-Packaging Accepted/Final Standards Track PEPs are missing Python-Version headers even though they were implemented. I've added those missing them via cross-referencing the What's New in Python documents, as well as the CPython commit history and the PEPs themselves.

Lint: Add missing Python-Version header in PEPs

---

pep-0630.rst

I'd welcome some PEP editor guidance:
- If an informational PEP is moved to a HOWTO, what should its status become?
- What's the best way to reference Python's dev (3.11) docs?
Here are my guesses.

PEP 630: superseded by a HOWTO in the docs

---

pep-0695.rst

This fixes up some of the inaccuracies in the 'Language Survey' section of the pep and adds a couple more languages.
- Related to https://github.com/python/peps/issues/2724

PEP 695: Fix/improve syntax & content of Language Survey section

---

pep_sphinx_extensions/pep_theme/static/style.css

Alternative to and closes https://github.com/python/peps/pull/2734.
Mute the table "zebra stripes", so some rows don't look more important than others.
Re: https://github.com/python/peps/pull/2734#issuecomment-1197502489 - let's use a different CSS colour for this, so we don't affect the colour already tuned for admonitions.
<table>
<tr>
<td><img width="808" alt="image" src="https://user-images.githubusercontent.com/1324225/181000861-eb920db9-ee00-461e-a3a4-db9240c87cd0.png">
<td><img width="813" alt="image" src="https://user-images.githubusercontent.com/1324225/181000925-f4c085ca-73dc-4c89-a062-b9f7d0c8c343.png">
</table>
<table>
<tr>
<td>
<td>
</table>
---
PS @CAM-Gerlach: you suggested `#111111` in https://github.com/python/peps/pull/2734#issuecomment-1197502489, I went with `#222222` …

Infra: Mute table zebra stripes to de-emphasise different rows

---

.github/CODEOWNERS
pep-0697.rst

I've juggled with this long enough, time for more eyes to see it.

PEP 697 (new): C-API for Extending Opaque Types

---

pep-0249.txt

To avoid confusion when using the DB-API 2.0 in the context of Python 3.
Add a note about a future upgrade to the Warning base class.
Fixes #2776.

PEP 249: Replace StandardError with Exception

---

pep-0619.rst

https://www.python.org/downloads/release/python-3107/
As as unscheduled release, I inserted this and kept the four remaining binary releases, bumping their patch version.

PEP 619: Add 3.10.7 release

---

pep-0585.rst

See https://discuss.python.org/t/concern-about-pep-585-removals
I mentioned the date explicitly so people not familiar with Python
release schedule have less arithmetic to do.
I also change the phrasing of the date to Python 3.9's EOL. The date
remains the same. Again, this is to help ease fear of writing 3.8 bridging
code for people who don't know Python version lifespan.
This should also be in line with ambv's (original author) intentions;
see bolded part of his message at
https://discuss.python.org/t/concern-about-pep-585-removals/15901/14

PEP 585: clarify removal as "no sooner than"

---

pep-0695.rst

Changes include:
* Updated link to typing-sig discussion
* Made clarifications to some terminology
* Made improvements to some code samples based on input from Guido
* Fixed a few formatting bugs
* Changed scoping rules for type parameters based on input from Guido and other reviewers
* Changed "autovariance" to "infer_variance" based in input that the former was confusing
* Removed detailed "compiler changes" section since it's an implementation detail and not normative

PEP 695: Incorporate feedback on draft PEP

---

pep-0532.txt
pep-0577.rst
pep-0598.rst

Fix footnote references: instead of `[1_]` should be of the form `[1]_`:
```
pep-0532.txt:886: WARNING: Footnote [1] is not referenced.
pep-0532.txt:889: WARNING: Footnote [2] is not referenced.
pep-0532.txt:892: WARNING: Footnote [3] is not referenced.
pep-0577.rst:806: WARNING: Footnote [1] is not referenced.
pep-0577.rst:809: WARNING: Footnote [2] is not referenced.
pep-0577.rst:812: WARNING: Footnote [3] is not referenced.
pep-0577.rst:815: WARNING: Footnote [4] is not referenced.
pep-0598.rst:885: WARNING: Footnote [1] is not referenced.
pep-0598.rst:888: WARNING: Footnote [2] is not referenced.
pep-0598.rst:891: WARNING: Footnote [3] is not referenced.
```
Also remove redundant emacs metadata, update a link redirect and fix a typo.
* …

PEP 532, 577, 598: Fix footnotes references

---

pep-0366.txt
pep-0395.txt
pep-0413.txt
pep-0426.txt
pep-0430.txt
pep-0440.txt
pep-0531.txt
pep-0535.txt
pep-3150.txt

```
pep-0366.txt:136: WARNING: Footnote [4] is not referenced.
pep-0395.txt:727: WARNING: Footnote [4] is not referenced.
pep-0413.txt:916: WARNING: Footnote [2] is not referenced.
pep-0426.txt:1510: WARNING: Footnote [1] is not referenced.
pep-0430.txt:208: WARNING: Footnote [1] is not referenced.
pep-0430.txt:211: WARNING: Footnote [2] is not referenced.
pep-0430.txt:214: WARNING: Footnote [3] is not referenced.
pep-0440.txt:1559: WARNING: Footnote [1] is not referenced.
pep-0440.txt:1565: WARNING: Footnote [3] is not referenced.
pep-0440.txt:1583: WARNING: Footnote [9] is not referenced.
pep-0531.txt:634: WARNING: Footnote [4] is not referenced.
pep-0531.txt:637: WARNING: Footnote [5] is not referenced.
pep-0531.txt:640: WARNING: Footnote [6] is not referenced. …
```

PEP 366, 395, 413, 426, 430, 440, 531, 535, 3150: Fix footnotes

---

pep-0001.txt

The Steering Council [recently changed the canonical PEP announcement venue from Python-Dev to Discourse](https://mail.python.org/archives/list/python-dev@python.org/thread/VHFLDK43DSSLHACT67X4QA3UZU73WYYJ/). Therefore, we should update PEP 1 to reflect this.

PEP 1: Update main PEP discussion venue from Python-Dev to Discourse

---

pep-0692.rst

Explicitly state that `Unpack`'s repr should be changed to `Unpack[T]`.

PEP 692: Explicitly describe the change to Unpack.__repr__ behavior

---

.github/CODEOWNERS
pep-0698.rst
pep-9999.rst

See earlier draft document at
https://docs.google.com/document/d/1dBkHKaOCqttnqzPo7kw1dzvbuFzNoOdx7OPyfbJHuV4/edit#
and discussion on `typing-sig` at
https://mail.python.org/archives/list/typing-sig@python.org/thread/7JDW2PKGF6YTERUJGWM3BRP3GDHRFP4O/
We still need a sponsor before we can proceed.

PEP 698: Override Decorator for Static Typing (`@typing.override`)

---

pep-0011.txt

This isn't a semantic change, but I just got "extended support" and "extended security updates" confused and Steve Dower had to correct me. So make it even more obvious in the text that we mean "extended support", and not "extended security updates".

PEP 11: Clarify Windows support phases

---

pep-0690.rst

PEP 690: Update PEP after implementation details
- Simpler `excluding` contract for `set_lazy_imports()` (any container)
- Add `is_lazy_imports_enabled()` API
- `PyDict_Next()` replaced by `PyDict_NextWithError()` that can set an error
- Add per-module opt-in for scientific Python use case: `enable_lazy_imports_in_module()`
- Discuss `sys.flags.lazy_imports` - reflects only `-L` flag, not `set_lazy_imports()` call
- Discuss how `subprocess` propagates the `-L` flag from `sys.flags`
- Remove wrapping with `LazyImportError` -- turned out to be problematic in practice
- Discuss behavior with `set_lazy_imports()` deeper in a stack of frames: it changes behavior midway in the nearest module frame, and all later-created frames
- Mention that lazy objects can "escape" via garbage collector

PEP 690: Update for second round of discussions

---

pep_sphinx_extensions/pep_theme/static/style.css

Followup to #2740 and #2734 
After further discussion with @gvanrossum and a lot of experimentation, tweaking and testing, I've resolved the remaining outstanding issues with styling for tables, and (I believe) substantially improved their presentation overall, along with related fixes. Initially, this PR further lightened the zebra stripes in tables and fixed the relative contrast issues with the code literal backgrounds and the table stripes. However, after adding the horizontal/vertical rules and darker header to maintain sufficient contrast and readability, in the end all the shades of grey ended up being unnecessarily distracting and overcomplicated, so I removed the zebra stripes altogether, with the end product being very similar to a slightly contrast-refined version of the tables …

Style: Fix zebra stripes and improve table & code presentation

---

pep-0011.txt

As a followup to #2801 , this PR:
* Adds and updates background, clarifications and links to clearly reflect the current status quo situation with Windows support policies, specifically that the lifecycle refereed to is the Fixed lifecycle policy, clarifying the distinction with the newer "Modern" lifecycle policy introduced since the PEP's last revision in this area, and prepares for a future decision on the policy to adopt toward Windows 10+ releases which follow the latter (without intending to make a substantive policy change itself, just clarifying the present status quo until a more specific policy is discussed, decided and adopted).
* Further clarifies the situation with ESU updates, and improves the text and terminology used therein.
* Makes several minor technical fixes to PEP …

PEP 11: Clarify Fixed vs. Modern lifecycle & non-support of ESU

---

pep-0681.rst

Clarified the following behaviors around classes decorated with `dataclass_transform`:
1. Attributes on such a class or its base classes are not considered to be fields.
2. Classes that are indirectly derived from such a class are still assumed to have dataclass-like semantics.
3. Method synthesis on a class is not impacted by the presence of explicit method declarations on that class's base classes. For example, the presence of an explicit `__init__` method on a base class, will not cause `__init__` synthesis to be skipped on a derived class. This is true when using functions decorated with `dataclass_transform` as well as with classes/metaclasses decorated with `dataclass_transform`.
These clarifications address questions from users in https://github.com/microsoft/pyright/issues/3907 …

PEP 681: Clarifications about classes decorated with `dataclass_transform`

---

pep_sphinx_extensions/pep_zero_generator/writer.py

This table is not too useful, and for some reason we're not properly
mangling email addresses in the table. For simplicity, just omit the
table.

Topic pages: remove authors table

---

pep-0698.rst

Fix some typos. Would like to give some comments to the PEP as the maintainer of overrides package, but I'll do it on reddit for example.

Fix typos in PEP 698

---

pep-0569.rst
pep-0596.rst
pep-0619.rst

This updates the release PEPs with the recent announcements of the Python 3.8.15, 3.9.15 and 3.10.8 ~quintuple~ *I can't count* quadruple release (with 3.7.15, which was already updated in #2829 ) on Tuesday, 2022-10-11, per the [announcement](https://discuss.python.org/t/python-versions-3-10-8-3-9-15-3-8-15-3-7-15-now-available/19889).
Also, cleans out the old clutter while we're touching these anyway.

PEP 569, 596, 619: Add release dates for 2022-10-11 release

---

pep-0668.rst

This PEP describes a new feature for Python Packaging interoperability,
which is better classified under this type.

PEP 668: Change to Standards Track

---

.pre-commit-config.yaml
pep-0240.txt
pep-0357.txt
pep-0447.txt
pep-0461.txt

* Upgrade check versions to latest (particularly Sphinx-Lint, fixing several false positives and false negatives)
* Enable single-backtick default role checks for txt and rst now that all false positives and true positives are fixed on both ( sphinx-contrib/sphinx-lint#34 )
* Fix several outstanding syntax errors detected on PEPs 240, 357, 447 and 461, and clean up a few additional things

Lint: Upgrade linters, enable backtick check & fix new errors

---

.pre-commit-config.yaml
pep-0440.txt
pep-0441.txt
pep-0523.txt
pep-0612.rst

As suggested by @stroxler in https://github.com/python/peps/pull/2834#discussion_r994449405 , we don't currently have any automated checks for the standard PEP header order. This adds such a check, and fixes the three remaining PEPs that didn't conform (and one other related problem spotted in the process).

Lint: Add a new check for consistent PEP header order

---

.github/CODEOWNERS
pep-0700.rst

PEP 700: Additional Fields for the Simple API for Package Indexes

---

Makefile

We were missing the `.PHONY` declarations in the Makefile, let's add them next to each target.
Docs: https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html
(Related: https://github.com/python/devguide/pull/972, https://github.com/python/cpython/pull/98266.)

Infra: Declare Makefile targets as phony

---

pep_sphinx_extensions/pep_zero_generator/writer.py

Currently we have no Provisional PEPs:
https://peps.python.org/#provisional-peps-provisionally-accepted-interface-may-still-change
For PEP 0, we still want the subheading for the table of contents, but instead of an empty table (which looks like an error) let's put some text there:
https://pep-previews--2839.org.readthedocs.build/#provisional-peps-provisionally-accepted-interface-may-still-change

Infra: Only emit a category table when it has entries

---

pep-0458.txt

OK'd by coauthors in [Discourse conversation](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/132).

PEP 458: Clarify sequence of PyPI and pip integration

---

pep_sphinx_extensions/pep_theme/templates/page.html

To reproduce:
1. Go to a topic index page:
* https://peps.python.org/topic/
* https://peps.python.org/topic/packaging/
* https://peps.python.org/topic/release/
* https://peps.python.org/topic/typing/
2. Click "Page Source (GitHub)" in the left menu
Actual result:
404 this is not the page you are looking for, because these pages are generated at build time and don't exist in the Git repo.
Expected result:
Either no 404, or no link in the first place.
Fix:
Let's not generate the link.
Preview:
* https://pep-previews--2843.org.readthedocs.build/topic/
* https://pep-previews--2843.org.readthedocs.build/topic/packaging/
* https://pep-previews--2843.org.readthedocs.build/topic/release/
* https://pep-previews--2843.org.readthedocs.build/topic/typing/

Infra: Don't generate broken source link for topic pages

---

pep-0693.rst

Python 3.12.0 alpha 1 has been released, let's set this PEP to active. 
* https://discuss.python.org/t/python-3-12-0-alpha-1-released/20298 
I put the 25th as the release date, as that's what I see on the download page:
* https://www.python.org/downloads/release/python-3120a1/

PEP 693: Set to active with 3.12.0a1 release

---

pep-0689.rst

I'm getting back to this one!
The `PyUnstable_` prefix is an unwieldy compromise, but, better than nothing.

PEP 689: Rewrite, with PyUnstable_ prefix

---

pep-0541.txt

This PR adds some clarification to additional things that PyPI maintainers consider to be 'invalid projects' and adds some additional clarification to existing items.
(CC @ambv as the original author)

PEP 541: Additional clarifications on invalid projects

---

pep-0698.rst

We decided to add this for two reasons:
- It was specifically requested by the author of the `overrides` library, because there there are some handy runtime uses of override information (such as propagating docstrings, which we highlight as a concrete example)
- We realized that we actually added `__final__` to `@typing.final` in spite of it not being specified in PEP 591, which we felt strongly suggests that even if we omit it we would later change our minds.
This runtime behavior is currently implemented in typing_extensions (see https://github.com/python/typing_extensions/pull/86) as well as pyre_extensions.
I ran `pre-commit`, it looks like there are no lint errors

PEP 698: Add `__override__` flag to runtime behavior

---

pep-0684.rst

I'll be updating this branch in response to discussion on https://discuss.python.org/t/pep-684-a-per-interpreter-gil/19583.
Significant changes:
* settled on keeping the allocators global but requiring that they *all* be thread-safe
* the state of the existing "small block" will be moved to `PyInterpreterState`
* dropped references to mimalloc
* simplified the C-API changes
* clarified the situation with incompatible extension modules
* proposed that extensions always opt in to per-interpreter GIL support with a new `PyModuleDef` slot (at least until we have enough evidence that multi-phase init is sufficient)
* expanded "How to Teach This"

PEP 684: Updates for Round 2 of Discussions

---

pep-0649.rst

This fixes the formatting of a couple of nested lists so that they render correctly (i.e: as lists rather than paragraphs).

PEP 649: Fix nested list formatting

---

Makefile

Normally you can run `make help` or just `make` on Sphinx projects and get help listing the available commands.
For example, [CPython docs](https://github.com/python/cpython/blob/main/Doc/Makefile#L28-L45):
```console
$  make -C Doc help
Please use `make <target>' where <target> is one of
clean      to remove build files
venv       to create a venv with necessary tools
html       to make standalone HTML files
htmlview   to open the index page built by the html target in your browser
htmlhelp   to make HTML files and a HTML help project
latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
text       to make plain text files
texinfo    to make Texinfo file
epub       to make EPUB files
changes    to make an overview over all changed/added/deprecated items
linkcheck  to check …
```

Infra: Add 'make help'

---

pep-0690.rst

A (hopefully final) set of updates to PEP 690 before submitting to the SC.
Most notably, removes the `importlib.enable_lazy_imports_in_module()` API per feedback from Brett, and adds a link to pyperformance benchmark numbers.

PEP 690: Last(?) round of updates

---

pep-0572.rst

[PEP 572](https://peps.python.org/pep-0572/) should be marked Final, as indicated by @ericvsmith [here](https://discuss.python.org/t/multiple-released-peps-have-status-accepted-not-final/20776/4).

PEP 572: Mark as Final

---

pep-0585.rst

[PEP 585](https://peps.python.org/pep-0585/) should be marked Final, as indicated by @hauntsaninja [here](https://discuss.python.org/t/multiple-released-peps-have-status-accepted-not-final/20776/5).

PEP 585: Mark as Final

---

pep-0616.rst

PEP 616: Mark as Final

---

pep-0453.txt
pep-0477.txt
pep_sphinx_extensions/pep_zero_generator/constants.py

As discussed on #2696 , tweaks the packaging page description text to clarify scope to be PyPA only and removes PEP 453/477 (ensurepip) accordingly.
Closes #2696

Meta: Clarify scope of Packaging topic and rm ensurepip PEPs (453/477)

---

pep-0698.rst

At this time, Pyre still does not have strict override enforcement.
This (and supporting codemod tools) are still something we want, but given that we have not yet delivered this and do not have a firm ETA we should not make claims about specific plans in the PEP text.

PEP 698: Change the wording for strict mode section

---

pep_sphinx_extensions/pep_zero_generator/parser.py

Fixes https://github.com/python/peps/issues/2878.
Add `"number": int` to the body in the API.
```json
{
"1": {
"title": "PEP Purpose and Guidelines",
"authors": "Warsaw, Hylton, Goodger, Coghlan",
"discussions_to": null,
"status": "Active",
"type": "Process",
"topic": "",
"created": "13-Jun-2000",
"python_version": null,
"post_history": "21-Mar-2001, 29-Jul-2002, 03-May-2003, 05-May-2012, 07-Apr-2013",
"resolution": null,
"requires": null,
"replaces": null,
"superseded_by": null,
"url": "https://peps.python.org/pep-0001/"
},
...
```
https://peps.python.org/api/peps.json
```json
{
"1": {
"number": 1,
"title": "PEP Purpose and Guidelines",
"authors": "Warsaw, Hylton, Goodger, Coghlan",
"discussions_to": null,
"status": "Active",
"type": "Process",
"topic": "",
"created": "13-Jun-2000", …
```

Infra: Include PEP number in API

---

pep-0013.rst
pep-8104.rst

Initial draft with pertinent dates and details.

PEP 8104: 2023 Term Steering Council election

---

pep-3141.txt

Made small typo changes per discussion in #2880. Scope of changes limited to reduce burden on historical PEP.

PEP 3141: Fix typo in Number.Complex.imag() docstring

---

pep-0693.rst

Note the release of 3.12.0a2 (dated yesterday because that is when the release branch was cut).

PEP 693: Note the release of 3.12.0a2

---

pep-0249.txt

As discussed on the DB-SIG ML.
Fix the creation date to point to the announcement date of the DB-API 2.0.
Add years to the acknowledgements.
Minor editorial changes.

Add optional Connection.autocommit attribute to PEP 249

---

pep-0248.txt

The headers did not include the original author (Greg Stein) and listed a wrong create date.

PEP 248: Fix Author and Created date headers

---

pep-0698.rst

This changes the count of reasons for rejecting runtime enforcement to match the actual number of reasons given.

PEP 698: fix typo enumerating runtime enforcement rejections

---

pep-0698.rst

This idea came up in the PEP discussion:
https://discuss.python.org/t/pep-698-a-typing-override-decorator/20839/4
We decided against including this, but as promised I am including the idea and potential upside as well as our rationale for not including it in the "Rejected Alternatives" section.
Checked code with
```
pre-commit run --files pep-0698.rst
```

PEP 698: Include discussion of pinning the ancestor class

---

pep-0698.rst

We claimed that there are two disadvantages to overrides: it makes code more verbose, and requires developers to update subclasses when possibly-breaking changes happen to base classes.
In discussion, it was pointed out that the second disadvantage is kind of strange - it is exactly the same as the advantage of using @override in the first place because the whole point is that it is not usually safe to assume subclasses can be unchanged when a method they override is removed from a base class.
I think just pointing out verbosity is good enough, I think it's understood that more verbose code potentially requires more edits to change, and in reality I think the case when it was safe to ignore invalidated overrides is pretty rare so making that a big focus seems a little weird.
An earlier …

PEP 698: reword the disadvantages section

---

pep-0698.rst

As suggested in after-merge comments on
https://github.com/python/peps/pull/2893
Maybe I've spent too much time in big-company roadmapping meetings, I didn't used to accidentally say things like this :D

PEP 698: reword "value add" -> "benefits"

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.rst

As originally brought up in #2898 ; the Contributing Guide and the PR template both state that the CLA should be signed _prior_ to submitting a PR, but in fact the current workflow with the bot is to sign the CLA _after_. This clarifies that in both places, and also takes the opportunity to further stress reading the Contributing Guide before opening a PR to ensure this repo is the appropriate place for it.

Meta: Update Contrib Guide & PR template for new CLA bot

---

pep-0646.rst

As agreed in https://github.com/python/cpython/pull/98267#discussion_r1003515475, and tentatively approved by the SC in https://github.com/python/steering-council/issues/145, here's a retroactive amendment to PEP 646 detailing the rules for type substitution in generic aliases, as determined in https://github.com/python/cpython/issues/91162 post-PEP-acceptance, and currently only documented in `test_typing.py` at https://github.com/python/cpython/blob/a0bc75e2fdd53680cb147881bcb3754bd56aa2fa/Lib/test/test_typing.py#L592.
This is a bit complicated, so happy to iterate for better pedagogy.
@gvanrossum @serhiy-storchaka @pradeep90

PEP 646: Add section on type substitution in generic aliases

---

pep-8104.rst

As noted on [discuss.python.org](https://discuss.python.org/t/steering-council-nominations-are-now-open-2023-term/21062/3) the links were incorrect

PEP-8104: Correct links for nomination/vote deadlines

---

pep-0689.rst

The prefix is very visible, so:
- No opt-in macro
- No new Include/ subdirectory
Removed frame evaluation API: I haven't found a way to use it, so I can't test it.
Mention that unstable API should be documented and tested.
Add link to rough reference implementation.

PEP 689: Updates from discussion & initial implementation

---

pep_sphinx_extensions/pep_processor/transforms/pep_headers.py
pep_sphinx_extensions/pep_zero_generator/constants.py
pep_sphinx_extensions/pep_zero_generator/parser.py
pep_sphinx_extensions/pep_zero_generator/writer.py
pep_sphinx_extensions/tests/pep_processor/transform/test_pep_headers.py
pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py

This helps people look up what the PEP status and type really mean by linking to their descriptions in PEP 1.
https://peps.python.org/pep-0700/
https://pep-previews--2842.org.readthedocs.build/pep-0700/
And on PEP 0, we have a list of types and statuses, let's also link these to the same places in PEP 1.
Plus turn them from quoted text to bullet points.
https://peps.python.org/pep-0000/#pep-types-key
https://pep-previews--2842.org.readthedocs.build/#pep-types-key
I'm not too sure about using the "§" symbol in "PEP 1 § PEP Types", but it's in the tooltip. Perhaps "PEP 1 > PEP Types" or "PEP Types" is clearer?

Infra: Link status and type headers to descriptions

---

pep-8104.rst

Steering Council nominations for 2023 term election have closed, this updates with those results and the current voter roll.

PEP 8104: Nominations and Voter Roll

---

pep-0697.rst

- Use a flag, `Py_TPFLAGS_ITEMS_AT_END`, rather than a slot. This way the subclass doesn't need to worry about items (if the superclass is set up right).
- The result of `PyObject_GetTypeDataSize` may be higher than requested by -basicsize (e.g. due to alignment). It is safe to use all of it (e.g. with memset).
- Mention that `basicsize == 0` and `itemsize == 0` already work. I’ll add explicit docs & tests though.
- Add link to initial implementation
- Add endorsements
- Add a “big picture” decision tree
- Rewording
- Mention possible flags for alternative item layouts

PEP 697: Changes based on initial implementation & docs

---

pep-0485.txt

The alternative formula ``abs(a-b) <= tol * (a + b)/2`` does not work correctly for values ``a + b < 0``.

PEP 485: Fix relative difference formula

---

pep-0699.rst

Accidentally mixed British and American English :).

PEP 699: Make the spelling consistent

---

pep-0701.rst

PEP 701: Add some clarifications to f-string debug expressions and tokens

---

pep-0620.rst

When the author cancels a PEP, it's Withdrawn. The SC does rejections.

PEP 620: Withdrawn rather than rejected

---

pep-0562.rst

The first example in the PEP doesn't use `!r` while formatting the name of the module and the attribute.  The following example does.  This PR fixes the first example so that it matches the second and the regular behavior of Python while trying to access a non-existing module variable.

PEP 562: Fix example by adding repr in an error message

---

pep-0701.rst

PEP 701: Correct link to nested interpolation strings

---

pep-0701.rst

This is intended to be more helpful than the noise it generates; I totally understand if it doesn't succeed in that and should be closed instead 😄 
- Fix one typo
- Fix one verb tense
- Replace instances of `f-literal` with `f-string literal` for consistency and clarity (please let me know if there is an intended nuance there that I'm missing!)

PEP 701: Proofreading / copy editing

---

pep-0688.rst

@encukou this is an attempt to clarify some of the areas you
brought up in https://discuss.python.org/t/pep-688-take-2-making-the-buffer-protocol-accessible-in-python/19756/15?u=jelle
and subsequent posts. Would you mind taking a look to see if
this addresses your concerns?

PEP 688: Enhance and clarify the specification

---

pep-0699.rst

This PR amends the PEP to follow the standard deprecation policy, in line with the SC's feedback on the Discourse thread https://discuss.python.org/t/pep-699-remove-private-dict-version-field-added-in-pep-509/19724/10?u=kj0.

PEP 699: Follow standard deprecation policy

---

pep-0692.rst

Abandon the syntax change proposal (for example `def foo(**kwargs: **Movie): ...`) in favor of using `Unpack` exclusively.

PEP 692: Abandon the syntax change proposal

---

.github/CODEOWNERS
pep-0702.rst

This is the first time anyone other than me sees this document, so I welcome any feedback.

PEP 702: Type system support for deprecations

---

pep_sphinx_extensions/pep_theme/static/style.css

In #2409, CSS was added to invert images that would otherwise be hard to see on dark background.
Since inversion doesn’t just affect brightness, but also hue, there’s a problem: Some background colors have perceptually less contrast with their text when hue rotated.
This PR rotates their hue back, fixing this. Also I prefer the less vaporware aesthetic of the original colors. E.g. the white-on-red is much more readable than white-on-cyan in [PEP 458](https://peps.python.org/pep-0458/):
<table>
<thead>
<tr>
<th>Without this PR
<th>With this PR
<tbody>
<tr>
<td width="50%"><img src="https://user-images.githubusercontent.com/291575/211005055-35d02d00-936e-49ef-9492-cf45951aa2f7.png" alt="without">
<td width="50%"><img src="https://user-images.githubusercontent.com/291575/211005019-3fa68378-14 …

Infra: Only invert image brightness, not hue

---

requirements.txt

This updates the Sphinx requirement to allow 6.1.2, but blacklists 6.1.0 and 6.1.1 (broken versions) from being installed.
A

Uncap the Sphinx requirement

---

pep-0561.rst

Fixes https://github.com/python/typing/issues/1334.
\cc @ethanhs as PEP author.

PEP 561: Clarify 4th step in Module Resolution Order

---

pep-0617.rst

PEP 617: Fix typo `out` -> `our`

---

pep_sphinx_extensions/pep_theme/templates/page.html

The PEP HTML headers have a link to the RSS feed:
* https://www.python.org/dev/peps/peps.rss
This is the old location, and there's a redirect in place to the new location, but let's link directly to the new one:
* https://peps.python.org/peps.rss

Infra: link directly to RSS feed at peps.python.org

---

pep-0509.txt
pep-0699.rst

See SC decision at https://discuss.python.org/t/pep-699-remove-private-dict-version-field-added-in-pep-509/19724/13.

PEP 699 & 509: Accept 699 and replace 509

---

pep-0689.rst

PEP 689: Mark as Accepted

---

pep-0698.rst

In our original draft to PEP 698, we wanted to emphasize that the PEP exclusively deals with `@override`, rather than adding new rules about override type signature.
We did this by stating that compatibility rules were pre-existing. This is true de-facto, because all type checkers implement at least some compatibility checks, but upon a careful re-reading it turns out compatibility checks on subclass methods are not specified in any PEP.
As a result, we should simply state that this PEP is not adding any new rules on signatures, without alluding to type checking rules that are not specified in previous PEPs.
I will sparately start a discussion in typing-sig about whether we want to provide a paper trail in PEPs - either a new PEP or a light amendment to PEP 484 - to make compatibility …

PEP 698: Tighten up the section about typing rules.

---

.github/workflows/render.yml
Makefile
readthedocs.yaml

I keep forgetting what `make render` and `make pages` actually do, and to be sure need to check how the `Makefile` calls `build.py` and how that calls `sphinx-build`.
Let's add `make html` and `make dirhtml` aliases.
These are the actual Sphinx builder names, and the same `Makefile` targets are used by other Sphinx/Python projects, including CPython docs and the devguide, so we can use muscle memory.
(They're also the default for new Sphinx projects.)
And then I don't think we need the old `make render` and `make pages` and can mark them as deprecated?

Infra: Use consistent 'make html' and 'make dirhtml'

---

pep_sphinx_extensions/__init__.py
pep_sphinx_extensions/pep_processor/parsing/pep_role.py
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py

Another dev papercut:
Most of the internal links are ["root-relative"](https://mor10.com/html-basics-hyperlink-syntax-absolute-relative-and-root-relative/), that is, they begin with `/`.
For example, https://peps.python.org/ links to `/pep-0008`:
```html
<a class="pep reference internal" href="/pep-0008" title="PEP 8 – Style Guide for Python Code">8</a>
```
This is fine on https://peps.python.org/ and the PR preview builds (e.g. https://pep-previews--2956.org.readthedocs.build/) which are served at the root of the domain, and when serving locally with something like `python -m http.server --directory build` (that `--directory build` being important).
However, for a static site, opening local html files directly in the browser should be enough: `open build/index.html`. But the root …

Infra: Use relative links to ease development

---

pep-0702.rst

PEP 702: Changes after discussion

---

pep-0703.rst

This makes a few small changes to PEP 703:
* Replaces the proposed configure flag`--without-gil` with `--disable-gil` per Inada Naoki's suggestion
* Adds two "rejected ideas" to clarify questions from the discussion
* Expands on a possible timeline for unification of the build modes

PEP 703: --disable-gil and other small changes

---

pep-0013.rst

Update PEP 13 with the results of the latest steering council election: [PEP 8104](https://peps.python.org/pep-8104/).

PEP 13: Update current SC members for 2023 term

---

pep_sphinx_extensions/pep_processor/transforms/pep_headers.py

Fixes #2980.
After https://github.com/python/peps/pull/2972, when building `dirhtml`, we need to re-add the initial `/` for the links to PEPs in the Replaces/Superseded-By/Requires headers.
https://pep-previews--2981.org.readthedocs.build/pep-0509/ <--> https://pep-previews--2981.org.readthedocs.build/pep-0699/

Infra: Fix Replaces/Superseded-By/Requires links for dirhtml

---

pep_sphinx_extensions/pep_theme/static/style.css

Without wanting to bikeshed too much!
The dark theme's current background colour has a bit of a greenish tint: `#001111` (labelled "Dark Green" on [some sites](https://www.htmlcsscolor.com/hex/001111)) which looks a bit off.
The background shouldn't be pure black, the contrast is too high. Here's what a few other sites use:
* `#0d1117` [GitHub](https://github.com/)
* `#121212` [Google's Material Design](https://m2.material.io/design/color/dark-theme.html#properties)
* `#202020` [Furo](https://pradyunsg.me/furo/)
* `#202124` [Google](https://www.google.com/)
* `#2d2d2d` [Stack Overflow](https://stackoverflow.com/)
Previews:
<table>
<tr>
<th><pre>#001111</pre>
<th><pre>#121212</pre>
<th><pre>#202020</pre>
<th><pre>#202124</pre>
<th><pre>#2d2d2d</pre>
<tr>
<td><img width="1624" alt="image" …

Infra: Use dark grey instead of dark green for dark theme background

---

.github/CODEOWNERS
pep-0704.rst

Enforce the use of virtual environments and establish a conventional name for the virtual environment directory.

PEP 704: Require virtual environments by default for installers

---

pep-0701.rst

PEP 701: Incorporate more feedback from the discussion thread

---

pep-0582.rst

Adds explanation of handling `bin/` directory, or how we are not trying to replace the existing virtual environments.

PEP 582: Add more explanation based on feedback

---

pep-0698.rst

See https://github.com/python/steering-council/issues/160#issuecomment-1409208844
@JelleZijlstra the other things I'm aware of that I / we need to do:
- announce this to typing-sig
- make PRs for cpython and typeshed to update the typing module; this will involve a bit of a learning curve for me
- I'm guessing make a PR on typing_extensions to import from typing in future versions of Python?
Are all those steps needed / is there anything I missed?

PEP 698: Mark as Accepted

---

.pre-commit-config.yaml

Re: https://github.com/PyCQA/isort/pull/2078
Fixes lint errors such as https://github.com/python/peps/actions/runs/4051441599/jobs/6969773973 in https://github.com/python/peps/pull/2993:
```
[INFO] Installing environment for https://github.com/PyCQA/isort.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/runner/.cache/pre-commit/repo0jaa0x15/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
Processing /home/runner/.cache/pre-commit/repo0jaa0x15
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'done' …
```

Infra: Update precommit to fix Poetry

---

pep-0517.txt

As discussed on Discourse:
https://discuss.python.org/t/amending-pep-517-with-a-sentence-on-handling-duplicate-config-settings-keys/23222.

PEP 517: add clarifying sentence about duplicate keys in config-settings

---

.pre-commit-config.yaml
pep-0013.rst
pep-0609.rst
pep-8000.rst
pep-8001.rst
pep-8002.rst
pep-8010.rst
pep-8011.rst
pep-8012.rst
pep-8013.rst
pep-8014.rst
pep-8015.rst
pep-8016.rst
pep-8100.rst
pep-8101.rst
pep-8102.rst
pep-8103.rst
pep-8104.rst
pep_sphinx_extensions/pep_zero_generator/constants.py

Fixes https://github.com/python/peps/issues/2987.
Group the language governance PEPs, plus the steering council election PEPs, and the various proposed models.
Preview:
* https://pep-previews--2993.org.readthedocs.build/topic/governance/

Meta: Add a governance topic

---

pep-0582.rst

Brings back the rejected idea of parent directory scanning.

PEP 582: Updates the rejected ideas list

---

Makefile
infra/main.tf
pep-0001.txt
pep-0012.rst
pep-0012/pep-NNNN.rst
pep_sphinx_extensions/pep_zero_generator/subindices.py

Document the Topic header in PEPs 1 and 12.
As suggested by @warsaw in https://github.com/python/peps/pull/2986#issuecomment-1409533600.
The Governance topic will be added in https://github.com/python/peps/pull/2993.

PEP 1 and 12: Document Topic header

---

.pre-commit-config.yaml
pep-0684.rst
pep_sphinx_extensions/pep_processor/transforms/pep_headers.py

In PR #3004 , a regression was introduced in the linter, bypassing the check that Discourse links are to the thread rather than to an individual message (as the modern link form of `Post-History` is for keeping a history of the `Discussions-To` threads, rather than links to individual messages about the PEP, which can go in the PEP body if desired).
This is also a pretty easy mistake to make by accident, as if you've scrolled past the first message, the message number will be appended to the URL, leaving readers unintentionally stuck in the middle of the thread rather than at the start (which also messes with Discourse's bookmarking of where you left off reading a thread).
Finally, as the headers are intended to be structured data in an easily-machine-parsable format, consumed by a number …

Lint: Allow per-message Post-History links w/trailing slash

---

pep-0619.rst
pep-0664.rst
pep-0693.rst

Python 3.10.10
Release Date: Feb. 8, 2023
https://www.python.org/downloads/release/python-31010/
Python 3.11.2
Release Date: Feb. 8, 2023
https://www.python.org/downloads/release/python-3112/
Python 3.12.0a5
Release Date: Feb. 7, 2023
https://www.python.org/downloads/release/python-3120a5/

PEPs 619, 664, 693: Update newest release dates

---

.github/CODEOWNERS
conf.py
pep-0706.rst

This doesn't really need to be a PEP, but, not being the tarfile expert, I wrote it as part of my research. And it might be useful for others.
* [n/a] Any project stated in the PEP as supporting/endorsing/benefiting from it confirms such

PEP 706: Filter for tarfile.extractall

---

pep-0706.rst

PEP 706: Fix typo

---

pep-0706.rst

- Add a section on adding filters to zipfile. Not *quite* a “rejected idea”, but IMO the PEP is good enough without it.
- Add a note on a registration mechanism
- Remove Open Issue “How far should this be backported?”. That'll be up to release managers, no need to put it in the PEP.
- Fix a few obvious mistakes, typos, formatting
---

PEP 706: Add some notes, remove open issue, fix mistakes & formatting

---

.github/CODEOWNERS
pep-0708.rst
pep-9999.rst

PEP 708: Extending the Repository API to Mitigate Dependency Confusion Attacks

---

pep-0008.txt

Authored-by: Hugo van Kemenade <hugovk@users.noreply.github.com>

PEP 8: Allow both one and two spaces after period

---

pep-0709.rst

This "incompatibility" does not actually exist in the current reference implementation, I just hadn't realized that it had been fixed.

PEP 709: Remove obsolete incompatibility subsection

---

.github/workflows/documentation-links.yml

Once merged, this will automatically add a docs preview link to PRs.
> GitHub Action that automatically edits Pull Requests' descriptions with a link to documentation's preview on Read the Docs.
https://github.com/readthedocs/actions/tree/v1/preview
For example: https://github.com/python/docs-community/pull/75

Infra: Automatically edit PRs with link to RTD preview

---

.github/workflows/documentation-links.yml

Follow on from https://github.com/python/peps/pull/3031.
See for example https://github.com/python/peps/pull/3034: it links to https://pep-previews--3034.org.readthedocs.build/en/3034/ (404) but should like to https://pep-previews--3034.org.readthedocs.build/ because we build Read the Docs as a "single version" with no language or other versions.
Docs: https://github.com/readthedocs/actions/tree/v1/preview#configuration
Likely needs merging to take effect.
----
:books: Documentation preview :books:: https://pep-previews--3035.org.readthedocs.build/en/3035/

Infra: RTD preview links should be single version

---

pep_sphinx_extensions/pep_zero_generator/writer.py

As suggested by @malemburg at https://discuss.python.org/t/proposal-peps-should-be-change-proposals/21068/19?u=hugovk, make the topic listing more prominent on the first page by putting it right before the category listing:
https://pep-previews--2892.org.readthedocs.build/
Shall we move the "The PEPs are [indexed by topic](https://github.com/python/peps/compare/topic/) for specialist subjects." text into this new section? For example:

Infra: Add index by topic to PEP 0

---

pep_sphinx_extensions/pep_zero_generator/constants.py
pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py
pep_sphinx_extensions/pep_zero_generator/writer.py

Follow on from https://github.com/python/peps/pull/2892.
That PR also inserts the links on subindex pages too:
But the links are 404, e.g. https://peps.python.org/topic/packaging/topic/packaging
We don't really need them there, so let's only add it for the "real" PEP 0 page.
---
Also, fix the links to have `.html` for the "html" builder, and put Governance first in the list, to match the https://peps.python.org/topic/ page.
----
:books: Documentation preview :books:: https://pep-previews--3037.org.readthedocs.build/

Infra: Only add Topics index to PEP 0, not topic indices

---

pep-0566.rst

This PR updates the spec to better match reality rather than attempting to do the opposite.
Ref: https://packaging.python.org/en/latest/specifications/core-metadata/#keywords
Ref: https://github.com/pypa/packaging/issues/570#issuecomment-1186093995

PEP 566: Fix keywords delimiter in JSON conversion

---

README.rst

Fixes https://github.com/python/peps/issues/2985.
----
:books: Documentation preview :books:: https://pep-previews--3043.org.readthedocs.build/

Meta: Document the shortcut links

---

pep-0693.rst

> Release Date: March 8, 2023
* https://www.python.org/downloads/release/python-3120a6/
----
:books: Documentation preview :books:: https://pep-previews--3045.org.readthedocs.build/pep-0693/

PEP 693: Update with the release date for 3.12.0a6

---

pep-0709.rst

----
:books: Documentation preview :books:: https://pep-previews--3046.org.readthedocs.build/

PEP 709: inline comps in all scopes, mention tracing/profiling

---

pep-0426/pepsort.py
pep-0554.rst
pep-0560.rst
pep-0633.rst

see https://github.com/sphinx-contrib/sphinx-lint/pull/56 and https://github.com/sphinx-contrib/sphinx-lint/issues/54.
----
:books: Documentation preview :books:: https://pep-previews--3049.org.readthedocs.build/

Fix invalid escape sequence and dangling hyphens.

---

pep-0558.rst

I informed the SC quite a while back that I was planning to defer this PEP again,
finally updating the actual PEP status.
----
:books: Documentation preview :books:: https://pep-previews--3050.org.readthedocs.build/

Defer PEP 558 (defined semantics for locals()) once more

---

pep-0558.rst

----
:books: Documentation preview :books:: https://pep-previews--3051.org.readthedocs.build/

PEP 558: fix typo & tweak wording in deferral note

---

pep-0698.rst

Attn: @stroxler
Apologies if these are coming at an unsuitable time in the life cycle of the PEP. 
- Some minor typo fixes
- Harmonizing the code formatting of some functions & packages
- Some suggested punctuation changes
- Change to the external link to the `overrides` package to allow code formatting in the link
- Converting uses of "get" to "set" when referring to adding `__override__` to decorated objects, for semantic consistency
cc @python/proofreaders

PEP 698: Fix typos and suggest edits

---

pep-0696.rst

PR #3052 accidentally linked directly to an arbitrary comment in the Discussions-To thread rather than the thread itself, and managed to bypass the linter by adding a trailing slash, which was introduced in #3005 as an escape hatch in response to the author's desire in #3004 to link to a specific post, given a strong reason to do so. It was presumably unintentional here, and thus this PR fixes it.
----
:books: Documentation preview :books:: https://pep-previews--3053.org.readthedocs.build/

PEP 696: Have Discussions-To point to thread rather than comment

---

pep-0709.rst

----
:books: Documentation preview :books:: https://pep-previews--3071.org.readthedocs.build/

PEP 709: clarify that async comprehensions are also inlined

---

.github/CODEOWNERS

Temporarily remove `@stevendaprano` from [`CODEOWNERS`](https://github.com/python/peps/blob/main/.github/CODEOWNERS) pending https://discuss.python.org/t/suspending-a-core-developer-for-conduct-issues/25278 to fix:
----
:books: Documentation preview :books:: https://pep-previews--3079.org.readthedocs.build/

Infra: Fix CODEOWNERS errors

---

.codespell/exclude-file.txt
.codespell/ignore-words.txt
.github/workflows/lint.yml
docs/rendering_system.rst

* Check spelling on the CI, but don't fail the CI, so we can check output for PRs
* Fix a typo in the rendering system docs
* Add "dedented" and "falsy" to ignored words list: they're always fine
* Ignore the specific lines that contain "pullrequest", "ClassE", "inout": they're fine in those instances
---
For reference, the remainder all look valid:
```
pep-0653.rst:596: stategy ==> strategy
pep-0526.txt:467: undocummented ==> undocumented
pep-0697.rst:340: retreive ==> retrieve
pep-0665.rst:58: producting ==> producing, production
pep-0642.rst:1702: recenty ==> recently
pep-0205.txt:189: referencable ==> referenceable
pep-0205.txt:213: referencable ==> referenceable
pep-0205.txt:213: referencable ==> referenceable
pep-0622.rst:2110: equilvalent ==> equivalent
pep-0011.txt:45: plaforms …
```

Lint: Check spelling on CI but don't fail

---

pep_sphinx_extensions/pep_processor/transforms/pep_footer.py

As originally discovered reviewing PEP 710 (PEP-710) in PR #3076 , the References section does not get hidden as intended if its doctree contains `node`s of type `system_message`, which are invisible docutils messages hidden in the rendered output (and thus not adding any visible content to the section). This can happen if the References section contains any hyperlink target labels that have the same name as the implicit targets generated for each section heading (i.e. the name of the section). This isn't a real issue, particularly since both we and Sphinx discourage using these implict section heading links for multiple reasons anyway, but we should still properly hide the References section in cases like these.
Therefore, we just add `nodes.system_message` to the list of "invisible" …

Infra: Fix hiding of References if it contains invisible SystemMessage

---

.github/CODEOWNERS

While they are the original authors, this is a living document that changes whenever the release process is tweaked.
----
:books: Documentation preview :books:: https://pep-previews--3086.org.readthedocs.build/

PEP 101: PRs to the release management PEP shouldn't ping Guido and Barry

---

.github/CODEOWNERS
pep-0710.rst
pep-9999.rst

Based on discussion in [this thread](https://discuss.python.org/t/draft-pep-recording-provenance-of-installed-packages/24838), opening this pull-request with a draft PEP.
> @CAM-Gerlach: Just for the others' benefit (and to cross-reference them), this was originally submitted as PR #2988 , but later withdrawn, revised and re-submitted here.
----
:books: Documentation preview :books:: https://pep-previews--3076.org.readthedocs.build/

PEP 710: Recording the provenance of installed packages

---

pep_sphinx_extensions/pep_zero_generator/writer.py

**Description**
This pull request addresses an issue where navigating from `/pep-0000/` to a topic would result in a 404 error page on the Python PEPs website. 
**Problem**
To reproduce the problem, follow these steps:
1. Go to [/pep-0000/](https://www.python.org/dev/peps/pep-0000/)
2. Click on any topic link.
3. Observe that a 404 error page is displayed. [Example](https://peps.python.org/pep-0000/topic/governance).
**Solution**
To fix the issue, I added a relative path to the topics folder. 
----
:books: Documentation preview :books:: https://pep-previews--3093.org.readthedocs.build/

Infra: Fix topics links from pep-0000

---

README.rst
docs/build.rst

The current command `make render` is deprecated and should be replaced with `make html` to build.
----
:books: Documentation preview :books:: https://pep-previews--3094.org.readthedocs.build/

Meta: Change make render to make html in docs

---

pep-0704.rst

----
:books: Documentation preview :books:: https://pep-previews--3111.org.readthedocs.build/

PEP 704: Add a missing word in PEP withdrawal notice

---

pep-0649.rst

Follow on from https://github.com/python/peps/pull/3106, fix backticks to fix the linting on the CI, and also some typos and formatting, and remove the redundant emacs metadata.
----
:books: Documentation preview :books:: https://pep-previews--3107.org.readthedocs.build/pep-0649/

PEP 649: fix backticks

---

pep-0619.rst

See https://www.python.org/downloads/release/python-31011/
----
:books: Documentation preview :books:: https://pep-previews--3116.org.readthedocs.build/

PEP 619: Update with final release date for 3.10.11

---

pep-0649.rst

----
:books: Documentation preview :books:: https://pep-previews--3113.org.readthedocs.build/

PEP 649: typo fixes and minor clarifications

---

pep-0649.rst

Larry suggested to make this a separate PR from https://github.com/python/peps/pull/3113 since it might require more discussion.
----
:books: Documentation preview :books:: https://pep-previews--3118.org.readthedocs.build/

PEP 649: distinguish annotations requested as strings vs objects

---

pep-0649.rst

* Move the "Mistaken rejection" section up to Overview.
* Stipulate that the exact value of strings returned by SOURCE format may change in the future.
* Disallow walrus and generator operators in annotation expressions.
----
:books: Documentation preview :books:: https://pep-previews--3124.org.readthedocs.build/

Fixes to PEP 649 based on feedback.

---

pep-0649.rst

Follow-up from #3124. The syntax is currently 'broken' on https://peps.python.org/pep-0649/ -- image below:
A
----
:books: Documentation preview :books:: https://pep-previews--3125.org.readthedocs.build/

PEP 649: Fix literal block syntax

---

pep_sphinx_extensions/pep_theme/static/style.css

Before:
After:
----
:books: Documentation preview :books:: https://pep-previews--3075.org.readthedocs.build/

Infra: Make the sticky banner opaque for better readability

---

pep-0713.rst

----
:books: Documentation preview :books:: https://pep-previews--3130.org.readthedocs.build/

PEP 713: Add link to reference implementation

---

.codespell/ignore-words.txt
pep-0011.txt
pep-0205.txt
pep-0285.txt
pep-0426.txt
pep-0526.txt
pep-0554.rst
pep-0582.rst
pep-0622.rst
pep-0642.rst
pep-0652.rst
pep-0653.rst
pep-0665.rst
pep-0669.rst
pep-0670.rst
pep-0674.rst
pep-0677.rst
pep-0683.rst
pep-0684.rst
pep-0689.rst
pep-0690.rst
pep-0691.rst
pep-0701.rst
pep-0706.rst
pep-0708.rst

https://github.com/python/peps/actions/runs/4843117521/jobs/8630554766?pr=3128#step:5:87:
```plain
Check for common misspellings in text files..............................Failed
- hook id: codespell
- exit code: 65
pep-0642.rst:1702: recenty ==> recently
pep-0205.txt:189: referencable ==> referenceable
pep-0205.txt:213: referencable ==> referenceable
pep-0205.txt:213: referencable ==> referenceable
pep-0582.rst:49: depenencies ==> dependencies
pep-0652.rst:245: aded ==> added
pep-0653.rst:596: stategy ==> strategy
pep-0701.rst:379: withing ==> within
pep-0701.rst:439: withing ==> within
pep-0011.txt:45: plaforms ==> platforms
pep-0622.rst:2110: equilvalent ==> equivalent
pep-0670.rst:524: retreive ==> retrieve
pep-0426.txt:1287: overal ==> overall
pep-0708.rst:126: similiar ==> similar …
```

Lint: Fix outstanding codespell spelling errors

---

pep-0696.rst

Support for tuples for `ParamSpec` default values was removed in #3052.
From the PEP
```rst
``ParamSpec`` defaults are defined using the same syntax as
``TypeVar`` \ s but use a ``list`` of types or an ellipsis
literal "``...``" or another in-scope ``ParamSpec`` (see :ref:`696-scoping-rules`).
```
/CC: @Gobot1234
----
:books: Documentation preview :books:: https://pep-previews--3133.org.readthedocs.build/

PEP 696: Use list for ParamSpec default [Fix]

---

pep-0703.rst

This updates PEP 703 with results from the nogil 3.12 rebase. I will make a new post on discuss.python.org once the PEP is updated on peps.python.org.
The substantial changes are summarized below:
- Performance results on Python 3.12
- Shrink `ob_ref_local` to 32-bits and use the extra space for GC bits and a per-object mutex
- Get rid of `PyGC_Head` (shrinks GC objects)
- Faster deallocation code path in the common case (additional specification on biased reference counting states)
- ``Py_mod_gil`` slot from PEP discussion
- Targets Python 3.13

PEP 703: Update PEP with results from nogil 3.12 rebase

---

pep-0693.rst

As proposed by release manager @Yhg1s in https://discuss.python.org/t/postponing-3-12-beta-1-feature-freeze/26406/1:
> Considering how many accepted changes are still being worked on (PEPs 684, 687, 688, 695, 697 at least) and still being decided on by the SC (PEPs 649, 702 and 709), I’m planning to postpone feature freeze and beta 1 for 3.12 by two weeks, without changing the rest of the schedule.

PEP 693: Postpone 3.12.0b1 by two weeks

---

conf.py
pep-0689.rst

-  I've linked this PR in the [Steering Council request](https://github.com/python/steering-council/issues/185)
- I hope it is!
* To a Draft PEP
- I've linked this PR in the [Steering Council request](https://github.com/python/steering-council/issues/185)
* To fix an editorial issue (markup, typo, link, header, etc)
----
:books: Documentation preview :books:: https://pep-previews--3123.org.readthedocs.build/

PEP 689: Tweak a policy, add canonical-doc and Mark as Final

---

pep-0706.rst

* https://discuss.python.org/t/23149/27
----
:books: Documentation preview :books:: https://pep-previews--3134.org.readthedocs.build/

PEP 706: Add changes found in review, Mark Final

---

pep-0697.rst

----
:books: Documentation preview :books:: https://pep-previews--3141.org.readthedocs.build/

PEP 697: Mark Final

---

pep-0569.rst
pep-0596.rst
pep-0619.rst
pep-0664.rst
pep-0693.rst

Occasionally releases happen a bit later than originally planned. And sometimes the `yyyy-mm-dd` date is updated in the release PEP, but not the day name (eg. Monday -> Tuesday).
Mismatches identified using this script, that finds date strings of the format "Xxxday, yyyy-mm-dd", parses the string into a `datetime`, then formats it back to a string and compares to the original: is the PEP's day name different from the real one for that date?
Then checked the date against the python.org release announcements, or in the case of "3.12 development begins", against the branching commit.
<details>
<summary>date_validator.py</summary>
```python
"""
Check PEPs have valid date strings of the format "Xxxday, yyyy-mm-dd"
Catches yyyy-mm-dd dates that have the wrong day.
"""
import argparse
import …
```

PEP 569, 596, 619, 664, 693: Fix days for release dates

---

pep-0710.rst

[RFC 2119](https://www.rfc-editor.org/rfc/rfc2119) deals with SHOULD etc. language, and [RFC 21119](https://www.rfc-editor.org/rfc/rfc21119) doesn't exist.
----
:books: Documentation preview :books:: https://pep-previews--3147.org.readthedocs.build/

PEP 710: Fix RFC 2119 reference

---

generate_rss.py
pep_sphinx_extensions/pep_processor/transforms/pep_footer.py
pep_sphinx_extensions/pep_zero_generator/writer.py

`datetime.datetime.utcnow` and `datetime.datetime.utcfromtimestamp` raise deprecation warnings in Python 3.12: https://github.com/python/cpython/issues/103857.
`datetime.UTC` is a (new in 3.11) alias of the older `datetime.timezone.utc`, but I think we want to keep support for older versions here, to make things easier for PEP authors.
https://docs.python.org/3/library/datetime.html#datetime.UTC
----
:books: Documentation preview :books:: https://pep-previews--3148.org.readthedocs.build/

Infra: Replace deprecated utcnow and utcfromtimestamp

---

pep-0701.rst

----
:books: Documentation preview :books:: https://pep-previews--3151.org.readthedocs.build/

PEP 701: Correct handling of format specifiers and nested expressions

---

pep-0693.rst

Update PEP 693 with the actual date of 3.12 beta 1, and delay beta 2 by a day to not conflict with Memorial Day and Pentecost.
----
:books: Documentation preview :books:: https://pep-previews--3153.org.readthedocs.build/

PEP 693: note release of beta 1 and delay beta 2 by a day

---

pep-0594.rst

----
:books: Documentation preview :books:: https://pep-previews--3156.org.readthedocs.build/

PEP 594: Set Status to Final

---

pep-0696.rst

----
:books: Documentation preview :books:: https://pep-previews--3145.org.readthedocs.build/

PEP 696: Add note about lazy eval with PEP 695

---

pep-0693.rst

Announced by release manager @Yhg1s in https://discuss.python.org/t/delaying-3-12-beta-2-by-a-week/27232:
> Because there are a number of important bugs being worked on that impede the testing of 3.12, it would be a shame to delay all that by a month, and it’s only been a week since beta 1, I’m delaying beta 2 until next week. (In retrospect I should have realised a week is not enough for third parties to find bugs *and* us to fix them, so lesson learned).
> 
> (See [Type object's ob_type does not get set when tp_bases is set before PyType_Ready · Issue #104614 · python/cpython · GitHub ](https://github.com/python/cpython/issues/104614), [`tp_bases` of `object` is `NULL`: undocumented or unintentional behavior change in 3.12? · Issue #105020 · python/cpython · GitHub …

PEP 693: delay 3.12 beta 2 by a week

---

pep_sphinx_extensions/pep_theme/static/mq.css
pep_sphinx_extensions/pep_theme/static/style.css
pep_sphinx_extensions/pep_theme/templates/page.html

Space is important for the readability of any kind of text.
Right now the PEP webpages use a Google font with a lot of custom CSS to pull the text in tighter and with less whitespace.
I find the font, small size and tight spacing hard to read (and my eyes aren't getting any younger!). Using default fonts and spacing feels more readable and loads faster. The Google font causes an annoying initial layout shift after it's loaded and the page is re-rendered.
Readability was brought up when we overhauled the PEPs infra as part of PEP 676. But as the other improvements and benefits of migration were so big, it made sense to press ahead without delaying to discuss this further.
One year on, the overhauled infra has been working really well. Let's now improve the readability :)
Some of the …

Infra: improve text readability and webpage performance

---

.github/CODEOWNERS
pep-0714.rst
pep-9999.rst

----
:books: Documentation preview :books:: https://pep-previews--3160.org.readthedocs.build/

PEP 714: Rename dist-info-metadata in the Simple API

---

pep-0708.rst

- Allows tracking multiple repositories to support the use case where a repository proxy is explicitly merging two or more namespaces together.
- Reword the repository tracks intro to be more explicit that it's per project, not per repository.
---
----
:books: Documentation preview :books:: https://pep-previews--3162.org.readthedocs.build/

PEP 708: Allow tracking multiple repositories and rewording

---

pep-0001.txt
pep-0012.rst

Ref: https://github.com/python/peps/pull/3161#issuecomment-1579857385
> Hey ... could you please avoid renaming the file back and forth? It obsoletes all reviewer comments and suggestions, and will furthermore make comments on in-flight reviews completely disappear into the void, which I've had happen to my half-dozen review suggestions so far twice now (which is, as you might imagine, rather frustrating 🙂).
> 
> This is why we've switched to specifically asking in the new PEP checklist (in your OP) that instead of using a placeholder number, you just give the PEP the next available number that it would be assigned anyway (not used by a published or in-PR PEP) yourself from the get go, to avoid the need for a file name, etc. change in all but the unlikely event that your PEP number …

PEP 1/PEP 12: Update PEP number assignment guidance

---

pep-0371.txt

The project name and URL were since repurposed for a different purpose. Linking to the archived version from the PEP's timeframe is important to avoid confusion when doing historical research.
----
:books: Documentation preview :books:: https://pep-previews--3166.org.readthedocs.build/

Update the link to pyprocessing from PEP-0371.

---

pep-0708.rst

Update with grammar and clarification fixes from @pfmoore 
----
:books: Documentation preview :books:: https://pep-previews--3165.org.readthedocs.build/

PEP 708: Grammar Fixes and Clarification

---

pep-0715.rst

Raised by @pfmoore: https://discuss.python.org/t/pep-715-disabling-bdist-egg-distribution-uploads-on-pypi/27610/2?u=woodruffw
----
:books: Documentation preview :books:: https://pep-previews--3168.org.readthedocs.build/

PEP 715: clarify which types are still supported

---

pep-0715.rst

@pfmoore
----
:books: Documentation preview :books:: https://pep-previews--3175.org.readthedocs.build/

PEP 715: Typo in header

---

pep-0621.rst
pep-0668.rst

Re: https://discuss.python.org/t/meta-should-the-peps-page-index-by-not-just-the-last-name/27918/6?u=hugovk
Fix Tzu-ping Chung's name to be spelled per his preference, and remove the duplication at https://peps.python.org/#authors-owners:
@uranusjr How does this look?
----
:books: Documentation preview :books:: https://pep-previews--3176.org.readthedocs.build/

PEP 621, 668: Fix name spelling

---

pep-0527.txt

See https://github.com/python/peps/pull/3180#pullrequestreview-1496861545.
----
:books: Documentation preview :books:: https://pep-previews--3181.org.readthedocs.build/

PEP 527: Recategorize as "Standards Track"

---

.github/CODEOWNERS

Follow on from https://github.com/python/peps/pull/3184, thanks for the reminder @JelleZijlstra.
----
:books: Documentation preview :books:: https://pep-previews--3185.org.readthedocs.build/

PEP 719: Add to CODEOWNERS

---

.github/CODEOWNERS
pep-0387.txt

----
:books: Documentation preview :books:: https://pep-previews--3182.org.readthedocs.build/

PEP 387: Add Soft Deprecation section

---

Makefile
conf.py

It's come up a couple of times that `build.py` is wrapping `sphinx-build`.
This PR replaces all calls of `build.py` in `Makefile` with direct calls to `sphinx-build`, and follows the [CPython `Makefile`](https://github.com/python/cpython/blob/main/Doc/Makefile) where possible to minimise differences and ease maintenance across repos. 
----
:books: Documentation preview :books:: https://pep-previews--3195.org.readthedocs.build/

Infra: Call sphinx-build directly in Makefile instead of via build.py wrapper

---

pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py

…which is ironically broken  :) 
> See the [PyPA specification update process](https://www.pypa.io/en/latest/specifications/#handling-fixes-and-other-minor-updates) for how to propose changes.
Found on https://peps.python.org/pep-0566/ and other places 
----
:books: Documentation preview :books:: https://pep-previews--3199.org.readthedocs.build/

Proposing a change to the "proposing a change" hyperlink

---

pep-0721.rst

Fixed a typo in the sentence "Tools are allowed to ignore this PEP when running on Python **p**ithout tarfile filters."
----
:books: Documentation preview :books:: https://pep-previews--3200.org.readthedocs.build/

PEP721: fixing a typo

---

pep-0693.rst

Re: https://www.python.org/downloads/release/python-3120b4/
----
:books: Documentation preview :books:: https://pep-previews--3203.org.readthedocs.build/

PEP 693: Update 3.12.0b4 release date

---

pep-0715.rst

Fix this Sphinx warning:
```
pep-0715.rst:52: WARNING: term not in glossary: 'packaging:Built Distributions'
```
Also doesn't create the link at https://peps.python.org/pep-0715/#the-bdist-egg-format:
> in 2012 as [the standardized format](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format) for packaging:Built Distributions.
Creates a link at https://pep-previews--3188.org.readthedocs.build/pep-0715/#the-bdist-egg-format:
> in 2012 as [the standardized format](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#binary-distribution-format) for [built distributions](https://packaging.python.org/en/latest/glossary/#term-Built-Distribution).
----
:books: Documentation preview :books:: …

PEP 715: Fix link to packaging term

---

pep-0393.txt

Fixes #3205
----
:books: Documentation preview :books:: https://pep-previews--3211.org.readthedocs.build/

PEP 393: Replace broken link with an Internet Archive one

---

.github/CODEOWNERS
pep-0720.rst
pep-9999.rst

----
:books: Documentation preview :books:: https://pep-previews--3192.org.readthedocs.build/

PEP 720: add "Cross-compiling Python packages" PEP draft

---

pep-0554.rst

Fix this warning:
```
pep-0554.rst:1335: WARNING: Citation [petr-c-ext] is not referenced.
```
The reference to the footnote was removed in https://github.com/python/peps/pull/3067, let's also remove the footnote itself. Alternatively, we could convert it a bulleted footnote, there's already a couple of those.
Also remove redundant emacs metadata.
----
:books: Documentation preview :books:: https://pep-previews--3189.org.readthedocs.build/pep-0554/

PEP 554: Convert unreferenced footnote to bullet point

---

pep-0394.txt
pep-0400.txt
pep-0482.txt
pep-0526.txt
pep-0544.txt
pep-0557.rst
pep-0573.rst
pep-0583.rst
pep-0612.rst
pep-0615.rst
pep-0622.rst
pep-0633.rst
pep-0634.rst
pep-0636.rst
pep-0642.rst
pep-0649.rst
pep-0669.rst
pep-0675.rst
pep-0680.rst
pep-0689.rst
pep-0692.rst
pep-0695.rst
pep-0696.rst
pep-0697.rst
pep-0701.rst
pep-0704.rst
pep-0710.rst
pep-0720.rst
pep-3151.txt

This PR resolves all outstanding duplicate label and duplicate citation warnings. I have not yet addressed unreferenced footnote warnings.
I took the general strategy of replacing a target above a section heading with references directly to that section heading, or where impractical, disambiguting the target with ``PEP NNN``. I also converted all the citations in PEP 482 to links, as they were causing duplicate citation warnings.
See #3213 for context.
A
P.S. opened as draft so as not to ping, I do consider this ready for review.
----
:books: Documentation preview :books:: https://pep-previews--3214.org.readthedocs.build/

Many PEPs: Resolve reference warnings

---

pep-0639.rst

Addresses #3215 by directly linking to version 2.2.2 of the SPDX specification.
----
:books: Documentation preview :books:: https://pep-previews--3216.org.readthedocs.build/

PEP 639: fix broken link to SPDX spec

---

pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py

This reverts commit 08124264e6cc590b472d7f4f023ebe3e6ff3071a (https://github.com/python/peps/pull/3199).
Short version: I broke links on pypa.io (https://github.com/pypa/pypa.io/pull/88), but I've now unbroken them (https://github.com/pypa/pypa.io/pull/90) so we can revert this temporary fix.
----
:books: Documentation preview :books:: https://pep-previews--3218.org.readthedocs.build/

Infra: Revert "Fix a URL in the PyPA specification banner (#3199)"

---

pep-0326.txt

Footnote [10] does not exist.  Footnotes [5], [8], and [11] are unreferenced. Commit 778f8da removed the reference to [5] (then numbered [6]) and added [8] with no reference. [11] was added in 64497e6 with no reference. Without an apparent need for these three, they are removed. The remaining footnotes and their text references are re-numbered.
----
:books: Documentation preview :books:: https://pep-previews--3225.org.readthedocs.build/

PEP 326: Remore unreferenced footnotes and renumber

---

pep-0299.txt

This one is fixing incorrect reStructuredText.
----
:books: Documentation preview :books:: https://pep-previews--3223.org.readthedocs.build/

PEP 299: Resolve unreferenced footnotes

---

pep-0262.txt

Footnote [1] doesn't seem to have ever been referenced, I've simply removed the reference markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3220.org.readthedocs.build/

PEP 262: Resolve unreferenced footnotes

---

pep-0277.txt

Footnote [1] doesn't seem to have ever been referenced, I've simply removed the reference markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3221.org.readthedocs.build/

PEP 277: Resolve unreferenced footnotes

---

pep-0292.txt

Footnote [3] was added in 1ac7cab, to a section entitled *BDFL Weathervane*; the section was later removed in fa6ff92, but the footnote remained. I've therefore removed footnote [3] and added a reference to old footnote [5] (now [4]).
A
----
:books: Documentation preview :books:: https://pep-previews--3222.org.readthedocs.build/

PEP 292: Resolve unreferenced footnotes

---

pep-0232.txt

The footnote was referenced from within a code block example, so I've lifted the reference up. I also updated the links.
A
----
:books: Documentation preview :books:: https://pep-previews--3219.org.readthedocs.build/

PEP 232: Resolve unreferenced footnotes

---

pep-0323.txt

Footnotes [1] was never referenced, and the reference to [2] was removed in 36e7a69 -- this commit removes the markup syntax.
A
----
:books: Documentation preview :books:: https://pep-previews--3224.org.readthedocs.build/

PEP 323: Resolve unreferenced footnotes

---

pep-0329.txt

Footnote [2] was never referenced, remove the markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3226.org.readthedocs.build/

PEP 329: Resolve unreferenced footnotes

---

pep-0340.txt

Footnote [1] was originally referenced in the introduction to the PEP as background of why it came into being, before being removed in 45c25ac. I've removed the syntax and updated links to archive.org versions.
A
----
:books: Documentation preview :books:: https://pep-previews--3228.org.readthedocs.build/

PEP 340: Resolve unreferenced footnotes

---

pep-0343.txt

Footnote [12] was added in f860cb2 with no reference -- I can't find a working archive.org link (all say that the patch is private), so I've removed [12] and re-numbered the remaining footnotes.
A
----
:books: Documentation preview :books:: https://pep-previews--3230.org.readthedocs.build/

PEP 343: Resolve unreferenced footnotes

---

pep-0617.rst

In the rationale section, the expression for the intended rule for assignment expressions has brackets around the wrong part, making the logic hard to follow.
For reference, here's an excerpt of [Guido's post](https://discuss.python.org/t/preparing-for-new-python-parsing/1550/5) which was likely the source for the section:
> The first case is that of assignment expressions. The Grammar says:
> 
> ```
> namedexpr_test: test [':=' test]
> ```
> 
> but what we really want to say is:
> 
> ```
> namedexpr_test: [NAME ':='] test
> ```
> Unfortunately that’s not LL(1) since NAME is also in the FIRST set of test. (You can think of test as the pre-PEP-572 top-level expression rule, named test for historical reasons.)
----
:books: Documentation preview :books:: …

PEP 617: Fix expression typo in rationale

---

pep-0491.txt

Footnote [1] referenced an email pertaining to PEP 427; I've removed the footnote.
A
----
:books: Documentation preview :books:: https://pep-previews--3240.org.readthedocs.build/

PEP 491: Resolve unreferenced footnotes

---

pep-0371.txt

Footnote [6] has existed since the initial draft of the PEP; I've added a reference in a sensible place. Footnote [8] was added in 351a920, and is really a post-history update.
A
----
:books: Documentation preview :books:: https://pep-previews--3234.org.readthedocs.build/

PEP 371: Resolve unreferenced footnotes

---

pep-0425.txt

Footnotes [1] and [2] have existed since the initial draft; both never referenced. I've removed the syntax.
A
----
:books: Documentation preview :books:: https://pep-previews--3236.org.readthedocs.build/

PEP 425: Resolve unreferenced footnotes

---

pep-0355.txt

Another instance of footnote references from within a code block -- I've removed the footnote markup from [1] and updated the comments in the Specification.
A
----
:books: Documentation preview :books:: https://pep-previews--3231.org.readthedocs.build/

PEP 355: Resolve unreferenced footnotes

---

pep-0361.txt

Update to correct reStructuredText format.
A
----
:books: Documentation preview :books:: https://pep-previews--3232.org.readthedocs.build/

PEP 361: Resolve unreferenced footnotes

---

pep-0502.txt

The references to footnotes [10] and [11] were removed in 1bd2f20; I've added references in what seems a sensible place.
A
----
:books: Documentation preview :books:: https://pep-previews--3242.org.readthedocs.build/

PEP 502: Resolve unreferenced footnotes

---

pep-0505.rst

Fixed a whitespace issue.
A
----
:books: Documentation preview :books:: https://pep-previews--3243.org.readthedocs.build/

PEP 505: Resolve unreferenced footnotes

---

pep-0419.txt

Footnote [4] referenced the initial email to Python-Dev, and [5] referenced https://github.com/python/cpython/issues/58935, both of which seem severable from the main text.
A
----
:books: Documentation preview :books:: https://pep-previews--3235.org.readthedocs.build/

PEP 419: Resolve unreferenced footnotes

---

pep-0644.rst

Fix reST syntax.
A
----
:books: Documentation preview :books:: https://pep-previews--3252.org.readthedocs.build/

PEP 644: Resolve unreferenced footnotes

---

pep-0654.rst

Footnote [13] was added in cef697a, which also added the stanza on "Implementing a better task spawning API..." to which I've added a reference to [13].
A
----
:books: Documentation preview :books:: https://pep-previews--3254.org.readthedocs.build/

PEP 654: Resolve unreferenced footnotes

---

pep-0667.rst

A few proposed updates to PEP 667. Namely:
* Add a brief section on interaction with PEP 709 inlined comprehensions. Contrary to https://github.com/python/cpython/pull/105715#issuecomment-1600479868, I don't think that we need to, or should, make `frame.f_locals` be a proxy in module or class scopes. In particular, making `locals()` always return a new snapshot (rather than the true persistent locals dict) in module or class scopes would be too large a back-compat break, I think, since people may be currently relying on assignment to `locals()` in those scopes. Instead I think we can simply preserve the current (3.12) behavior that `locals()` returns a new snapshot dict in module/class scope only when inside an inlined comprehension. This PEP makes that behavior consistent with how …

PEP 667: add 709 impact, other tweaks

---

pep-0571.rst

Re-numbered, as footnote [18] was unused.
A
----
:books: Documentation preview :books:: https://pep-previews--3248.org.readthedocs.build/

PEP 571: Resolve unreferenced footnotes

---

pep-0545.txt

Footnote [2] has never been referenced; I removed the markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3247.org.readthedocs.build/

PEP 545: Resolve unreferenced footnotes

---

pep-3104.txt

Footnote [15] existed in the first draft of the PEP, I've removed the syntax.
A
----
:books: Documentation preview :books:: https://pep-previews--3256.org.readthedocs.build/

PEP 3104: Resolve unreferenced footnotes

---

pep-3135.txt

Footnotes [1] and [2] existed since the re-numbering of PEP 3135, but had their references removed in 8e2ffa3. This removes the markup (and also fixes the markup of [*History*](https://peps.python.org/pep-3135/#history)).
A
----
:books: Documentation preview :books:: https://pep-previews--3260.org.readthedocs.build/

PEP 3135: Resolve unreferenced footnotes

---

pep-3100.txt

Footnote [26] was unreferenced -- it was added in c47893b, but it seems there was a typo with the reference -- footnote [25] was added in 91f95b4 and relates to the lines that I've added a reference to [25] in.
A
----
:books: Documentation preview :books:: https://pep-previews--3255.org.readthedocs.build/

PEP 3100: Resolve unreferenced footnotes

---

.github/CODEOWNERS
pep-0722.rst

@python/pep-editors - I've grabbed the next PEP number (722) that seemed available. Hope that's OK, I can change the number if needed.
----
:books: Documentation preview :books:: https://pep-previews--3210.org.readthedocs.build/

PEP 722: Dependency specification for single-file scripts
