- pep-0013.rst
- pep-8103.rst
> PEP 8103: Official dates for 2022 term election

- .github/CODEOWNERS
- pep-0670.rst
> PEP 670: Convert macros to functions in the Python C API

- pep-0670.rst
> PEP 670: Nitpick

- .github/CODEOWNERS
- pep-0672.rst
See discussion here: https://mail.python.org/archives/list/python-dev@python.org/thread/6DBJJRQHA2SP5Q27MOMDSTCOXMW7ITNR/#CBI7ME3YUAVVH5B6LSC745GJSVUIZJHO
> PEP 672 (new): Unicode-related Security Considerations for Python

- pep-0665.rst
> PEP 665: take 2

- pep-0663.txt
I found the creation date confusing at first, and was then motivated to fix when spotting the other typos.
> PEP 663: Fix typo and creation date

- .github/CODEOWNERS
- pep-0673.rst
Format text and code to fit within 79 characters.
cc @Gobot1234
> PEP 673: Initial commit for Self Types.

- pep-0483.txt
Need to use the parameters provided to get to Error that is suggested in the comments.
> PEP 483: fixes issue of getting wrong Error

- pep-0646.rst
> PEP 646: fix typo

- pep-0674.rst
> PEP 674: Disallow using macros as l-value

- pep-0674.rst
> PEP 674: Backward compatibility

- pep-0674.rst
> PEP 674: HPy endorsement

- pep-0674.rst
> PEP 674: Fix typo

- pep-0674.rst
> PEP 674: Sam's endorsment for the nogil section

- .github/CODEOWNERS
- pep-0676.rst
Submitting here to claim a PEP number as [advised by Nick](https://discuss.python.org/t/request-for-comment-making-pep-rendering-self-contained/10774/21).
*(I haven't added Mariatta to CODEOWNERS yet as I think a PEP number needs to be assigned first)*
A
> PEP 676: PEP Infrastructure Process

- pep-0613.rst
> PEP 613: Change unicode quotes with ASCII quotes

- pep-0672.rst
> PEP 672: Fix typo

- pep-0677.rst
Include everyone who's helped review the PEP draft so far :)
Remove the TODO, which I hadn't intended to commit - surprised no one asked me to get rid of it in code review!
> PEP 677: Update the thanks section

- pep-0616.rst
> PEP 0616 (removeprefix) typo in 'Rejected' section

- pep-0646.rst
A code block was formatted as a quotation by mistake.
> PEP 646: Fix code markup

- pep-0011.txt
> PEP 11: Ungender the volunteer pronoun.

- pep-0679.rst
> PEP 679: Allow parentheses in assert statements

- pep-0680.rst
> PEP 680: Address merwok's review

- pep-0673.rst
@JelleZijlstra Just realized that we need to add this.
I'm guessing the next step is to add an issue in this tracker: https://github.com/python/steering-council/issues
> PEP 673: Add Post-History.

- pep-0648.rst
> PEP 648: Update status to rejected

- pep-0646.rst
@gvanrossum @pradeep90 
Just a small change :)
> PEP 646: Clarify indexing assignment

- conf.py
@JelleZijlstra 
Annoyingly simple fix, as usual!
xref https://github.com/AA-Turner/peps/runs/4834683325 for a successful build
A
> Fix Sphinx build

- pep-0674.rst
> PEP 674: Address Tim Felgentreff's review

- pep-0646.rst
Huge thank you to everyone who helped get this across the finish line, especially @gvanrossum! Well done to all of us, @mrkmndz @pradeep90 @vsiles @fylux!
> PEP 646: Mark as Accepted

- pep-0673.rst
> PEP 673: Mark as Accepted and add Resolution link

- pep-0676.rst
> PEP 676: Barry Warsaw is the delegate

- pep-0678.rst
> PEP 678: Update link to documentation PR

- pep-0674.rst
> PEP 674: List fixed projects; change title

- pep-0664.rst
> PEP 664: Mark Python 3.11.0 alpha 5 as released

- pep-0594.rst
I hope this might save others from the same journey of discovery that I
had in https://github.com/zopefoundation/zope.publisher/issues/39.
> PEP 594: mention how to replace (Mini)FieldStorage

- pep-0674.rst
> PEP 674: Clarify Statistics

- pep-0680.rst
> PEP 680: Mark as accepted

- pep-0683.rst
Some things I noticed while reading through #2341.
> PEP 683: Implement minor typographical changes

- pep-0484.txt
[Per the request](https://github.com/python/peps/issues/2199#issuecomment-1058821862) of @gvanrossum in #2199 .
> PEP 484: Update status from Provisional to Final

- pep-0682.rst
Per the announcement at https://discuss.python.org/t/accepting-pep-682-format-specified-for-signed-zero/14088, after being appointed PEP-Delegate for PEP 682, I'm accepting the PEP.  This PR updates the PEP headers accordingly.
> PEP 682: Updating headers for PEP acceptance

- pep-0664.rst
https://discuss.python.org/t/python-3-11-0a6-is-now-available/14105
> PEP 664: Update actual 3.11a6 release date

- AUTHOR_OVERRIDES.csv
- pep-0458.txt
- pep-0588.rst
- pep-8001.rst
- pep-8100.rst
- pep-8101.rst
- pep-8102.rst
- pep-8103.rst
various government agencies all agree my name doesn't have those bits now :)
> legally dropped the middle name and suffix.

- .github/workflows/render.yml
xref https://github.com/python/peps/pull/2410#issuecomment-1065585004
A
> PRS: Remove artifact upload

- pep-0685.rst
> PEP 685: address review comments

- generate_rss.py
closes #2407, closes #2406
This builds on Hugo's fix to also fix everything else.
A
> PRS: Fix RSS generation and resolve all warnings

- pep-0594.rst
This sentence doesn't currently make grammatical sense (though its meaning is admittedly clear).
> PEP 594: Fix minor typo

- pep-0594.rst
updating link for asyncio to corrected link
> PEP 594: minor fix of hyperlinks in table of replacements

- pep-0675.rst
cc @pradeep90 (and congratulations!)
> PEP 675: Mark as accepted

- pep-0619.rst
https://discuss.python.org/t/python-3-10-4-and-3-9-12-are-now-available-out-of-schedule/14568
https://docs.python.org/release/3.10.4/whatsnew/changelog.html
> PEP 619: Add 3.10.4 release

- pep-0665.rst
> Update pep-0665.rst much to must

- pep-0670.rst
@vstinner & @erlend-aasland, this should make the PEP more understandable & complete
> PEP 670: Rearrange and reword the PEP

- pep_sphinx_extensions/pep_theme/static/colour_scheme.js
Closes #2487 
(Just signed the CLA so may not have gone through yet)
> Fix colour scheme toggling when switching from default dark mode

- pep-0687.rst
> PEP 687: Add Discussions-To & Post-History

- pep-0664.rst
> PEP 664: 3.11.0 alpha 7 released

- pep-0682.rst
The implementation of PEP 682 was completed in python/cpython#30049.
> PEP 682: Change status to Final

- .github/CODEOWNERS
> PEP 687: Add to CODEOWNERS

- .github/CODEOWNERS
- infra/.gitignore
- infra/config.tf
- infra/main.tf
Unfortunately this is only manageable by me for now. I'll contact HashiCorp about extending our account to allow more users (to at least cover new PSF infra staff starting May 23).
> Terraform fastly service

- infra/main.tf
(also tests terraform cloud integration)
> Infra: bump HSTS to recommended settings

- pep-0011.txt
> PEP 11: fix nit typo of my name

- pep-0594.rst
> PEP-0594: Fix tiny typo

- README.rst
It's very useful but a bit buried. Hopefully this will help more people find it.
cc @gvanrossum
> Infra: Add note on finding the RTD preview

- pep-0689.rst
> PEP 689: Add Post-History

- pep-0485.txt
Updating so I can submit a new PEP with matching email.
Per Issue #2565 -- there can only be one per author.
@AA-Turner: Here you go, thanks!
> Update my email address in PEP-485 to a more recent one.

- pep-0690.rst
Adds the missing header and a link to the discussion.
> PEP 690: Adds discussion header and link

- pep-0691.rst
> PEP 691: Add Discussions-To

- pep-0664.rst
> PEP 664: Add 3.11.0b1 release date

- pep-0664.rst
> PEP 664: Fix indentation error

- pep-0687.rst
> PEP 687: Retarget to Python 3.12

- pep-0623.rst
Implemented in https://github.com/python/cpython/pull/92537
> PEP 623: Change status to Final

- pep-0007.txt
> PEP 7: Add note about greppable exception messages

- pep-0671.rst
> PEP 671: Fix formatting

- pep-0664.rst
> PEP 664: Add feature list

- pep-0619.rst
> PEP 619: Update bugfix release dates

- pep-0668.rst
As per https://discuss.python.org/t/10302/41
> PEP 668: Add PEP-Delegate

- pep-0690.rst
> PEP 690: Update draft per discussion and feedback

- pep-0694.rst
Thanks to @JelleZijlstra for catching these!
> PEP694: Grammar fixes

- pep-0687.rst
> PEP 687: Mark as Accepted

- .github/CODEOWNERS
> PEP 693, 694: add to CODEOWNERS

- pep-0801.rst
> PEP 801: We are the 801

- pep-0691.rst
> PEP691: fixed markup mistake

- pep-0683.rst
> PEP 683: Fix Link Formatting

- pep-0664.rst
> PEP-664: Update the date of the release of Python3.11.0b4

- pep-0664.rst
> Correct the date of Python 3.11.0b5

- pep-0695.rst
Incorporated feedback and updated the implementation section to reflect the latest prototype implementation.
> PEP 695: Incorporate feedback

- pep-0495.txt
see: https://github.com/python/cpython/issues/90359
> PEP 495: Update PyDateTime_GET_FOLD name into PyDateTime_DATE_GET_FOLD

- pep-0432.txt
Follow up to https://github.com/python/peps/pull/2716, fix code block per https://github.com/python/peps/pull/2716/files#r927791162.
> PEP 432: fix code block

- pep-0695.rst
> PEP 695: fix TypeScript syntax

- pep-0694.rst
programatically -> programmatically
> PEP 694: Fix typos

- pep-0664.rst
> PEP 664: Add 3.11.0b5 release date

- pep-0664.rst
To give more time between beta 5 and RC1.
> PEP 664: 3.11.0 RC1 expected Friday, 2022-08-05

- pep-0625.rst
> PEP 625: Mark as draft again

- pep-0664.rst
> PEP 664: Update 3.11 RC1 release date

- pep-0669.rst
> PEP 669: Clarify section on DISABLE.

- pep-0669.rst
> PEP 669: Clarify and restrict interaction with PEP 523

- pep-0678.rst
> PEP 678: fix typo in sample code

- pep-0669.rst
A few wording fixes & clarifications.
It's entirely possible the clarifications are wrong, please clarify the other way if so :)
> PEP 669: nitpicks & clarifications

- pep-0692.rst
Introduces proposed enhancements from the [discuss thread](https://discuss.python.org/t/pep-692-using-typeddict-for-more-precise-kwargs-typing/17314/21) and expands the "Motivation" section.
> PEP 692: Introduce proposed enhancements and expand Motivation section

- pep-0669.rst
> PEP 669: Require names for tools.

- pep-0689.rst
> PEP 689: Defer for now

- pep-0689.rst
> PEP 689: Fix typo in deferral note

- pep-0692.rst
Updated the Reference Implementation section to point to the latest mypy implementation of more precise kwargs typing.
> PEP 692: Update Reference Implementation section

- pep-0664.rst
> PEP 664: Add 3.11.0rc2 release date and correct date for 3.11.0 final

- pep-0518.txt
> PEP 518: Fix typo

- pep-0674.rst
> PEP 674: Update top 5000 PyPI projects stats

- .pre-commit-config.yaml
- pep-0684.rst
Note: I've left some TODO (actually "XXX") comments as placeholders in response to some of the feedback.
> PEP 684: Updates for Round 1 of Discussions

- pep-0683.rst
Note: I've left some TODO comments as placeholders in response to some of the feedback.
CC @eduardo-elizondo
> PEP 683: Updates for Round 4 of Discussions

- conf.py
- pep_sphinx_extensions/__init__.py
- requirements.txt
This is included in Sphinx core from version 5.1.
A
> Remove ``include_patterns`` monkeypatching

- pep-0699.rst
> PEP 699: Add Discussions-To

- pep-0698.rst
> PEP 698: Fix typo in example code

- pep-0697.rst
Rewrite the motivation/rationale.
The actual proposal stays nearly the same.
> PEP 697: Rewrite

- pep-0699.rst
> PEP 699: Add post history

- pep-0697.rst
> PEP 697: Add Post-History & Discussions-To

- pep-0669.rst
- pep-0696.rst
Follows further discussion on typing-sig
cc @erictraut
> PEP 696: Improve section "Using another TypeVarLike as the default"

- pep-0646.rst
> PEP 646: Add forgotten parameter name in examples

- pep-0688.rst
> PEP 688: Enhancements from discussion

- pep-0688.rst
> PEP 688: New Post-History links

- pep-0675.rst
Fixes https://github.com/python/peps/issues/2853
> PEP 675: Clarify Motivation query examples are abridged

- pep-0700.rst
> PEP 700: Update following discussions on Discourse

- pep-0383.txt
Fixes https://github.com/python/peps/issues/2862, and removes some redundant metadata.
> PEP 383: Fix broken link

- pep-0688.rst
> PEP 688: Small tweaks

- pep-0695.rst
> PEP-695: Fix formatting of code example

- pep-0683.rst
I've also updated the `Post-History` and `Discussions-To` headers.
> PEP 683: Mark the PEP as Accepted

- pep-0674.rst
* Set Python version to 3.12
* Update stats on top 5000 PyPI projects
* Complete Post History
> Update PEP 674

- pep-0619.rst
- pep-0664.rst
> Update 3.11.1 and 3.10.9 release dates

- pep-0674.rst
> PEP 674: Deferred

- pep-0620.rst
> PEP 620: Rejected

- pep-8104.rst
Withdrawn nominations:
* Change TBD -> None
Plus change voting period to past tense and remove a rogue `)`.
> PEP 8104: No withdrawn nominations

- pep-0701.rst
> PEP 701: Add discussion link

- pep-0700.rst
> PEP 700: Mark as accepted

- pep-0701.rst
> PEP 701: Incorporate feedback from the discussion thread

- pep-0701.rst
> PEP 701: Mention about code generators

- pep-0702.rst
> PEP 702: Add link

- pep-0702.rst
Pointed out by @hugovk on Discord.
> PEP 702: fix typos

- pep-0702.rst
> PEP 702: More discussion of precedent and runtime behavior

- pep-0698.rst
As far as I know this is the last update needed ahead of SC review.
> PEP 698: discuss.python.org thread to post-history

- pep-0659.rst
I'm not an academic, but when I click on the paper, it says 2011 on the first page. So surely it was published in 2011 right? (Admittedly I'm a bit confused, so I might be wrong)
> PEP 659: Mark's Paper was published in 2011, not 2010

- pep-0696.rst
> PEP 696: Add further clarification and edge cases

- pep-0582.rst
Adds `Rationale` section to the PEP
> Adds Rationale section in the PEP

- pep-0554.rst
> PEP 554: Simplify!

- pep-0702.rst
> PEP 702: Add to Post-History

- pep-0702.rst
> PEP 702: Fix typo, section ordering

- pep-0699.rst
> PEP 699: Add implementation link

- pep-0582.rst
`stie-packages` -> `site-packages`
> PEP 582: Correct typo

- .pre-commit-config.yaml
- pep-0684.rst
I had forgotten to update the Post-History header back in October.  There was also one minor point from that round of discussion that I had not added to the PEP yet.
> PEP 684: Minor Updates

- pep-0702.rst
> PEP 702: Update number of parameters in specification

- pep-0582.rst
Updates the PEP based on discussion. We now talk about having a full scheme and also opened an issue to repository to track any discussion related to new API.
> PEP 582: Updates sysconfig scheme requirement

- pep-0688.rst
> PEP 688: Expand backwards compatibility section

- pep-0706.rst
> PEP 706: Fix trivial typo

- pep-0692.rst
> PEP 692: Mark as accepted

- pep-0695.rst
----
:books: Documentation preview :books:: https://pep-previews--3033.org.readthedocs.build/en/3033/
> PEP 695: Update Post-History to include Discourse thread

- pep-0707.rst
----
:books: Documentation preview :books:: https://pep-previews--3034.org.readthedocs.build/en/3034/
> PEP 707: add discussion link and some discussion feedback

- pep-0706.rst
Address Greg's [review on Discourse](https://discuss.python.org/t/23903/8)
----
:books: Documentation preview :books:: https://pep-previews--3038.org.readthedocs.build/
> PEP 706: Address Greg's review

- pep-0707.rst
----
:books: Documentation preview :books:: https://pep-previews--3039.org.readthedocs.build/
> PEP 707: fix link to another PEP

- pep-0701.rst
----
:books: Documentation preview :books:: https://pep-previews--3048.org.readthedocs.build/
> PEP 701: Specify a lower bound for the nesting level

- pep-0696.rst
----
:books: Documentation preview :books:: https://pep-previews--3052.org.readthedocs.build/
> PEP 696: Final round of changes before submitting to SC

- pep-0701.rst
----
:books: Documentation preview :books:: https://pep-previews--3054.org.readthedocs.build/
> PEP 701: Fix typos

- pep-0705.rst
Link PEP 705 to newly-created discussion thread
----
:books: Documentation preview :books:: https://pep-previews--3055.org.readthedocs.build/
> PEP-705: Link discuss thread

- pep-0701.rst
----
:books: Documentation preview :books:: https://pep-previews--3056.org.readthedocs.build/
> PEP 701: Mark it as accepted

- pep-0554.rst
This change also includes some minor fixes and a note about concurrent.futures.
----
:books: Documentation preview :books:: https://pep-previews--3057.org.readthedocs.build/
> PEP 554: Drop "Shareable" Objects

- pep-0554.rst
----
:books: Documentation preview :books:: https://pep-previews--3058.org.readthedocs.build/
> PEP 554: Update the Post History

- pep-0661.rst
```diff
- Most common exiting idioms...
+ Most common existing idioms...
```
----
:books: Documentation preview :books:: https://pep-previews--3059.org.readthedocs.build/
> PEP 661: Fix minor typo

- pep-0705.rst
----
:books: Documentation preview :books:: https://pep-previews--3061.org.readthedocs.build/
> PEP-705: Fix typo

- pep-0554.rst
----
:books: Documentation preview :books:: https://pep-previews--3063.org.readthedocs.build/
> PEP 554: Always Do Run() in the Foreground

- pep-0708.rst
----
:books: Documentation preview :books:: https://pep-previews--3060.org.readthedocs.build/
> PEP 708: Clarifications + Reject Defining the Explicit Configuration

- pep-0554.rst
This includes minor fixes and other edits based on some feedback (https://discuss.python.org/t/pep-554-multiple-interpreters-in-the-stdlib/24855/7). 
----
:books: Documentation preview :books:: https://pep-previews--3067.org.readthedocs.build/
> PEP 554: Minor Updates

- pep-0706.rst
* Mark ak accepted
* Update reference implementation link
> PEP 706: Mark Accepted & update ref. implementation link

- pep-0704.rst
----
:books: Documentation preview :books:: https://pep-previews--3081.org.readthedocs.build/
> PEP 704: Withdraw and add a withdrawal notice

- pep-0669.rst
----
:books: Documentation preview :books:: https://pep-previews--3077.org.readthedocs.build/
> PEP 669: Mark as accepted

- pep-0582.rst
Re: 
* https://github.com/python/steering-council/issues/165#issuecomment-1486558595
* https://discuss.python.org/t/pep-582-python-local-packages-directory/963/430
----
:books: Documentation preview :books:: https://pep-previews--3078.org.readthedocs.build/
> PEP 582: Mark as rejected

- pep-0711.rst
----
:books: Documentation preview :books:: https://pep-previews--3091.org.readthedocs.build/
> PEP 711: fill in discussion links

- pep-0101.txt
----
:books: Documentation preview :books:: https://pep-previews--3085.org.readthedocs.build/
> PEP 101: Add information on Sigstore

- pep-0702.rst
----
:books: Documentation preview :books:: https://pep-previews--3092.org.readthedocs.build/
> PEP 702: Final tweaks

- pep-0554.rst
----
:books: Documentation preview :books:: https://pep-previews--3096.org.readthedocs.build/
> PEP 554: Bump to 3.13

- pep-0684.rst
----
:books: Documentation preview :books:: https://pep-previews--3097.org.readthedocs.build/
> PEP 684: Mark as Accepted

- pep-0697.rst
----
:books: Documentation preview :books:: https://pep-previews--3101.org.readthedocs.build/
> PEP 697: Mark as Accepted

- pep-0695.rst
----
:books: Documentation preview :books:: https://pep-previews--3103.org.readthedocs.build/
> PEP 695: Mark as accepted

- pep-0707.rst
----
:books: Documentation preview :books:: https://pep-previews--3098.org.readthedocs.build/
> PEP 707: Mark as rejected

- pep-0649.rst
----
:books: Documentation preview :books:: https://pep-previews--3106.org.readthedocs.build/
> Update PEP 649 with a major revision.

- .github/CODEOWNERS
- AUTHOR_OVERRIDES.csv
- pep-0713.rst
- pep-9999.rst
----
:books: Documentation preview :books:: https://pep-previews--3117.org.readthedocs.build/pep-0713/
> PEP 713: Callable Modules

- pep-0712.rst
----
:books: Documentation preview :books:: https://pep-previews--3120.org.readthedocs.build/
> PEP 712: Adding discussion links

- pep-0713.rst
----
:books: Documentation preview :books:: https://pep-previews--3121.org.readthedocs.build/
> PEP 713: add discussion link

- pep-0008.txt
https://github.com/python/peps/blob/6eb6167770c051b5f31c6fa23c33ab575c3bac34/pep-0008.txt#L483
`lower:[upper]:step`
----
:books: Documentation preview :books:: https://pep-previews--3128.org.readthedocs.build/
> PEP 8: Clarify variable name in slice 

- pep-0709.rst
----
:books: Documentation preview :books:: https://pep-previews--3140.org.readthedocs.build/
> PEP 709: mark as accepted

- pep-0701.rst
----
:books: Documentation preview :books:: https://pep-previews--3150.org.readthedocs.build/
> PEP 701: Add Marta to the list of authors

- pep-0537.txt
----
:books: Documentation preview :books:: https://pep-previews--3159.org.readthedocs.build/
> PEP 537: 3.7.17 release

- pep-0715.rst
Adds a link to the DPO thread for this PEP.
----
:books: Documentation preview :books:: https://pep-previews--3167.org.readthedocs.build/
> PEP 715: Discussions-To

- pep-0715.rst
Follow-on to #3168.
----
:books: Documentation preview :books:: https://pep-previews--3169.org.readthedocs.build/
> PEP 715: list valid extensions

- pep-0692.rst
- Typo fix on line 126.
- Make on of the examples a bit more readable.
----
:books: Documentation preview :books:: https://pep-previews--3173.org.readthedocs.build/
> PEP 692: Small fixes

- pep-0715.rst
Thanks to all who reviewed!
----
:books: Documentation preview :books:: https://pep-previews--3180.org.readthedocs.build/
> PEP 715: Mark as Accepted

- pep-0714.rst
----
:books: Documentation preview :books:: https://pep-previews--3186.org.readthedocs.build/
> PEP 714: Mark Accepted

- pep-0537.txt
----
:books: Documentation preview :books:: https://pep-previews--3187.org.readthedocs.build/
> Move 3.7 to end-of-life status

- pep-0384.txt
- pep-0652.rst
----
:books: Documentation preview :books:: https://pep-previews--3177.org.readthedocs.build/
> PEP 384, 652: Add canonical-doc notices

- pep-0681.rst
----
:books: Documentation preview :books:: https://pep-previews--3197.org.readthedocs.build/
> PEP 681: Fix a typo.

- pep-0383.txt
- pep-0421.txt
- pep-0529.txt
- pep-0689.rst
- pep-0701.rst
- pep-0706.rst
- pep-0714.rst
- pep-0715.rst
----
:books: Documentation preview :books:: https://pep-previews--3202.org.readthedocs.build/
> PEP 383, 421, 529, 689, 701, 706, 714, 715: Fix typos

- pep_sphinx_extensions/pep_theme/static/style.css
----
:books: Documentation preview :books:: https://pep-previews--3204.org.readthedocs.build/
> Meta: Remove overridden values in styles.css.

- pep-0722.rst
See [this comment](https://github.com/python/peps/pull/3210#pullrequestreview-1563427454)
----
:books: Documentation preview :books:: https://pep-previews--3269.org.readthedocs.build/
> PEP 722: Typo fix

- pep-0721.rst
Congratulations @encukou!
A
----
----
:books: Documentation preview :books:: https://pep-previews--3267.org.readthedocs.build/
> PEP 721: Mark as Accepted

- .github/workflows/documentation-links.yml
- .github/workflows/lint.yml
- .github/workflows/render.yml
- .github/workflows/test.yml
- Makefile
- build.py
Misc GHA workflow updates:
- Standardise formatting
- Add permissions section
- Add concurrency section
- Set ``FORCE_COLOR``
- Ensure ``pip`` is cached
A
----
:books: Documentation preview :books:: https://pep-previews--3270.org.readthedocs.build/
> Update GitHub Actions workflows

- .github/workflows/render.yml
----
:books: Documentation preview :books:: https://pep-previews--3273.org.readthedocs.build/
> Grant the Render workflow write permissions

- pep-0723.rst
See https://github.com/python/peps/pull/3277/files#r1286078922
cc @ofek
----
:books: Documentation preview :books:: https://pep-previews--3278.org.readthedocs.build/
> PEP 723: Fix swapped references

- pep-0722.rst
----
:books: Documentation preview :books:: https://pep-previews--3284.org.readthedocs.build/
> PEP 722: Fix reference implementation

- pep-0723.rst
----
:books: Documentation preview :books:: https://pep-previews--3279.org.readthedocs.build/
> PEP 723: update based on feedback

- pep-0722.rst
----
:books: Documentation preview :books:: https://pep-previews--3292.org.readthedocs.build/
> PEP 722: A couple of additional points for the rejected options

- pep_sphinx_extensions/pep_processor/html/pep_html_builder.py
----
:books: Documentation preview :books:: https://pep-previews--3294.org.readthedocs.build/
> Support Sphinx 7.2 in ``pep_sphinx_extensions``

- pep-0723.rst
----
:books: Documentation preview :books:: https://pep-previews--3297.org.readthedocs.build/
> Finalize PEP 723

- pep-0723.rst
----
:books: Documentation preview :books:: https://pep-previews--3307.org.readthedocs.build/
> PEP 723: Remove ``run.version``

- pep-0727.rst
PEP 727: Rewordings and clarifications from feedback by @mikeshardmind
----
:books: Documentation preview :books:: https://pep-previews--3315.org.readthedocs.build/
> PEP 727: Rewordings and clarifications

- pep-0376.txt
xref: #3275
----
:books: Documentation preview :books:: https://pep-previews--3318.org.readthedocs.build/
> PEP 376: Remove fragment from Post-History entry

- pep-0623.rst
xref: #3275
----
:books: Documentation preview :books:: https://pep-previews--3319.org.readthedocs.build/
> PEP 623: Remove fragment from Resolution

- pep-0720.rst
xref #3275
----
:books: Documentation preview :books:: https://pep-previews--3324.org.readthedocs.build/
> PEP 720: Remove blank ``Resolution`` header

- pep-0726.rst
From feedback by @oscarbenjamin
----
:books: Documentation preview :books:: https://pep-previews--3320.org.readthedocs.build/
> PEP 726: Correct and expand specification

- pep-0402.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3329.org.readthedocs.build/
> PEP 402: Standardise authors

- pep-3333.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3330.org.readthedocs.build/
> PEP 3333: Standardise authors

- pep-0516.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3331.org.readthedocs.build/
> PEP 516: Standardise authors

- pep-0518.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3332.org.readthedocs.build/
> PEP 518: Standardise authors

- pep-0381.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3333.org.readthedocs.build/
> PEP 381: Standardise authors

- pep-0382.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3334.org.readthedocs.build/
> PEP 382: Standardise authors

- pep-0384.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3336.org.readthedocs.build/
> PEP 384: Standardise authors

- pep-0397.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3338.org.readthedocs.build/
> PEP 397: Standardise authors

- pep_sphinx_extensions/pep_zero_generator/parser.py
- pep_sphinx_extensions/pep_zero_generator/writer.py
- pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
----
:books: Documentation preview :books:: https://pep-previews--3340.org.readthedocs.build/
> PEP 0: Refactoring

- pep_sphinx_extensions/pep_zero_generator/parser.py
----
:books: Documentation preview :books:: https://pep-previews--3341.org.readthedocs.build/
> PEP 0: Remove unneeded import

- pep-0201.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3342.org.readthedocs.build/
> PEP 201: Resolve dangling hyphens

- pep-0235.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3345.org.readthedocs.build/
> PEP 235: Resolve dangling hyphens

- pep-0249.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3346.org.readthedocs.build/
> PEP 249: Resolve dangling hyphens

- pep-0374.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3350.org.readthedocs.build/
> PEP 374: Resolve dangling hyphens

- pep-0465.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3353.org.readthedocs.build/
> PEP 465: Resolve dangling hyphens

- pep-0471.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3354.org.readthedocs.build/
> PEP 471: Resolve dangling hyphens

- pep-0479.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3355.org.readthedocs.build/
> PEP 479: Resolve dangling hyphens

- pep-0492.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3356.org.readthedocs.build/
> PEP 492: Resolve dangling hyphens

- pep-0512.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3357.org.readthedocs.build/
> PEP 512: Resolve dangling hyphens

- pep-3101.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3360.org.readthedocs.build/
> PEP 3101: Resolve dangling hyphens

- pep-3124.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3362.org.readthedocs.build/
> PEP 3124: Resolve dangling hyphens

- pep-3135.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3363.org.readthedocs.build/
> PEP 3135: Resolve dangling hyphens

- pep-3333.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3364.org.readthedocs.build/
> PEP 3333: Resolve dangling hyphens

- pep-3001.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3359.org.readthedocs.build/
> PEP 3001: Resolve dangling hyphens

- pep-0101.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3368.org.readthedocs.build/
> PEP 101: Resolve uses of the default role

- pep-0310.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3370.org.readthedocs.build/
> PEP 310: Resolve uses of the default role

- pep-0329.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3372.org.readthedocs.build/
> PEP 329: Resolve uses of the default role

- pep-0345.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3374.org.readthedocs.build/
> PEP 345: Resolve uses of the default role

- pep-0326.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3371.org.readthedocs.build/
> PEP 326: Resolve uses of the default role

- pep-0381.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3375.org.readthedocs.build/
> PEP 381: Resolve uses of the default role

- pep-0523.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3377.org.readthedocs.build/
> PEP 523: Resolve uses of the default role

- pep-0542.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3380.org.readthedocs.build/
> PEP 542: Resolve uses of the default role

- pep-0545.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3381.org.readthedocs.build/
> PEP 545: Resolve uses of the default role

- pep-0534.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3379.org.readthedocs.build/
> PEP 534: Resolve uses of the default role

- pep-0531.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3378.org.readthedocs.build/
> PEP 531: Resolve uses of the default role

- pep-3143.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3383.org.readthedocs.build/
> PEP 3143: Resolve uses of the default role

- pep-3103.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3382.org.readthedocs.build/
> PEP 3103: Resolve uses of the default role

- pep-3147.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3385.org.readthedocs.build/
> PEP 3147: Resolve uses of the default role

- pep-0399.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3390.org.readthedocs.build/
> PEP 399: Resolve uses of the default role

- pep-0402.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3391.org.readthedocs.build/
> PEP 402: Resolve uses of the default role

- pep-0391.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3388.org.readthedocs.build/
> PEP 391: Resolve uses of the default role

- pep-0423.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3392.org.readthedocs.build/
> PEP 423: Resolve uses of the default role

- pep-0447.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3396.org.readthedocs.build/
> PEP 447: Resolve uses of the default role

- pep-0499.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3397.org.readthedocs.build/
> PEP 499: Resolve uses of the default role

- pep-3149.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3401.org.readthedocs.build/
> PEP 3149: Resolve uses of the default role

- pep-0516.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3400.org.readthedocs.build/
> PEP 516: Resolve uses of the default role

- pep-0457.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3404.org.readthedocs.build/
> PEP 457: Resolve uses of the default role

- pep-0302.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3369.org.readthedocs.build/
> PEP 302: Resolve uses of the default role

- pep-0339.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3373.org.readthedocs.build/
> PEP 339: Resolve uses of the default role

- pep-0477.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3409.org.readthedocs.build/
> PEP 477: Resolve uses of the default role

- pep-0461.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3407.org.readthedocs.build/
> PEP 461: Resolve uses of the default role

- pep-0485.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3410.org.readthedocs.build/
> PEP 485: Resolve uses of the default role

- pep-0488.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3411.org.readthedocs.build/
> PEP 488: Resolve uses of the default role

- pep-0493.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3412.org.readthedocs.build/
> PEP 493: Resolve uses of the default role

- pep-0425.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3393.org.readthedocs.build/
> PEP 425: Resolve uses of the default role

- pep-0495.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3413.org.readthedocs.build/
> PEP 495: Resolve uses of the default role

- pep-0497.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3414.org.readthedocs.build/
> PEP 497: Resolve uses of the default role

- pep-0725.rst
----
:books: Documentation preview :books:: https://pep-previews--3416.org.readthedocs.build/
> PEP 725: Fix example using `project.optional-dependencies`

- .github/workflows/lint.yml
- .github/workflows/render.yml
- .github/workflows/test.yml
----
:books: Documentation preview :books:: https://pep-previews--3422.org.readthedocs.build/
> Infra: Use actions/checkout version 4

- peps/pep-0702.rst
----
:books: Documentation preview :books:: https://pep-previews--3442.org.readthedocs.build/
> PEP 702: Move to warnings, expand spec

- peps/pep-0729.rst
----
:books: Documentation preview :books:: https://pep-previews--3462.org.readthedocs.build/
> PEP 729: Update Discussions-To

- peps/pep-0670.rst
- peps/pep-0687.rst
----
:books: Documentation preview :books:: https://pep-previews--3463.org.readthedocs.build/
> PEP 670, 687: Update Erlend's email

- peps/pep-0602.rst
----
:books: Documentation preview :books:: https://pep-previews--3467.org.readthedocs.build/
> PEP 602: Fix lint, unbreak CI

- peps/pep-8001.rst
----
:books: Documentation preview :books:: https://pep-previews--3466.org.readthedocs.build/
> PEP 8001: Update my email address

- .github/CODEOWNERS
- peps/pep-0730.rst
----
:books: Documentation preview :books:: https://pep-previews--3473.org.readthedocs.build/pep-0730/
> PEP 730: Adding iOS as a supported platform

- peps/pep-0727.rst
PEP 727: Update `first_name` to `name` from feedback by @gpshead
----
:books: Documentation preview :books:: https://pep-previews--3478.org.readthedocs.build/
> PEP 727: Update `first_name` to `name` from feedback by Gregory P. Smith

- peps/pep-0731.rst
----
:books: Documentation preview :books:: https://pep-previews--3481.org.readthedocs.build/
> PEP 731: Add Discussions-To and Post-History

- peps/pep-0722.rst
----
:books: Documentation preview :books:: https://pep-previews--3499.org.readthedocs.build/
> PEP 722: Mark as rejected

- peps/pep-0732.rst
cc @jablonskidev 
----
:books: Documentation preview :books:: https://pep-previews--3509.org.readthedocs.build/
> PEP 732: Add Discussions-To and Post-History, fix typo

- peps/pep-0732.rst
----
:books: Documentation preview :books:: https://pep-previews--3515.org.readthedocs.build/
> PEP 732: Clarify group names and history

- peps/pep-0729.rst
----
:books: Documentation preview :books:: https://pep-previews--3513.org.readthedocs.build/
> PEP 729: expand to five members; list initial names

- peps/pep-0705.rst
----
:books: Documentation preview :books:: https://pep-previews--3520.org.readthedocs.build/
> PEP 705: Add new discussion thread URL

- peps/pep-0702.rst
----
:books: Documentation preview :books:: https://pep-previews--3524.org.readthedocs.build/
> PEP 702: Mark as Accepted

- peps/pep-8105.rst
----
:books: Documentation preview :books:: https://pep-previews--3530.org.readthedocs.build/
> PEP 8105: i dropped the ball, move dates on pep.

- peps/pep-0712.rst
----
:books: Documentation preview :books:: https://pep-previews--3496.org.readthedocs.build/
> PEP 712: Update with suggestions/clarifications from discussion

- peps/pep-8105.rst
----
:books: Documentation preview :books:: https://pep-previews--3543.org.readthedocs.build/
> PEP-8105: update with nominations and voter roll

- peps/pep-0729.rst
https://discuss.python.org/t/pep-729-typing-governance-process/35362/11?u=jelle
----
:books: Documentation preview :books:: https://pep-previews--3539.org.readthedocs.build/
> PEP 729: Reword confusing "end users" wording

- peps/pep-0737.rst
----
:books: Documentation preview :books:: https://pep-previews--3555.org.readthedocs.build/
> PEP 737: Add link to PEP discussion

- peps/pep-0698.rst
Fixes the broken or moved links in PEP 698
Closes #3568
> PEP 698: adjust broken or shifted links

- peps/pep-0013.rst
- peps/pep-8105.rst
----
:books: Documentation preview :books:: https://pep-previews--3582.org.readthedocs.build/
> PEP-8105 redux

- peps/pep-0013.rst
- peps/pep-8105.rst
----
📚 Documentation preview 📚: https://pep-previews--3584.org.readthedocs.build/
> PEP 8105: Publish final and complete results

- peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--3590.org.readthedocs.build/
> PEP 734: Add Links For Discussions

- peps/pep-0723.rst
TODO: Review and fix hyperlinks
----
📚 Documentation preview 📚: https://pep-previews--3601.org.readthedocs.build/
> PEP 723: Modify the spec based on post-acceptance discussions

- peps/pep-0732.rst
----
📚 Documentation preview 📚: https://pep-previews--3604.org.readthedocs.build/
> PEP 732: Mark as Active

- peps/pep-0467.rst
----
📚 Documentation preview 📚: https://pep-previews--3608.org.readthedocs.build/
> PEP 467: update

- peps/pep-0467.rst
- correct python version
- add Discussions-to header
----
📚 Documentation preview 📚: https://pep-previews--3609.org.readthedocs.build/
> PEP 437: update meta info

- peps/pep-0693.rst
----
📚 Documentation preview 📚: https://pep-previews--3624.org.readthedocs.build/
> PEP 693: Explicitly list 3.12's future patch release dates.

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3625.org.readthedocs.build/
> PEP 741: Python Configuration C API

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3626.org.readthedocs.build/
> PEP 741: Add Discussions-To

- peps/pep-0696.rst
cc @Gobot1234, let me know if you agree with these
----
📚 Documentation preview 📚: https://pep-previews--3638.org.readthedocs.build/
> PEP 696: Proposed changes

- peps/pep-0467.rst
----
📚 Documentation preview 📚: https://pep-previews--3611.org.readthedocs.build/
> PEP 467: add discouraged use example

- .github/CODEOWNERS
- .github/dependabot.yml
- .github/workflows/lint.yml
- .github/workflows/render.yml
- .github/workflows/test.yml
- .pre-commit-config.yaml
- .ruff.toml
- Makefile
- tox.ini
- Add Dependabot to keep GitHub Actions up-to-date
- Add hugovk to more CODEOWNERS
- Bump GitHub Actions
- Update pre-commit and fix Ruff deprecation warnings
- Build docs with number of processes = number of CPU cores
- Add Python 3.13 to tox, already in CI
----
📚 Documentation preview 📚: https://pep-previews--3645.org.readthedocs.build/
> Meta: Update config

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3652.org.readthedocs.build/
> PEP 741: Second version

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3654.org.readthedocs.build/
> PEP 741: Add Post History

- peps/pep-0726.rst
----
📚 Documentation preview 📚: https://pep-previews--3642.org.readthedocs.build/
> PEP 726: fix type of sys.modules

- peps/pep-0718.rst
----
📚 Documentation preview 📚: https://pep-previews--3594.org.readthedocs.build/
> PEP 718: Update discussions link

- peps/pep-0742.rst
----
📚 Documentation preview 📚: https://pep-previews--3665.org.readthedocs.build/
> PEP 742: Add Discussions-To; use TypeIs

- peps/pep-0735.rst
----
📚 Documentation preview 📚: https://pep-previews--3685.org.readthedocs.build/
> PEP 735: Fix a typo — "iif" -> "if"

- peps/pep-0667.rst
----
📚 Documentation preview 📚: https://pep-previews--3687.org.readthedocs.build/
> PEP 667: Add Tian to the list of authors

- peps/pep-0742.rst
Example sections on:
- When to use TypeIs
- How to write a safe TypeIs
- TypeIs vs. TypeGuard
Also note the implementations in typing-extensions and pyanalyze.
----
📚 Documentation preview 📚: https://pep-previews--3683.org.readthedocs.build/
> PEP 742: Expand "How to Teach This"

- peps/pep-0657.rst
----
📚 Documentation preview 📚: https://pep-previews--3605.org.readthedocs.build/
- specifically https://pep-previews--3605.org.readthedocs.build/pep-0657/#motivation
> PEP 657: Fix alignment typo

- peps/pep-0739.rst
Signed-off-by: Filipe Laíns <lains@riseup.net>
----
📚 Documentation preview 📚: https://pep-previews--3690.org.readthedocs.build/
> PEP 739: first round of feedback

- peps/pep-0394.rst
And remove redundant fields, and update BPO link.
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
----
📚 Documentation preview 📚: https://pep-previews--3691.org.readthedocs.build/
> PEP 394: Fix formatting

- peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--3664.org.readthedocs.build/
> PEP 734: Updates After Discussion

- peps/pep-0739.rst
Signed-off-by: Filipe Laíns <lains@riseup.net>
----
📚 Documentation preview 📚: https://pep-previews--3693.org.readthedocs.build/
> PEP 739: add missing fields

- peps/pep-0730.rst
----
📚 Documentation preview 📚: https://pep-previews--3694.org.readthedocs.build/
> PEP 730: Mark as accepted

- peps/pep-0726.rst
----
📚 Documentation preview 📚: https://pep-previews--3695.org.readthedocs.build/
> PEP 726: Mark as Rejected

- peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--3698.org.readthedocs.build/
> PEP 734: Fix the Example Code Under Interpreter.call_in_thread()

- peps/pep-0696.rst
- peps/pep-0705.rst
----
📚 Documentation preview 📚: https://pep-previews--3699.org.readthedocs.build/
> PEP 696, 705: Mark as Accepted

- peps/pep-0667.rst
----
📚 Documentation preview 📚: https://pep-previews--3688.org.readthedocs.build/
> PEP 667: Add discussion and implementation link

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3706.org.readthedocs.build/
> PEP 741: Add Multi-phase section

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3709.org.readthedocs.build/
> PEP 741: Add sys.set_config()

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3710.org.readthedocs.build/
> PEP 741: Fix table formatting

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3711.org.readthedocs.build/
>  PEP 741: Remove the Python API

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3712.org.readthedocs.build/
> PEP 741: remove Spawn process section

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3713.org.readthedocs.build/
> PEP 741: Fix small mistakes

- peps/pep-0739.rst
----
📚 Documentation preview 📚: https://pep-previews--3717.org.readthedocs.build/
> PEP 739: add hexversion value in the example

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3718.org.readthedocs.build/
> PEP 741: Add PyInitConfig_GetExitcode() function

- peps/pep-0728.rst
Changes:
* Mention interaction with `__new__` and `__init__`
* Fix typos/bugs in examples
* Revise consistency rules interacting with `dict[str, VT]`
* Minor wording changes to the rejected ideas section
----
📚 Documentation preview 📚: https://pep-previews--3697.org.readthedocs.build/
> PEP 728: Address Review Feedback

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3719.org.readthedocs.build/
> PEP 741: Update Discussions-To link

- peps/pep-0737.rst
The Steering Council accepted the PEP.
----
📚 Documentation preview 📚: https://pep-previews--3720.org.readthedocs.build/
> Set PEP 737 status to Accepted

- peps/pep-0728.rst
----
📚 Documentation preview 📚: https://pep-previews--3722.org.readthedocs.build/
> PEP 728: Update the reference implementation support.

- peps/pep-0737.rst
----
📚 Documentation preview 📚: https://pep-previews--3723.org.readthedocs.build/
> PEP 737: Set status to Final

- peps/pep-0728.rst
----
📚 Documentation preview 📚: https://pep-previews--3724.org.readthedocs.build/
> PEP 728: Wording updates for clarity in certain sections

- peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3726.org.readthedocs.build/
> PEP 741: Add another example needing a stable ABI

- peps/pep-0667.rst
----
📚 Documentation preview 📚: https://pep-previews--3731.org.readthedocs.build/
> PEP 667: Remove open issues section, as the issues have been resolved

- peps/pep-0667.rst
----
📚 Documentation preview 📚: https://pep-previews--3730.org.readthedocs.build/
> PEP 667: Incorporate feedback

- peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--3741.org.readthedocs.build/
> PEP 734: Minor Updates

- peps/pep-0738.rst
----
📚 Documentation preview 📚: https://pep-previews--3740.org.readthedocs.build/
> PEP 738: Mark as accepted

- peps/pep-0664.rst
----
📚 Documentation preview 📚: https://pep-previews--3745.org.readthedocs.build/
> PEP 664: Add 3.11.9 release date

- peps/pep-0742.rst
----
📚 Documentation preview 📚: https://pep-previews--3747.org.readthedocs.build/
> PEP 742: Mark as Accepted

- peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--3749.org.readthedocs.build/
> SC decides to Defer PEP 734

- peps/pep-0744.rst
Also, make inline links anonymous.
----
📚 Documentation preview 📚: https://pep-previews--3752.org.readthedocs.build/
> PEP 744: Add Discussions-To and Post-History

- peps/pep-0740.rst
~~Not ready for merge yet;~~ opening up so that @di and others can review before I make more changes.
----
📚 Documentation preview 📚: https://pep-previews--3692.org.readthedocs.build/
> PEP 740: Feedback, round 2

- peps/pep-0639.rst
----
📚 Documentation preview 📚: https://pep-previews--3776.org.readthedocs.build/
> PEP 639: Update the discussion thread link + acknowledge the advisors

- peps/pep-0719.rst
Fixes #3780 
----
📚 Documentation preview 📚: https://pep-previews--3779.org.readthedocs.build/
> PEP 719: Update 3.13.0b1 release date

- peps/pep-0544.rst
Related issue: #3312 
----
📚 Documentation preview 📚: https://pep-previews--3783.org.readthedocs.build/
> PEP 544: Update Example

- peps/pep-0649.rst
https://discuss.python.org/t/pep-649-deferred-evaluation-of-annotations-tentatively-accepted/21331/65
----
📚 Documentation preview 📚: https://pep-previews--3790.org.readthedocs.build/
> PEP 649: Retarget to 3.14

- peps/pep-0602.rst
----
📚 Documentation preview 📚: https://pep-previews--3797.org.readthedocs.build/
> PEP 602: Link to SC acceptance

- peps/pep-0729.rst
----
📚 Documentation preview 📚: https://pep-previews--3799.org.readthedocs.build/
> PEP 729: Link to current membership

- peps/pep-0737.rst
----
📚 Documentation preview 📚: https://pep-previews--3806.org.readthedocs.build/
> PEP 737: Clarify '%T' description

- peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--3815.org.readthedocs.build/
> PEP 749: Discussions-To

- peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--3816.org.readthedocs.build/
> PEP 749: Make one point more explicit

- peps/pep-0746.rst
----
📚 Documentation preview 📚: https://pep-previews--3822.org.readthedocs.build/
> Add note to PEP-746 about  raising NotImplementedError

- peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--3831.org.readthedocs.build/
> PEP 749: Add note on signature of __annotate__

- peps/pep-2026.rst
----
📚 Documentation preview 📚: https://pep-previews--3837.org.readthedocs.build/
> PEP 2026: Add Discussions-To and Post-History

- peps/pep-0747.rst
----
📚 Documentation preview 📚: https://pep-previews--3839.org.readthedocs.build/
> PEP 747: Add Discussions-To link

- peps/pep-0747.rst
----
📚 Documentation preview 📚: https://pep-previews--3849.org.readthedocs.build/
> PEP 747: Add new "How to Teach This" section. Address other feedback.

- .github/CODEOWNERS
- peps/pep-0731.rst
----
📚 Documentation preview 📚: https://pep-previews--3852.org.readthedocs.build/
> PEP 731: Update C API WG members

- peps/pep-0710.rst
----
:books: Documentation preview :books:: https://pep-previews--3246.org.readthedocs.build/
> PEP 710: Add ``index_url`` key to ``provenance_url.json``

- peps/conf.py
----
📚 Documentation preview 📚: https://pep-previews--3855.org.readthedocs.build/
> Intersphinx config: add Python 3.13 docs

- peps/pep-2026.rst
----
📚 Documentation preview 📚: https://pep-previews--3860.org.readthedocs.build/pep-2026/
> PEP 2026: Update following discussion

- peps/pep-0011.rst
cc @freakboy3742 
----
📚 Documentation preview 📚: https://pep-previews--3865.org.readthedocs.build/
> PEP 11: Add Russell as an iOS contact

- peps/pep-0719.rst
----
📚 Documentation preview 📚: https://pep-previews--3868.org.readthedocs.build/
> PEP 719: Update for today's release of 3.13.0b4

- peps/pep-0008.rst
Previous one works, but it redirects to the Camel_Case
> PEP 8: Fixed wiki link

- peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3879.org.readthedocs.build/
> PEP 710: require at leat one hash to be stated

- peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3881.org.readthedocs.build/
> PEP 710: check uv for possible naming collision

- peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3882.org.readthedocs.build/
> PEP 710: state initial support in PDM

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3883.org.readthedocs.build/
> PEP 751: address comments

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3888.org.readthedocs.build/
> PEP 751: add `editable` to `packages.directory`

- peps/pep-0661.rst
These are in anticipation of (finally) submitting PEP 661 to the steering council for review.
> PEP 661: Small updates

- peps/pep-0750.rst
----
📚 Documentation preview 📚: https://pep-previews--3901.org.readthedocs.build/
> PEP 750: Add Discussions-To header

- peps/pep-0750.rst
----
📚 Documentation preview 📚: https://pep-previews--3902.org.readthedocs.build/
> PEP 750: Fix code example and CPython version in abstract

- peps/pep-0752.rst
https://discuss.python.org/t/pep-752-package-repository-namespaces/61227
----
📚 Documentation preview 📚: https://pep-previews--3911.org.readthedocs.build/
> PEP 752: Update discussion history

- peps/pep-0752.rst
----
📚 Documentation preview 📚: https://pep-previews--3919.org.readthedocs.build/
> PEP 752: Fix terminology markup

- peps/pep-0741.rst
Remove outdated sentence.
----
📚 Documentation preview 📚: https://pep-previews--3923.org.readthedocs.build/
> PEP 741: Update abstract

- peps/pep-0639.rst
Follow-up on: https://github.com/python/peps/pull/3926
----
📚 Documentation preview 📚: https://pep-previews--3928.org.readthedocs.build/
> PEP 639: Mark as Provisional

- peps/pep-0741.rst
Update also Implementation links.
----
📚 Documentation preview 📚: https://pep-previews--3935.org.readthedocs.build/
> PEP 741: Set Status to Final

- peps/pep-0752.rst
----
📚 Documentation preview 📚: https://pep-previews--3950.org.readthedocs.build/
> PEP 752: minor touchups

- peps/pep-0755.rst
----
📚 Documentation preview 📚: https://pep-previews--3951.org.readthedocs.build/
> PEP 755: minor touchups

- peps/pep-0752.rst
- peps/pep-0755.rst
----
📚 Documentation preview 📚: https://pep-previews--3952.org.readthedocs.build/
> PEP 752, 755: update history

- peps/pep-0739.rst
- peps/pep-0739/example.json
- peps/pep-0739/python-build-info-v1.schema.json
----
📚 Documentation preview 📚: https://pep-previews--3954.org.readthedocs.build/
> PEP 739: Update based on discussion feedback

- peps/conf.py
- peps/pep-0757.rst
* more hyperlinks
* expand "open questions" section
* add Discussions-To and Post-History
> PEP 757: minor edits

- peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--3963.org.readthedocs.build/
> PEP 757: Fix typo

- peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--3964.org.readthedocs.build/
> PEP 756: Remove flags

- peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--3966.org.readthedocs.build/
> PEP 757: Make PyLong_DigitArray.obj private

- peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--3968.org.readthedocs.build/
> PEP 756: Remove Open Questions

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3969.org.readthedocs.build/
> PEP 751: updates based on user feedback

- peps/conf.py
- peps/pep-0757.rst
ToDo:
----
📚 Documentation preview 📚: https://pep-previews--3975.org.readthedocs.build/
> PEP 757: address review, sync with PR and prettify

- peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--3981.org.readthedocs.build/
> PEP 756: Add Discussions-To and Post-History headers

- peps/pep-3126.rst
Minor fix - missing result in example code
----
📚 Documentation preview 📚: https://pep-previews--3978.org.readthedocs.build/
> PEP 3126: Minor Fix - Result Missing From Example Code

- peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--3984.org.readthedocs.build/
> PEP 757: misc edits

- peps/pep-0747.rst
----
📚 Documentation preview 📚: https://pep-previews--4006.org.readthedocs.build/
> PEP 747: Fix code block formatting. Fix grammar.

- peps/pep-0758.rst
----
📚 Documentation preview 📚: https://pep-previews--4016.org.readthedocs.build/
> PEP 758: Add Post-History

- peps/pep-0746.rst
----
📚 Documentation preview 📚: https://pep-previews--4019.org.readthedocs.build/
> PEP 746: Rename __supports_type__ to __supports_annotated_base__

- pep_sphinx_extensions/pep_zero_generator/writer.py
----
📚 Documentation preview 📚: https://pep-previews--4021.org.readthedocs.build/
> Infra: Mention 'Superseded' in section heading

- .github/CODEOWNERS
- peps/pep-0761.rst
----
📚 Documentation preview 📚: https://pep-previews--4027.org.readthedocs.build/pep-0761/
> PEP 761: Deprecating PGP signatures for CPython artifacts

- peps/pep-0526.rst
Fixes https://github.com/python/peps/issues/4024
> PEP 526: Fix broken link to implementation

- peps/pep-0761.rst
----
📚 Documentation preview 📚: https://pep-previews--4034.org.readthedocs.build/
> PEP 761: Add Discussions-To link

- peps/pep-0761.rst
----
📚 Documentation preview 📚: https://pep-previews--4035.org.readthedocs.build/
> PEP 761: Add additional links to Sigstore docs

- peps/pep-0759.rst
Point to the DPO thread.
----
📚 Documentation preview 📚: https://pep-previews--4038.org.readthedocs.build/
> PEP 759: Add Discussions-To header

- peps/pep-0661.rst
----
📚 Documentation preview 📚: https://pep-previews--4046.org.readthedocs.build/
> PEP 661: Small changes, clarifications and better wording (towards submission)

- peps/pep-0661.rst
----
📚 Documentation preview 📚: https://pep-previews--4050.org.readthedocs.build/
> PEP 661: Add missing sections and correctly populate Post-History

- peps/pep-0661.rst
----
📚 Documentation preview 📚: https://pep-previews--4051.org.readthedocs.build/
> PEP 661: Add bool value to reference impl and examples

- .github/CODEOWNERS
- peps/pep-0762.rst
Preview here: https://pep-previews--4048.org.readthedocs.build/pep-0762/
> PEP 762: REPL-acing the default REPL

- peps/pep-0761.rst
Also tagging @woodruffw as a reviewer for technical accuracy.
> PEP 761: Add notes for Cosign and offline verification

- peps/pep-0745.rst
https://discuss.python.org/t/python-3-14-0-alpha-1/68039
----
📚 Documentation preview 📚: https://pep-previews--4057.org.readthedocs.build/
> PEP 745: 3.14.0a1 was released on 2024-10-15

- peps/pep-0743.rst
----
📚 Documentation preview 📚: https://pep-previews--4060.org.readthedocs.build/
> PEP 743: Delegate to the C API Working Group

- peps/pep-0661.rst
This is an attempt to specify the behavior that I suggested on Discuss
and that has been endorsed by the Typing Council.
----
📚 Documentation preview 📚: https://pep-previews--4065.org.readthedocs.build/
> PEP 661: Proposed typing specification changes

- peps/pep-8106.rst
----
📚 Documentation preview 📚: https://pep-previews--4077.org.readthedocs.build/
> PEP 8106: 2025 Term Steering Council election

- peps/pep-8106.rst
----
📚 Documentation preview 📚: https://pep-previews--4079.org.readthedocs.build/
> PEP 8106: Update year to 2024

- peps/pep-0743.rst
Looks like we forgot to add this in March.
----
📚 Documentation preview 📚: https://pep-previews--4084.org.readthedocs.build/
> PEP 743: Add Discussions-To header

- peps/pep-0763.rst
Official discussion thread: https://discuss.python.org/t/69487
----
📚 Documentation preview 📚: https://pep-previews--4089.org.readthedocs.build/
> PEP 763: add Discussions-To

- peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--4094.org.readthedocs.build/
> PEP 756: Mark as Withdrawn

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4097.org.readthedocs.build/
> PEP 751: update post history

- peps/pep-0525.rst
----
📚 Documentation preview 📚: https://pep-previews--4110.org.readthedocs.build/
> PEP 525: Fix comment in code example

- peps/pep-0761.rst
----
📚 Documentation preview 📚: https://pep-previews--4113.org.readthedocs.build/
> PEP 761: Mark as Active

- peps/pep-0011.rst
----
📚 Documentation preview 📚: https://pep-previews--4115.org.readthedocs.build/
> PEP 11: be more specific about the WASI triple

- peps/pep-0012/pep-NNNN.rst
Followup from #4058.
----
📚 Documentation preview 📚: https://pep-previews--4129.org.readthedocs.build/
> PEP 12: Remove explicit mention of real name

- peps/pep-0745.rst
----
📚 Documentation preview 📚: https://pep-previews--4131.org.readthedocs.build/
> PEP 745: 3.14.0a2 was released on 2024-11-19

- peps/pep-0765.rst
----
📚 Documentation preview 📚: https://pep-previews--4125.org.readthedocs.build/pep-0765/
> PEP 765: add report as appendix

- peps/pep-0765.rst
----
📚 Documentation preview 📚: https://pep-previews--4130.org.readthedocs.build/
> PEP 765: add rejected ideas section

- peps/pep-8106.rst
----
📚 Documentation preview 📚: https://pep-previews--4135.org.readthedocs.build/
> PEP-8106: update with nominations and voter roll

- peps/pep-0757.rst
This reverts commit 5074ef63c2b354e002c43a76d7bfff901e7223d5.
----
📚 Documentation preview 📚: https://pep-previews--4141.org.readthedocs.build/
> Revert "Set PEP 757 status to Accepted (#4140)"

- peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4142.org.readthedocs.build/
> PEP 757: Remove PEP Delegate

- peps/pep-0767.rst
----
📚 Documentation preview 📚: https://pep-previews--4157.org.readthedocs.build/
> PEP 767: Update Discussions-To

- peps/pep-0013.rst
- peps/pep-8106.rst
----
📚 Documentation preview 📚: https://pep-previews--4161.org.readthedocs.build/
> PEP 8106: Publish results

- peps/pep-0768.rst
----
📚 Documentation preview 📚: https://pep-previews--4171.org.readthedocs.build/
> PEP 768: Fix a small typo

- peps/pep-0768.rst
----
📚 Documentation preview 📚: https://pep-previews--4175.org.readthedocs.build/
> PEP 768: Correct attribution

- peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4189.org.readthedocs.build/
> PEP 770: Add discussion link

- peps/pep-0694.rst
- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4203.org.readthedocs.build/
> PEP 751: orient towards a requirements file lock file replacement

- peps/pep-0769.rst
----
📚 Documentation preview 📚: https://pep-previews--4191.org.readthedocs.build/
> PEP 769: Add Discussions-To and Post-History

- peps/pep-0769.rst
----
📚 Documentation preview 📚: https://pep-previews--4214.org.readthedocs.build/
> PEP 769: Incorporated open issues resolutions to the rest of the document.

- Makefile
Similar to https://github.com/python/cpython/pull/129094.
----
📚 Documentation preview 📚: https://pep-previews--4217.org.readthedocs.build/
> Infra: fix venv creation for the local Python using uv

- peps/pep-0744.rst
Just a quick update to change my email address
----
📚 Documentation preview 📚: https://pep-previews--4233.org.readthedocs.build/
> PEP 744: Update Savannah's email address

- peps/pep-0773.rst
----
📚 Documentation preview 📚: https://pep-previews--4237.org.readthedocs.build/
> PEP 773: Various text improvements

- peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4222.org.readthedocs.build/
> PEP 770: Add sections for Users, Projects, and SCA tools in 'How to Teach'

- peps/pep-0668.rst
- peps/pep-0720.rst
- peps/pep-0739.rst
----
📚 Documentation preview 📚: https://pep-previews--4244.org.readthedocs.build/
> misc: change my email to lains@python.org

- peps/pep-0772.rst
----
📚 Documentation preview 📚: https://pep-previews--4254.org.readthedocs.build/
> Add Discussions-To header for PEP 772

- peps/pep-0765.rst
----
📚 Documentation preview 📚: https://pep-previews--4255.org.readthedocs.build/
> PEP 765: Mark as Accepted

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4260.org.readthedocs.build/
> PEP 751: fix a spelling mistake

- peps/pep-0769.rst
----
📚 Documentation preview 📚: https://pep-previews--4273.org.readthedocs.build/
> PEP 769: Fixed exception in a example code snippet.

- peps/pep-0774.rst
----
📚 Documentation preview 📚: https://pep-previews--4261.org.readthedocs.build/
> PEP 774: Add calculation details

- peps/pep-0774.rst
----
📚 Documentation preview 📚: https://pep-previews--4274.org.readthedocs.build/
> PEP 774: Add Post-History

- peps/pep-0508.rst
----
📚 Documentation preview 📚: https://pep-previews--4277.org.readthedocs.build/
> PEP 508: Add canonical spec link

- peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--4289.org.readthedocs.build/
> PEP 749: Close open issues, other updates

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4293.org.readthedocs.build/
> PEP 751: update example from a proof-of-concept

- peps/pep-0545.rst
----
📚 Documentation preview 📚: https://pep-previews--4294.org.readthedocs.build/
> PEP 545: Add python-docs-translations org mention

- peps/pep-0545.rst
----
📚 Documentation preview 📚: https://pep-previews--4295.org.readthedocs.build/
> PEP 545: Minor updates

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4311.org.readthedocs.build/
> PEP 751: update acknowledgements

- peps/pep-0780.rst
----
📚 Documentation preview 📚: https://pep-previews--4324.org.readthedocs.build/
> PEP 780: Update discussion links

- peps/pep-0770.rst
Forgot to remove this issue as this PEP no longer specifies source SBOMs.
----
📚 Documentation preview 📚: https://pep-previews--4322.org.readthedocs.build/
> PEP 770: Resolving conditional source SBOM issue

- peps/pep-0752.rst
----
📚 Documentation preview 📚: https://pep-previews--4332.org.readthedocs.build/
> PEP 752: minor stylistic update

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4336.org.readthedocs.build/
> PEP 751: Mark as Accepted

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4337.org.readthedocs.build/
> PEP 751: Add the acceptance date

- pep_sphinx_extensions/LICENCE.rst
----
📚 Documentation preview 📚: https://pep-previews--4347.org.readthedocs.build/
> Meta: Correct a typo in LICENCE.rst

- .github/CODEOWNERS
----
📚 Documentation preview 📚: https://pep-previews--4359.org.readthedocs.build/
> Sort CODEOWNERS

- peps/pep-0649.rst
cc @larryhastings 
----
📚 Documentation preview 📚: https://pep-previews--4371.org.readthedocs.build/
> PEP 649: Fix my name

- peps/pep-0788.rst
https://discuss.python.org/t/pep-788-reimagining-native-threads/89863
----
📚 Documentation preview 📚: https://pep-previews--4390.org.readthedocs.build/pep-0788/
> PEP 788: Add discussion link

- peps/pep-0773.rst
----
📚 Documentation preview 📚: https://pep-previews--4392.org.readthedocs.build/
> PEP 773: Mark as Accepted

- pep_sphinx_extensions/pep_theme/templates/page.html
Closes #4396.
A
----
📚 Documentation preview 📚: https://pep-previews--4398.org.readthedocs.build/
> Infra: Add site analytics via Plausible

- peps/pep-0720.rst
----
📚 Documentation preview 📚: https://pep-previews--4397.org.readthedocs.build/
> PEP 720: tweak some grammar

- peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4419.org.readthedocs.build/
> PEP 751: add canonical link to spec

- peps/pep-0775.rst
----
📚 Documentation preview 📚: https://pep-previews--4417.org.readthedocs.build/
> PEP 775: Withdraw

- peps/pep-0791.rst
----
📚 Documentation preview 📚: https://pep-previews--4427.org.readthedocs.build/
> PEP 791: add Discussions-To

- peps/pep-0774.rst
----
📚 Documentation preview 📚: https://pep-previews--4439.org.readthedocs.build/
> PEP 774: Mark as Deferred

- peps/pep-0793.rst
----
📚 Documentation preview 📚: https://pep-previews--4443.org.readthedocs.build/
> PEP 793: Add Discussions-To

- peps/pep-0794.rst
----
📚 Documentation preview 📚: https://pep-previews--4450.org.readthedocs.build/
> PEP 794: Update post-history

- peps/pep-0719.rst
----
📚 Documentation preview 📚: https://pep-previews--4461.org.readthedocs.build/
> PEP 719: Record the expedited 3.13.5 release.

- peps/pep-0722.rst
----
📚 Documentation preview 📚: https://pep-previews--4486.org.readthedocs.build/
> PEP 722: Link to replacement PEP

- peps/pep-0788.rst
----
📚 Documentation preview 📚: https://pep-previews--4493.org.readthedocs.build/
> PEP 788: Rename the PEP, per discussion

- peps/pep-0798.rst
----
📚 Documentation preview 📚: https://pep-previews--4499.org.readthedocs.build/
> PEP 798: Add link to Discourse thread

- Makefile
Fixes #4501 
----
📚 Documentation preview 📚: https://pep-previews--4502.org.readthedocs.build/
> ensure `make venv` exits on error

- peps/pep-0800.rst
----
📚 Documentation preview 📚: https://pep-previews--4508.org.readthedocs.build/
> PEP 800: Add Discussions-To link

- peps/pep-0772.rst
----
📚 Documentation preview 📚: https://pep-previews--4512.org.readthedocs.build/
> PEP 772: Update Post-History

- .github/workflows/test.yml
- tox.ini
----
📚 Documentation preview 📚: https://pep-previews--4523.org.readthedocs.build/
> Infra: test Python 3.14

- peps/pep-0676.rst
- peps/pep-0723.rst
- peps/pep-0726.rst
- peps/pep-0802.rst
----
📚 Documentation preview 📚: https://pep-previews--4533.org.readthedocs.build/
> Use a different address for Adam Turner

- peps/pep-0802.rst
----
📚 Documentation preview 📚: https://pep-previews--4534.org.readthedocs.build/
> PEP 802: Improve ``repr()`` & ``str()`` example

- peps/pep-0803.rst
----
📚 Documentation preview 📚: https://pep-previews--4578.org.readthedocs.build/
> PEP 803: Add Discussions-To

- peps/pep-0806.rst
cf https://github.com/python/peps/pull/4609#pullrequestreview-3270504857
----
📚 Documentation preview 📚: https://pep-previews--4611.org.readthedocs.build/
> PEP 806: Discussions-To link

- peps/pep-0694.rst
----
📚 Documentation preview 📚: https://pep-previews--4612.org.readthedocs.build/
> PEP 694: Update Post-History

- peps/pep-0694.rst
----
📚 Documentation preview 📚: https://pep-previews--4613.org.readthedocs.build/
> PEP 694: Point Discussions-To link to the Round 2 thread

- peps/pep-0788.rst
----
📚 Documentation preview 📚: https://pep-previews--4624.org.readthedocs.build/
> PEP 788: Add the new discussion link

- peps/pep-0810.rst
cc @pablogsal @Yhg1s 
These are some further editorial changes I'd suggest to clarify some points that currently require jumping around the text a bit.
A
----
📚 Documentation preview 📚: https://pep-previews--4625.org.readthedocs.build/pep-0810/
> PEP 810: Editorial follow-ups

- peps/pep-0810.rst
----
📚 Documentation preview 📚: https://pep-previews--4646.org.readthedocs.build/
> PEP 810: Add link to demo
