- pep-0522.txt
The core proposal (raising BlockingIOError) remains the same,
but the rationale and background sections now go into much more
depth for folks that want it.
The PEP now also explicitly covers the related changes to interpreter
and random module initialization, as well as providing references
to most of the related bugs.python.org messages.
> PEP 522: Rewrite accounting for Nathaniel's feedback

- .travis.yml
Prompted by https://github.com/python/peps/issues/5 (Set up Travis to build the peps) and https://github.com/python/peps/pull/16#issuecomment-226974669 : 
> (in this case we need to pull the branch locally and build the HTML version of the file) 
I was wondering if I could setup Travis to auto build all my Pull requests, and push them on my  gh-pages without committing my (encrypted) ssh key to this repo. And make that (relatively) simple for anyone to have the same functionality.
So this is my attempt at doing it. 
Once something similar is into the main repo, then any user "just" have to 
- set-up a secret `DEPLOY_KEY` env variable  on **Travis** 
- upload a corresponding public key as a **Deploy Key** on  **GitHub**
- activate `Travis`.
That's it.
Now every branch they push get deploy …
> Build with Travis, including users PRs.

- pep-0042.txt
git diff seem to get confused again, `--word-diff --ignore-all-space` is again useful but will remove most of the nesting conveying content. 
I did a manual check of the rendered version, but may have missed  somethings.
> Convert pep-0042 to Rst

- pep-0020.txt
I was torn between converting the Zen of Python into a list, or monospaced. It looks better monospaced.
> Convert pep 20 to Rst

- Makefile
- genpepindex.py
- pep-0012.txt
- pep2html.py
Not completely sure how that would interact with deploying pep on pythondotorg and other services.
> Handle pep files with `.rst` extensions.

- pep-0492.txt
> Fix typo in PEP 492

- pep-0201.txt
Note that link to Greg's link at the end is wrong:
> Greg Wilson's questionaire on proposed syntax to some CS grad students
http://www.python.org/pipermail/python-dev/2000-July/013139.html
It does not exists. While the archive **do** go to this date.
I believe that woudl be
https://mail.python.org/pipermail/python-dev/2000-July/006427.html
[Python-Dev] multi-loop quiz results
Thu, 13 Jul 2000 15:17:41 -0400 (EDT)
> I gave 20+ grad students in computer engineering and computer
> science...
> Convert pep 201 to rst.

- pep-0503.txt
This was suggested by @dstufft in pypa/pip#3847
> Add data-requires-python attribute to file links (PEP 503)

- pep-0484.txt
Fixes https://github.com/python/typing/issues/249 
@gvanrossum please review
> [WIP] Add scoping rules for type variables to PEP 484

- pep-0345.txt
---
In pep 345; I could have changed it into [a witch](https://www.youtube.com/watch?v=zrzMhU_4m-g) but I think it was not the intent.
> 'Fix typo: wich -> which'

- pep-0345.txt
Pep 386 - "Changing the version comparison module in Distutils" has been
replaced by Pep 440 - "Version Identification and Dependency
Specification"
Pep 345 still refer to pep 386, I suppose it is meant to reference pep
440 now.
--- 
The only "gotcha" is that pep 345 says that `Requires-Python = 3` is valid: 
> Requires-Python: 3 : Any Python 3 version, no matter wich one, excluding post or pre-releases.
That it must comply to the version specifiers:
> Version numbers must be in the format specified in Version Specifiers .
Which should match pep 386, now superseded by 440, in which `3` alone is not valid. 
So peps are contradicting themselves.
> Update pep 345 to reference pep 440 that supersede pep 386.

- pep-3107.txt
- pep-3110.txt
Changes based on discussion in rejected pull request #86. URLs to svn branches changed to revision-only. Text acknowledges the branch was originally named "p3yk" before being renamed to "py3k", to prevent future suggestions to correct it.
> correct "p3yk" typos  - redux

- pep-0103.txt
SSH connection sharing is a way to speedup a lot of short ssh sessions like git over ssh.
> SSH connection sharing 

- pep-0523.txt
I think this was a misunderstanding on someone's part. It's fairly new.
> Google's python frame change isn't years old

- pep-0517.txt
PEP 518 gave a detailed rationale for using a TOML config file; I'm pretty sure that's meant to be instead of, not in addition to, the JSON file proposed in this and PEP 516.
Ping @njsmith @rbtcollins
> Update PEP 517 to use pyproject.toml from PEP 518

- pep-0484.txt
Fixes https://github.com/python/typing/issues/284
@gvanrossum Please take a look.
> PEP 484: Clarify meaning of bare Tuple, etc.

- pep-0483.txt
- pep-0484.txt
@gvanrossum Please take a look. In this PR:
* More precise description of ``Any`` following recent discussion on ``Union[Any, X]``
* Updated properties of ``Union`` following same discussion
* Added an exception that unparameterized generics still could be used with instance and class checks (basically as a drop-in replacement for ``collections.abc``)
> Updates for PEPs 484 and 483

- pep-0001.txt
We can't immediately change the default when there's no `Content-Type` but we should deprecate it and strongly prefer reStructuredText.  There's also #4 to consider.
> Strongly prefer reStructuredText.

- pep-0484.txt
Fixes https://github.com/python/typing/issues/303
@gvanrossum Please take a look. I made a PR to allow this in mypy https://github.com/python/mypy/pull/2302 . Here I just propose to soften the restriction, i.e., avoid "must".
As a motivation, in Python one always can substitute expressions, so that if ``IntNode = Node[int]; IntNode()`` works, then it is reasonable to also allow ``Node[int]``, but say that the first way is preferred.
> Soften restriction for runtime generics in PEP 484

- pep-0505.txt
While reading through PEP-0505 I noticed that the quotation which is explaining the None-aware expression in English was closing the quote using two double quotes.
> Fix quotation in PEP-0505

- README.rst
README.rst doesn't even suggest a preference for .rst over text/plain.  Reworded, to better match the change in PEP1.
> README.rst should indicate a preference for .rst

- pep-0505.txt
- Replace emoji with C# spelling for operators.
- Remove some unnecessary alternative spellings.
- Add proper python code blocks.
- Other miscellany.
> Clean up PEP-505.

- pep-0484.txt
Fixes https://github.com/python/typing/issues/237
@gvanrossum @ddfisher Please take a look.
> Clarify per-argument type comments in PEP 484

- pep-0484.txt
Fixes https://github.com/python/typing/issues/271 and https://github.com/python/mypy/issues/1212
@JukkaL @gvanrossum 
Please review.
@JukkaL The third example works in mypy (with appropriate function bodies), Guido wants to double check that mypy could be patched so that first two examples also work.
> PEP 484: Allow annotating first argument of instance and class methods

- pep-0532.txt
This is the successor to PEP 531 that defines a single new operator (`else`), as well as changes to the definition of comparison chaining that would allow the related protocol to also be used to implement element-wise comparison of NumPy array elements.
The earlier iterations of the PEP are included in the PR rather than being squashed out of existence for historical interest - they include additional evidence as to why I decided that approach was a bad idea, and keeping that history in the main PEPs repo seems like a better idea than referring back to the branch in my fork.
> PEP 532: Defining "else" as a protocol based circuit breaking operator

- pep-0101.txt
- pep-3156.txt
@gvanrossum @1st1 the work is still in progress, sorry.
But I need your advice.
Should the PEP reflect the following:
- child watchers in loop policy
- strong list of _context keys_ supported by `loop.call_exception_handler(context)`
- strong list of _names_ supported by `transport.get_extra_info()`
- Task's methods like `get_stack()` and `print_stack()`
I would appreciate the careful review of existing changes as well.
P.S.
@bdarnell had asked me to let him involved into the PEP update.
Hi've asked to mention @glyph also.
> WIP for asyncio PEP update (not finished yet)

- pep-0484.txt
Fixes https://github.com/python/typing/issues/210
@gvanrossum @ddfisher This behaviour with ``--fast-parser`` is in mypy since mid-May. It looks like nobody is complaining. Maybe it's time to add this to the PEP?
> PEP 484: Add a note that misplaced type comments are errors for typecheckers

- pep-0534.rst
This is a draft PEP entitled "Distributing a Subset of the Standard Library" that aims to standardize and improve how Python handles omissions from its standard library. This is relevant both to Python itself as well as to Linux and other distributions that are packaging it, as they already separate out parts of the standard library into optionally installable packages.
Thread on the python-ideas mailing list:
https://mail.python.org/pipermail/python-ideas/2016-November/043805.html
> PEP 534: Distributing a Subset of the Standard Library

- pep-0303.txt
Mostly converted via a script but there were manual adjustments :)
Let me know what you think about this.
> Restify PEP 303

- pep-3145.txt
I added the link to bug tracker issue 18823 (mentioned in PEP Withdrawal section) into the references section.
The rest was converted via a script.
> Restify PEP 3145

- pep-0517.txt
This is the other option for `--user` editable installs: don't try to standardise a mechanism. This could always be added back in a later PEP.
Alternative to gh-140
> 517: Remove install_editable hook (Option 1c)

- pep-0517.txt
The key is in the build-system table, so making this a dash would improve consistency. On English keyboards, it also avoids needing to press shift. There seemed to be a consensus on distutils-sig in favour of this change.
> 517: Change build_backend to build-backend

- pep-0206.txt
Straightforward conversion.
I used my (imperfect) script at https://github.com/Mariatta/restify_me for this. 
Feedback are welcome :)
> Restify PEP 206

- pep-0484.txt
This resolves https://github.com/python/typing/issues/336
> Document `__foo` syntax for positional-only args

- pep-0524.txt
- pep-0529.txt
Reported at https://github.com/python/pythondotorg/issues/1038
> Fix typos in PEP 524 and PEP 529

- pep-0526.txt
Fixes https://github.com/python/typing/issues/339
Following the discussion on python/typing issue (and taking into account that ``dict`` in 3.6 is ordered beeing an implementation detail) it is proposed to make ``__annotations__`` ordered.
@gvanrossum Please, take a look.
> PEP 526: Variable __annotations__ should be ordered

- pep-0536.txt
Hi, I announced some time ago that I’d pick this up, now I’ve finally managed to write it!
I hope the general structure, phrasing, formatting and so on are OK, this is my first PEP.
[rendered](http://bl.ocks.org/flying-sheep/raw/9202bb95b013b3f5c8a5eaefe06ae1ea/)
> PEP 536: Final Grammar for Literal String Interpolation

- pep-0487.txt
Found a typo in PEP 487. Not sure if this is the proper way to go about reporting/fixing it, but here it is regardless.
> PEP 487: fixed typo

- pep-3107.txt
Fixes https://github.com/python/peps/issues/168 for real
> Fix broken url in PEP 3107

- pep-0221.txt
- pep-0229.txt
- pep-0240.txt
- pep-0277.txt
- pep-0286.txt
- pep-0295.txt
- pep-0297.txt
- pep-0306.txt
- pep-0341.txt
- pep-0666.txt
PEP 221
PEP 229
PEP 240
PEP 277
PEP 286
PEP 295
PEP 297
PEP 306
PEP 341
PEP 666
🎉 
https://github.com/python/peps/issues/4
> reSTify 10 more PEPs 

- pep-0001.txt
Minor and inconsequential, but just one of those itches that I had to scratch.
Changes "reference" to "references".
> Incredibly minor typo fix in pep-0001

- pep-0212.txt
- pep-0216.txt
- pep-0219.txt
- pep-0228.txt
- pep-0235.txt
- pep-0269.txt
- pep-0288.txt
- pep-0312.txt
- pep-0315.txt
- pep-3102.txt
PEP 212
PEP 216
PEP 219
PEP 228
PEP 235
PEP 269
PEP 288
PEP 312
PEP 315
PEP 3102
https://github.com/python/peps/issues/4
> Convert 10 PEPs to reSt

- pep-0211.txt
- pep-0218.txt
- pep-0223.txt
- pep-0243.txt
- pep-0244.txt
- pep-0265.txt
- pep-0278.txt
- pep-0279.txt
- pep-0337.txt
- pep-0356.txt
- pep-0379.txt
- pep-3144.txt
PEP 211
PEP 218
PEP 223
- fix couple typos: 'discussed' and 'incompatibility'
- add reference to a python-dev discussion titled 'Go \x yourself'
PEP 243
PEP 244
PEP 265
PEP 278
PEP 279
PEP 337
PEP 356
PEP 379
PEP 3144
Ongoing work for https://github.com/python/peps/issues/4
> Convert 12 PEPs

- pep-0484.txt
Fixes https://github.com/python/typing/issues/363
@gvanrossum Please, take a look.
> PEP 484: add an example of iterable unpacking with type comments

- pep-3110.txt
Hi, I got through the PEP-3110 and I found out that both links to Guido's repository are returning 404.
> Replace reference links with valid URLs.

- pep-0484.txt
@gvanrossum Could you please take a look at this? (when you have time, this is not urgent)
Fixes https://github.com/python/typing/issues/367
> PEP 484: Clarify type erasure and instantiation of concrete collections

- pep-0208.txt
- pep-0272.txt
- pep-0273.txt
- pep-0292.txt
- pep-0320.txt
- pep-0330.txt
- pep-0331.txt
- pep-0357.txt
- pep-3130.txt
- pep-3140.txt
PEP 208
PEP 272:
- Fix example traceback code, 
from ``File "<stdin>", line 1, in ?``
into ``File "<stdin>", line 1, in <module>``
PEP 273:
- replace urls from http://python.org/sf/*
into https://bugs.python.org/issue*
PEP 292
PEP320:
- move urls into references section
- replace urls from http://python.org/sf/*
into https://bugs.python.org/issue*
PEP 330
PEP 331:
- fix PSF contributor agreement url
- replace urls from http://python.org/sf/*
into https://bugs.python.org/issue*
PEP 357
PEP 3130
PEP 3140
Continuing work for https://github.com/python/peps/issues/4
> Convert 10 text PEPs to reST format

- pep-0263.txt
- pep-0272.txt
PEP 263: remove extra colon and unnecessary backticks
PEP 272: remove extra colon and change back traceback code
@berkerpeksag I addressed the comments from the previous PRs.
Thanks.
> Fixes to PEP 263 and PEP 272

- pep-0468.txt
Looks like a typo to me. But not sure.
> Ordered **kwargs starts in 3.6 instead of 3.5.

- pep-0261.txt
- pep-0267.txt
- pep-0325.txt
- pep-0358.txt
- pep-0361.txt
Continuation for https://github.com/python/peps/issues/4
> Convert PEPs 261, 267, 325, 358, 361

- pep-0512.txt
Removed trailing slash from pythocat link, since it wouldn't resolve with it. (Also testing how easy it is to make a pull request prior to forking a repo.)
I can confirm it was quite easy to contribute! Nice job on the migration to Github. :)
> fixed pythocat link

- pep-0543.rst
This is a formal request for a PEP number for a draft PEP I have been shopping around the Python community for a couple of months now: a unified TLS API for Python. This draft PEP has been discussed multiple times on the Python Security-SIG mailing list, and once on python-ideas. At this point, I'd like to get a proper PEP number before I submit the PEP for consideration to python-dev (per the procedure in PEP 1).
Once the PEP number is assigned I'll send the PEP to python-dev for discussion. It's quite possible that this PEP will end up being revised in the face of python-dev feedback.
> Proposal: A Unified TLS API for Python

- pep-3333.txt
The current algorithm supplied in the URL Reconstruction section utilises urllib.quote, however this was changed in Python 3, so that it is now urllib.parse.quote. As this document was rewritten to support Python 3, the algorithm should also support Python 3.
> Fix URL Reconstruction algorithm to support Python 3

- pep-0463.txt
Copied the notice from https://mail.python.org/pipermail/python-dev/2014-March/133118.html
I looked at the PEP recently and noticed that it still claims to be a draft. I had to search in my email archive to confirm that it has in fact been rejected.
> Mark PEP 463 as rejected

- pep-0538.txt
- updates reference implementation to use PYTHONCOERCECLOCALE
- removes hard dependency on PEP 540
- still notes PEP 540 covers case where no relevant C-with-UTF-8
locale is available
- clarifies that these settings are still recommended over the
legacy C locale settings for older Python 3 versions, even if
we don't recommend backporting the automatic coercion
> PEP 538: Update reference implementation

- pep-0103.txt
Withdraw PEP 103 as it's too generic and doesn't really deals with Python development.
> Withdraw PEP 103

- pep-0263.txt
Observed to be missing the backslashes on
https://www.python.org/dev/peps/pep-0263/#defining-the-encoding
> PEP 263: Fix escaping of "\"s in regex and strings

- pep-0007.txt
according to PEP 7, "braces are strongly preferred but may be omitted where C permits".
thus, IMHO, the examples in the PEP should have curly braces too.
> PEP 7: add curly braces to if block

- pep-0484.txt
As discussed in https://github.com/python/typing/issues/165, it is time to document the ``NoReturn`` type.
@gvanrossum Please take a look when you will have time.
> PEP 484: Add NoReturn type

- pep-0010.txt
- pep-0213.txt
- pep-0214.txt
- pep-0224.txt
- pep-0308.txt
- pep-0310.txt
- pep-0321.txt
- pep-0339.txt
- pep-0348.txt
- pep-0358.txt
- pep-0379.txt
- pep-0447.txt
- pep-0495.txt
- pep-0497.txt
- pep-0500.txt
- pep-0518.txt
- pep-3108.txt
- pep-3136.txt
- pep-3140.txt
- pep-3141.txt
In some files mixed tabs and spaces were used in Python code.
Some files looked correctly only with 4-space tabs.
> Replace tabs with spaces and fix identation errors.

- pep-0484.txt
This question appeared recently on mypy's gitter channel. Here I clarify scoping rules for type variables in inner classes and add an example.
It was discussed, that these rules are maybe too restrictive. But this is necessary if we want to keep
```python
class Bad(Iterable[T]):
...
```
and
```python
class Bad(Iterable[T], Generic[T]):
...
```
equivalent. If people will ask, then we could later relax the rule and allow binding of inner class type variables to outer class type variables (however, I think this is highly unlikely).
@gvanrossum Please take a look.
> PEP 484: Clarify scoping of type variables

- pep-0508.txt
This PR has 2 changes. They come from a discussion on pypa/packaging/issues/86.
This first is not a mistake per-say. I changed the example to compare
`python_version < 2.7` instead of `2.7.10`, as it'll avoid some surprise, if comparing while having Python 2.7.13 installed, and then expection this to be False, but then evaluates as True because the user forgot that `python_version` is only the first two number of the python version, which is roughly equivalent to `2.7.0` in PEP-440 version comparison.
The second one is a small mistake. The PEP stated:
> PEP-426 markers [...] will handle version comparisons with ``python_version`` "2.7.10" differently.
which is wrong, because `python_version` will never be "2.7.10", because it's only the first two version numbers, "2.7". This is why I …
> PEP-508: Fix imprecisions about `python_version`

- pep-0001.txt
- pep-0012.txt
Update PEP 1 and PEP 12 with instruction to use the number 9999.
Closes https://github.com/python/peps/issues/223
> Use number 9999 in a draft PEP

- pep-0544.txt
This implements two sets of comments by Guido, comments from python-dev, and adds links to working implementation.
Attn: @JukkaL @ambv @gvanrossum
> Updates for PEP 544: Protocols

- pep-0544.txt
Fixes a few typos in an example and a confusing phrase.
> fix typos in PEP 544

- pep-0484.txt
This was discussed in https://github.com/python/typeshed/issues/270#issuecomment-296411726. Both mypy and pytype behave as described already. We should document this behavior in the PEP to make sure people are aware of it and promote uniformity.
Mypy also implicitly promotes bytearray to bytes in both Python 2 and 3. Not sure if that's worth codifying in the PEP too.
@vlasovskikh Is this also OK for PyCharm?
> PEP 484: Add implicit promotions for Python 2.7

- pep-0544.txt
This PR adds adapters to postponed/rejected ideas, drops ``Set``s from proposed protocols list (they are too large), and adds one clarifying comment. This PR also adds a link to the runtime implementation.
Attn: @JukkaL @ambv @gvanrossum
> Few more updates to PEP 544: Protocols

- pep-0539.txt
Long overdue updates to the PEP-539 draft, summarizing discussion in the original [python-ideas thread](https://mail.python.org/pipermail/python-ideas/2016-December/043983.html) and updates to the [implementation](http://bugs.python.org/issue25658) since the last version of the draft.
@ncoghlan @ma8ma
> Updates to PEP-539 draft

- pep-0544.txt
The interface should be named `LabeledItem` and not `LabeledValue`.
> Correct bad naming in TypeScript example

- pep-0484.txt
Clarification based on python/mypy#2878
> Update generic class attribute and type variable usage

- pep-0545.txt
I discussed about the translation licensing issue with Van L and he directed me toward a nice solution which is: The PSF should write a "Documentation Contribution Agreement" and we'll have to ensure by one way or another that each contributors, from each contribution source whatever they are, agree with it.
This PR also contain previously unmerged feedback I got on python-dev (typos and so on).
> PEP 545: Update licensing after discussion with Van. L from the PSF

- pep-0011.txt
`..` was missing and the directives weren't caught.
> Fix omission with PEP-11

- pep-0544.txt
This adds two items to rejected ideas that appeared in recent discussions on mypy tracker, and updates notes on runtime implementation.
It looks like all questions/uncertainties are now addressed, so that the PEP is ready for a next round on python-dev.
Attn: @JukkaL @ambv @gvanrossum
> Updates to PEP 544: Protocols

- pep-0203.txt
- pep-0238.txt
> reSTify PEP203 and PEP238

- pep-0011.txt
Part of the PEP 538 implementation is to add a new
"Legacy C Locale" section to PEP 11 that explicitly
limits our support for running Python 3.7+ in the
ASCII based legacy C locale.
(Note: if PEP 540 is also accepted, this section will
be amended accordingly)
> Update PEP 11 for PEP 538 acceptance

- pep-0517.txt
From a discussion on the mailing list.
This is not yet completely agreed upon, but it's my best take on the solution.
> PEP 517: Specify UTF-8 for captured output

- pep-0007.txt
Closes #279 
See https://mail.python.org/pipermail/python-dev/2017-May/148092.html
> Braces are required everywhere

- pep-0237.txt
When converting this PEP to reST, I ran into an issue with the enumerated list in the Transitions section.  Originally, the phases were numbered A, B, and C and then, further down, phase B was split into B0 and B1.  When I rendered the HTML, the A, B, C were converted automatically to 1, 2, 3 and the B0 and B1 would not display correctly at all.  Since these numbers are referenced elsewhere in the document, I changed the numbering to use 1, 2, and 3 and I changed the subsets of phase 2 to be 2a and 2b.
I researched for a workaround, but was unable to find anything other than the hack I've done here of using a non-enumerated list for 2a and 2b.
> reSTify PEP237

- pep-0236.txt
- pep-0247.txt
- pep-0342.txt
- pep-0344.txt
- pep-3134.txt
> reSTify 5 PEPs

- pep-0517.txt
Alternative to #275 
@dstufft @pfmoore @leorochael
> PEP 517: Add prepare_build_files hook

- pep-0008.txt
PEP 3131 (Unicode identifiers) includes a policy section
covering their use within the standard library.
This adds an explicit cross-reference to that section from
the prescriptive naming conventions section of PEP 8
> Cross-reference PEP 3131 from PEP 8

- pep-0517.txt
Ping @ncoghlan - I think this implements everything you suggested on  #277 except for the sdist directory question (does the backend create a `foo-1.0` directory, or just dump the files directly into `build_directory`?). I have no strong feeling on that question, but you didn't sound certain, so I thought I'd leave it for further discussion before making a change.
> PEP 517: Misc changes from discussion

- pep-0007.txt
> Braces example for multiline conditionals

- pep-0517.txt
Plus a note about argument passing which occurred to me.
Things I wasn't sure about from the discussion:
- Do we want to rename the `build_wheel` hook now that it makes an unpacked wheel, e.g. `export_wheel_contents` to match `export_sdist_contents`?
- I have assumed that the wheel hook puts its contents in the directory it's passed, rather than creating a subfolder. This is in keeping with the structure of wheels, which do not have a single top-level directory (unlike sdists), but it wouldn't fit with a future hypothetical extension to build multiple wheels at once; we would need a separate hook for that.
> PEP 517: Latest recommended changes

- pep-0517.txt
An ambiguity in the wording made it look like `metadata_directory` for `build_wheel` would be the same directory as was passed in to the `prepare_wheel_metadata` hook. It makes more sense, I think, for it to be the `.dist-info` directory returned from `prepare_wheel_metadata`.
> PEP 517: Clear up ambiguity about metadata_directory

- pep-3150.txt
There was a spurious space at the beginning of the line, that transformed the paragraph into a definition list item.
> Remove spurious whitespace

- pep-0426.txt
A couple of links in PEP 426 were broken due to malformed markup.  Also, the PEP 301 reference at the bottom of the file was unused.
The "thematically appropriate" YouTube link is still dead, but I don't know what to do about that one.
> Fix broken links in PEP 426

- pep-0517.txt
- `get_build_wheel_requires` specifies any requirements for building a wheel.
- `get_build_sdist_requires` works the same way to specify requirements for building an sdist.
- `prepare_build_wheel_files` is the new name for `prepare_build_files`, for clarity.
> PEP 517: Add hook for sdist build deps

- pep-0496.txt
PEP 496 was never Accepted or Active, so the correct status
is "Rejected in favour of PEP 508" rather than "Superseded
by PEP 508".
> Use correct status for PEP 496

- pep-0539.txt
Updated to reflect recent changes to the implementation in python/cpython#1362; in particular changes needed to support `Py_LIMITED_API`.
> Updates to PEP 539 draft

- pep-0008.txt
- pep-0225.txt
- pep-0308.txt
- pep-0436.txt
- pep-0498.txt
fixed typos regarding parenthesis/parentheses (singular vs plural)
> fix minor typos

- pep-0545.txt
The bot will not be required as the agreement is just to be displayed,
there's no actual signing part.
It's done like this to enable contributions from many different
sources: we'll just have to clearly display this agreement on every
contribution sources.
> PEP 545: Update contribution agreement according to the PSF recommendations

- pep-0517.txt
This brings the hooks in line with discussion on the mailing list:
- Remove the hook to copy input files to a build directory before building a wheel.
- Add the `build_directory=None` parameter to the `build_wheel` hook.
- Rename the optional hooks to make it clearer what they do.
> PEP 517: Update hooks in line with discussion

- pep-0517.txt
- update hook names and signatures
- clearly separate sdist building & wheel building
- add support for out-of-tree wheel builds
> PEP 517: update backend example

- pep-0484.txt
See discussion in https://github.com/python/typeshed/pull/1484#discussion_r127114355.
cc @ilevkivskyi @gvanrossum
> PEP 484: Clarify that submodules in a package are exported

- pep-0484.txt
See https://github.com/python/typing/issues/418#issuecomment-313753006.
Let's leave it up to type-checkers whether they want `unicode`, in Python 2 code, to mean "only unicode" or "str or unicode".
> PEP 484: Remove statement about unicode, in the python2.7 section.

- pep-0517.txt
- replace with prepare_metadata_for_build_wheel where appropriate
- update the API evolution example to be based on build_sdist
rather than prepare_wheel_metadata
- also clarified the frontend example code covering one way to
handle prepare_metadata_for_build_wheel being optional
> PEP 517: remove prepare_wheel_metadata references

- pep-0517.txt
- use plain strings rather than pathlib.Path
- drop config_settings as irrelevant
- return relevant absolute paths from the example
helper functions
> PEP 517: Fix metadata preparation example

- pep-0517.txt
We have a long section comparing the two PEPs which is now mostly of historical interest, so I've moved it to an appendix.
I'd still be in favour of making it shorter as well, because we keep needing to update its examples as the specification evolves (and I keep forgetting to do so). But I haven't done that yet.
cc @ncoghlan @njsmith
> 517: Move comparison to PEP 516 into an appendix

- pep-0539.txt
Update [PEP 539][pep539] TSS API draft since [PR 1362][pr1362] was updated
- update specification to omit `PyThread_tss_delete_value` and `PyThread_ReInitTSS` ([bpo-25658#msg298342][1])
- update outdated explanation since CPython's own TLS implementation was removed ([bpo-30832][2])
- add `Support Platform Changes` to would update PEP 11
- fix identifier, terminology and typo
- update explanations for `PyThread_tss_alloc` function and `Implementation` topic
cc @ncoghlan @embray 
[pep539]: https://www.python.org/dev/peps/pep-0539/
[pr1362]: https://github.com/python/cpython/pull/1362
[1]: https://bugs.python.org/issue25658#msg298342
[2]: https://bugs.python.org/issue30832
> PEP 539: update draft to omit two functions

- pep-0496.txt
The footnote/reference links in PEP 496 weren't actually hyperlinks.  This fixes that.
> Fix footnote/reference links in PEP 496

- pep-0491.txt
Two lines of RFC822-style headers were being formatted as a single-line blockquote instead of a preformatted code block.  In addition, the prose immediately before them called them "files" instead of "fields."  This PR fixes that.
> Fix typos in PEP 491

- pep-0517.txt
We seem to be reaching the conclusion that this is not needed, and removing it allows the spec to be simpler.
> PEP 517: Remove build_directory parameter

- pep-0513.txt
See bug pypa/auditwheel#80 for details.
> Added libresolv to whitelisted manylinux1 libraries

- pep-0539.txt
~~Closed this PR because had stopped long.~~
**Edit (2017-08-28): reopen this PR**
Update [PEP 539][pep539] draft to clean up for posting second draft to python-dev.
Highlight of changes
- add specification for new features
- add explanation what the existing API's behavior became ([bpo-30832][1])
- add specification based on reference implementation
- add specification which the existing API design would be carried over into new API ([python-ideas][2])
- add table for comparison of API specification
- add example for dynamic allocation
- add rationale why not exposing ``NATIVE_TSS_KEY_T`` as part of the limited API ([bpo-comment][3])
cc @ncoghlan @embray
[pep539]: https://www.python.org/dev/peps/pep-0539/
[1]: https://bugs.python.org/issue30832
[2]: …
> PEP 539: update draft

- pep-0551.rst
Main update is renaming "log hooks" to "audit hooks" as suggested by Nick.
Also adjusted some suggested hooks based on the implementation, and clarified some recommendations.
> PEP 551 updates

- pep-0517.txt
I think we have now agreed on:
* srcdir not on sys.path
* A backend-provided exception class to signal that `build_sdist` has failed for an understood reason. I have called this `UnsupportedOperation`, which I think someone suggested, but I'm half expecting another bikeshed about the name. ;-)
cc @ncoghlan @njsmith @pfmoore @dholth @dstufft
> PEP 517: latest round of updates

- pep-0550.rst
Changes:
* Coroutines have no logical context by default (a revert to the V3
semantics).
* All APIs have been placed to the ``contextvars`` module, and
the factory functions were changed to class constructors
(``ContextVar``, ``ExecutionContext``, and ``LogicalContext``).
* ContextVar.lookup() got renamed back to ContextVar.get() and gained
the `topmost` and `default` keyword arguments;
* Added ContextVar.delete().
* Fixed ContextVar.get() cache bug (thanks Nathaniel!).
* Added a few more design considerations points.
* Various minor edits and enchancements.
> PEP-0550 V5

- pep-0484.txt
The previous version was not entirely clear.
cc @ilevkivskyi
> Clarify Python versioning in stub file search path

- pep-0562.rst
This adds an example of module ``__getattr__`` usage that implements lazy imports to Rationale of PEP 562.
> Update PEP 562 with an example

- pep-0285.txt
> reSTify PEP 285

- pep-0212.txt
- author unreachable
- enumerate() covers the use case
Closes https://github.com/python/peps/issues/207
> Mark PEP 212 as Rejected

- pep-0561.rst
I have made some more edits to my PEP. In summary:
* Move to adding a new metadata specifier so that more tools can participate
* Clarify version matching between third party stubs and runtime packages.
* various other fixes for clarity, readability, and removal of repetition
@ncoghlan I would appreciate a review of this new version if you have time. Thanks!
> V3 revision of PEP 561: Distributing Type Information

- pep-0539.txt
Wording-only change, replacing the word "default value" with "initializer" making more sense.
Related PR: https://github.com/python/cpython/pull/4096
> PEP 539: Fix wording about Py_tss_NEEDS_INIT

- pep-0308.txt
> reSTify PEP 308

- pep-0561.rst
Add CPython implementation, sample package to be installed, and package
to check installed packages.
> PEP 561: Add implementation links and changelog

- pep-0001.txt
Refs: https://mail.python.org/pipermail/python-dev/2017-October/149990.html
> Post-History should include dates of postings to python-ideas

- pep-0485.txt
I somehow had "smaller" for both the weak and strong cases -- not sure how I let that slip through originally
> Fixed a (critical) typo

- pep-0008.txt
- pep-0564.rst
Consistency format 'multi-'.
Fixed capitalization of 'latin', 'boolean', 'unicode' to 'Latin', 'Boolean', 'Unicode'.
>  Update pep-0008.txt

- pep-0407.txt
This is the wrong Post-History link for this PEP. I've updated it to what I think is the [correct link](https://mail.python.org/pipermail/python-dev/2012-January/115573.html). The [existing link](https://mail.python.org/pipermail/python-dev/2012-January/115838.html) refers to a different proposal/thread entirely.
> Fix Post-History link in PEP 407

- pep-3103.txt
Fix spelling: smorgasboard -> smorgasbord.
Clarification: the word "smorgasboard" does not exist.  Merriam-Webster lists "smorgasbord", as does the Oxford English Dictionary.  Google Ngram shows the spelling "smorgasbord" is used about 200× more than the spelling "smorgasboard".
> Fix spelling: smorgasboard -> smorgasbord.

- pep-0560.rst
@ilevkivskyi This started as an attempt to fix a few grammatical nits; it expanded in more punctuation fixes, more grammar fixes, removal of `:` from section headings, addition of two section headings, and a clarification that new dunder names are allowed by the language reference.
> Small edits for PEP 560

- pep-0561.rst
Note that the implementations are not quite updated yet, but they will be by the end of the day.
> Update PEP 561 to use package metadata in place of distribution metadata

- pep-0561.rst
@ethanhs Here are some small tweaks to your PEP 561, mostly to clarify a few things that confused me on initial reading. (E.g. when I saw a key `'pkg'` in some example code I wasn't sure if it was a fixed key or simply an example name -- I changed this to `'foopkg'` everywhere.
> Proposed small tweaks to the text of PEP 561

- pep-0562.rst
I also have added an example about pickleability as proposed by Serhiy. I don't think we need to provide
some special helpers, unless we all converge quickly on what exactly is needed (and in which stdlib module it should appear).
> PEP 562: Updates following recent discussions

- pep-0560.rst
There were no comments concerning the API, most changes here are just clarifications and wording improvements suggested on python-dev. One minor additional change if to clarify _when_ ``__orig_bases__`` is stored: before the metaclass is called, not after. I don't use this (since we will not have metaclasses in ``typing``), but it is a bit faster and gives potentially more flexibility.
> PEP 560: Wording improvements after discussion on python-dev

- pep-0562.rst
I didn't add any specification for helper functions. Also I think we don't need module ``__set_name__`` (it was brought by Serhiy) since it is still very new and much less known compared to ``__getattr__``.
> Update PEP 562 following suggestions on python-dev

- pep-0562.rst
Here is a possible clarification about how module ``__getattr__`` works. Are there any other action items in this PEP? It looks like all the recent questions were addressed.
> PEP 562: Minor clarification based on python-dev discussion

- pep-0257.txt
See https://github.com/python/peps/issues/484 for details.
Closes https://github.com/python/peps/issues/484
> Remove "XXX Mention docstrings of 2.2 properties."

- pep-0557.rst
I noticed the formatting looks strange on the rendered PEP:
I wonder if it was meant as
```
With ``__InitVar__``s ...
```
instead of 
```
With ``__InitVar__``'s
```
> PEP 557, fix markup.

- pep-0544.txt
"form" appears to be a typo for "from", but it's possible I'm confused.
> typo fix for pep 544

- pep-0484.txt
Promise an updated schedule for non-provisional status and the end of
non-typing annotations in PEP 563, and link there for the `__future__`
statement as well.
**NOTE:** This requires an update to PEP 563 as well, since it currently refers to the end of PEP 484's provisional status. I want to [keep it provisional](https://github.com/python/typing/issues/495#issuecomment-342644111) for at least one more release cycle, at least for some restricted value of provisional: the basic spelling of types won't change incompatibly, and the typing.py module won't be withdrawn, but we need to be able to add new features to typing.py in bugfix releases, and we need the freedom to change *undocumented* parts of the implementation as well. The goal is that by the time 3.8 comes around we can import …
> Add links to PEP 563.

- pep-0508.txt
Fix 1 bug. Enhance handling of trailing whitespace for URLs. Correct spelling.
Add tests.
> Pep 508 parser fixes

- pep-0566.txt
This adds a packaging metadata 1.3 PEP (as discussed in #388).
The goal here is not to provide a full specification for all fields, but to:
* Motivate and describe the addition of the new fields or changes to existing fields;
* Point to the [Core Metadata Specifications](https://packaging.python.org/specifications/core-metadata/) reference document as the canonical source for the specification.
(CC: @ncoghlan)
> PEP 566: Metadata for Python Software Packages 1.3

- pep-0540.txt
- CentOS 7 is a better example of problems than Alpine Linux
(default locale is C/POSIX, C.UTF-8 isn't available for coercion)
- reword the annex discussing the design trade-offs between
PEP 538's locale coercion and PEP 540's introduction of a
UTF-8 specific mode
> PEP 540: Update based on PEP 538 experience

- pep-0554.rst
After updating the signature of Interpreter.run(), I forgot to update the examples accordingly.  This change fixes that.
> PEP 554: Fix the examples.

- pep-0567.rst
Per @gvanrossum request, this PR has some small edits that I hope are non-controversial (by which I mean that if anyone disagrees with any of them, I'll just back them out) - minor points of spelling and grammar. The rest of my comments and questions are hereunder.
@1st1
* Question: what initializes the value for a new context? Can it clone the value for the starting context? Should it? Or is it always fresh with defaults?
* Context.run(callable, *args) ==> no kwargs support?
* What happens if you set, set again, then reset from the first one's token? A peek at the implementation shows that it simply resets the value, so aside from having magic that allows it to represent "no value", the token buys nothing that you couldn't get by simply returning the old value - which is a valuable API …
> PEP 567 review and copyedits

- pep-0567.rst
* Add **kwargs to Context.run()
* Add a concurrent.futures example
* Better clarify the need for Token
* What's N in O(N)
* Context() creates an empty Context
* Mention Context.name in the Specification
> pep-567: Additions

- pep-0567.rst
Add C API section.  cc @gvanrossum @Rosuav
> pep-567: Add C API section.

- pep-0498.txt
See this thread on python-dev:
https://mail.python.org/pipermail/python-dev/2017-December/151282.html
NOTE: PEPs aren't really supposed to be documentation for end users, so maybe there's not point in this little clarification. And some clarification has been added to the main Python docs.
But why not? People do come here to learn about new features.
> Tiny bit more clarity about the format specifiers in PEP 498

- pep-0498.txt
It applies to the implementation, not to end users passing these in to
f-string -- the latter is fine (e.g. print(f"Locals are {locals()}")).
CC: @mariatta
> Clarify the prohibition on locals() and globals().

- pep-0568.rst
As discussed in
https://mail.python.org/pipermail/python-dev/2018-January/151605.html
it seems useful to write down what an extension of PEP 567 to full
"context stack" semantics would look like, even if we aren't planning
to consider it for 3.7. That's what this is.
> First draft of PEP 568

- pep-0566.txt
This is the text that I proposed on distutils-sig.
cc @ncoghlan @di @dholth .
> 566: Mention that version specifiers no longer need to be in parentheses

- pep-0567.rst
> pep-567: ContextVar.reset() raises a RuntimeErorr on already used tokens

- pep-0008.txt
There is a response in StackOverflow to the question: [What is the naming convention in Python for variable and function names?](https://stackoverflow.com/questions/159720/what-is-the-naming-convention-in-python-for-variable-and-function-names). It says see PEP 8 and makes the statement "Use the function naming rules: lowercase with words separated by underscores as necessary to improve readability."
That statement is found in other sources and confirmed by experienced Python programmers. But, PEP 8 does not yet support that statement.
> PEP 8 Explicitly State Variable Names convention? #535

- pep-0376.txt
use `/` for unix-like path separator and `\` for Windows path separator
> use correct path separator

- pep-0567.rst
The "Design Considerations" section had only one subsection which
was a discussion of a rejected idea.  Merging it into "Rejected Ideas"
simplifies the document structure.
Fix a bug in a code snippet in the "ContextVar.unset()" subsection.
cc @gvanrossum
> pep-567: Merge "Design Considerations" and "Rejected Ideas"

- pep-0008.txt
- pep-0484.txt
- pep-0526.txt
Fixes #543 
As discussed in https://github.com/python/typeshed/pull/1803 I update three PEPs: 8, 484, and 526
with the relevant discussion about the coding style for variable annotations and their preferred use in stub files.
> Add coding style recommendations for variable annotations

- pep-0567.rst
Changes:
* Rename `PyContext * PyContext_Copy()` to `PyContext * PyContext_CopyCurrent()`;
* Add a new `PyContext * PyContext_Copy(PyContext *)` function.
This brings parity between C & Python APIs. 
@gvanrossum: this is the last change I can currently think of.
> pep-567: Tweak C API

- pep-0001.txt
If R. David Murray's first initial is not escaped, it is interpreted as
the alphabetic ordinal in an enumerated list and rendered as
"18. David Murray".
> Fix rendering of editor's first initial

- pep-0561.rst
Also note that a py.typed file is not needed for stub only packages.
cc @gvanrossum I believe you wanted these changes based on last Friday's discussion?
> Change to -stubs over _stubs

- pep-0485.txt
> Fix IPython spelling in pep 485

- pep-0541.txt
It isn't appropriate for the PSF to ask a single community
volunteer to accept full responsibility for the PSF's
policy on PyPI name management.
Delegating the task to the Packaging Working Group is more
appropriate, since we're already responsible for handling
the PSF's budget in this area, and there's a lot of overlap
between budget management and risk management.
> PEP 541: Make the Packaging WG the approval authority

- pep2html.py
The PEP summary/email lines that aren't the first line in their group
have an extra leading space because the previous line is printed with a
trailing space. The special lines read from pep-0000.txt should be
printed with no extra ending to be consistent with what the python2
version did with a print statement that ends with a comma.
> Fix PEP summary/email line indent in pep-0000.html

- pep-0345.txt
- pep-0376.txt
- pep-0425.txt
- pep-0427.txt
- pep-0506.txt
- pep-0539.txt
- 376, 425, 427: reference implementations now live outside CPython
- 506: implemented and released in Python 3.6
- 539: implemented in Python 3.7
> Mark several PEPs as final

- README.rst
`.rst` file extension is now supported. I think new PEPs should be in `.rst`.
> Readme: Change pep-0999.txt to pep-0999.rst

- .gitignore
- pep-0484.txt
Fixed a small syntax error and imported the `logging.Logger` - it is needed in the code for indicate the type of variable `def __init__(..., logger: Logger) -> ...`
P.s. Ignore temporary files for the vim editor.
P.p.s. I'm already signed the CLA.
> PEP 484: Fix the example code

- pep-0467.txt
There was an **unexpected indentations error** at 111 line on pep-0467.txt, so the travis build was failed.
> Fix the unexpected indentations error on pep-0467.txt

- pep-0571.rst
This seemed to be the consensus on distutils-sig, although it wasn't unanimous.
I've added a paragraph explaining the name change, and clarifying that the year is only a rough guide for compatibility.
> 571: Update manylinux2 -> manylinux2010

- pep-0541.txt
- only mention psf-legal@... for IP concerns
- use post-migration link for PyPI
- drop Source Forge footnote entirely
> PEP 541: Update external references

- pep-0571.rst
cc @markrwilliams @ncoghlan 
This is meant to fix the omission Nick noted in this message:
https://mail.python.org/pipermail/distutils-sig/2018-February/031971.html
> 571: Describe fallback platform checking using glibc version

- pep-0540.txt
Most dictionaries list it as nonstandard or incorrect usage, and recommend that "regardless" be used instead
> Change irregardless to regardless

- pep-0561.rst
This update points to a real implementation in a type checker for PEP 561. I also modified the language to clarify that stub packages should take priority over any installed inline packages (so not just those in the same directory).
> PEP 561: Point to mypy implementation and clarify stub package priority.

- pep-0574.rst
Because the `BYTEARRAY` opcode needs to include the 64-bit length of the data (like `BINBYTES8` does already), I would find it more consistent to name that opcode `BYTEARRAY8` directly.
This is actually what @pitrou ended implementing in his draft branch for pickle protocol 5.
> PEP 574: rename BYTEARRAY to BYTEARRAY8

- pep-0001.txt
- some interoperability specifications (e.g. the package index
download API) will never have a standard library implementation
- auxiliary files can go in a subdirectory
- PEP issues should be reported against the GitHub repo rather than
bugs.python.org
> PEP 1: Update some out of date details

- pep-0394.txt
Please do not merge yet. I'll send this for discussion on python-dev, but I think a concrete pull request makes the review easier.
---
In Fedora, I found that PEP 394's strict recommendation that `python` points to `python2` is holding us back. I would like to officially relax this in several cases.
The problems are:
- For developers that are not following the language's development, the fact that `python` invokes `python2` sends a strong signal that 2 is somehow the preferred version, and it's OK to start new projects in it.
- Users <s>and sysadmins</s> that *do* want to “live in the future” are switching the symlink to `python3` themselves. We would like to give them a supported, documented way to do so -- and make surer they're aware of the caveats.
- The `python2` command is still not …
> PEP 394: Allow the `python` command to not be installed, and other minor edits

- pep-0545.txt
People get 404 when visiting the old url, if they haven't joined the
translation team.
> PEP 545: fix transifex url

- pep-0560.rst
It is quite unusual to update already accepted PEPs, but it turns out I forgot to add this section. The calling convention ``METH_O|METH_CLASS`` was already discussed, is already implemented, and is tested in `testcapi` module. This section is mostly needed to "legalise" the current implementation. So that there will be no discussions in future whether this is intentional, or just an implementation artefact.
@gvanrossum I think I need your special permission for this.
> Clarify C calling convention for __class_getitem__ in PEP 560

- pep-0544.txt
This PR contains a set of (hopefully) final updates to PEP 544:
* Rename `@runtime` to `@runtime_checkable`
* Postpone making mappings and sequences protocols, this can be done later in Python 3.8
* Update the implementation status
* More strict and precise specification for `isinstance()` and `issubclass()` with protocols.
* Few typos
Attn: @gvanrossum @JukkaL @ambv
> Update PEP 544

- pep-0544.txt
This is already implemented in mypy in exactly the same way it works for nominal classes (and thus shares most bugs of self-types in nominal classes). The question is: if self-types in protocols just follow the specification of PEP 484 do we need this additional subsection? (Or is it still helpful just as an example?)
Attn: @gvanrossum @JukkaL @ambv
> PEP 544: Specify self-types in protocols

- pep-0539.txt
Follow-up to https://github.com/python/peps/pull/648
The genpepindex script requires the headers to be in a particular order.
In `pep-0539.txt` the order was different, breaking the build for everyone.
> PEP 539: Fix Python-Version header

- pep-3107.txt
Since we ended up with `__annotations__`, it would be much less confusing if this used it instead of referring to a property that does not exist.
> "func_annotations" -> " __annotations__"

- pep-0577.rst
- pep-9999.rst
Competing proposal for PEP 572 that focuses on allowing
augmented assignments as expressions, and treats
"NAME := EXPR" primarily as an explanatory tool for
the updated augmented assignment semantics.
> PEP 577: Augmented assignment expressions

- pep-0547.rst
Officially defer PEP 547. It is not ready, yet.
@Traceur759, do you agree?
> Defer PEP 547

- pep-0572.rst
@Rosuav, @tim-one: On the plane home from PyCon I did some major surgery on PEP 572. The tl;dr is that I removed the changes to comprehensions and added Tim's proposal for making := inside a comprehension write the target in the containing scope. There's a bit more, below are the bullets from my local commits.
- Remove changes to comprehension scope
- Make := in comprehensions assign to containing non-comprehension scope
- Clarify binding precedence (tighter than comma, not at same level as =)
- Remove mention of more complex targets in the future
- Explicitly disallow toplevel :=
- Rewrite section on differences with =, enumerating all of them
- Remove "here's how this could be written without :=" from examples
- Tweak first paragraph of "Syntax and semantics"
- Add "Exceptional cases" …
> Pep 572 update

- pep-0484.txt
This came up in python/mypy#5156; we agreed that it was an oversight in the original specification of this feature to not allow this.
> Arguments that end with `__` are not positional-only

- pep-0373.txt
2.7.15 releases are now past:
https://mail.python.org/pipermail/python-announce-list/2018-May/011914.html
https://mail.python.org/pipermail/python-dev/2018-April/152706.html
> PEP 373: Add 2.7.15 release dates

- pep-0263.txt
The characters before the # in a coding declaration line can be spaces, tabs, or form feeds; the escape sequence for a form feed is a `\f`, not a `\v` as is shown here.
> PEP 263: fix typo in coding regex

- pep-0577.rst
Guido providing some excellent feedback on the initial draft of PEP 577, and in
responding to it I realised that while the augmented assignment analogy had
helped me clarify what was bothering me about PEP 572's proposed handling
of previously undeclared assignment targets, actually allowing full inline
augmented assignments has enough other downsides that even I don't think
this particular PEP is a good way of resolving those concerns.
> PEP 577: Revise & withdraw based on review feedback

- pep-0575.rst
- pep-0579.rst
- pep-0580.rst
PEP 579: an informational meta-PEP, as proposed in https://mail.python.org/pipermail/python-ideas/2018-May/051005.html and https://mail.python.org/pipermail/python-ideas/2018-June/051408.html
I took the number 579 to avoid a conflict with #674.
PEP 580: a standards track PEP, meant to replace PEP 575. This proposes the C call protocol, which solves several issues of PEP 579. Some discussion already happened at https://mail.python.org/pipermail/python-dev/2018-June/153908.html
PEP 575: withdrawn because it solves the same issues but in a worse way.
> PEP 579 and 580: the C call protocol

- pep-0551.rst
- pep-0578.rst
At Guido's request, I am splitting PEP 551 into two PEPs. The end result will be:
* PEP 578 is a standards track PEP for Python 3.8 adding runtime audit and open-for-import hooks
* PEP 551 is an informational PEP providing guidance for those integrating Python into secure/audited environments
The `spython` implementation will become a sample associated with PEP 551 and will not be checked in with the PEP 578 changes.
> Begins splitting PEP 551 into PEP 578

- pep-0518.txt
It is common to reference to different parts of the specification when
discussing the changes brought about by this PEP. This change makes it
easier to do so by introducing subsections to the main specification.
/cc @ncoghlan @dstufft @njs @brettcannon
> PEP 518: Add subsections to Specification section

- pep-0572.rst
@tim-one Can you review this carefully? I know I've screwed up the details of these translations in the past many times.
@ncoghlan I think these cases show the implementer the variants they need to know about (assuming that if they know how to do one level of nesting they can do any number of levels :-). Let me know if you think more examples are needed.
> PEP 572: Add Appendix B with translations of various comprehension cases

- pep-0572.rst
- Dropped "TODO: Include Guido's evidence, and do a more systematic search."
I think the current text is good enough.
- Relented on assignment expressions in default values other than top
level.  (Mainly because the syntactic/semantic check would be
awkward, and it was already called out as a possible style
recommendation instead.)
- Clarified that a lambda counts as "the current scope" (containing an
assignment expression).
- Added prohibition on [... for i in i := ...].
- Specified that scope-related prohibitions should raise
TargetScopeError, a subclass of SyntaxError.
> PEP 572: Address several small issues

- pep-0572.rst
Remove "Open questions and TODOs" since they're now all decided.
> PEP 572: Move the proposed evaluation order change to "Syntax and semantics"

- pep-0572.rst
Also explain what's wrong with `->`.
> PEP 572: Explain why 'as TARGET' is inferior

- pep-0572.rst
Exactly what it says on the tin. :stuck_out_tongue:
> PEP 572: Fix typo ("assing -> assign")

- pep-0484.txt
Following discussion in python/typing#275, there is a consensus that it is better to require optional types to be made explicit. This PR changes the wording of PEP 484 to allow, but not require, type checkers to treat a None default as implicitly making an argument Optional.
> PEP 484: Do not require type checkers to treat a None default specially

- .gitignore
- Makefile
- genpepindex.py
- pep0/constants.py
- pep0/output.py
- pep0/pep.py
Converting the PEP index to reStructuredText allows for
direct hyperlinks to individual PEP categories, as well as
other parts of the PEP index.
It also provides a hyperlinked Table of Contents at the top
of the page for easier navigation.
> Convert PEP index to ReST

- pep-0572.rst
A case equally confusing to default values, I think.
> PEP 572: disallow ungrouped assign-expr in annotations

- pep-0101.txt
- pep-0292.txt
- pep-0435.txt
- pep-0446.txt
- pep-3156.txt
- pep2html.py
- pep2pyramid.py
We're already linking PEP numbers in "Replaces:", and "Requires:".
Adjusted the code so it can link "Superseded-By:".
Add the "Replaces:" header where they're missing.
Closes https://github.com/python/peps/issues/477
> Linkify the PEP numbers in "Superseded-By" header.

- pep-0572.rst
The current PEP wording suggests assignment expressions can't be
annotated at all, which isn't quite true: as with any other name binding
operation, they can still be annotated via a separate local declaration.
> PEP 572: Annotations are supported, via separate declarations

- pep-0572.rst
PEP 572: Make very clear in the Appendix C example that the function local remains unbound until the caller executes the genexp.
> PEP 572:  clarify Appendix C example

- pep-0572.rst
(This section would gzip very efficiently. "Unparenthesized assignment
expressions are prohibited...")
> PEP 572: Add another UAEAP bullet point

- pep-0572.rst
- Delete 'Pending Acceptance' section
- Mark reference implementation as incomplete
- Add the ^L back before the Emacs Local Variables section
> PEP 572: Acceptance

- pep-0572.rst
Closes #737 
Added sentence to Abstract, as requested in https://github.com/python/peps/pull/737#issuecomment-404543462 by @gvanrossum.
> PEP 572: Mention the two minor changes in the Abstract

- pep-0306.txt
Two links have been updated:
* The CPython Developer's Guide no longer supports `/en/latest` in the URL. This returns a 404. Updated to a working link.
* http://www.python.org/sf/676521 redirects to https://legacy.python.org/sf/676521. This returns a 403 as the legacy site has been partially phased out. Updated to a working link.
> PEP 306: Fix dead links for Dev Guide and BPO issue

- pep-0042.txt
- pep-0262.txt
- pep-0277.txt
- pep-0278.txt
- pep-0283.txt
- pep-0285.txt
- pep-0289.txt
- pep-0293.txt
- pep-0298.txt
- pep-0304.txt
- pep-0306.txt
- pep-0309.txt
- pep-0311.txt
- pep-0318.txt
- pep-0322.txt
- pep-0338.txt
- pep-0339.txt
- pep-0341.txt
- pep-0342.txt
- pep-0349.txt
- pep-0352.txt
- pep-0356.txt
- pep-0361.txt
- pep-0366.txt
- pep-3100.txt
- pep-3119.txt
- pep-3129.txt
- pep-3132.txt
`http://www.python.org/sf/<issue-num>` or `http://python.org/sf/<issue-num>` redirects to `https://legacy.python.org/sf/<issue-num>`. This returns a 403 as the legacy site has been partially phased out.
Any reference to `http://www.python.org/sf/<issue-num>` or `http://python.org/sf/<issue-num>` has been changed to `https://bugs.python.org/issue<issue-num>`
> Multiple PEPs: Fix dead links for issues

- pep-0505.rst
Currently this code is mis-formatted as regular text in block quote, losing line breaks
CLA signed in the past, I'm `cben` on bugs.python.org.
> PEP 505: fix code formatting to be literal block

- pep-0004.txt
Remove the part about `".., which SHOULD be a patch posted to
bugs.python.org."`
I think that is referring to the old way where changes to the PEP has to be a patch uploaded to bpo.
Nowadays it is as GitHub pull request, but I'm not sure if we need to be specific about it.
Alternatively it can ends with: `", which SHOULD be a GitHub pull request."`
> PEP 4: remove the part about about "should be a patch to bpo".

- pep-0013.rst
- pep-8000.rst
- pep-8001.rst
- pep-8002.rst
- pep-8010.rst
- pep-8011.rst
- pep-8012.rst
These are the placeholder PEPs for the selection of a new Python language governance model.  We are reserving PEPs in the lower 8000s for the supporting material, and PEP 13 for the final, codified model PEP.
> Initial crop of governance model PEPs

- pep-8002.rst
> PEP 8002: Add information about Project Jupyter governance

- pep-0581.rst
Use auto-numbering for footnotes to make it easier to add/remove notes.
> PEP-0581: use auto-numbering for footnotes.

- pep-0484.txt
The definition of AnyStr as given makes sense only in Python 3, as observed by @srittau. To prevent confusion, this PR changes the definition to use Text instead of str.
I also changed the two places where AnyStr was defined as an example, and made a few other related adjustments:
- Remove mention of None as modifying the type, which is not true as of #689.
- Move Text up in the list of convenience definition because we now need it for the definition of AnyStr.
- Modify definition of Optional to use `None` instead of `type(None)`, because the latter is not a valid static type.
> PEP 484: Clarify definition of AnyStr

- pep-8002.rst
I know this doesn't fit the rationale, but as I posted on Zulip I believe the rationale is unnecessarily restrictive (specifically, employees at Microsoft have the power to change team or company, and many do, when they dislike the processes used - when the process works, retention rates reflect it).
But I'm happy to leave the rationale there and simply mark this as an exception. Mostly, I want to ensure the "final arbiter who is not a contributor" scenario is written up.
> PEP 8002: Add section describing an idealised version of the process used at Microsoft

- pep-0566.rst
- Permit direct references as an alternative to version specifiers
- Permit public index servers to prohibit strict matching specifiers
and direct references
Closes #763 
/cc @di @pfmoore
> PEP 566: Support for direct references and permit public index servers to add restrictions

- pep-0001.txt
Closes #788.
Reference: https://mail.python.org/pipermail/python-ideas/2018-September/053586.html
The criteria are taken from section "PEP Editor Responsibilities & Workflow" and edited to reflect the submitter's viewpoint.
Collateral damage: The format of the section was changed from bullet points without interpoint vertical whitespace to insert whitespace because rstpep2html doesn't like the more compact formatting I tried.  A period was used to terminate the last bullet point.
> PEP 1: Add approval criteria to section "Submitting a PEP".

- pep-0577.rst
When I withdrew PEP 577, I intended to write up a new alternative
to both it and PEP 572, but the replacement never reached a state
where I liked it enough to post it.
So this amends the withdrawal notice to make it clear that there's
no further alternative planned.
> Amend misleading withdrawal notice on PEP 577

- pep-3141.txt
Fixed the `The Scheme numerical tower` url
I signed the Contributor Agreement
> PEP 3141: fix broken numerical tower link

- pep-8000.rst
- pep-8011.rst
> PEP 8011: Python Governance by Trio of Pythonistas

- pep-0561.rst
As brought up in https://github.com/python/mypy/issues/5520.
cc @gvanrossum
> PEP 561: Clarify ordering of module resolution

- pep-8011.rst
- term limit (5 years, same as release manager's role)
- disbanding the trio when one member quits
- use same voting mechanism as PEP 8001
- clarify that an individual can be nominated in more than one slate
> PEP 8011: Clarify open points

- pep-0484.txt
Per discussion in python/typeshed#1652 and python/typing#589.
> PEP 484: Remove mention of typing.io and .re

- pep-0008.txt
Previously, the PEP contained roughly the following three rules, in sequence:
1. Never use spaces around `=` when used to indicate a parameter default
2. Something unrelated
3. DO use spaces around `=` when used to indicate a parameter default if there is also a parameter annotation present
This was, in my opinion, confusing, since rules 1 and 3 contradict each other. If you read both, it's not too hard to deduce the intended meaning (don't use spaces for default parameters of unannotated parameters, but do use them for annotated parameters), but it's still technically a contradiction as written, and somebody scan-reading the document could easily just see the first rule and walk away misled.
This commit attempts to clarify this part of the PEP by:
* Combining the first and third rules …
> PEP 0008: Clarify self-contradictory =-spacing rules

- pep-8015.rst
* PEP 8015: rename Core Board to Steering Committee
* Steering Committee doesn't approve PEPs
* Move PSF Code of Conduct Workgroup section
* Limit committee mandates
* Add Version History and Copyright sections
> Adjust the PEP 8015 (version 4)

- pep-8001.rst
Suggested change to use CVIS instead of a github repository to enable private ballots.
> PEP 8001: Use CVIS instead of a github repository

- pep-8010.rst
Version 2
- Renamed to "The Technical Leader Governance Model"
- "singular leader" -> "singular technical leader"
- The adoption of PEP 8001 voting procedures is tentative until that
PEP is approved
- Describe what happens if the GUIDO steps down
- Recall votes require a super majority of core devs to succeed
> Version 2 updates

- pep-0557.rst
Corrects spelling of “explicitly”.
> PEP 557: Fix typo

- pep-8015.rst
* The Steering Committee is now made of 5 people instead of 3.
* There are no term limits (instead of a limit of 2 mandates:
6 years in total).
* A committee member can now be a PEP delegate.
> PEP 8015: Committee has 5 members

- pep-8001.rst
https://discuss.python.org/t/pep-801x-authors-are-you-on-track-for-the-vote-between-nov-16-nov-30/432/27
> PEP 8001: Add a review period and adjust the vote period

- pep-8016.rst
* Removed the requirement that council members have to be core team
members; added the requirement that non-core-team council candidates
need to be nominated by a core
team member. Rationale: Steve Dower is worried that we may have a
shortage of core team members who are willing to serve on the
council. I'm not worried myself, but I like Steve and don't want him
to worry; this is an easy way to help with that. Requiring a core
team member nomination should be harmless, since any candidate that
can't get a nomination is certainly not going to win a vote, and it
lets us filter out random jokers early.
* Added some language to emphasize that emeritus core team members
will still be listed on the website and their past contributions
will continue to be recorded.
* Changed the vote tie-breaker …
> PEP 8016: more tweaks based on discussion

- pep-8001.rst
The vote's supposed to start in a few days, so I figured it would be
good to get out ahead of any last-minute futzing with the text. Here's
a fully-fleshed-out proposal for the vote instructions and options, so
everyone can review.
I also set up a test vote on CIVS, using the text in my initial
commit, so you can see how it will actually look in context:
https://civs.cs.cornell.edu/cgi-bin/vote.pl?id=E_f3dd3ec110515d32&akey=add219018ca56843
I'll post these links on python-committers too.
CC: @ewdurbin
> PEP 8001: Add draft of vote details

- pep-8016.rst
This doesn't change the meaning at all; just removes a confusing term.
Thanks to Xiang Zhang for pointing this out here:
https://discuss.python.org/t/pep-8016-the-steering-council-model/394/36
> PEP 8016: remove confusing term "strict majority"

- pep-0517.txt
Later on in the same PEP, it says that the `.zip` example can't possibly work:
> [source distributions] will be gzipped tar archives, with the .tar.gz extension. Zip archives, or other compression formats for tarballs, are not allowed at present.
This, and other documentation issues not fixed here, was noted in a blog post I was reading: https://blog.schuetze.link/2018/07/21/a-dive-into-packaging-native-python-extensions.html. Full credit to @konstin.
> PEP 0517: Remove misleading ".zip" example sdist

- pep-0581.rst
It is now possible to automate issue assignee and labels via templates.
https://blog.github.com/changelog/2018-12-05-issue-template-automation-improvements/
> PEP 581: Mention GitHub's new feature wrt issue template

- pep-0583.txt
This old draft PEP came up in an in-person conversation. It turns out to be almost vanished from the internet; the only source of it I could find is on Launchpad: https://code.launchpad.net/~jyasskin/python/memory-model-pep So, I'm assigning it a number, marking it Withdrawn, and checking it in so as not to lose a historical record.
> Check in the memory model PEP.

- pep-0494.txt
- pep-0537.txt
https://blog.python.org/2018/12/python-372rc1-and-368rc1-now-available.html
> PEP 494/537: 3.7.2rc1 and 3.6.8rc1 released

- pep-0013.rst
- pep-8016.rst
~~**Don't merge yet**: waiting to hear from Aymeric Augustin about the licensing.~~
Despite what [I said earlier](https://discuss.python.org/t/organizing-the-council-elections/549/4), this uses the text from PEP 8016 verbatim. My thanks to the PSF for their help in [covering up my mistake](https://mail.python.org/pipermail/psf-community/2018-December/000614.html).
CC: @dstufft
> PEP 13: make it real

- pep-0013.rst
The core team members list is only available for core members. Otherwise a 404 error is displayed so people will try to fix what seems to be a broken link (like me).
This PR is done to close #863
I already signed the CLA to contribute to cpython.
Of course, feel free to rewrite it; english is not my native tongue.
> PEP 13: Add info about the limited access to members list

- pep-0013.rst
- pep-0584.rst
- pep-8100.rst
Inspired by this thread:
https://discuss.python.org/t/how-do-we-want-to-collect-nominees/590
@EWDurbin: I listed you as an author, similar to how release managers
are the official authors of release schedule PEPs. Is that OK?
> PEP 8100: a PEP to track details of the steering council election

- pep-8100.rst
I'm nominating David Mertz to the steering council because of his interest expressed in this Python-Dev thread here (and after consulting with him):
https://mail.python.org/pipermail/python-dev/2019-January/155988.html
After merging this, I'll create a topic on Discourse and add to the PEP a hyperlink to the topic, like there is for the other nominees.
> PEP 8100: Nominate David Mertz for steering council

- pep-8100.rst
This adds the hyperlink to the Discourse discussion.
> PEP 8100: Add hyperlink to discussion topic for David Mertz.

- pep-0574.rst
Make it a requirement that buffers are contiguous. Efficient tooling for non-contiguous buffers is not available from CPython currently, and consumers shouldn't be required to implement their own handling.
Also add a bit of trivia about an undocumented ZODB-specific `cPickle` hook.
> PEP 574: update

- pep2html.py
Running with latest CPython master gives several warnings like
```
pep2html.py:87: SyntaxWarning: invalid escape sequence \s
"(PEP\s+(?P<pepnum>\d+))|"
```
> pep2html: use raw strings where needed

- pep-0384.txt
Following the post at https://mail.python.org/pipermail/python-dev/2018-April/152642.html I am adding explicitly that undocumented functions can be considered part of the stable ABI.
Apart from that, some minor reorganization and rewording.
> Clarify PEP 384

- pep-0551.rst
"Rejected Advice" sounds like the section will contain false
statements that should not be followed, instead it contains true
statements about things you should not do.
Change the title to "Things not to do" to be clearer that these are
correct advice but of a negative sense.
> PEP 0551: change title of "Rejected Advice" section

- pep-0469.txt
Fix #852 by updating line 129 in PEP469
> PEP 469: Fix #852 by removing typo iter(d.iteritems()) -> iter(d.items())

- pep-0001.txt
NOTE: Currently posted for Steering Council review, so definitely don't merge this yet :)
Minimalist adjustment to the PEP process to account for the
language governance changes.
- final design authority is now the elected Steering Council
- BDFL-Delegate process is now used for all PEPs, with the
Steering Council looking to appoint a delegate if nobody
volunteers of their own accord, and PEPs being deferred
if no suitable delegate can be found
- avoiding the role renaming bikeshed for the time being by
keeping the BDFL-Delegate title
This will allow us to start processing additional PEPs for
Python 3.8.
I also addressed some existing issues that the above changes
made more readily apparent:
- clarified that the PEP process is used for more than just
the CPython reference interpreter
- …
> PEP 1: Update for governance changes

- .gitignore
- .travis.yml
- Makefile
the peps are built... may as well publish a tarball directly from travis.
python.org hosting is being updated and i'm trying to move it away from local
disk storage, which the current pep integration relies on.
this will allow python.org to pull the tarball out of S3 and do it's work.
> create package target

- pep-0008.txt
Avoid unnecessary mixing of line length and window width, as it can be confusing.
> Talk about line length instead of window size

- pep-0517.txt
Proposed changes to PEP 517 to add support for self-hosting backends and in-tree hooks.
See https://discuss.python.org/t/pep-517-backend-bootstrapping/789 for the discussions on this topic.
> PEP 517: Add draft wording for self-hosting backend and in-tree hook support

- pep-0432.txt
This isn't a full PEP 432 update, but it at least makes it better describe
what we've already learned from attempting to implement aspects of it
as a private configuration API in Python 3.7.
> PEP 432: Update to better reflect status quo

- pep-0381.txt
This proposal was effectively Withdrawn years ago, we just never
explicitly marked it as such.
> PEP 381: Mark as Withdrawn

- pep-0432.txt
Also update the tentative target Python version to 3.9.
> PEP 432: Direct discussions to capi-sig

- pep2html.py
> Support the 'Sponsor' header field

- pep-0008.txt
From 
> does not import objects whose name starts with an underscore.
into
> does not import objects whose names start with an underscore.
Closes https://github.com/python/pythondotorg/issues/1387
> PEP 8: minor grammar improvement

- pep-0586.rst
This pull request fixes one or two typos in PEP 586.
It also slightly adjusts the wording of the section on type inference as suggested here: https://github.com/Michael0x2a/peps/pull/1#discussion_r265795433
> PEP 586: Fix typos and tighten wording

- pep-0556.rst
> PEP 556: Mark deferred

- pep-0576.rst
- pep-0579.rst
- pep-0580.rst
Petr had been mentioned as a potential delegate prior to the governance
changes, and with Petr's agreement, the Steering Council is appointing
him to review the competing proposals in these PEPs, and make the
decision on which approach to pursue to resolve the issues with the
status quo.
> PEPs 576, 579, 580: Appoint Petr Viktorin as BDFL-Delegate

- pep-0499.txt
Also updates the PEP with links to the reference implementation,
and adds an Open Questions section to highlight known areas of
compatibility risk.
> PEP 499: Delegate to Nick Coghlan

- pep-0508.txt
fixed typo in identifier_end rule that was resulting in attribute error when trying to run the grammar.
> PEP 0508: change identifer_end rule to identifier_end

- pep-0580.rst
The flag `CCALL_FUNCARG` was always a bit of a wart: it was meant to pass the callable object to support (amongst other things) PEP 573. This was a problem for bound methods: should the "callable object" be the method or the original function?
I realized that this problem could be solved (without sacrificing any use cases) by instead passing the ``PyCCallDef *`` instead. The implementation of bound methods ensures that the ``PyCCallDef *`` used by the method is the same as the original function.
@encukou
> PEP 580: new flag CCALL_DEFARG instead of CCALL_FUNCARG

- pep-0578.rst
Haven't implemented these changes yet, and I want to do that before committing this, but at least getting the new proposed names out there early.
> PEP 578: Rename open_for_import to io.open_code

- pep-0570.rst
The name of a positional-only parameter can occur in `**kwds`.
(This is not really an addition to the specification, it just clarifies a corollary.)
This was brought up in https://github.com/python/cpython/pull/12637#issuecomment-480481885
> PEP 570: Demonstrate a corner case

- pep-0440.txt
Example of old behaviour:
```python
>>> is_canonical('1٤')
True
```
> PEP 440: regex should not permit Unicode [Nd] characters

- pep-0590.rst
Clarifies the use of `PY_VECTORCALL_ARGUMENTS_OFFSET`.
The minimal implementation has also been updated to use `const` arguments.
https://github.com/python/cpython/commit/46e9b77d4b2dfd9f2dcb86842e217a40b243835f
> PEP 590: Clarify the use of PY_VECTORCALL_ARGUMENTS_OFFSET.

- pep-0517.txt
Make it explicit that including a ``setup.py`` is still needed if the build backend tool uses it (aka dropping the setup.py) is not mandatory.
The current wording could mislead someone to think that the ``build_backend`` keyword and ``setup.py`` are mutually exclusive (aka need not - could be interpreted as must not).
> PEP 517: Improve wording on including setup.py in the source distribution

- pep-0578.rst
Clarifications as requested by @ncoghlan (not sure he agrees with the clarifications, but he asked for them ;) )
> PEP 578: Add clarifications around open_code() for non-code files

- pep-0590.rst
- Add "Vectorcall" to the PEP title to make it easier to reference
- Mention "fastcall" in the abstract, for people familiar with the term
@markshannon, are you OK with renaming the PEP like this?
> PEP 590: Add "Vectorcall" and "fastcall" keywords

- pep-0586.rst
@Michael0x2a please review
The additions to the Abstract example may be controversial, I'm happy
to change these -- or anything else -- if you're uncomfortable with my
suggestions.
> PEP 586: Small wording changes from review; expanded example in Abstract

- pep-0432.txt
- pep-0587.rst
- add Victor and Eric as co-authors (as they're definitely API co-designers)
- add a dependency on PEP 587
- revised implementation strategy to cover extracting other PEPs for more settled API subsets
- update PEP 587 to be explicit that it's covering things the native CPython CLI already uses,
so the level of speculation it involves is actually pretty low, while the speculative stuff remains
in PEP 432
- add mentions of PEP 587 where relevant throughout the PEP 432 text
- revise the phase descriptions to better match PEP 587
- revise several aspects of the speculative API design in PEP 432 to better align with PEP 587
(in particular, the previous `PyMainInterpreterConfig` is now `PyConfigAsObjects`)
> PEP 432: Update based on the extracted PEP 587 API

- pep-0586.rst
This commit adds a section discussion how Literal types interact with Final from PEP 591, if both PEPs are accepted. In short, it states that type checkers are expected to understand that assignment statements of the form `var: Final = value` are a way of declaring `var` to effectively be of type `Literal[value]` in certain cases.
> PEP 586: Add section about Final

- pep-0586.rst
This pull request relaxes PEP 586 so that type checkers are now expected to maintain backwards compatibility on a best-effort basis, rather than a mandatory basis (as per the earlier discussion on typing-sig).
It also rearranges the order in which information is presented: the section now opens with and focuses on an example of what a too-disruptive inference strategy would look like.
> PEP 586: Make backwards compatibility best-effort

- pep-0586.rst
This commit adjusts two sections of this PEP that are related to enums.
First, it removes the sections regarding the interaction between enums, imports, and Any. I wasn't aware that the import behavior described in that section was mypy-only and isn't codified in PEP 484. So, I decided to just remove that section entirely -- it didn't feel there was much I could salvage there.
Instead, I opted to adjust the "invalid parameters" section to explain in a little more detail why `Literal[Any]` is not allowed.
Second, I split up the section about type narrowing into two.
The first new section is a reminder that PEP 484 requires type checkers to support certain kinds of exhaustiveness checks when working with enums. To make this more clear, I adjusted the example to be more closer to what is …
> PEP 586: Rewrite sections regarding enum

- pep-0573.rst
I'd like to target the module state access PEP to Python 3.9, and focus on C calling convention PEPs (580 & 590) for Python 3.8.
cc @ericsnowcurrently @Dormouse759 @ncoghlan
> PEP 573: Defer to Python 3.9

- pep-0590.rst
Rather than just removing `PyObject_VectorCall`, I've also renamed the clumsily named `PyOject_VectorCallWithCallable` to `PyObject_VectorCall` and corrected the note about the  use of `PY_VECTORCALL_ARGUMENTS_OFFSET` in `PyObject_VectorCall`. 
Also corrects the section on internal CPython changes.
> PEP 590: Remove unnecessary PyObject_VectorCall function.

- pep-0554.rst
There is too little time left before the 3.8 release and I don't want Antoine to feel rushed to pronounce.  The implementation is mostly complete, so we *could* land it for 3.8.  However, the experience in 3.8 wouldn't be nearly as good, in part because we're still sharing the GIL.  Plus, we need more confidence that extension modules won't be severely impacted by the wide-spread use of subinterpreters.  Waiting for 3.9 will allow us to address both issues, as well improve performance (especially startup).
> PEP 554: Change target version to 3.9.

- pep-0587.rst
* Add "PyConfig with dynamic memory allocations" section
* Add functions:
* PyWideStringList_Append(list, item)
* PyConfig_SetString(config_str, str)
* PyConfig_SetWideString(config_str, str)
* PyConfig_SetWideStringFromString(config_str, str)
* PyConfig_Read(config)
* PyConfig_SetArgv(config, argc, argv)
* PyConfig_SetWideArgv(config, argc, argv)
* PyConfig_Clear(config)
* Py_INIT_IS_ERROR(err)
* Py_INIT_IS_EXIT(err)
* Remove Py_INIT_USER_ERR(MSG) function
* On Windows, PyInitError.exitcode type is now "unsigned int"
and Py_ExitInitError() now calls ExitProcess(exitcode).
* PyInitError: add private _type field. The "prefix" field becomes a
private "_func" field.
* Rename PyWideCharList to PyWideStringList
> PEP 587: Init API v2

- pep-0590.rst
Will allow Cython to use vectorcall in versions before 3.8.
> PEP 590: Swap tp_vectorcall_offset and tp_vectorcall slots.

- pep-0517.txt
The previous wording could be taken as suggesting that frontends should opt
out of their PEP 517 processing entirely if `build-backend` was not defined,
whereas it's actually fine to just use the `setuptools` provided backend that
implements the legacy build semantics.
> PEP 517: Clarify expected front end handling of setup.py based trees

- pep-0592.rst
> PEP 592: Support for "Yanked" Files on the Simple API

- pep-0590.rst
The discussion on GH-1028 got out of hand.
This PR attempts to collect the "uncontroversial" changes, and also to collect the unresolved issues.
If there's something here you don't agree with, point it out.
I'll add it to the following list of things to hash out (and, if feasible, revert the change here).
Please don't discuss any of these in this PR.
cc @markshannon @jdemeyer 
I'm not sure this was settled.
* `uintptr_t` (original)
* `Py_ssize_t` (matches type of `offsetof` and existing practice)
* `ptrdiff_t` (actual "difference of pointers" type)
This is probalby pointless bikeshedding.
* `PyObject *(*call) (PyObject *self, PyObject *const *args, Py_ssize_t nargs, PyObject *kwname)`
* `vectorcallfunc`
(There is a discussion on what code is "trusted".)
* `PyCall_MakeVectorcall` …
> PEP 590: Base update

- pep-0591.rst
> PEP 591: clarify that type checkers may not allow `Final` in loops

- pep-0457.txt
This PEP: shorthand notation to describe positional-only arguments
PEP 570: Elevating that notation to actual Python syntax
> PEP 457: Better distinguish this PEP from PEP 570

- pep-0590.rst
This simply codifies what's already in the reference implementation, so it should be uncontroversial:
- the `nargs` argument comes after `args` in vectorcall functions.
- `kwnames` is passed as `PyObject *` instead of `PyTupleObject *` (like most other C API functions, the generic `PyObject *` is used instead of a specific struct like `PyTupleObject *`)
- the argument `kwnames` may be `NULL`
CC @encukou @markshannon
> PEP 590: Use PyObject *kwnames, which may be NULL

- pep-0590.rst
Since `__set__` and `__delete__` are no longer mentioned in the description of `Py_TPFLAGS_METHOD_DESCRIPTOR`, also `tp_descr_set` shouldn't be mentioned in the section about subclassing.
> PEP 590: no longer mention tp_descr_set

- pep-0544.txt
See https://github.com/python/mypy/issues/5018 for motivation.
Attn: @gvanrossum @JukkaL @ambv
> PEP 544: Specify usage of modules as subtypes of protocols

- pep-0590.rst
Rename `PyCall_MakeVectorCall` -> `PyVectorcall_Call` since it's consistent with how other C API functions are named: it's doing a `*argstuple`/`**kwdict` call (just like `PyObject_Call` and `PyCFunction_Call`) and it does that using the vectorcall protocol.
So really `PyVectorcall_Call` is the most correct name.
CC @encukou @markshannon
> PEP 590: rename PyCall_MakeVectorCall -> PyVectorcall_Call

- pep-0544.txt
cc @gvanrossum @JukkaL @ambv 
This PR contains mostly minor wording tweaks plus a paragraph _explicitly_ allowing class objects as implementations of protocols, previously there were questions whether it is actually allowed, see https://github.com/python/mypy/issues/4536.
> Minor tweaks to PEP 544

- pep-0587.rst
* Thomas Wouters is now the BDFL-delegate
* Elaborate the Rationale
* New "Path configuration" section
* New "Python Issues" section
* Add PyWideStringList_Insert() function
* Add PyConfig.configure_c_stdio option.
* Add PyConfig.parse_argv field
* Rename bytes/wide functions. Add "Bytes" to functions taking char*,
remove "Wide" from functions taking wchar_t*. Rename
PyConfig_DecodeLocale() to PyConfig_SetBytesString().
* PyConfig: Rename '_frozen' to 'pathconfig_warnings'
* Re-introduce PyConfig._init_main
* Complete tables of global configuration variables; annotate
variable values which are negated.
> PEP 587: API v3

- pep-0518.txt
As requested/suggest by @njsmith
> PEP 518: Clarify any tool can use the tool table

- pep-0590.rst
I suggest to keep the flag `METH_FASTCALL` for now instead of adding a new flag `METH_VECTORCALL`. First of all, this allows compatibility with all Python versions starting from 3.6 (at least, if not combined with `METH_KEYWORDS`). Second, it makes a clear separation between the vectorcall protocol and the `PyMethodDef` struct, which are more or less orthogonal. Third, using the name `METH_VECTORCALL` for a calling convention which is not the `vectorcallfunc` calling convention would be confusing.
CC @encukou @markshannon @scoder
> PEP 590: remove METH_VECTORCALL flag

- pep-0587.rst
> PEP 587 version 4

- pep-0594.rst
Updates from discussions on python-dev and Twitter.
> PEP 594: Update with discussion items

- pep-0558.rst
Changing the frame API semantics based on whether or not a
tracing function is active is tricky to implement and hard
to document clearly, so this simplifies the proposal by
instead having the frame API always expose a write-through
proxy at function scope, and restricting the dynamic
snapshot behaviour to the locals() builtin.
> PEP 558: Remove dynamic frame semantics proposal

- pep-0558.rst
- new design discussion section to cover the requirement that the
semantics of locals() itself at function scope be left alone
- propose a C level API that exactly matches Python level
frame.f_locals semantics
- other minor text formatting and wording updates
> PEP 558: Note compatibility constraints on locals(), other updates

- pep-0594.rst
The information in the table was wrong.
> PEP 594: asyncore and asynchat are deprecated since 3.6

- pep-0594.rst
> PEP 594: track experts

- pep-0590.rst
In the Steering Council discussions leading up to the [2019-04-26 update], I was appointed BDFL delegate for PEPs 576, 579, 580, and 590.
PEP 590 was still just a draft on the mailing list when the SC updated the PEPs themselves, so it wasn't updated then.
[2019-04-26 update]: https://github.com/python/steering-council/blob/master/updates/2019-04-26_steering-council-update.md#peps
> PEP 590: Record BDFL delegate

- pep-0484.txt
As discussed on the typing-sig mailing list, the currently specified behavior for `# type: ignore` on a line by itself has remained mostly unimplemented and doesn't seem useful. Instead, the PEP now mandates a syntax for ignoring all errors in a specific file, which is more obviously useful.
I considered adding a sentence like "Individual type checkers may add additional syntax for silencing errors", but it didn't seem particularly useful since type checkers in general are free to add extensions to what PEP 484 specifies.
While I was at it I added a reference to PEP 526 to an out-of-date sentence adjacent to the modified paragraph.
> Change specification for `# type: ignore`

- pep-0544.txt
This includes couple edits inspired by recent discussions:
* Remove mention of metaclasses from implementation details section (PEP 560 makes them unnecessary).
* Explcitly mention callback protocols as an important use case.
cc @ambv @JukkaL @gvanrossum
> PEP 544: Couple final edits

- pep-0587.rst
* Add "Experimental Multi-Phase Initialization API" section
* Add PyPreConfig._config_init private field.
* Rename PyInitError to PyStatus.
* Rename PyInitError_Failed() to PyStatus_Exception()
* Rename Py_ExitInitError() to Py_ExitStatusException()
* Fix Python Configuration default values: isolated=0
and use_environment=1, instead of -1.
* Document #ifdef MS_WINDOWS
* Define path conf function
> PEP 587 version 5

- pep-0587.rst
* Fix _init_main=0 example: set config._init_main=0.
* Document special builds needed by some speficic options like
show_alloc_count.
* Specify that preconfiguration only requires command line arguments
* for the "Python Configuration" (not for "Isolated Configuration").
> PEP 587: Fix a few minor issues

- pep-0594.rst
> PEP 594: Fix typos

- pep-0594.rst
Change 
> This was often refrained to as "batteries included"
to
>  This was often referred to as "batteries included"
> PEP 594: miswording fix

- pep-0594.rst
> PEP 594: Update 2

- pep-0590.rst
> PEP 590: Mark the main API as private to allow changes in Python 3.9

- pep-0484.txt
- pep-0544.txt
- pep-0558.rst
- pep-0574.rst
- pep-0586.rst
- pep-0587.rst
- pep-0589.rst
- pep-0590.rst
- pep-0591.rst
- pep-0594.rst
- pep-0595.rst
In C, bitwise operations are much better defined on unsigned values.
Since we do `nargs & ~PY_VECTORCALL_ARGUMENTS_OFFSET`, we should do it on an unsigned value.
cc @jdemeyer @markshannon
> PEP 590: Use size_t for "number of arguments + flag"

- pep-0534.txt
Alas, we couldn't prioritize this enough for 3.8. It is still on the table, though.
cc @torsava @ncoghlan
> PEP 534: Postpone to 3.9

- pep-0544.txt
The example with `Concrete` and `Template` is supposed to highlight that adding properties to a protocol in the implementation of a method is not supported, and does not add to the required signature of the protocol.
However, this also has the problem of `Concrete` not being a `Template` anyway because it is missing that `method`.
> PEP 544: Remove additional error from error example

- pep-0591.rst
Reference implementation was linked incorrectly in the "References" section.
> PEP 0591: Fix a broken reference

- pep-0484.txt
[Link](https://www.python.org/dev/peps/pep-0484/#callable)
"Similarly, there is no support for specifying callback signatures with a variable number of **argument** of a specific type."
Changed to:
**arguments**
[Link](https://www.python.org/dev/peps/pep-0484/#the-typing-module)
"I/O **releated** types:"
Changed to:
**related**
[Link](https://www.python.org/dev/peps/pep-0484/#the-type-of-class-objects)
"... that's a subtype of ``C``, not a special form.  **IOW**, in the above example calling e.g. ``new_user(Union[BasicUser, ProUser])`` is ..."
Changed to:
**In other words**
I'm reasonably sure **IOW** is intended to mean **In other words** (i.e. [UrbanDictionary:IOW](https://www.urbandictionary.com/define.php?term=IOW) instead of one of [Wikipedia:IOW](https://en.wikipedia.org/wiki/IOW)) …
> PEP 484: Fixed typos, IOW, apply PEP8 inline comment space

- pep-0598.rst
Alternative to PEP 596 that aims to reduce feature delivery latency
by giving ourselves access to a new, less disruptive, feature
delivery vehicle, rather than by increasing the frequency with
which we deploy our existing disruptive feature delivery vehicle.
> PEP 598: Introducing minor feature releases

- pep-0598.rst
- use baseline feature release and incremental feature release
rather than major/minor feature release
- introduce a new "feature_complete" flag on sys.version_info
to allow the branch state to be inspected at runtime
- impose a runtime feature detection requirement on all features
added in incremental feature releases
> PEP 598: Adjust terminology and other updates

- pep-0394.txt
> PEP 394: Allow for more flexibility in handling /usr/bin/python

- pep-0581.rst
bpo tickets can be automatically closed by using special keyword.
Not sure how many core devs are aware of this. It would be great to document it in devguide.
See related issue: https://github.com/python/devguide/issues/502
> PEP 581: mention that bpo tickets can be automatically closed.

- pep-0001.txt
- pep-0012.rst
Closes #123 
I also went ahead and added myself as an author to PEP 12 since I seem to keep tweaking that PEP so I'm happy to share ownership/burden over it. 😄
> use a dual license of public domain or CC0-1.0-Universal

- pep-0513.txt
- pep-0571.rst
From https://github.com/pypa/manylinux/issues/305 : `libcrypt.so.1` was one of the whitelisted libraries that wheels could assume would always be on the host system. This appears to be no longer the case, as Fedora 30 has moved to `libcrypt.so.2`, and some wheels fail to load on that platform.
If I have understood correctly, `libcrypto.so.1` must therefore be removed from the whitelist. I'd like @njsmith or someone to confirm that I've got the right idea.
I'm using Fedora 30, and I've yet to have a wheel fail to load myself, so hopefully this means that not many wheels were linking it anyway, and the practical impact isn't too great.
> PEP 513 & 571: Remove libcrypt.so.1 from whitelist

- pep-0508.txt
Per #560, the current definition of `python_version` is not compatible with a 2+ digit major or minor version. There were no objections to changing the definition to more accurately reflect the semantic content intended to be conveyed (i.e. the major and minor version).
CC @finefoot
> PEP 508: Update definition of python_version

- pep-0566.rst
- pep-0599.rst
- pep-9999.rst
Discussion is here: https://discuss.python.org/t/the-next-manylinux-specification/
> PEP 599: manylinux2014 PEP

- pep-0598.rst
- explicitly discuss potential implications for CI and
deployment management follow a useful discussion
with Barry Warsaw
- propose locking down even provisional APIs once
a given release series is feature complete
- note that delay in adopting major feature releases
may prevent PEP 596 from having the desired
effect of reducing feature delivery latency
- rephrase the section about Python 3.10 vs 4.0
to make it clear that the PEP isn't *proposing*
releasing 4.0 after 3.9, just discussing the impact
the different choice of version number would have
on the proposal
- reference Anthony Sottile's "Python 3.10" compatibility
testing project
> PEP 598: CI implications, provisional APIs, other tweaks

- pep-0582.rst
Remove extra space prior to closing "``", which was causing the rest of the sentence to appear monospaced.
> PEP 582: Minor formatting fix.

- pep-0599.rst
* The vsyscall usage in glibc was removed in the 2.14 release, so this is not relevant for manylinux2014.
* Update PyPI support section to allow for blocking non-compliant uploads
> PEP 599: Updates

- pep-0598.rst
- several Scientific Python projects are working on a
common version support policy for their projects,
which we need to take into account when considering
changes to our release cadence
- reviewing that draft NEP highlighted several problems
with the way this PEP was using the "major" and "minor"
terms, so this takes a pass through that, replacing
inappropriate uses of "major" with "feature", and
and inapproriate uses of "minor" with "micro"
- I also went through and collected statistics on how many
changes we've been making in micro releases that
warranted version added/changed notes in the docs
> PEP 598: Fix terminology, reference support policy NEP

- pep-0569.rst
https://mail.python.org/archives/list/python-announce-list@python.org/thread/BCIHRB5N6AKPCBVO4TQYSYSPOBMV3GXL/
> PEP 569: Python 3.8.0b3 released

- pep-0600.rst
This is a major rewrite of the text, but there are minimal changes to
the actual technical details (in particular, there's some
clarification of the details of how it relates to previous manylinux
PEPs). Instead, it's mostly fleshing out the rationale and aligning
the text with the discussion on Discourse.
> PEP 600: Update text to align with discussion

- pep-0381.txt
- pep-0456.txt
- pep-0546.txt
- pep-0587.rst
- pep-3103.txt
> Fixed typos

- pep-0572.rst
- switch from the new `TargetScopeError` to a plain `SyntaxError`
as per referenced python-dev discussion
- clarify rationale for those extra SyntaxError cases (we don't
want current CPython implementation details to implicitly leak into
the "do what CPython does" de facto language specification)
- broaden one of the error cases to handle the fact that CPython's
symbol table analysis for a comprehension involves two different
scopes and hence makes it difficult to detect when the target of
a named expression in the iterable expression gets re-used as an
iteration variable in the comprehension
- note that even dead code affects the symbol analysis pass
> PEP 572: TargetScopeError->SyntaxError, other SyntaxError adjustments

- pep-0586.rst
PEP 586 was actually authored in March 2019, not March 2018 -- see the [commit log history](https://github.com/python/peps/commits/master/pep-0586.rst).
> PEP 586: Fix 'Created' date

- pep-0343.txt
I was reading this PEP and tried to click the link, but it was dead. A quick Google search for `raymond chen control flow macros` gave me the new link.
I have signed the Contributor License Agreement.
> PEP 343: Update link to Raymond Chen's blog post

- pep-0601.txt
- pep-9999.txt
This is a draft PEP to propose forbidding return/break/continue breaking out of a finally suite.
> PEP 601: Forbid return/break/continue breaking out of finally

- pep-0573.rst
The substantial change here is removing `PyType_offsets`. Dino is working on a better way to specify these, which will hopefully be straightforward enough to not need a PEP.
The public domain dedication is changed. I figure I don't need explicit permission from all co-authors, since y'all placed this in public domain :)
cc @Dormouse759
> PEP 573 updates

- pep-0001.txt
In today's (2019-09-17) Steering Council meeting, we agreed to relax the language around requiring a core developer to be a PEP sponsor.  This PR modifies the language to allow any person (core or otherwise) to become a PEP sponsor with the approval of the Steering Council.  Of course, if the PEP author is a core dev, it's still the case that a sponsor is not required.
> PEP 1: Update language on sponsorships

- pep-0551.rst
Complete broken sentence, based on content in https://github.com/python/peps/commit/cd795ec53c939e5b40808bb9d7a80c428c85dd52#diff-a370cb418156597b81cb01e582c6f518R438
> PEP-551: Complete missing end of sentence

- pep-0604.rst
syntax to write ``Union[X,Y]`` and ``Optional[X]`` easier.
> PEP 0604: Syntax to write ``Union[X,Y]`` and ``Optional[X]`` easier.

- pep-0008.txt
As per discussion on PEP 601: https://discuss.python.org/t/pep-601-forbid-return-break-continue-breaking-out-of-finally/2239/32
> PEP 8: Discourage use of return/break/continue in finally

- pep-0571.rst
The PEP was still referencing an old (beta?) Docker image. It was also
written in the plural, but there is only a single image (x86_64, no
i686).
This update was discussed in
https://github.com/pypa/manylinux/issues/179#issuecomment-487852362
but it's taken me until now to get permission to sign the CLA.
> PEP 571: Fix link to manylinux2010 Docker image

- pep-0458.txt
Facebook Research has now funded implementation of cryptographic signing of packages on PyPI. Per https://github.com/pypa/warehouse/issues/5247#issuecomment-535278176 this means that PEP 458 now moves out of Deferred status and into Draft status.
Since the PEP was created, the BDFL-Delegate for PyPI-related PEPs has shifted, and Donald Stufft is now the Delegate.
> PEP 458: Move to Draft status and update Delegate

- pep-0458.txt
Uses static last stable version tag (v0.11.1), instead of dynamic branch name (develop), when pointing to documents in the TUF repository. This makes them more prone to become outdated but less prone to 404.
Note, that the two referenced tuf publications are also available under more permanent, albeit paywalled DOIs:
[2] https://doi.org/10.1145/1866307.1866315
[13] https://doi.org/10.1145/1455770.1455841
> PEP 458: update dead or outdated references

- pep-0587.rst
PyConfig_InitPythonConfig() and PyConfig_InitIsolatedConfig() no
longer return PyStatus: they cannot fail anymore.
> PEP 587: PyConfig_InitPythonConfig() cannot fail anymore

- pep-0571.rst
`manylinux2010` is based on CentOS 6 which is bundled with `GCC 4.4` and corresponding `libgcc_s.so`. Current PEP says that its maximum version is `GCC_4.3.0` but this should be updated to `GCC_4.4.0` because 32-bit CentOS 6 has many symbols with `GCC_4.4.0` but 64-bit CentOS 6 doesn't. It seems that this constraints was made only with 64-bit CentOS 6.
From [libgcc-glibc.ver](https://github.com/gcc-mirror/gcc/blame/master/libgcc/config/i386/libgcc-glibc.ver), they put new symbols introduced with `GCC 4.3` in `GCC_4.4.0` only for 32 bits. As a result, those symbols are placed in different version tag depending on architecture.
Comment in the source says:
```
```
Without this change, application built on 32-bit CentOS 6 and linked with following functions cannot be manylinux2010-compliant …
> PEP 571: Update GCC_4.5.0

- pep-0598.rst
- pep-0605.rst
- pep-9999.rst
* proposes the regular publication of production-ready beta releases rather than making full X.Y.0 feature releases more common
* claims PEP 605 as the PEP number
* includes the withdrawal of PEP 598 in favour of this proposal
* originally drafted over in https://github.com/ncoghlan/peps/pull/4 with @zooba, @aeros167, and @h-vetinari
> PEP 605: A rolling feature release stream for CPython

- pep-0487.txt
Just something small I noticed while reading up on `__init_subclass__`.
> PEP 487: Remove extra underscore.

- pep-0599.rst
More information in [auditwheel discussion](https://github.com/pypa/auditwheel/pull/192/files#r332459037) of [manylinux2014 Pull Request](https://github.com/pypa/auditwheel/pull/192)
> PEP 599: Allow CXXABI_TM_1 symbol version

- pep-0600.rst
1. Note that the auditwheel project will maintain docs
2. Note that we'll update the old PEPs to note that they've been replaced
3. In compatibility logic, check for compatibility before checking for overrides
See: https://discuss.python.org/t/pep-600-future-manylinux-platform-tags-for-portable-linux-built-distributions/2414/4
> PEP 600: Small updates in response to Paul's feedback

- pep-0584.rst
The most significant changes here are that Steven and I have withdrawn the subtraction part of the proposal, and updated the pure-Python equivalent code to use `self.copy()`.
The rest of the changes are mostly background info, formatting, and summaries of the latest round of discussions. There will likely be at least one more draft before the PEP is finalized.
CC @Rosuav @stevendaprano
> PEP 584: Remove subtraction and add more background.

- pep-0606.rst
- pep-0607.rst
Review PEP providing shared background for PEPs 602 and 605, covering both
common problem statements, and key differences in the proposals to address
those problems.
Originally developed in https://github.com/ncoghlan/peps/pull/5 with @zooba and @ambv
> PEP 607: Shared background for release cadence change proposals

- pep-0605.rst
Also updates the NEP 29 section to cover the latest wording
of that proposal, and makes it clear that mere acceptance
of the PEP doesn't prevent us from ever changing the release
process again.
> PEP 605: Update for PEP 607 publication

- pep-0571.rst
> PEP 0571: compiler version matching x86_64 docker image

- pep-0013.rst
Change PEP 13 to make the Council Election use regular (multiwinner) approval voting, the same thing used for the PSF board elections, instead of restricting the number of votes to the number of seats in the Council.
> PEP 13: Change the Council Election to use Approval voting.

- pep-0345.txt
The [existing Project-URL section](https://www.python.org/dev/peps/pep-0345/#project-url-multiple-use) is a bit weak:
- Every other field in this PEP lists the field name in the example, this one was missing it
- I don't know what "_The label is a free text limited to 32 signs_" means.
- It's confusing, why you would use this field instead of using "Home-page"?
Description was improved in [PEP-0459](https://www.python.org/dev/peps/pep-0459/#project-urls) but that was withdrawn.
Likely the strange wording in this section was due to historical reasons: in https://github.com/python/peps/commit/0ed1ae32e9f4152f40294bfc6ba79998f29e1275 three separate fields (`Repository-URL`, `Repository-Browser-URL`, `Bug-Tracker-URL`) were consolidated into `Project-URL` (multiple use).
I've tried to update …
> PEP 345: Improve example for the Project-URL field and clarify purpose

- pep-0541.txt
PEP 541 details the rules for transferring ownership of abandoned PyPI projects whose owners cannot be reached. Understandably, this is a common starting point for people who want to claim such projects.
This PR adds explicit information on how to go about getting an abandoned name. In particular, it points people to the Warehouse issues as the place to request a transfer - this [seems to be the de-facto standard approach](https://github.com/pypa/warehouse/search?q=PEP+541&unscoped_q=PEP+541&type=Issues). It also tries to emphasise that this should be a last resort, to hopefully prevent a flood of requests.
I'm happy to change this if a Github issue is not the preferred way to request an ownership transfer. Arguably sending an email doesn't tie it to having a Github account, but on the …
> PEP 541: Add section on how to request a name transfer

- pep-0484.txt
Following discussion on the typing-sig mailing list. cc @srittau @gvanrossum
> PEP 484: Change the consent requirement to be informational

- pep-0604.rst
Various copyedits and clarifications.
@pprados 
Additional questions and comments:
* AIUI `isinstance(5, int|str)` is an intended part of the proposal, but it's not really explored. This is highly significant and needs a bit more elaboration: what exactly will be returned, and will that object (eg `Union`) now be available as a builtin? Will it be the same as `typing.Union` and if so, will `typing.Union` now just be the same as the builtin? (If so, typing.py could just say `Union = Union` to import it for backward compatibility.)
* If it's of value, Pike also has union types using this syntax. See for instance http://pike.lysator.liu.se/docs/man/chapter_3.html#3.5 . Any other languages do this? Can there be a section in the PEP for Prior Art?
* There's a bit of an orphanned bullet point. …
> PEP 0604 copyediting

- pep-3108.txt
I noticed the sentence "Python 3.0 has presents a chance to...", so I removed "has" so that the sentence reads "Python 3.0 presents a chance to..."
> PEP 3108: Fixed small grammar typo, removed "has"

- pep-0593.rst
Note that the discussion happened here:
https://mail.python.org/archives/list/typing-sig@python.org/thread/CZ7N3M3PGKHUY63RWWSPTICVOAVYI73D/
> PEP 593: Accept, and update post history

- pep-0554.rst
Fixes #1229; CLA signed.
In PEP 554, "Passing objects via marshal" section example code, `create_fifo` should be `create_channel`.
@ericsnowcurrently
> PEP 554: Fix minor typo in marshal example code (#1229)

- pep-0593.rst
@ilevkivskyi Maybe we can even mark this Final, since it's been implemented in the 3.7 stdlib?
> PEP 593: Set Python-Version: 3.9

- pep-9999.rst
As discussed in https://discuss.python.org/t/draft-pep-recording-the-origin-of-distributions-installed-from-direct-url-references/1535/25
cc/ @cjerdonek
> Recording the Direct URL Origin of installed distributions

- pep-0579.rst
I approve PEP 579, with an explicit note that acceptance of an Informational PEP doesn't really mean that much. PEP 590 is the important one.
cc @jdemeyer
> PEP 579: Accept (with a reminder on informational PEPs)

- pep-0584.rst
There's no need to put "DRAFT" at the top of the PEP, that's already in the headers.
There are more formatting issues with this PEP that as a PEP editor
bother me, but IMO the authors should be made to do those, after
studying PEP 12.
I'll just merge this once the tests pass; I'll post a message with a content critique to python-ideas shortly.
> PEP 584: Add post-history and remove draft note

- pep-0553.rst
Found a missing `return None` in the implementation Python code while implementing the PEP in PyPy.
> PEP 553: Add missing return None in except clause to pseudo-code

- pep-0611.rst
- pep-1000000.rst
Draft version of PEP 611, "The one million limit".
> PEP 611: 'The one million limit'

- pep-0508.txt
Without this, running the test code and grammar result in an error like:
```
A -> ('A', [], [], None)
A.B-C_D -> ('A.B-C_D', [], [], None)
aa -> ('aa', [], [], None)
name -> ('name', [], [], None)
Traceback (most recent call last):
File "test.py", line 164, in <module>
parsed = compiled(test).specification()
File "/tmp/user/1000/tmp.NdEyR4kt1E/env/lib/python3.8/site-packages/parsley.py", line 98, in invokeRule
raise err
ometa.runtime.ParseError:
name<=1name>=3
^
Parse error at line 1, column 12: expected EOF. trail: [quoted_marker]
```
> PEP 508: Add missing comma to grammar test code

- pep-0611.rst
Ran the rest of PEP 611 through mechanical spellchecking (set to UK English), results applied.
In addition (in a separate commit), inserted "version" in two sections before a CPython version number, the first time it's mentioned without being identified as such. But I can drop (or separate out) that change if requested.
> PEP 611: Spellchecking, minor copyedit

- pep-0456.txt
The conditional statement likely meant "if", not "is"
> PEP-456: fix typo

- pep-0612.rst
This is a pull request for a new PEP proposal for adding a new category of type variables to the PEP 484 typing ecosystem -- ParameterSpecifications.
Some procedural notes:
1. Although this PEP was not discussed in python-ideas, it was extensively discussed by the attendees of the last Python typing summit, where it reached general consensus, on everything except for the name for the feature itself, where there was some disagreement.  I anticipate some discussion on this front in typing-sig.
2. This has been implemented into Pyre, missing only handling for user-defined generic classes.
3. I discussed this submission ahead of time with @ilevkivskyi, a core contributor, could I add you as a sponsor?
4. It looks like 612 is the next free number, but I may not be looking in all of the …
> PEP 612: Parameter Specification Variables

- pep-0567.rst
I use the sketched Python code in the PyPy's 3.7 implementation of contextvars and noticed a typo in ContextVar.reset: the local name data does not exist. I think this is the correct way to express it (at least it passes tests for us). /cc @1st1
> PEP 567: typo in pseudocode of ContextVar.reset

- pep-0558.rst
When updating the PEP to specify independent snapshots for locals()
at function scope, I missed this reference to the old semantics
that returned a direct reference to the dynamic internal snapshot.
> PEP 558: Fix mention of old locals() semantics

- pep-0573.rst
* report TypeError rather than SystemError when bad types are passed
to new APIs
* add PyType_FromModuleAndSpec to the list of new functions
* wrap text at 80 columns
* add C API docs links for thread-local storage and context variables
* note in abstract that only the initial state lookup from slots is
inherently slow, with subsequent lookups being amenable to caching
* other minor wording tweaks
> PEP 573: SystemError->TypeError and misc copy-edits

- pep-0458.txt
Per conversation in
https://discuss.python.org/t/pep-458-surviving-a-compromise-of-pypi/2648/21
about problems with current title, and and per former PEP coauthor
Vladimir Diaz in
https://mail.python.org/archives/list/distutils-sig@python.org/thread/TXM2O34TMSHH5U6WA2IF7XKO5J3G5NQQ/#3QLN4KECII6KULKYXS7U4CVBEPGK4B6S
> PEP 458: Change title to clarify intent

- pep-0458.txt
Updated the Discussions-To header to reflect the current conversation happening at: https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648
> PEP 458: Update Discussions-To header

- pep-0458.txt
*Context:*
Addresses a review comment from @dstufft on https://github.com/python/peps/pull/1203#discussion_r346403324, and follows a discussion in https://github.com/secure-systems-lab/peps/issues/68, where @brainwane proposed more detailed workflows. My reasoning for keeping it brief was that I was under the impression that client and uploader workflows are not actually in the scope of PEP 458. If desired I am happy to add additional details.
*Changes:*
Add subsection to section "Managing Future Changes to the Update Process" that explains how to transition from an old (e.g. because it has become weak) to a new (e.g. stronger) hashing algorithm without disrupting client workflows.
> PEP 458: add hash algorithm transition plan

- pep-0573.rst
- Remove the MRO walker, PyType_DefiningTypeFromSlotFunc, as it was
found it can give wrong results when a type's special methods are
changed (which can be done from Python code).
Solving the issue is deferred to a future PEP (and/or perhaps a
private CPython function).
- Split public C-API from CPython implementation details. It turns out
that alternate C-API implementations have grown more important
since 2016, if only for experimenting with possible optimizations.
- Add potentially confusing terms "Defining Class" and "C-API" to the
terminology section.
- Mention that ht_module i not inherited by subclasses.
- Remove modules to be ported initially: zipimport (since rewritten
in Python), _io and _cvs (need module state from slot methods).
cc @Dormouse759
> PEP 573: Remove DefiningTypeFromSlotFunc, split public/private API

- pep-0613.rst
Note: Python CLA has been signed but is pending the check at https://check-python-cla.herokuapp.com/
> PEP 613: Explicit Type Aliases

- pep-0458.txt
Clarify that this PEP does not affect GPG support per the discussion on [discourse](https://discuss.python.org/t/pep-458-secure-pypi-downloads-with-package-signing/2648/66).
> PEP 458: Add non-goals section

- pep-0458.txt
Clarify that json metadata can be optionally compressed on the wire to reduce the metadata size.
cc @ncoghlan @trishankatdatadog
> PEP 458: Allow compression of json metadata

- pep-0613.rst
Incorporating some feedback: https://github.com/python/peps/pull/1278
as well as closing the open issue listed previously.
> Updates to PEP 613 Explicit Type Aliases

- pep-0458.txt
* PEP 458: use "OpenPGP" instead of "GPG".  The signature format is OpenPGP.  Other
OpenPGP implementations exist aside from gpg, the OpenPGP tool from the GnuPG project.
> PEP 458: use "OpenPGP" instead of "GPG"

- pep-0458.txt
Made minor edits including:
* letting the PSF appoint offline key holders
* moving content from abstract to motivation to make the abstract more succinct
* updating the threat model
* resolving some minor inconsistencies
> PEP 458: Add clarification

- pep-0612.rst
Identifier must match TypeVar name
> PEP 612: Fixed bad TypeVar definition

- pep-3132.txt
With two elements, the starred middle expression just is an empty list.
> PEP 3132: Fix example description

- pep-0376.txt
Currently, part of PEP 376 renders like this:
* field delimiter : *,*
* quoting char : *"*.
* line terminator : `os.linesep` (so `\r\n` or `\n`)
It is quite easy to mix up the actual character with the adjoining punctuation. Marking the code as code should help a bit. The first commit here does that.
The PEP uses Markdown-style syntax for code (single rather than double backticks) extensively; in all the cases *code* makes more sense than *italics*. The second commit all the other cases; these probably don't help readability that much. I'll be happy to remove that commit; I'm not sure what the policy is on touching up 10-year old PEPs (though it is still an [active standard](https://packaging.python.org/specifications/recording-installed-packages/)).
> Pep 376: Use ReST syntax for code, rather than Markdown syntax

- pep-0585.rst
- Rename `__parameters__` to `__args__`, for typing.py compatibility
- Genericize, re.{Pattern,Match} ~and io.IO~
- list != list[int], but list[int] == list[int] (and list[str] != list[int])
- Add a lazy `__parameters__` that contains the unique type vars in `__args__` (also for typing.py compatibility)
- make dict[str][str] fail, but dict[T, str][int] return dict[int, str]
- expose proxy type as types.GenericAlias
- pickle and copy should work
- link to implementation
> PEP 585: updates green-lighted by Lukasz

- pep-0558.rst
Updates the locals() C API proposal as per the discussion at https://discuss.python.org/t/pep-558-defined-semantics-for-locals/2936/19
This update also avoids the term "snapshot" in the proposed C API and reference documentation, as we don't use that term elsewhere in the C API and documentation, and instead refer to shallow copies instead.
> PEP 558: Update proposed C API

- pep-0581.rst
In the "Downsides of GitHub" section, the references for "backing up GitHub" and "increasing triage effort" were switched. Now they are correct.
On the PEPs website [here](https://www.python.org/dev/peps/pep-0581/) these are 15 and 16.
> PEP 581: Fix switched reference links

- pep-0585.rst
The rationale is described in the change itself.
> PEP 585: Disallow isinstance([1, 2], list[str])

- pep-0458.txt
James Bennett pointed out that "package signing" is widely misunderstood
as referring specifically to end-to-end signing with individual
publisher keys, rather than to metdata signing in general.
This updates the title and abstract to instead use the term "signed
repository metadata", and also updates a few other sections that
still gave the impression that implementing PEP 458 would be
enough to give the full end-to-end signing support that is actually
covered in PEP 480.
> PEP 458: Use 'signed repository metadata' terminology

- pep-0483.txt
- pep-0484.txt
- pep-0585.rst
> PEP 483, 484, 585: Use parameterized instead of parametrized

- pep-0594.rst
If we're deprecating and removing `uu` we should do the same to the codec of the same name.
> PEP 594: Mention uu_codec

- pep-0615.rst
This is an initial draft of a PEP that I have provisionally assigned PEP 615 (though if someone gets to that number before we merge this, I will take the next available number).
This proposes adding a ``zoneinfo`` module to the standard library, and covers some of the semantics of the ``ZoneInfo`` class and the data sources.
This document is not entirely finished, but I wanted to get it posted in the hopes of getting some initial review comments.
One thing to note: I have mostly tried to use "semantic newlines" here, so that changes to wordings or concepts would give somewhat clean diffs. If that's not the standard style or if it's hard to review, I can switch to another way to do newlines.
Things to do:
~As you can see, with the exception of the explicitly-mentioned WIP section (Windows …
> PEP 615: Add PEP proposing zoneinfo module

- pep-0585.rst
A brief summary of @ncoghlan's explanation on python-dev.
> PEP 585: Explain the choice of GenericAlias over GenericType

- pep-0615.rst
The biggest component of this change is to switch Windows support from "Rejected ideas" to "Open ideas", based on private e-mail correspondence with Matt Johnson-Pint (@mj1856), where he pointed me at the existence of the ICU API.
Additionally, I have addressed feedback from [Paul Eggert](https://mm.icann.org/pipermail/tz/2020-February/028843.html) on the IANA time zone mailing list, in particular clarifying the behavior of the library in the event that the data is updated during an interpreter run.
I have also addressed feedback from Stuart Bishop (@stub42), Guido van Rossum and Alexander Belopolsky (@abalkin) on the behavior of `ZoneInfo` pickles.
I have also partially addressed the feedback from Petr Viktorin [on the discourse …
> PEP 615: Windows support, address first round of feedback

- pep-0458.txt
In secure-systems-lab/peps#73 Figure 2 became Figure 1. This change fixes a missed reference update. It also removes a stray "and".
Note: The live [PEP 458](https://www.python.org/dev/peps/pep-0458/) page still references the [old `pep-0458-1.png`](https://s3.dualstack.us-east-2.amazonaws.com/pythondotorg-assets/media/dev/peps/pep-0458/pep-0458-1.png), although this repo has the  [correct `pep-0458-1.png`](https://github.com/python/peps/blob/master/pep-0458-1.png).  This is due to an issue in the pep generation script, for which I have provided a fix in https://github.com/python/pythondotorg/pull/1556. It would be nice to integrate the fix. Or, until then, just replace the file on the server.
> PEP 458: Fix figure reference and typo

- pep-0534.txt
None of us are currently working on this PEP, so remove the Python-Version target, mark it as Deferred, and explain the key work that remains to be done.
> PEP 534: Mark as Deferred

- pep-0499.txt
This is pretty close to acceptance, but requires some additional work as described in https://bugs.python.org/issue36375#msg356499.
If that work is expected to be done in the next few weeks, we can reject this PR, and update the PEP instead. Otherwise, let's defer until 3.10.
> PEP 499: Mark as deferred until 3.10

- pep-3154.txt
Hi
possible typo in pep 3154. GLOBAL_STACK -> STACK_GLOBAL ?
> PEP 3154: fix typo

- pep-0616.rst
* Fix handling of empty string in tuple of prefixes
* Fix code snippets for repeated removal
* Remove trailing whitespace
> PEP 616: Fix behavior of code snippets

- pep-0483.txt
This shorthand is no longer recommended - see #689 which changed it in PEP 484.
> PEP 483: Remove reference to implicitly Optional parameters

- pep-0615.rst
After some additional personal e-mail discussions, I have come to the conclusion that supporting TZif via ICU is not going to be as seamless as I had hoped, and it may not even be possible to achieve the same results that we can get if we have access to the raw data, so I'm going to move it to the "rejected" pile, and hopefully once PEP 615 is done we can start work on getting `tzdata` shipped automatically with CPython.
I also haven't seen much push-back on the `PYTHONTZPATH` environment variable as we have it now, and I realized that by restricting the valid values to *absolute* paths (which seems like it would be a good idea anyway), we can buy ourselves the option to add a "special value" later on, so there's really no longer a compelling reason to leave this up in the air.
@zooba …
> PEP 615: Move ICU support and alternate paths to rejected ideas

- pep-0615.rst
No one has really commented on the section about using the datetime module, so I think we can go ahead and move that to "Rejected ideas".
I've also clarified the rationale for not allowing the `ZoneInfo` object's behavior to change.
> PEP 615: Resolve "using datetime" and add rationale to updates section

- pep-0008.txt
Unifying "Yes/No" flags format in PEP 8 which described in #1341
> PEP 8: Extract Yes/No flags from code blocks

- pep-0384.txt
https://bugs.python.org/issue15140
In PEP 384, the PyType_Spec struct has  "const char *doc" and "unsigned int flags" these is not present in the implementation (Include/object.h).
> PEP 384: Update PyType_Spec struct per bpo-15140

- pep-0617.rst
Fix minor typo.
Fix what appears to be meant as a numbered list that was reflowed incorrectly.
Clarify a slightly awkward sentence about the EXTRA C macro.
> Fix typos and other minor edits in PEP 617.

- pep-0615.rst
This is updates to the PEP in response to @warsaw's comments in https://github.com/python/steering-council/issues/22
@warsaw: Sorry I said I would do these last night but I didn't end up having time. Let me know if you'd like to see any changes here. I went with a footnote for the "first-party" term, since it appears in several places.
I am also not married to the name `zoneinfo.ZoneInfoNotFoundError`. `pytz` calls it `UnknownTimezone` (but their constructor is `pytz.timezone`), and `dateutil` returns `None` instead of raising an exception.
I will update the reference implementation soon-ish - it is falling slightly out of spec from this stuff because I still need to do a bit of clean-up on the C extension, and I'd like to merge that before I do stuff like changing names around and adding …
> PEP 615: Updates in response to Steering Council feedback

- pep-0617.rst
Numerous small changes to improve readability of the LL(1) background: idiomatic usage improved, sentences split, clearer expression of certain ideas. Emphasis that the LL(1) constraint obscures the meaning of the grammar.
(First raised as issue #1362.)
> PEP 617: Clean-up of LL(1) section

- pep-0617.rst
Also another minor correction.
CC: @gvanrossum @pablogsal 
Closes we-like-parsers/cpython#76.
> PEP 617: Change migration plan - default to pegen in 3.9a6

- pep-0617.rst
Following @brettcannon's suggestion on python/steering-council#24, I moved the meta grammar after all the different operators are explained.
CC: @gvanrossum @pablogsal
> PEP 617: Move metagrammar after explanation of operators

- pep-0617.rst
The shown text was incorrect. The bpo link pointed to the intended bug. ... Fixed the text.
> PEP 617: Fix typo

- pep-0429.txt
Mark Python 3.4's PEP as Final, like all the other EOL Pythons' PEPs.
~Also fix a small typo in Python 2.7's PEP 373. (Please me know if this shouldn't be in this same PR.)~
--> Removed, was fixed in https://github.com/python/peps/pull/1375.
> PEP 429: Python 3.4 is EOL, mark PEP status as final

- pep-0592.rst
Per https://discuss.python.org/t/pep-592-support-for-yanked-files-in-the-simple-repository-api/1629/34 the implementation is now finalized.
cc @ncoghlan @dstufft @di
> PEP 592: Change status to Final

- pep-0563.rst
The Language Summit discussion suggests this should be flipped either in Python 3.9 or in Python 3.10. An informal poll ran at the event with 33 votes has shown that 65% would like to see the change in 3.9, 29% in 3.10, 3% in 4.0, and 3% "never" :-)
This PR is open to gather feedback from those concerned.
Side note: The previously documented policy of raising deprecation warnings if there's any annotation was unrealistic. It would raise huge numbers of warnings, a lot of them in third-party code that the receiver of the warning can do nothing about. That part we need to remove from the document anyway.
> Make `from __future__ import annotations` the default in Python 3.10

- pep-0563.rst
Follow on from https://github.com/python/peps/pull/1371.
Ping @ambv.
> PEP 563: Make `from __future__ import annotations` the default in Python 3.10

- pep-0619.rst
For PEP 619, correct the year for 3.10.0 final, so that the date reads 2021-10-04 (was 2020-10-04).
> PEP 619: fix year for 3.10.0 final

- pep-0318.txt
It should be wiki.python.org instead of www.python.org
Closes #1426
> PEP 318: Fix the url to Python Decorators Wiki

- pep-0609.rst
Change PyPA governance procedures to reflect moving under the PSF CoC.
Per conversation in https://discuss.python.org/t/move-to-the-psf-code-of-conduct/3876/ and https://discuss.python.org/t/pep-609-pypa-governance/2619/23 .
cc @di 
> PEP 609: Move PyPA to PSF Code of Conduct

- pep-0573.rst
API for module state access from C extension methods has been implemented in Python 3.9.
> PEP 573: Mark as final

- pep-0622.rst
PEP 622: Summary of the changes made
Change `patten` to `pattern`
> pep-0622.rst: fix typo

- pep-0543.rst
- pep-0595.rst
Updates based on the Steering Council's PEP Parade and replies with the PEP authors.
> Withdraw PEP 543 and PEP 595

- pep-0612.rst
This PR updates PEP 612  following discussions on [typing-sig](https://mail.python.org/archives/list/typing-sig@python.org/thread/UDHSH4EVVIDKNLRX2YGCIUCBGZ5ALRKC)
These updates include:
* `ParameterSpecification` is abbreviated to `ParamSpec`
* finite-length parameter modification via `typing.type_variable_operators.Concatenate` is integrated throughout the PEP
* the `ParametersOf` counterproposal is discussed
* a proposed but deferred solution for modifying named parameters is discussed
* the prose has been edited for clarity
* variable names have been shortened to make the code examples more compact
> PEP 612: Updates from typing-sig discussions

- pep-0622.rst
Deliberately omitting the mini-grammar on 139.
> PEP 622: Update Appendix A Grammar

- pep-0008.txt
Instead of requiring that comments be written in Strunk & White Standard English, require instead that English-language comments be clear and easily understandable by other English speakers. This accomplishes the same goal without alienating or putting up barriers for people (especially people of color) whose native dialect of English is not Standard English. This change is a simple way to correct that while maintaining the original intent of the requirement. This change also makes the requirement more clear to people who are not familiar with Strunk & White, since for programmers, the main relevant aspect of that standard is "be clear and concise;" simply saying that instead of referencing Strunk & White communicates this more effectively.
> PEP 8: Change requirement to adhere to Standard English

- pep-0622.rst
The well-known languages with bound-once matching are Erlang and Prolog.
[Prolog is matching patterns with unifications](http://www.deransart.fr/prolog/unification.html), hence this technique is natural to achieve.
[Erlang is using scope to classify if variable is to be bound or loaded](https://erlang.org/doc/reference_manual/expressions.html#variables), this is closer to PEP 622.
> PEP 622: Fix wrong statements of Haskell

- pep-0622.rst
It should never raise if an attribute is missing.
Also remove one last mention of the exception for a single positional argument (since we no longer have this exception).
See https://github.com/gvanrossum/patma/issues/111#issuecomment-650874268
> PEP 622: Update definition of __match__

- pep-0622.rst
Also, document the remaining error-checking behavior.
> PEP 622: Drop ImpossibleMatchError

- pep-0622.rst
Also make the section headings describing various types of pattern plural, e.g. "Capture patterns".
See https://github.com/gvanrossum/patma/issues/112
> PEP 622: Rename name pattern to capture pattern

- pep-0508.txt
The definition of python_version was updated in #1123.
However, two closing parentheses are missing:
https://github.com/python/peps/blob/47fa1fb501121f6c8956493b28b30f4300fbd1df/pep-0508.txt#L280
https://github.com/python/peps/blob/47fa1fb501121f6c8956493b28b30f4300fbd1df/pep-0508.txt#L537
Note: It is not necessary to change the line 519 because a closing parenthesis exists.
> PEP 508: Add missing parentheses

- pep-0622.rst
This required more finagling of the text than the previous rename.
> PEP 622: Rename 'named sub-pattern' to 'walrus pattern'

- pep-0622.rst
The section that explains the decision to defer an extended
custom matching protocol has been transformed into a section
that defers custom matching altogether.
> PEP 622: Re-wrote deferred ideas section

- pep-0622.rst
Just a rough draft to see what this would look like (I didn't bother with the rejected or deferred ideas sections).
I'll note that these changes naturally lent themselves to placing increased emphasis on `__match_args__`, which I think is good.
> PEP 622: Drop __match__ from the spec

- pep-0622.rst
Much of this was cribbed from https://github.com/gvanrossum/patma/issues/93
> PEP 622: Write up why we reject alternative spellings of OR patterns

- pep-0622.rst
This describes more explicitly how exceptions are handled during pattern matching, addressing gvanrossum/patma#111
> PEP 622: Add exception semantics

- pep-0622.rst
This addresses issues discussed in gvanrossum/patma#110 about clarity of names bound when a failed pattern has succesful partial matches
> PEP 622: make the binding semantics explicit

- pep-0622.rst
It claimed to start with 1, and maybe proceed with 2.  The example currently starts with 0, and maybe proceeds with 1, maybe followed by other possibilities.
> PEP 622: sync explanation with example; case 0 is now first.

- pep-0622.rst
Note this is not just a simple search and replace; there are places where the word 'target' refers to an assignment target; I have not changed those.
> PEP 622: Change 'target' to 'subject'.

- pep-0622.rst
This addresses some concerns about possible methods being called by the `match` statement.
> PEP622: Be more explicit about side-effects

- pep-0622.rst
An initial section to the syntax and semantics, showing the "menu" of available patterns.
Added some "simplified syntax" to each pattern class
Minor fixes + typos
> PEP 622: Include overview to different patterns and summarised syntax

- pep-0625.rst
This PEP describes a standard naming scheme for a Source Distribution, also known as an *sdist*. This scheme distinguishes an sdist from an arbitrary archive file containing source code of Python packages, and can be used to communicate information about the distribution to packaging tools.
> Draft PEP: File name of a Source Distribution

- pep-0596.rst
@ambv, is 3.9.0b5 still expected July 20, or is that pushed back now? How about the rest of the releases?
> PEP 596: 3.9.0b4 was published last Friday

- pep-0008.txt
Turn ``Tkinter`` to ``tkinter``. See issue #1520 .
> Convert Python 2 example in PEP 8 to Python 3

- pep-0612.rst
* Made indentation consistent in code snippets
* removed extraneous backslash in grammar
* tiny bit more detail in a confusing snippet
> PEP 612: Polishing up

- pep-0622.rst
The original requires `len(value) > 1`, not `len(value) >= 1`.
> PEP 622: Fix example

- pep-0624.rst
New section describes why this PEP doesn't deprecate
`PyUnicode_Decode***()` APIs.
> PEP 624: Add rejected idea.

- pep-0627.rst
This documents my proposed update to "Recording installed distributions", moving from [PEP 376](https://www.python.org/dev/peps/pep-0376/) to a specification under PyPA.
See also:
* the [Discourse thread](https://discuss.python.org/t/pep-627/4126) for discussion;
* PyPA pull request: (https://github.com/pypa/packaging.python.org/pull/756)
* [The PEP](https://github.com/encukou/peps/blob/pep-0627/pep-0627.rst) rendered by GitHub
* [Proposed specification](https://github.com/encukou/packaging.python.org/blob/pep-627-recording-installed-projects/source/specifications/recording-installed-packages.rst) rendered by GitHub
> PEP 627: Recording installed projects

- pep-0629.rst
* Fixes the wording to actually say what was meant with regards to compatibility on minor versions.
* Restructure compatibility section to be easier to read.
* Add myself as BDFL-Delegate
* I'm the default delegate for PyPI PEPs, and this PEP should be uncontroversial, so I believe this should be fine. If anyone has concerns Paul Moore has volunteered to act as delegate in my place.
> PEP 629: Fix and clarify wording, add BDFL-Delegate header

- pep-0387.txt
Reviewing PEP 387 for SC pronouncement, I found one typo.  I also suggest including text for APIs explicitly documented as **provisional**.
> Suggested changes for PEP 387

- .travis.yml
Fork CI builds fail on the deploy step, because they (correctly) don't have the deploy credentials.
For example, failing fork build:
* https://travis-ci.org/github/hugovk/peps/jobs/711542881
Instead, only do the deploy for this upstream `python/peps` repo.
For example, passing fork build:
* https://travis-ci.org/github/hugovk/peps/builds/711552315
This will encourage people to make sure tests pass on branches, and less likely to submit a failing PR.
* https://docs.travis-ci.com/user/deployment#conditional-releases-with-on
> CI: Only deploy for upstream to prevent forks failing

- pep-0001.txt
See [discussion on Discourse](https://discuss.python.org/t/pep-editors-are-you-still-around/4727/4?u=encukou).
This PR does a bit more than just replace the mailing list with the GitHub group: I meant to be closer to the current practice. Please amend and update this however you see fit.
- `peps@python.org` is replaced by mentioning @python/pep-editors
- Developers with write access are expected to handle their PRs
themselves, and may mention @python/pep-editors if needed.
This corresponds to the current situation (and means less
work/responsibility for PEP editors, without a real downside).
- Taking ownership of a PEP is done through GitHub rather than e-mail
- A note about core devs managing their own PRs is repeated in
"PEP Editor Responsibilities & Workflow": people might look there …
> PEP 1: Remove mentions of peps@python.org, update the process

- pep-0627.rst
As pip now implements REQUESTED, the main reason to remove the file is gone,
so I'm adding it back as it is in PEP 376.
Possibly fixing the semantics is left to another PEP.
> PEP 627: Bring back the REQUESTED file

- pep-0596.rst
- pep-0619.rst
Resolves #1551 
In response to @hugovk's [comment](https://github.com/python/peps/issues/1551#issuecomment-668985256) I have gone for the following wording:
> Subsequent bugfix releases every two months.
which avoids the ambiguity of "bi-monthly".
> PEP 596 and PEP 619: Correct bugfix release cadence

- pep-0012.rst
- pep-0548.rst
- pep-0554.rst
- pep-0565.rst
- pep-0572.rst
- pep-0573.rst
- pep-0575.rst
- pep-0588.rst
- pep-0591.rst
- pep-0595.rst
- pep-0605.rst
- pep-0610.rst
- pep-0613.rst
- pep-0621.rst
- pep-0622.rst
Update:
* PEP 12
* PEP 548
* PEP 554
* PEP 565
* PEP 572
* PEP 573
* PEP 575
* PEP 588
* PEP 591
* PEP 595
* PEP 605
* PEP 610
* PEP 613
* PEP 621
* PEP 622
In Markdown, single backticks are for inline code: `for_example_like_this`
In reStructuredText, single backticks are for "interpreted text" and "domain- or application-dependent" (see table below).
* On https://www.python.org/dev/peps/ it's rendered as _italics_.
* For example: https://www.python.org/dev/peps/pep-0548/#semantics
* Most of these should use double backticks for `inline_code`
* Some have a misplaced `_` and are meant to be hypertext references
* I don't think any of these were meant to be italics, but if so let's use single asterisks
Ref:
* https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup
I'll …
> Fix RST backticks

- pep-0626.rst
> PEP 626:Guarantee stability of line table during release and define API for out-of-process tools.

- pep-0606.rst
Fix \`\` in section "Cleaning up Python and DeprecationWarning" (L136).
> PEP 606: Fix incorrect backticks

- pep-0445.txt
- pep-0467.txt
- pep-0548.rst
- pep-0621.rst
Like https://github.com/python/peps/pull/1559, for:
* PEP 445
* PEP 467
* PEP 548
* PEP 621
Found with:
```console
$ git grep "[A-Za-z0-9]\`\`[A-Za-z0-9]"
pep-0445.txt:``PyMem_Realloc()`` indirectly call``PyObject_Malloc()`` and
pep-0467.txt:This PEP proposes that ``bytes`` and ``bytearray``gain an optimised
pep-0548.rst:Reading this we first see the``break``, which obviously applies to
pep-0621.rst:for using``long_description`` and a corresponding
```
> Fix incorrect backticks

- pep-0627.rst
See [discussion on Discourse](https://discuss.python.org/t/pep-627-updating-pep-376-making-record-optional-in-installed-dist-info/4126/30?u=encukou)
> PEP 627:  Remove REQUESTED from the spec 

- pep-0630.rst
- pep-9999.rst
See the [capi-sig discussion](https://mail.python.org/archives/list/capi-sig@python.org/thread/6CGIIZVMJRYHWZDJLNWCLPSYYAVRRVCC/).
@python/pep-editors, I'd appreciate your opinion on this “current state+HOWTO” Informational PEP.
PEP 1 seems written with Standards Track PEPs in mind, so I skipped on some advice from it.
On the `XXX` notes: I'd like to fix those after this becomes a PEP, so I can more easily refer to this document in discussions about a good place for the file.
> PEP 630: Isolating Extension Modules

- pep-0622.rst
I made a few changes to Carol's text, in particular I made the bulleted lists more consistent and switched some commas around. I also removed the ToC that Carol included at the end of the Abstract -- the PEP formatting tools already create a ToC and Carol's formatting was a little off.
Note that a lot of Carol's work (but not all) was simply splitting long, dense paragraphs into bullet points while leaving all the words of the original, in the same order.
Finally, Carol left two TODOs in her text:
- After the initial paragraph of the Abstract she added a note saying "Why pattern matching". Do we want to say a thing about it here?
- At the start of "Matching process" she added a note labeled **Reword** which I left as a comment, suggesting there's more to be done to this section.
CC: …
> PEP 622: Proposed rewrite of Abstract and Overview (mostly) by @willingc

- pep-0627.rst
Paul Moore accepted this PEP on [Discourse](https://discuss.python.org/t/pep-627/4126/42).
This should ideally be merged immediately after [the PyPA spec PR](https://github.com/pypa/packaging.python.org/pull/756).
> PEP 627: Mark as Accepted

- pep-0615.rst
It repeatedly refers to a ZoneInfo object as a "file", confusing it with either the file it was constructed from, or the IO object representing the file.
> PEP 615: consistent terminology

- pep-0631.rst
There are two separate commits that make two changes:
1. Replace `sorted(..., key=lambda d: d.lower())` with `sorted(..., key=str.casefold)`: I'm not sure why these things need to be sorted in a case-insensitive way (we can always just drop the `sorted` entirely if it's not necessary), but I think `str.casefold` is the right logical operation to perform even if they aren't allowed to contain non-ASCII characters at the moment.
2. Used f-strings and take advantage of the fact that in Python 3.6+, dictionaries are already ordered (though again I'm not sure why we need it to be ordered in the first place).
I think the f-strings in particular make this much easier to read at the cost of wide compatibility. Implementations that want wider compatibility can always backport and use the more …
> PEP 631: Refactor reference implementation

- pep-0345.txt
2 improvements:
1. According to document in both [PEP 314](https://www.python.org/dev/peps/pep-0314/#author-optional) and [PEP 345](https://www.python.org/dev/peps/pep-0345/#author-optional), there's no difference in **Author**, but a change in **Author-email** to make it optional. This change also follows the [11 years old logic in Distutils](https://github.com/python/cpython/blame/9f9dac0a4e58d5c72aa3b644701cb155c009cb2c/Lib/distutils/command/check.py#L100-L103).
2. To make the changed fields clear as **Deprecated fields**, I append the change description in bracket.
> PEP 345: correct the Changed fields in "Summary of Differences From PEP 314"

- pep-0345.txt
Neither pip nor setuptools or warehouse are expecting them and since
Requires-Python disallows multiple use, environment markers would be
useless.
Cf https://github.com/pypa/packaging.python.org/pull/771 for more context.
> PEP 345: Disallow environment markers in Requires-Python

- pep-0571.rst
Following popular demands over at manylinux, the `i686` image was updated to use the same `devtoolset-8` as the `x86_64` image.
`devtoolset-8` was not included in the first place because was not available anywhere for `i686`. We're now rebuilding it on COPR to address concerns expressed in the manylinux repo about this software stack inconsistency.
> PEP 571: Toolchain change in the manylinux2010 i686 image

- pep-0637.txt
Adds the Post-History metadata with the date of the announcement email sent to python-ideas
> PEP 637: Updated Post-History with the mail date to python-ideas

- pep-0637.txt
Without this:
* blocks of prose render as code
* blocks of code randomly render inside blockquotes
> PEP 637: Fix rST errors caused by incorrect indentation

- pep-0637.rst
Changed filename from txt to rst to get syntax highlighting in vim.
Changed indentation and formatting of the code snippets so that we don't get ugly yellow bars before and after each snippet.
> PEP 637: Renamed file to rst and changed formatting of block code

- pep-0638.rst
There is a typo in the link to https://www.linuxjournal.com/article/4731 at `References` section
> PEP 638: Fix typo in references

- pep-0637.rst
Removes the Ellipsis on keyword arguments, as it's normally accepted in python 3
> PEP 637: Removed currently normal Ellipsis on keyword argument

- pep-0639.rst
- pep-9999.rst
This is a new PEP to improve the license information handled in Core metadata which is now more than ready to enter the formal PEP process.  
The discussion has been taking at https://discuss.python.org/t/improving-license-clarity-with-better-package-metadata/2154 and in the original PR on my fork https://github.com/pombredanne/spdx-pypi-pep/pull/2
This has been triggered by several discussions in particular:
- https://github.com/pypa/warehouse/issues/2996
- https://github.com/pypa/interoperability-peps/issues/46
- https://github.com/pypa/packaging-problems/issues/41
- https://github.com/pypa/wheel/issues/138
- https://github.com/pombredanne/spdx-pypi-pep/issues/1#issuecomment-281343077
- pypa/packaging.python.org#635
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>
> PEP 639: Use SPDX license expressions in Core package metadata

- pep-0622.rst
- pep-0634.rst
- pep-0635.rst
- pep-0636.rst
Also change PEP 622 status to "Superseded", and mark that as "Superseded-By: 634".
We won't land this until we have a decent amount of content in each of the three new PEPs (but we'll still iterate after that).
> PEP 634, PEP 635, PEP 636: Create the structure for the PEP 622 split

- pep-0569.rst
* https://www.python.org/downloads/release/python-386/
* https://discuss.python.org/t/python-3-8-6-is-now-available/5299
> PEP 569: Python 3.8.6 was released on 2020-09-24

- pep-0596.rst
- pep-0619.rst
https://www.python.org/downloads/release/python-390/
https://www.python.org/downloads/release/python-3100a1/
> PEP 596, 619: Update based on released versions

- pep-0584.rst
Updating an existing key's value doesn't move it to the back.
> PEP 584: Fix order in specification examples

- pep-0343.txt
Clarify when the `__context__()` function was removed from the API; the projected 2.5a3 tag never happened.
Also remove `__context__()` from example code.
> PEP 343: Clean up some __context__ context

- pep-0621.rst
- pep-0636.rst
I'm starting with "SHOULD", but open to making it "MUST" for sdists to include this. The only reason for the latter is I wasn't sure if pip had worked through all the isolation build issues around simply having `pyproject.toml` defined.
> PEP 621: Clarify expectations for sdists

- pep-0638.rst
> PEP 638: Correct punctuation (accd'ing to "Gregg Ref. Man., 11th Ed.")

- pep-0621.rst
In PEP 621 rather than saying that values "cannot be dynamic" in source distributions it actually says "cannot **by** dynamic". I'm sure that's a typo.
> PEP 621: Fix typos

- pep-0640.rst
- pep-unused-assignment.txt
First draft of PEP 640: Unused variable syntax, making assigning to '?' really do what people sometimes think assigning to '_' does.
> PEP 640: Unused variable syntax

- pep-0635.rst
Now that PEP 640 exists we might as well mention another argument against "?".
@Tobias-Kohn
> PEP 635: More arguments against '?' wildcards

- pep-0008.txt
Based on a conversation w/ @gvanrossum during the 2020 core dev sprint, there was a suggestion to add an example for one line docstrings to draw more attention to it (the issue comes up decently often, especially in CPython PRs).
> PEP 8: Add one line docstring example

- pep-0594.rst
I propose to keep the legacy email modules.  They are still being maintained (at least as well as the new APIs) and they are probably in widespread use.  The dependencies on other stdlib modules that are being proposed to be removed should be handled separately.
> PEP 594: Don't remove the legacy email modules

- pep-0634.rst
Clarifies slightly better how mapping patterns work, in particular it covers better if a ``True`` key in a pattern matches a ``1`` value in the subject.
> PEP-634: Describe how keys are compared in mapping patterns

- pep-0636.rst
caught by @merwok in https://github.com/python/peps/commit/5f9a50d3d43f3b2b921ade84c3d6ca4dbf248480#r43496834
> PEP-636: Fix mistake on class patterns

- .github/workflows/build.yml
(Split from https://github.com/python/peps/pull/1570.)
Adds a GitHub Actions workflow to build and deploy, like Travis CI.
Notes:
* Travis CI builds against 3.7 and 3.7-dev. I only added 3.8 to GHA. Should it build against a range? For example, we can do 3.6-3.9.
* It will only deploy for `python/peps` and `master` (like Travis)
* I've left Travis CI in place for now. I'd suggest confirming the deploy works first from GHA, then removing from Travis in a followup PR.
* (I also noticed that on Travis, it's deploying for both 3.7 and 3.7-dev. It probably only needs doing from a single job.)
* Nice bonus: `make -j$(nproc)` is quicker on GHA (~80s) than Travis (~110s)
https://travis-ci.com/github/python/peps? They will need to be added at https://github.com/python/peps/settings/secrets
> Build and deploy HTML on GitHub Actions

- pep-0480.txt
This commit adds various updates to account for changes in PEP 458, including:
* updating the link to the Python glossary
* add definitions of distribution file, target files
* clarify ‘target files’ and ‘target metadata’
* Use BLAKE 2 instead of SHA-2 in filenames
* transaction process -> upload process
This commit also adds a few clarifications about the purpose of this PEP, including adding an overview of the changes needed to implement the PEP
> PEP 480: Update PEP 480 to account for changes to PEP 458

- pep-0440.txt
The clauses 1-8 in the Semantic Version 2.0.0 Specification:
*  https://semver.org/spec/v2.0.0.html
cover what were clauses 1-9 in the first release candidate of
that version of the specification:
*  https://semver.org/spec/v2.0.0-rc.1.html
The 3rd clause was removed:
*  https://github.com/semver/semver/issues/7
> PEP 440: update clause range for SemVer 2.0.0

- pep-0642.rst
A counter-proposal that mostly endorses PEP 634, but
proposes an alternative to the magic interpretation
of attribute lookups as value constraints while
simple names are capture patterns.
> PEP 642: Constraint Pattern Syntax for Structural Pattern Matching

- pep-0642.rst
Also links to the WIP reference implementation.
> PEP 642: Use correct terminology for new PEG parser

- pep-0001.txt
- pep-0012.rst
- pep0/pep.py
- pep2html.py
- pep2pyramid.py
Fixes #1431.
The first commit updates the header fields from BDFL-Delegate to PEP-Delegate.
The second updates other uses in PEPs. I left a couple in I thought should stay (one in a post history, another being contrasted with PEP Delegate).
And also added a bit to the PEP 1 paragraph that gives the BDFL background:
```diff
-This PEP still uses the title "BDFL-Delegate" for PEP decision makers. This was
+This PEP earlier used the title "BDFL-Delegate" for PEP decision makers. This was
a historical reference to Python's previous governance model, where all design
authority ultimately derived from Guido van Rossum, the original creator of the
Python programming language. By contrast, the Steering Council's design
authority derives from their election by the currently active core developers. …
```
> Change language from BDFL-Delegate to PEP-Delegate

- pep-0626.rst
> PEP 626: Clarify lifetimes of helper functions and struct.

- pep-0642.rst
* Set initial post date
* Remove most of the caveats on the reference implementation
(the PEP 634 test cases have been adjusted as necessary to
pass, and new PEP 642 specific test cases added)
* Additional subsection in Deferred Ideas for negated constraints
* Add notes on PEP 635's concerns about potential semantic confusion
between assignment targets and pattern matching
* Assorted final pre-publication tweaks
> PEP 642: Prepare for initial publication

- pep-0642.rst
* Equality prefix changes from '?' to '=='
* Identity prefix changes from '?is" to 'is'
* Wildcard marker reverts to '_'
* Syntactic shorthands from PEP 634 are mostly kept,
but only as syntactic sugar for the explicit forms
* AST changes allow most match-specific code to be
dropped from the compiler
> PEP 642: Accept Steven D'Aprano's counter-proposal (mostly)

- pep-0101.txt
Do not merge before https://github.com/python/cpython/pull/20969.
> PEP 101: Simplified due to centralisation of switchers in the doc.

- pep-0642.rst
* Switch to `__`` as the proposed wildcard marker
* OR patterns also need a disambiguating space before `==`
* Misc wording tweaks and other edits
> PEP 642: Additional edits for 2nd posting

- pep-0645.rst
- pep-9999.rst
Initial commit for the Optional syntax PEP. 
Relevant discussion from typing sig email thread: https://mail.python.org/archives/list/typing-sig@python.org/thread/SWAY6V7WZLVPGYQEMHXJROT2747OXSRX/
> PEP 0645: New Optional Syntax

- foo.py
- pep-0635.rst
@davidfstr, on python-dev, recommended we bring back this explanation from PEP 622.
CC @Tobias-Kohn
> PEP 635: Explain why mapping patterns ignore extra keys

- pep-0001.txt
- pep-0520.txt
- pep-0545.txt
- pep-0554.rst
- pep-0555.rst
- pep-0589.rst
- pep-0590.rst
- pep-0591.rst
- pep-0592.rst
- pep-0593.rst
- pep-0605.rst
- pep-0611.rst
- pep-0615.rst
- pep-0621.rst
- pep-0622.rst
- pep-0626.rst
- pep-0636.rst
- pep-0638.rst
- pep-8001.rst
- pep-8002.rst
- pep-8011.rst
- pep-8015.rst
Remove repeated words and in some cases reformat paragraph.
> Typos: Remove repeated words

- pep-0619.rst
https://www.python.org/downloads/release/python-3100a2/
> PEP 619: Update date for 3.10.0a2

- pep-0517.txt
As per https://bugs.python.org/issue38905
Signed-off-by: Bernát Gábor <bgabor8@bloomberg.net>
cc @pfmoore
> PEP-517: On Windows the subprocess calls don't start resolving from the PATH

- pep-0630.rst
[bpo-42111] is resolved, which closes the remaining "XXX" notes in the PEP.
It's ready for Active status (see https://github.com/python/peps/pull/1574#issuecomment-680145163).
[bpo-42111]: https://bugs.python.org/issue42111
> PEP 630: change to Active and link to the new xxlimited module

- pep-0423.txt
The existing link in the "Terminology" section is broken. If that page is still alive at another URL, I couldn't find it.
This new link (https://packaging.python.org/glossary/) seems to cover the same topics.
> PEP 423: Replace dead "terminology" link

- pep-0626.rst
See https://bugs.python.org/issue42718
Currently we either have to emit NOPs in the bytecode *or* break PEP 626.
This minor change to the PEP allows us more freedom in bytecode generation,
while keeping the promise of accurate tracing and debugging.
> PEP 626: Allow zero-width entries in code.co_lines(), to allow better bytecode generation.

- pep-0637.rst
Allows the notation with empty star, double star args as from discussion with @brandtbucher
> PEP 637 Allow notations for empty star arguments.

- pep-0612.rst
An unused variable was removed from the code example.
I also added a line to point to the [CPython implementation](https://github.com/python/cpython/pull/23702) for posterity.
> PEP 612: Clean up code examples, link to CPython implementation

- pep-0550.rst
There is a small typo in pep-0550.rst.
Should read `survey` rather than `survery`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, survery -> survey

- pep-0637.rst
Adds the required changes to the PyMappingMethods struct. Two new slots must be added for the dispatch.
> PEP 637: added new slots to the C interface changes

- pep-0646.rst
Naming:
* Rename Tensor -> Array (it's less jargony, and I think it's the more general term)
* Rename Expand -> Unpack (to be consistent with the terminology for normal tuples)
* Rename ArgTs -> Ts, ReturnT -> R
* Rename 'type tuple variable' -> 'type variable tuple'
Semantic:
* Explicitly state that a TypeVarTuple can hold *zero* or more types
* Explicitly state that TypeVarTuple doesn't support variance or bound yet
* Support Union[*Ts]
* Support concatenating multiple unpacked TypeVarTuple when there's no ambiguity
* Support aliases
* Remove support for class overloads; replace with overloads of individual methods
Pedagogical:
* Reorder introductory material to make it clearer how TypeVarTuples behave when not unpacked, and to make it clearer that using them without unpacking them is a …
> PEP 646: Various updates

- pep-0642.rst
* requires that all uses of bare names be qualified with the user's intent
* ensures that all name binding operations in patterns use the ``as`` keyword
* drops alignment with iterable unpacking syntax (always requires square brackets)
* drops alignment with class instantiation syntax (defines a new dedicated instance attribute matching syntax instead)
> PEP 642 v3: Explicit pattern matching syntax

- pep-0648.rst
Target 3.10 as we still have enough time. I was initially targeting 3.11 in case we had a larger discussion around this feature. We can always move to 3.11 later.
The Pr also includes a small grammar fix.
> PEP 648: Target Python 3.10 + minor wording fixes

- pep-0635.rst
This reverts commit aafca24693112ae2513f04169f355eba6ef4cd77.
PEP 642 was updated and the commentary here is out of date.
IMO we needn't address it here.
> Revert "PEP 635: Add a rebuttal of PEP 642 (GH-1691)"

- pep-0012.rst
The peps@python.org list has been shut down, and everything is done via
GitHub pull requests. Also, we no longer need some of the older steps,
and it's easier to read if some of the obscure/unusual options are
buried away in parentheses.
Open to discussion, can split this up if it's controversial.
> PEP 12: Clean up and modernize guidelines.

- pep-0651.rst
- pep-9999.rst
This PEP proposes that Python doesn't crash when after `sys.setrecursionlimit(1_000_000)` and that stack overflows and runaway recursion are treated differently.
> PEP 651: Robust Overflow Handling

- pep-0651.rst
Removes ``Py_CheckStackDepthWithHeadRoom`` and makes ``Py_EnterRecursiveCall`` call ``Py_CheckStackDepth``.
This should make the API easier to use, and be a bit more backwards compatible.
> PEP 651: Revise C-API

- pep-0650.rst
This fixes some minor formatting issues with the provided API functions.
It also adds the `path` argument to all functions: this is required for any installer that stores it's dependency information in a file in a local directory -- the backend must always know which directory it should be running from.
(cc @brettcannon)
> PEP 650: Updates to the API

- pep-0637.rst
Adds a use case in the proposal for star arguments as needed in PEP 646 Variadic Generics.
> PEP 637: Added notation use case for star arguments on PEP 646

- pep-0558.rst
The initial version of the PEP entrenched the tracing mode distinction,
and was worded accordingly.
Now that tracing mode is only relevant as a historical artifact that is
being eliminated, the wording should make that clear.
> PEP 558: Make it clear tracing mode is being eliminated

- pep-0619.rst
3.10.0a4 was released https://www.python.org/downloads/release/python-3100a4/
> PEP 619: Update 3.10.0a4 to be marked as released

- pep-0597.rst
Add EncodingWarning instead of DeprecationWarning.
Ref: https://discuss.python.org/t/pep-597-raise-a-warning-when-encoding-is-omitted/3880/23?u=methane
> PEP 597: Add EncodingWarning

- pep-0637.rst
Explicit rule on star args unpacking after discussion with @gvanrossum and @brandtbucher. See https://mail.python.org/archives/list/python-ideas@python.org/thread/IPPW3Z5NHQ7YRXESPTF64PPAX7CDQGCG/
> PEP 637: Added clause for star unpacking leaving the index as a tuple

- pep-0639.rst
Various changes to improve clarity and consistency. None of the changes
should change the meaning of any content.
> PEP 639: Changes for clarity and consistency

- pep-0650.rst
I think it's simpler to just consider the dependency group to be the requirements filename in the case of pip (and default to `requirements.txt` if the dependency group is `None`). Properly using the `path` argument means that this can be relative.
If we're adhering to the current API, the example should also return an exit code, not the result of `subprocess.call()`.
(cc @brettcannon)
> PEP 650: Fix typos, improve example

- pep-0624.rst
Add note about we can avoid creating a temporary Unicode object
in deprecated APIs for some codecs.
> PEP 624: Update alternative ideas

- pep-0621.rst
- pep-0635.rst
- pep-0637.rst
- pep-0639.rst
- pep-0642.rst
- pep-0644.rst
- pep-0645.rst
- pep-0647.rst
- pep-0650.rst
This is the same as https://github.com/python/peps/pull/1668, but without changes to code blocks, and without the linter.
> PEP 621, 635, 637, 639, 642, 644, 645, 647, 650: Fix single backticks

- pep-0427.txt
See https://discuss.python.org/t/requesting-clarification-for-pep-427-wheel-file-names-and-build-numbers/6988/ for the discussion leading to this clarification.
> PEP 427: clarify how the build tag plays into wheel file selection

- pep-0637.rst
Added a "how to teach" section explaining a possible phrase to use when explaining the feature in a training course, as suggested by @encukou on python-dev
> PEP 637 Added "how to teach" section

- pep-0646.rst
Feature removals:
* Remove `Map` (to be added in a separate PEP)
* Remove support for all forms of concatenation other than simply prefixing of a single `TypeVarTuple` (fancier forms of concatenation to also be added in a separate PEP)
Semantic changes:
* Try switching `Ts` back to mean the 'unpacked' version (such that `Ts = int, str; Tuple[Ts] = Tuple[int, str]`) to see whether everything still works. (Might revert this, pending future discussion in typing-sig.)
Clarifications:
* Type prefixing is not supported in `Callable`. Why?
* Stay in the spirit of 'keep this PEP simple, gosh darn it'.
* If we had `Callable[[int, Ts], Any]`, then the first argument would have to be positional-only, and that seems like it'll have complications.
* I expect most use-cases to be covered by PEP 612.
> PEP 646: Update based on typing-sig discussions

- .github/workflows/lint.yml
- .pre-commit-config.yaml
- Makefile
- pep-0646.rst
New version of https://github.com/python/peps/pull/1668, main difference is the linter has been updated so the `rst-backticks` skips code blocks (lines beginning with four spaces).
---
This PR adds two reStructuredText lint rules and runs them on the CI using GitHub Actions. [Example run.](https://github.com/hugovk/peps/runs/1848734386?check_suite_focus=true)
1. Detect single backticks, which should be double in RST for inline code, e.g. stuff fixed in https://github.com/python/peps/pull/1554.
2. Detect inline code touching normal text, e.g. stuff fixed in https://github.com/python/peps/pull/1560.
It adds a standalone `make` command to lint locally:
```sh
make lint
```
The pre-commit dependency is installed if needed.
This uses the [pre-commit](https://pre-commit.com/) tool for linting. …
> Lint RST on GitHub Actions

- pep-0636.rst
It seems unlikely that the `message` variable in these two examples is an iterable of actions, and especially confusing since in the pattern matching inside of the for loop, there is another `message` variable that would shadow this iterable of actions.
In this PR, I'm changing the name of the iterable of actions to `actions`, leaving the `message` variable created within the for loop the same.
> PEP 636: Is there a typo in the example code?

- pep-0652.rst
This PEP proposes that *CPython's Limited C-API and Stable ABI, introduced in PEP 384, will be formalized in a single definitive file, tested, and documented.* See https://discuss.python.org/t/pre-pep-maintaining-the-stable-abi/6986 for the discussion.
AFAICS, 652 is the next available number.
> PEP 652 (new): Maintaining the Stable ABI

- pep-0647.rst
clarify some points I was confused on ... why TypeGuard isn't just a boolean,
> PEP 647: clarify why type guards are not just a boolean

- pep-0647.rst
backwards compatibility for non-typing annnotations
> PEP 647: comment about backwards-compatibility

- pep-0636.rst
Signed-off-by: Matej Dujava <mdujava@kocurkovo.cz>
> PEP 636: Add missing colons at the end of case statement

- pep-0597.rst
* Add Backward/Forward Compatibility section
* Add How to teach this section
* Remove io.LOCALE_ENCODING constant
> PEP 597: Update

- pep-0597.rst
warn_encoding -> warn_default_encoding
> PEP 597: Use longer option name

- pep-0646.rst
Semantic changes:
* Unparameterised variadics are compatible with parameterised variadics in both direction
* Allow suffixing
Readability changes:
* De-emphasise unparameterised `Array` behaving like `Array[Any, ...]` to avoid the suggestion that `Array[Any, ...]` might be supported
* Explicitly forbid `Array[Any, ...]` and similar
* Clarify that only `*args` can be annotated as `*Ts`; other arguments must use `Tuple[*Ts]`
* Remove 'Final Notes' section (I was hoping we'd have more edge cases to add to this, but in the end there haven't been any, and the only example we do have is obscure enough that I think we can just remove it)
Also some minor typo fixes.
> Update PEP 646 draft

- pep-0654.rst
* Fix a few markup issues & typos; use REsT references.
* Mention Task Groups in Motivation; add an example of the ``trio.MultiError`` API
> A couple PEP 654 edits

- pep-0616.rst
In https://github.com/python/peps/issues/1639 , it looks like at least two people have taken issue with the example, and I don't think much is lost by removing it, except a lack of examples of `removesuffix()`. I think this is a reasonable replacement.
> PEP 616: Replace a misleading example

- pep-0634.rst
I don't think mapping patterns are supposed to raise TypeError on duplicate keys, instead it's probably ValueError.  A few paragraphs down the PEP mentions:
> If duplicate keys are detected in the mapping pattern, the pattern is considered invalid, and a ValueError is raised.
So it seems like a contradiction.
The implementation seems to only raise TypeError for class patterns too:
https://github.com/python/cpython/pull/22917/files
> PEP 634: Fix error typo in mapping patterns (TypeError ->ValueError)

- pep-0654.rst
> Add section about handling ExceptionGroups

- pep-0655.rst
> PEP 655: Marking individual TypedDict items as required

- pep-0618.rst
"deserves to" instead of "deserves do"
> PEP 618: Fix typo

- pep-0636.rst
Fix minor typo:  
"But ``**_`` would be redundant, so it not allowed."
--> "But ``**_`` would be redundant, so it **is** not allowed."
> PEP 636: Minor typo

- pep-0654.rst
> PEP-654: add BaseExceptionGroup//ExceptionGroup split

- pep-0654.rst
> PEP-654: add example of subgroup callback with side effects

- pep-0654.rst
> PEP-654: tidy up leaf_generator example

- pep-0001.txt
Also remind PEP editors to make sure that the support isn't conjecture but instead is actually backed up.
> PEP 1: Suggest people reach out to important projects to support their PEP's motivation

- pep-0654.rst
Use "exception group" instead of ExceptionGroup to make it flow better now that we also have BaseExceptionGroup.
> PEP-654: ExceptionGroup --> exception group in prose

- pep-0646.rst
This is the more-or-less final version now. I'll do one last read-through to confirm everything's consistent, then post in typing-sig to confirm it's ready for the Steering Committee.
Semantic changes:
* Remove support for type variable tuples in `Union`. Apparently the implementation would be tricky in Pyre because of special-casing around `Union`. That could be evidence that it would be tricky in Mypy and pytype. Since we don't have a specific use-case in mind, I think this is fine.
* Support concatenation in `Callable`. Pradeep pointed ou that `ParamSpec` doesn't cover all potential use-cases because it doesn't support concatenating suffixes (in turn because `ParamSpec`s can contain keyword arguments, and concatenation is positional).
Readability changes:
* Remove the section on a full …
> PEP 646: Update draft

- pep-0644.rst
Signed-off-by: Christian Heimes <christian@python.org>
> PEP 644: Mention Void and Gentoo changes (GH-1860)

- pep-0646.rst
Also note that a version of Pyre with PEP 646 has been released! Yay!
> PEP 646: Make some final final readability improvements

- pep-0654.rst
> PEP-654: add to the rejected ideas section, following public discussion

- pep-0621.rst
I interpreted the `{name} <{email}>` to mean Python string formatting, which is incorrect in some cases.
cc @Pyfisch @uranusjr @brettcannon
> PEP 621: mention that '{name} <{email}>' may need quoting

- pep-0654.rst
> PEP-654: use C traceback for some examples

- pep-0480.txt
Move from Deferred to Draft status, update discussion venue and author list, and fix an obsolete reference to Distutils.
> PEP 480: Fix status, author, discuss, reference

- pep-0653.rst
* Change name of `MATCH_CLASS` to `MATCH_POSITIONAL`.
* Drop `__attributes__` and use `__match_args__` instead.
* For `MATCH_DEFAULT`, `__match_args__` acts a map from positions to names.
* For `MATCH_POSITIONAL`, `__match_args__` acts a map from names to positions.
* Change semantics of `MATCH_DEFAULT` when match class patterns to those of PEP 634.
* Update translations.
* Further expand examples
> PEP 653: Change semantics to be closer to PEP 634, while keeping the important features of PEP 653.

- pep-0601.txt
Apparently the author/email lexer can't handle missing emails with authors, so temporarily I'll remove my address
> PEP 601: remove email due to lexer bug

- pep-0656.rst
- pep-9999.rst
As proposed in https://discuss.python.org/t/wheels-for-musl-alpine/7084
cc @brettcannon @tiran
> PEP 656: Platform Tag for Linux Distributions Using Musl

- pep-0654.rst
> PEP-654: allow subclassing of exception groups

- pep-0656.rst
> PEP 656: Clarification on platform definition and musl detection

- pep-0656.rst
I was made realised the current ``${ARCH}`` rule is potentially incompatible with previous PEPs.
> PEP 656: Also replace dots to match PEPs 425 and 427

- pep-0012.rst
As a small followup to PR #1886 , I noticed that the date format in the PEP 12 template is actually given as YYYY-MM-DD, while in the text it is described as dd-mmm-yyyy. Presuming the latter is correct, I've modified the former to be consistent with it. Also, I noticed that the `Python-Version` field was not marked as optional, despite being described as such in the text (and is certainly so in practice), so I fixed that as well.
> PEP 12: Make date format in template match prose, and mark Python-Version as optional

- .pre-commit-config.yaml
- pep-0316.txt
- pep-0328.txt
- pep-0361.txt
- pep-0371.txt
- pep-0378.txt
- pep-0381.txt
- pep-0389.txt
- pep-0390.txt
- pep-0403.txt
- pep-0407.txt
- pep-0412.txt
- pep-0413.txt
- pep-0482.txt
- pep-0483.txt
- pep-0541.txt
- pep-0617.rst
- pep-0622.rst
- pep-0628.txt
- pep-0648.rst
- pep-3118.txt
- pep-3128.txt
- pep-3150.txt
Adds some more cheap Pygrep checks to conservatively validate the formally-specified PEP fields against PEP 12 (i.e. the required fields are present, and non-empty fields match any required format), with a few exceptions:
* The Author/Sponsor/PEP-Delegate have a strictly-defined format in the spec, and I prototypes a regex to enforce it; however, due to numerous deviations in practice and the non-triviality of conforming them automatically, I don't attempt to enforce that here, and leave that to a future PR, if interest exists
* Similarly, it was straightforward to modify the `Created` regex to also check `Post-History`, but given the number of deviations that would need to be corrected, the non-triviality of doing so programmatically, and the likely lesser interest in parsing the data, I …
> Lint: Validate PEP fields against PEP 12

- pep-0636.rst
This was brought up by codeofdusk@gmail.com on the python-dev list.
> PEP 636: fix typo

- pep-0636.rst
otherwise, on trying this example
```python
>>> where_is(Point(x=0, y=42))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
TypeError: Point() takes no arguments
```
> PEP 636: add missing @dataclass

- pep-0653.rst
This cuts down PEP 563 to make it feasible to get into 3.10.
The `MATCH_POSITIONAL` and `__deconstruct__` features can wait for 3.11.
Semantics for `MATCH_DEFAULT` are near identical to PEP 634.
The logic for matching sequences and mappings has been simplified.
> PEP 653: Remove MATCH_POSITIONAL and make semantics for MATCH_DEFAULT near identical to PEP 634.

- pep-0654.rst
> PEP-654: clarify that ExceptionGroup is not trivial to implement correctly

- pep-0653.rst
As suggested by GvR.
Makes it clearer that `__match_args__` must be a tuple.
Renames `MATCH_DEFAULT` to the more meaningful `MATCH_ATTRIBUTES`.
> PEP 653: Split __match_kind__ into __match_container__ and __match_class__

- pep-0653.rst
Using `$value.keys() >= ...` is not possible for some mappings, so we need to use two argument `get()` as pointed out by @brandtbucher 
Also fix example.
> PEP 653: Fix example. Use get(key, sentinel) instead of __getitem__(key) for mappings.

- pep-0646.rst
> PEP 646: Be more explicit about grammar changes needed

- pep-0646.rst
A pretty reasonable reason for the SC to reject PEP 646 would be that alternatives for shape checking do already exist; let's be honest about that.
But let's also highlight the difference to the alternatives out there: _static_ checking, enabled by the beginnings of a standard that can act as a central point of reference.
@pradeep90 Do you wanna take a look over this? Maybe I've gone too far; my late-night writing can be a bit hit or miss...
> PEP 646: Add note of alternatives that exist

- .github/CODEOWNERS
- pep-0001.txt
All active core devs that have either authored or sponsored a PEP are now listed as the "owner" of that PEP file. This will help PEP editors by automatically assigning PRs to the appropriate core devs.
Closes #1804
> Introduce CODEOWNERS

- pep-0597.rst
Hello @methane ! Thanks so much for all your hard work on this and congratulations on the acceptance of PEP 597; I've personally been very much looking forward to this change, as I have run into issues with other libraries, tools and applications not explicitly specifying their encoding (particularly in the scientific Python realm) and breaking on Windows or other non-UTF-8 platforms countless times over the years, including just a few days ago in regebro/pyroma#28 .
Since I moonlight as a technical writer and copyeditor (and docs, theme and website maintainer for the Spyder IDE), I had noticed a number of minor grammar/textual issues with the prose, so thanks to @JelleZijlstra 's kind encouragement on @corona10 's PR #1885 that accepted this, I went ahead with suggesting some textual …
> PEP 597: Apply grammar, syntax and polish fixes, and clarify phrasing and terminology

- pep-0619.rst
> PEP 619: Update the list of PEPs included in 3.10

- pep-0634.rst
This was discussed on python-dev in the thread
https://mail.python.org/archives/list/python-dev@python.org/thread/YYIT3QXMLPNLXQAQ5BCXE4LLJ57EE7JV/#YYIT3QXMLPNLXQAQ5BCXE4LLJ57EE7JV
I don't think anyone disagrees that it's better if `__match_args__` is required to be a tuple.
- This helps static type checkers keep track of the values more easily
- It allows an optimization in the implementation where the pattern only needs to be recompiled when the value is changed.
> PEP 634: Change so __match_args__ must be a tuple

- pep-0634.rst
This resolves a discrepancy between the specification and the implementation, in favor of the current implementation. The spec used to state that you can't have patterns like these:
```
case int(x, real=0): ...
case int(real=1): ...
```
The implementation allows this and there is no good reason to disallow it, so it makes sense to rule that the PEP was mistaken here. (I don't recall why I put it in the PEP and in fact I was surprised to find it there.)
> PEP 634: Allow keyword patterns for int, str etc.

- pep-0656.rst
Suggested in https://discuss.python.org/t/7165/25 and https://discuss.python.org/t/7165/27
> PEP 656: Minor clarification on relation to PEP 600

- pep-0624.rst
> PEP 624: Typo
