python/peps

pep-3145.txt
Footnote [8] existed since the first draft, unreferenced -- I've removed the syntax.
A
----
:books: Documentation preview :books:: https://pep-previews--3261.org.readthedocs.build/
=> PEP 3145: Resolve unreferenced footnotes

pep-0572.rst
The references to footnote [1] were removed in 5e8b724, I inserted a reference in what seems a sensible place.
A
----
:books: Documentation preview :books:: https://pep-previews--3249.org.readthedocs.build/
=> PEP 572: Resolve unreferenced footnotes

pep-0645.rst
Both footnotes already existed as inline hyperlinks, so I removed the footnotes and kept the hyperlinks.
A
----
:books: Documentation preview :books:: https://pep-previews--3253.org.readthedocs.build/
=> PEP 645: Resolve unreferenced footnotes

pep-3147.txt
Footnote [21] was added in bac0ec1 and removed in c80d1ae -- this removes the markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3262.org.readthedocs.build/
=> PEP 3147: Resolve unreferenced footnotes

pep-3119.txt
Footnote [2] existed in the first draft, unreferenced. Footnote [3] was added in e06f400 and had its only reference removed in 3ff288b. Footnotes [9] and [10] were added in ac9a270 and had their references removed in 842b40e, when the Ordering ABCs were removed from the PEP. I've retained all four, removing the markup.
A
----
:books: Documentation preview :books:: https://pep-previews--3259.org.readthedocs.build/
=> PEP 3119: Resolve unreferenced footnotes

pep-0370.txt
Footnote [6] existed from the beginning of the PEP, but was never referenced. ``permalink.gmane.org`` doesn't seem to work anymore so I can't evaluate if the reference *was* useful -- removed the syntax for now, but this one is more of a judgement call.
Is there a way to map ``gmane.comp.python.devel/<number>`` to ``mail.python.org``?
A
----
:books: Documentation preview :books:: https://pep-previews--3233.org.readthedocs.build/
=> PEP 370: Resolve unreferenced footnotes

pep-0708.rst
Congratulations @dstufft!
cc: @pfmoore -- I tried to capture the salient points of your acceptance message, which ended up just being the bullet points -- please suggest any additions or deletions for the provisional acceptance note.
A
----
----
:books: Documentation preview :books:: https://pep-previews--3268.org.readthedocs.build/
=> PEP 708: Mark as Provisional

pep-0480.txt
Footnotes [6], [9], and [10] were introduced in 2689835, when PEP 480 was cleaved from 458, all unreferenced. I've read through the PEP and can't identify a useful place that references could be added, so I've removed the footnotes and renumbered.
A
----
:books: Documentation preview :books:: https://pep-previews--3238.org.readthedocs.build/
=> PEP 480: Resolve unreferenced footnotes

conf.py
The final PR in this series -- once all the "Resolve unreferenced footnotes" PRs are merged, we can enable [Sphinx's nit-picky mode](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky).
A
This also closes #3213.
----
:books: Documentation preview :books:: https://pep-previews--3263.org.readthedocs.build/
=> Warn on all missing references in PEPs

Makefile
These were deprecated half a year ago in #2968.
A
----
:books: Documentation preview :books:: https://pep-previews--3271.org.readthedocs.build/
=> Remove ``render`` and ``pages`` targets from the Makefile

Makefile
A
----
:books: Documentation preview :books:: https://pep-previews--3272.org.readthedocs.build/
=> Make Sphinx fail rendering on any warning

pep-0723.rst
In working on the Rust design for single-file packages, we found that there were too many decisions to make upfront in an RFC, so we instead opted to approve an experiment (eRFC) to figure out the design incrementally and then come back with a final proposal.  This implementation is considered unstable and requires a special flag (`-Zscript`) to access within the nightly builds of Rust.
This PR updates the description of Rust's approach to align with that.
----
:books: Documentation preview :books:: https://pep-previews--3277.org.readthedocs.build/
=> PEP 723: Correct comparison with Rust

pep-0693.rst
Re: https://www.python.org/downloads/release/python-3120rc1/
----
:books: Documentation preview :books:: https://pep-previews--3283.org.readthedocs.build/
=> PEP 693: Update 3.12.0rc1 release date

pep-0721.rst
- it's only a [spec addition](https://packaging.python.org/en/latest/specifications/source-distribution-format/#sdist-archive-features)
- the only changes were formatting, linking, typo fixes
----
:books: Documentation preview :books:: https://pep-previews--3285.org.readthedocs.build/
=> PEP 721: Mark Final

.github/PULL_REQUEST_TEMPLATE/Mark a PEP Final.md
----
:books: Documentation preview :books:: https://pep-previews--3286.org.readthedocs.build/
=> Infra: Fix directive name in PR template

.pre-commit-config.yaml, pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py, tox.ini
See message in commit c58adfa0dd8b1e5e0cb42856b67a77410e894d94 for details.
----
:books: Documentation preview :books:: https://pep-previews--3291.org.readthedocs.build/
=> Lint: Update outdated package dependencies & reformat files

pytest.ini
https://github.com/python-babel/babel/issues/873 and https://github.com/sphinx-doc/sphinx/issues/10440 have been fixed and released. 🚀 
----
:books: Documentation preview :books:: https://pep-previews--3296.org.readthedocs.build/
=> Infra: Remove resolved warning filters

pep-0703.rst
----
:books: Documentation preview :books:: https://pep-previews--3298.org.readthedocs.build/
=> PEP 703: fix some typos

pep-0722.rst
Noticed when reviewing the PEP 723 finalisation just now.
----
:books: Documentation preview :books:: https://pep-previews--3299.org.readthedocs.build/
=> PEP 722: Correct a spelling error

pep-0695.rst
Edit for valid Julia syntax
The syntax for Julia is incorrect. This edit changes the Julia syntax to exhibit valid Julia syntax
```julia
julia> struct StructA{T} where Int <: T <: Number
x::T
end
ERROR: syntax: invalid type signature around REPL[1]:1
julia> function func1{T <: Real}(v::Container{T}) end
ERROR: UndefVarError: `func1` not defined
```
The edited syntax is valid.
The edited syntax is completely valid Julia code as of Julia 1.9.2.
```julia
julia> begin
struct Container{Int <: T <: Number}
x::T
end
function func1(v::Container{T}) where T <: Real end
function func2(v::Container{T} where T <: Real) end
function func3(v::Container{<: Real}) end
function func4(t::Tuple{Real,Real}) end
end
func4 (generic function with 1 method)
julia> Container(5) …
```
=> PEP 695: Edit for valid Julia Syntax

pep-0715.rst
I believe this can be marked as final because the PEP has been fully implemented and eggs can no longer be updated to PyPI:
* https://github.com/pypi/warehouse/pull/14017
* https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/
* https://github.com/pypi/warehouse/pull/14118
* https://github.com/pypa/packaging.python.org/pull/1278
cc @woodruffw @di 
----
:books: Documentation preview :books:: https://pep-previews--3302.org.readthedocs.build/
=> PEP 715: Mark as final

pep-0001.txt
✏️ Fix typo in PEP 1
----
:books: Documentation preview :books:: https://pep-previews--3311.org.readthedocs.build/
=> PEP 1: Add a missing word in "Submitting a PEP"

.github/CODEOWNERS, pep-0727.rst, pep-0755.rst
Add PEP 727: Documentation Metadata in Typing
----
:books: Documentation preview :books:: https://pep-previews--3310.org.readthedocs.build/
=> PEP 727: Documentation Metadata in Typing

pep-0649.rst, pep-0652.rst, pep-0653.rst, pep-0665.rst, pep-0684.rst, pep-0690.rst, pep-0713.rst, pep-0727.rst
----
:books: Documentation preview :books:: https://pep-previews--3313.org.readthedocs.build/
=> PEP 649, 652, 653, 665, 684, 690, 713, 727: fix typos

pep_sphinx_extensions/__init__.py, pep_sphinx_extensions/pep_zero_generator/writer.py
Closes #3321
----
:books: Documentation preview :books:: https://pep-previews--3322.org.readthedocs.build/
=> Ensure the ``:pep:`` role works properly with the dirhtml builder

pep-0703.rst
xref #3275
----
:books: Documentation preview :books:: https://pep-previews--3323.org.readthedocs.build/
=> PEP 703: Remove blank ``Resolution`` header

pep-0418.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3327.org.readthedocs.build/
=> PEP 418: Standardise authors

pep-0284.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3328.org.readthedocs.build/
=> PEP 284: Standardise authors

pep-0383.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3335.org.readthedocs.build/
=> PEP 383: Standardise authors

pep-0393.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3337.org.readthedocs.build/
=> PEP 393: Standardise authors

pep-0205.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3343.org.readthedocs.build/
=> PEP 205: Resolve dangling hyphens

pep-0209.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3344.org.readthedocs.build/
=> PEP 209: Resolve dangling hyphens

pep-0333.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3347.org.readthedocs.build/
=> PEP 333: Resolve dangling hyphens

pep-0344.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3348.org.readthedocs.build/
=> PEP 344: Resolve dangling hyphens

pep-0367.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3349.org.readthedocs.build/
=> PEP 367: Resolve dangling hyphens

pep-0451.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3352.org.readthedocs.build/
=> PEP 451: Resolve dangling hyphens

pep-0439.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3351.org.readthedocs.build/
=> PEP 439: Resolve dangling hyphens

pep-0520.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3358.org.readthedocs.build/
=> PEP 520: Resolve dangling hyphens

pep-3115.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3361.org.readthedocs.build/
=> PEP 3115: Resolve dangling hyphens

pep-0001.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3366.org.readthedocs.build/
=> PEP 1: Resolve uses of the default role

pep-0386.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3376.org.readthedocs.build/
=> PEP 386: Resolve uses of the default role

pep-3148.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3386.org.readthedocs.build/
=> PEP 3148: Resolve uses of the default role

pep-3146.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3384.org.readthedocs.build/
=> PEP 3146: Resolve uses of the default role

pep-0431.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3394.org.readthedocs.build/
=> PEP 431: Resolve uses of the default role

pep-0512.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3399.org.readthedocs.build/
=> PEP 512: Resolve uses of the default role

pep-0510.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3398.org.readthedocs.build/
=> PEP 510: Resolve uses of the default role

pep-3151.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3402.org.readthedocs.build/
=> PEP 3151: Resolve uses of the default role

pep-0440.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3395.org.readthedocs.build/
=> PEP 440: Resolve uses of the default role

pep-0448.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3403.org.readthedocs.build/
=> PEP 448: Resolve uses of the default role

pep-0006.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3367.org.readthedocs.build/
=> PEP 6: Resolve uses of the default role

pep-0468.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3408.org.readthedocs.build/
=> PEP 468: Resolve uses of the default role

pep-0458.txt
* Change is:
A
----
:books: Documentation preview :books:: https://pep-previews--3405.org.readthedocs.build/
=> PEP 458: Resolve uses of the default role

.pre-commit-config.yaml
----
:books: Documentation preview :books:: https://pep-previews--3415.org.readthedocs.build/
=> Lint: Enable pre-commit default role checks

.github/CODEOWNERS, conf.py, pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py, pep_sphinx_extensions/pep_processor/transforms/pep_footer.py, pep_sphinx_extensions/pep_theme/templates/page.html, pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py, pep_sphinx_extensions/pep_zero_generator/subindices.py, pep_sphinx_extensions/pep_zero_generator/writer.py, pep_sphinx_extensions/tests/conftest.py, pep_sphinx_extensions/tests/pep_processor/transform/test_pep_footer.py, pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py, pep_sphinx_extensions/tests/pep_zero_generator/test_pep_index_generator.py
These are changes split out of the forthcoming PR that can stand on their own:
- Remove a left over entry from CODEOWNERS
- Use absolute paths where appropriate instead of implicit CWD-relative paths
- Use absolute paths in the tests
- Use Sphinx-provided paths in PEP 0 generation
A
----
:books: Documentation preview :books:: https://pep-previews--3417.org.readthedocs.build/
=> Infra: Prepare for moving PEPs to a subfolder

build.py, docs/build.rst, docs/rendering_system.rst
- All warnings are resolved
- Nitpicky is now always on
- Use direct links to PEPs
- Remove AUTHOR_OVERRIDES
- Fix list indentation
Split off from #3418
----
:books: Documentation preview :books:: https://pep-previews--3420.org.readthedocs.build/
=> Update documentation and build.py

pep-0499.txt
* Change is:
Dear @cameron-simpson @Rosuav @llllllllll,
In pursuit of #3275 (more maintainable PEP checks), I found that PEP 499 is the only PEP with a title longer than 80 characters. I've proposed a re-wording in this PR, but clearly this should have the blessing of the authors before we go ahead.
Feel free to reject my proposed re-wording, but ideally we can come up with something within the limit.
Thanks,
Adam
*Adding the DO-NOT-MERGE tag until at least one of the authors approves.*
----
:books: Documentation preview :books:: https://pep-previews--3325.org.readthedocs.build/
=> PEP 499: Shorten the title

pep-0693.rst
----
:books: Documentation preview :books:: https://pep-previews--3426.org.readthedocs.build/
=> PEP 693: Update the Python 3.12.0rc2 release date.

pep-0713.rst
----
:books: Documentation preview :books:: https://pep-previews--3423.org.readthedocs.build/
=> PEP 713: Mark as Rejected

pep-0727.rst
* Change is:
cc: @tiangolo
Each commit addresses a distinct issue. The last 5 re-write various things I was unclear on or I thought could do with an edit -- I've also added the three missing headers from this PEP for filling in later.
As in the earlier review, my thoughts remain that the "Additional Scenarios" outlined should just be banned.
Feel free to ask for clarification on any of the suggested changes.
(I'll submit a PR to wrap to 79 columns per PEP-1 after this one, as that's a purely editorial change.)
A
----
:books: Documentation preview :books:: https://pep-previews--3316.org.readthedocs.build/
=> PEP 727: Review

.gitattributes
See https://github.com/github-linguist/linguist/blob/master/docs/overrides.md for context.
The updated 'languages' widget would look like:
A
----
:books: Documentation preview :books:: https://pep-previews--3430.org.readthedocs.build/
=> Meta: Instruct linguist to include PEPs in the statistics

.github/workflows/lint.yml, .pre-commit-config.yaml
I didn't get a chance to review https://github.com/python/peps/pull/3429 before merge, so here are some suggestions.
https://github.com/astral-sh/ruff-pre-commit says (emphasis mine):
> _Ruff's pre-commit hook should be placed after other formatting tools, such as Black_ and isort, unless you enable autofix, in which case, Ruff's pre-commit hook should run before Black, isort, and other formatting tools, as Ruff's autofix behavior can output code changes that require reformatting.
Also only enable GitHub formatting for GitHub Actions, not the user's local console.
And also remove `--diff`, it prevents the formatting and annotation.
----
:books: Documentation preview :books:: https://pep-previews--3433.org.readthedocs.build/
=> Lint: Update Ruff config

peps/pep-0696.rst
----
:books: Documentation preview :books:: https://pep-previews--3427.org.readthedocs.build/
=> PEP 696: Add section on binding rules

peps/pep-0693.rst
Fixes https://github.com/python/peps/issues/3444.
----
:books: Documentation preview :books:: https://pep-previews--3443.org.readthedocs.build/
=> PEP 693: Add Python 3.12.0rc3 release date

peps/pep-0724.rst
@erictraut pointed out the discussions to location was the wrong spot. Updating to the new peps discussion location.
----
:books: Documentation preview :books:: https://pep-previews--3446.org.readthedocs.build/
=> PEP 724: Add the current Discussions-To thread

peps/pep-0703.rst
As requested by @brettcannon (in https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-3-12-updates/26503/99) and more recently by @gpshead (https://discuss.python.org/t/nogil-installers-on-windows/34049/3)
----
:books: Documentation preview :books:: https://pep-previews--3445.org.readthedocs.build/
=> PEP 703: Use 't' for proposed ABI tag

CONTRIBUTING.rst, peps/pep-0001.rst
As noted [by Hugo](https://discuss.python.org/t/29129/28).
A
----
:books: Documentation preview :books:: https://pep-previews--3453.org.readthedocs.build/
=> PEP 1: Cease recommending Typing-SIG (it has ceased to be!)

peps/pep-0724.rst
@neilgirdhar [pointed out](https://discuss.python.org/t/pep-724-stricter-type-guards/34124/8) this other thread that seems relevant as well.
----
:books: Documentation preview :books:: https://pep-previews--3447.org.readthedocs.build/
=> PEP 724: Add the Rationale section

pep_sphinx_extensions/pep_theme/static/style.css, pep_sphinx_extensions/pep_zero_generator/parser.py, pep_sphinx_extensions/pep_zero_generator/writer.py, pep_sphinx_extensions/tests/pep_zero_generator/test_parser.py
For https://github.com/python/peps/issues/1012.
Came up today in https://discuss.python.org/t/list-of-future-commitments/33785/4?u=hugovk.
----
:books: Documentation preview :books:: https://pep-previews--3434.org.readthedocs.build/
=> Infra: Add Python version to PEP 0 tables

peps/pep-0703.rst
----
:books: Documentation preview :books:: https://pep-previews--3456.org.readthedocs.build/
=> PEP 703: typo fix, "with with" -> "with"

peps/pep-0695.rst
Fixes python/cpython#104600.
We realized that the attribute should be writable on functions and
classes for the benefit of wrappers such as @functools.wraps.
cc @erictraut 
----
:books: Documentation preview :books:: https://pep-previews--3457.org.readthedocs.build/
=> PEP 695: __type_params__ attribute is writable

peps/pep-0695.rst
----
:books: Documentation preview :books:: https://pep-previews--3461.org.readthedocs.build/
=> PEP 695: Fix a typo in a type parameter name

peps/pep-0282.rst
fix issue #3465 
----
:books: Documentation preview :books:: https://pep-previews--3470.org.readthedocs.build/
=> PEP 282: update the log4j link in references

peps/pep-0632.rst
----
:books: Documentation preview :books:: https://pep-previews--3468.org.readthedocs.build/
=> PEP 632: Mark as final

peps/pep-0701.rst
----
:books: Documentation preview :books:: https://pep-previews--3460.org.readthedocs.build/
=> PEP 701: Clarify that newlines also end format specifier mode

peps/pep-3121.rst
* [n/a] Any substantial changes since the accepted version approved by the SC/PEP delegate
(There have been changes since 3.0, and the 3.0 docs for this were in a [different place](https://docs.python.org/3.0/extending/newtypes.html), but the feature was implemented as specified.)
----
:books: Documentation preview :books:: https://pep-previews--3471.org.readthedocs.build/
=> PEP-3121: Mark as Final

CONTRIBUTING.rst
In the process of submitting [PEP730](https://github.com/python/peps/pull/3473), I was confused about the process of populating the PEP from a template. This PR adds a note to the contribution guide so others don't hit the same problem.
----
:books: Documentation preview :books:: https://pep-previews--3474.org.readthedocs.build/
=> Meta: Add a note about populating the PR from a template.

peps/pep-0658.rst
I noticed while I was reading it
----
:books: Documentation preview :books:: https://pep-previews--3479.org.readthedocs.build/
=> PEP 658: fix typo

peps/pep-0729.rst
* Remove a "now", which gets repeated in the next sentence.
* Add explanations behind PEP numbers.
* Move "conformance tests" behind "buy-in" items, seems it seems to me that buy-in should come before writing the tests.
@JelleZijlstra @hauntsaninja 
----
:books: Documentation preview :books:: https://pep-previews--3483.org.readthedocs.build/
=> [PEP 729] A few proposed small changes

peps/pep-0729.rst, peps/pep-0731.rst
As these PEPs don't propose changes to Python, the Python-Version
header doesn't really make sense. I had assumed the header was required
but it's not.
----
:books: Documentation preview :books:: https://pep-previews--3484.org.readthedocs.build/
=> PEP 729, 731: Remove Python-Version

peps/pep-0719.rst
https://discuss.python.org/t/python-3-13-0-alpha-1/36109
----
:books: Documentation preview :books:: https://pep-previews--3485.org.readthedocs.build/
=> PEP 719: The first alpha of 3.13 was released on Friday 13th

peps/pep-0729.rst, peps/pep-0731.rst
This will list them on the https://peps.python.org/topic/governance/ page.
----
:books: Documentation preview :books:: https://pep-previews--3487.org.readthedocs.build/
=> PEPs 729, 731: Apply Governance topic

peps/pep-0702.rst
See https://discuss.python.org/t/pep-702-marking-deprecations-using-the-type-system/23036/53?u=jelle
I don't want to prescribe the exact behavior on tools and IDEs; they
can figure out for themselves what works best. This change is intended
to make it so they can adjust the message without worrying that they
are breaking the specification.
----
:books: Documentation preview :books:: https://pep-previews--3482.org.readthedocs.build/
=> PEP 702: Tools may clean up the deprecation message

peps/pep-0696.rst
The latest discussion thread is now on discourse.
Cc @Gobot1234 @JelleZijlstra 
----
:books: Documentation preview :books:: https://pep-previews--3493.org.readthedocs.build/
=> PEP 696: Update the discussions to link

peps/pep-0705.rst
I also noticed a mistake in one heading as I was putting the discussion post together (`ReadOnly` is a type qualifier, not a flag).
----
:books: Documentation preview :books:: https://pep-previews--3492.org.readthedocs.build/
=> PEP 705 Link to new discussion thread

peps/pep-0698.rst
----
:books: Documentation preview :books:: https://pep-previews--3490.org.readthedocs.build/
=> PEP 698: Add missing "self" parameters to methods and a colon to a class

peps/pep-0705.rst
- Respecify `BandAndAlbum` from previous section to avoid having to bounce around between examples.
- `NamedDict` was incorrectly used as an example of a type with `other_keys=Never` specified when it didn't, but then also used as an example of a type with `readonly=True`. Rewrite the `other_keys=Never` example completely, and move the `NamedDict` declaration down to the first example that correctly uses it.
----
:books: Documentation preview :books:: https://pep-previews--3495.org.readthedocs.build/
=> PEP 705: Clean up examples in Inheritance section

peps/pep-3333.rst
Only bytestrings should be written to output.
----
:books: Documentation preview :books:: https://pep-previews--3497.org.readthedocs.build/
=> PEP 3333: Fix a TypeError in the example CGI Driver code

peps/pep-0730.rst
Following [community discussion](https://discuss.python.org/t/pep-730-adding-ios-as-a-supported-platform/35854/46), this PR updates PEP 730.
Summary:
* Removal of the `sys.implementation._simulator` attribute, in favor of an attribute on ``platform.ios_ver()``
* Clarification and simplification of values returned by ``platform`` to be a closer match of ``os.uname()``
* Normalisation of spelling of ``ios`` in wheel tags and sysconfig definitions
* Clarification of the use of the version number in wheel tags.
* A revised approach to framework naming
* Clarifications of the decision process around GNU compiler triples, universal wheels, and availability of an interactive REPL
* Adds an open issue around availability of x86_64 hardware for buildbots. 
* Some minor typos …
=> PEP 730: Revisions and clarifications following community discussion

check-peps.py, peps/pep-0536.rst
Fixes https://github.com/python/steering-council/issues/209
I’m unclear what the fields of the last point should be
----
:books: Documentation preview :books:: https://pep-previews--3510.org.readthedocs.build/
=> PEP 536: Mark as Withdrawn

peps/pep-0703.rst
(https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-in-cpython-acceptance/37075)
----
:books: Documentation preview :books:: https://pep-previews--3512.org.readthedocs.build/
=> PEP 703: Mark as Accepted

check-peps.py
In #3510, I accidentally typed
```rst
Post-History: `18-Aug-2016 <https://mail.python.org/...
>`__
```
instead of
```rst
Post-History: `18-Aug-2016 <https://mail.python.org/...>`__
```
This PR makes the check-peps script detect that case like this (I tweaked the message a bit since):
… instead of crashing like this:
----
:books: Documentation preview :books:: https://pep-previews--3511.org.readthedocs.build/
=> Make check-peps’ _validate_post_history crash less

peps/pep-0733.rst
Also remove redundant `Content-Type` (https://github.com/python/peps/pull/3454) and fix a typo.
----
:books: Documentation preview :books:: https://pep-previews--3518.org.readthedocs.build/
=> PEP 733: Add Post-History

peps/pep-0554.rst
The bulk of the new text comes from what I removed in gh-2812 (a48b58596028f8b4bfae9512a04a7e8698a67d49).
One notable addition: `Interpreter.set_main_attrs()` (and `Interpreter.get_main_attr()`).
(I expect I'll have a few more tweaks before I'm ready to merge this.)
----
:books: Documentation preview :books:: https://pep-previews--3498.org.readthedocs.build/
=> PEP 554: Clean Up and Add Channels Back In

.github/workflows/render.yml, Makefile, docs/build.rst, readthedocs.yaml
Making the Makefiles from here, [CPython Docs](https://github.com/python/cpython/blob/main/Doc/Makefile) and [devguide](https://github.com/python/devguide/blob/main/Makefile) more similar, makes things easier to use and maintain.
* Refactor Makefile to remove duplication and by re-using targets via variables (like https://github.com/python/devguide/pull/1207)
* Add `make linkcheck` to match CPython docs and devguide, deprecate `make check-links` (similar way to https://github.com/python/peps/pull/2968)
* Rename `OUTPUT_DIR` to `BUILDDIR` to match CPython docs and devguide
----
:books: Documentation preview :books:: https://pep-previews--3514.org.readthedocs.build/
=> Infra: Refactor Makefile

peps/pep-0723.rst
- https://discuss.python.org/t/pep-722-723-decision/36763/1
- https://discuss.python.org/t/pep-722-723-decision/36763/6
----
:books: Documentation preview :books:: https://pep-previews--3505.org.readthedocs.build/
=> PEP 723: Mark as Provisional

peps/pep-0723.rst
https://discuss.python.org/t/name-for-pep-723-style-dependency-declarations/37993/4
----
:books: Documentation preview :books:: https://pep-previews--3522.org.readthedocs.build/
=> PEP 723: Rename to `Inline script metadata`

peps/pep-0440.rst
Spec was migrated in https://github.com/pypa/packaging.python.org/pull/1340
----
:books: Documentation preview :books:: https://pep-previews--3527.org.readthedocs.build/
=> PEP 440: Link to PyPA spec

Makefile, requirements.txt
Add a `make htmllive` target to use https://github.com/executablebooks/sphinx-autobuild.
When you run it, it builds the docs and serves them at something like http://127.0.0.1:8000/
You can visit any page, for example http://127.0.0.1:8000/pep-0101.html, and when you edit/save your source `.rst` file, it will automatically rebuild and update the page in the browser.
This drastically improves the edit/inspect loop. A very nice touch is it will also keep you at the same position in the page.
Compare before:
1. switch to IDE: edit, save
2. switch to prompt: `make html`
3. switch to browser: reload, inspect
4. repeat
To this PR:
1. switch to IDE: edit, save
2. ~switch to prompt: `make html`~
3. switch to browser: ~reload,~ inspect
4. repeat
(There's still some slowness due to …
=> Infra: Add `make htmllive` to rebuild and reload HTML files in your browser

peps/pep-0733.rst
PySide was listed as a binding generator for Qt, but PySide is the final project.
The name of the used binding generator that PySide uses, is Shiboken.
----
:books: Documentation preview :books:: https://pep-previews--3533.org.readthedocs.build/
=> PEP 733: Adjust binding generator for Qt

pep_sphinx_extensions/pep_theme/static/mq.css
* Remove header.
* Remove TOC sidebar.
* Remove TOC header if closed.
* Use appropriate page margins and max-width.
* Remove underlines from links and abbreviations.
* Use more compact headings.
Closes: #3480
----
:books: Documentation preview :books:: https://pep-previews--3486.org.readthedocs.build/
=> Infra: Improve print style

peps/pep-0730.rst
A second pass of revisions and clarifications on PEP 730, adding Tier 3 iOS support.
* Adds an explicit mention of iPadOS
* Proposes linking binary modules with libPython to avoid a deprecated compiler option
* Proposes dropping static libPython.a builds as a supported output format
* Clarifies the compilation process and the relationship between the configure/make/make install build and the useable artefacts.
----
:books: Documentation preview :books:: https://pep-previews--3529.org.readthedocs.build/
=> PEP 730: More revisions and clarifications

peps/pep-0007.rst
See [discussion over at Discourse](https://discuss.python.org/t/all-caps-for-macro-parameter-names/37119?u=erlendaasland).
----
:books: Documentation preview :books:: https://pep-previews--3516.org.readthedocs.build/
=> PEP 7: Add C pre-processor macro style recommendations

peps/pep-0731.rst
----
:books: Documentation preview :books:: https://pep-previews--3540.org.readthedocs.build/
=> PEP 731: List initial members and mark Accepted

peps/pep-0729.rst
----
:books: Documentation preview :books:: https://pep-previews--3542.org.readthedocs.build/
=> PEP 729: Mark as Active

peps/pep-0702.rst
Spotted this typo because I was facing this issue:
```python
@deprecated("test", category=None)
@property
def prop(self) -> int:
...
```
This can be fixed by applying the `deprecated` decorator first, I don't know if it worth mentioning in the PEP or docs :shrug: 
----
:books: Documentation preview :books:: https://pep-previews--3548.org.readthedocs.build/
=> PEP 702: Fix typo

peps/pep-0602.rst
Thanks to @hugovk for [finding](https://github.com/python/peps/pull/3467#issuecomment-1754423150) an appropriate thread URL.
----
:books: Documentation preview :books:: https://pep-previews--3472.org.readthedocs.build/
=> PEP 602: Restore Post-History header

.github/CODEOWNERS, peps/pep-0554.rst, peps/pep-0734.rst
----
:books: Documentation preview :books:: https://pep-previews--3523.org.readthedocs.build/pep-0734/
=> PEP 734: Multiple Interpreters in the Stdlib

peps/pep-0683.rst
CC @eduardo-elizondo
----
:books: Documentation preview :books:: https://pep-previews--3519.org.readthedocs.build/
=> PEP 683: Update the Perf Regression With the Final Benchmark Results

peps/pep-0005.rst, peps/pep-0006.rst
These are both marked as Active, but neither represents current
practice.
PEP 5 has been replaced by PEP 387, the backwards compatibility policy.
PEP 6 concerns bugfix releases. The procedure for those is now
documented at https://devguide.python.org/developer-workflow/development-cycle/
----
:books: Documentation preview :books:: https://pep-previews--3547.org.readthedocs.build/
=> PEP 5, 6: Mark as Superseded

.github/CODEOWNERS, peps/pep-0735.rst
I have attempted to put this together correctly, as a PEP to address three desires which have been expressed in the community:
- projects which do not build wheels
- some standardized non-`extra` solution for dev dependency grouping
- a standardized replacement for (or variant of) `requirements.txt` files
However, it's my first time writing a PEP, so I'm learning the process a bit here.
I'll post a thread on discourse as soon as this is up in draft, which will require an update to the discussion link, I believe.
* @brettcannon has volunteered to be Sponsor on this; which I believe counts for this item? "formally confirmed their approval" might mean this isn't satisfied yet?
* ~I did not add myself; should I?~
* I have every intention of writing a (very simple) reference implementation, …
=> PEP 735: Dependency Groups in pyproject.toml

peps/pep-0001.rst
Implements aspects of PEP-729.
See also python/steering-council#222.
----
:books: Documentation preview :books:: https://pep-previews--3550.org.readthedocs.build/
=> PEP 1: Mention the Typing Council

Makefile
Like https://github.com/python/devguide/pull/1233.
When running `make htmllive`, this will open the browser when the docs have been built the first time. 
It means you don't need to hunt around for the link in:
```console
❯ make htmllive
venv already exists.
To recreate it, remove it first with `make clean-venv'.
.venv/bin/sphinx-autobuild -b html -j 8  --re-ignore="/\.idea/|/venv/|/pep-0000.rst|/topic/" --open-browser --delay 0 peps build
[sphinx-autobuild] > sphinx-build -b html -j 8 /Users/hugo/github/peps/peps /Users/hugo/github/peps/build
Running Sphinx v7.2.6
loading pickled environment... done
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 2 changed, 5 removed
reading sources... [100%] topic/typing
looking for now-outdated files... …
```
=> Infra: `make htmllive`: open browser when ready

peps/pep-0621.rst
The reference is not rendered, not used, and it doesn't exist.
----
:books: Documentation preview :books:: https://pep-previews--3564.org.readthedocs.build/
=> PEP 621: Remove invalid reference

peps/pep-0737.rst
----
:books: Documentation preview :books:: https://pep-previews--3560.org.readthedocs.build/
=> PEP 737: Add %N format, recommend fully qualified name

peps/pep-0664.rst
https://www.python.org/downloads/release/python-3117/
----
:books: Documentation preview :books:: https://pep-previews--3565.org.readthedocs.build/
=> PEP 664: Update 3.11.7 release date

peps/pep-0621.rst
The build has broken because PEP 621 uses intersphinx to refer to the canonical docs at https://packaging.python.org but they've re-organised things (https://github.com/pypa/packaging.python.org/pull/1396) and deleted the old reference:
```
/home/runner/work/peps/peps/peps/pep-0621.rst:23: WARNING: undefined label: 'packaging:declaring-project-metadata'
```
https://github.com/python/peps/actions/runs/7092751804/job/19304712978
I've opened https://github.com/pypa/packaging.python.org/pull/1434 to add back the old reference, but let's also change it here, we can unblock our build quicker.
----
:books: Documentation preview :books:: https://pep-previews--3563.org.readthedocs.build/pep-0621/
=> PEP 621: Fix reference to canonical spec

peps/pep-0725.rst
Changes include:
- Minor copy-edits
- Improvements to Examples (validated with a full proof-of-concept implementation of using the metadata added by this PEP for automated builds)
- Improve abstract to state briefly what the PEP adds to pyproject.toml
- Complete the "reference implementation" section
- Add section on split `pkg` / `pkg-dev` packages, as well as how to treat needing Python development headers (xref https://github.com/rgommers/peps/issues/10)
- And discussion (under Open Issues for now) on versioning and canonical names of virtual dependencies
Note that the contents were already reviewed by @pradyunsg and @msaharan over on https://github.com/rgommers/peps/pull/13, so this should be good to go.
----
:books: Documentation preview :books:: …
=> PEP 725: version 2, addressing review comments on Discourse to date

peps/pep-0668.rst
Spec was imported in https://github.com/pypa/packaging.python.org/pull/1372/files
----
:books: Documentation preview :books:: https://pep-previews--3532.org.readthedocs.build/pep-0668/
=> PEP 668: Link to PyPA spec

pep_sphinx_extensions/pep_theme/static/style.css, peps/pep-0008.rst
As suggested in https://github.com/python/docs-community/issues/22.
Like https://pep8.org, add green and red borders on the left side of "good" and "bad" code examples.
For example:
<table>
<tr>
<td><img width="815" alt="image" src="https://github.com/python/peps/assets/1324225/c6c0b717-293b-4625-ac4e-4fe9b9ccd384">
<td><img width="821" alt="image" src="https://github.com/python/peps/assets/1324225/664abaa8-8dd2-41e8-953a-5f911ef7f95d">
<tr>
<td>
<td>
</table>
(This PR also removes redundant `Version`, `Last-Modified` and `Content-Type` headers, and `Local Variables:` footer.)
We are not relying on colour to convey information; as before, the info about whether examples are good or bad is conveyed via the text.
We can later apply this to other good/bad code examples in other PEPs, such as …
=> PEP 8: Add green and red sidbar for good and bad examples

peps/pep-0634.rst
Link to https://docs.python.org/3/reference/compound_stmts.html#the-match-statement as the canonical docs, and remove some redundant headers.
cc @Fidget-Spinner 
----
:books: Documentation preview :books:: https://pep-previews--3576.org.readthedocs.build/pep-0634/
=> PEP 634: Mark as Final

peps/pep-0013.rst, peps/pep-8105.rst
----
:books: Documentation preview :books:: https://pep-previews--3580.org.readthedocs.build/
=> PEP-8105: Publish results

peps/pep-0448.rst
The passage in the PEP misleads its readers into believing, that unpacking in comprehensions is supported. This is not the case, as presented by the abstract itself:
> This PEP does not include unpacking operators inside list, set and  dictionary comprehensions although this has not been ruled out for future proposals.
See discussion in https://discuss.python.org/t/pep-448-contradictory-abstract/40657/6
----
:books: Documentation preview :books:: https://pep-previews--3573.org.readthedocs.build/
=> PEP 448: Fix misleading passage in the abstract

peps/pep-0693.rst
As is done for the other release schedule PEPs
----
:books: Documentation preview :books:: https://pep-previews--3578.org.readthedocs.build/
=> PEP 693: Add 3.12.1 release date

peps/pep-0727.rst
PEP 727: Specify `Doc` in type aliases documents the type alias symbol, update rejected ideas
----
:books: Documentation preview :books:: https://pep-previews--3581.org.readthedocs.build/
=> PEP 727: Specify `Doc` in type aliases documents the type alias symbol, update rejected ideas

peps/pep-0675.rst
Fixes https://github.com/python/docs-community/issues/22.
As suggested by @encukou in https://github.com/python/docs-community/issues/22, the dangerous "naive" SQL code could do with a red marker.
<table>
<tr>
<td>
<td>
</table>
Regarding accessibility, similar to https://github.com/python/peps/pull/3567, we're not relying on colour to convey meaning, it's also there in the text. ✅ 
Are there any examples in this PEP that could benefit from a red or green (or even yellow) sidebar? Perhaps the "written safely" one immediately after could be green?
Also remove the redundant headers.
----
:books: Documentation preview :books:: https://pep-previews--3574.org.readthedocs.build/
=> PEP 675: Mark malicious code example with red sidebar

peps/pep-0719.rst
* https://www.python.org/downloads/release/python-3130a2/
* https://discuss.python.org/t/python-3-13-0-alpha-2/39379
----
:books: Documentation preview :books:: https://pep-previews--3544.org.readthedocs.build/
=> PEP 719: 3.13.0a2 has been released

peps/pep-0726.rst
Zero is a non-negative number, but since zero is being excluded here, the check is really ensuring that it is a positive number.
----
:books: Documentation preview :books:: https://pep-previews--3562.org.readthedocs.build/
=> PEP 726: Fix error message description

README.rst, peps/pep-0426.rst
Hello,
I realize this is a minor thing, but I believe [Read the Docs](https://github.com/readthedocs) as an organization deserves their name to be written as they write it themselves, so I'd like to suggest changes that:
* replace `ReadTheDocs` with `Read the Docs`
* update a link to avoid a redirection
Best regards!
----
📚 Documentation preview 📚: https://pep-previews--3588.org.readthedocs.build/
=> Update Read the Docs name and URL

peps/pep-0709.rst
PEP 709 was implemented in Python 3.12, we should mark it as Final so it's no longer listed under [Accepted PEPs (accepted; may not be implemented yet)](https://peps.python.org/#accepted-peps-accepted-may-not-be-implemented-yet).
Should this have a `.. canonical-doc::` banner at the top to link to canonical docs?
For example, compare https://peps.python.org/pep-0634/
All I could find in the CPython docs is the [What's New entry](https://docs.python.org/3/whatsnew/3.12.html#pep-709-comprehension-inlining), but perhaps as an internal change, "canonical docs" doesn't apply in this instance?
----
📚 Documentation preview 📚: https://pep-previews--3591.org.readthedocs.build/
=> PEP 709: Mark as Final

peps/pep-0617.rst
Also replace some old BPO links with their more accessible GitHub issue equivalents, and update some code block formatting.
----
📚 Documentation preview 📚: https://pep-previews--3596.org.readthedocs.build/
=> PEP 617: Mark as Final

peps/pep-0617.rst
Follow on from https://github.com/python/peps/pull/3596.
Sorry for the second PR, I forgot to actually commit this for the first PR...
Using a Sphinx label is more reliable in case of later re-orgs.
----
📚 Documentation preview 📚: https://pep-previews--3597.org.readthedocs.build/
=> PEP 617: Update canonical link

peps/pep-0467.rst
----
📚 Documentation preview 📚: https://pep-previews--3603.org.readthedocs.build/
=> PEP 467: ascii constructors removed

peps/pep-0011.rst
----
📚 Documentation preview 📚: https://pep-previews--3612.org.readthedocs.build/
=> PEP 11: wasm32-unknown-emscripten is no longer supported

peps/pep-0735.rst
I didn't know how to title this, since it's a pretty broad set of things I worked up. In brief:
- Remove the PEP 723 use-case
- Change to non-normalized names which require normalization
- Update the reference implementation to normalize
- Clarify the meaning of an Include
- Forbid cycles in includes
- Add a section on validation and compatibility which clearly defines future-compatible behavior
- Remove 'include list' from open issues
- Add 'includes of `[project]` tables' to open issues
----
📚 Documentation preview 📚: https://pep-previews--3607.org.readthedocs.build/
=> PEP 735: 'Draft 3', updating to match current discussion

peps/pep-0011.rst
Just proposed text right now for discussion, but as the text of the policy requires a bit of interpretation (since Microsoft changes their lifecycle and set of releases frequently), I think it's worth writing our current intention in here.
----
📚 Documentation preview 📚: https://pep-previews--3617.org.readthedocs.build/
=> PEP 11: Add note about interpreting current Windows release

peps/pep-0495.rst, peps/pep-0732.rst
Improves accessibility, as recommended by PEP 12:
https://peps.python.org/pep-0012/#images
(Let's try and make sure images in new PEPs have alt text.)
Also centre the image in PEP 732; PEP 495's already are centred.
----
📚 Documentation preview 📚: https://pep-previews--3606.org.readthedocs.build/
=> PEP 495 and 732: Add alt text to images

.github/PULL_REQUEST_TEMPLATE/Mark a PEP Final.md, pep_sphinx_extensions/__init__.py, pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py, peps/conf.py, peps/pep-0012.rst, peps/pep-0612.rst
Link to https://docs.python.org/3/library/typing.html#typing.ParamSpec as the canonical docs, and remove a redundant header.
cc @Fidget-Spinner
----
:books: Documentation preview :books:: https://pep-previews--3575.org.readthedocs.build/pep-0612/
=> PEP 612: Mark as Final

peps/pep-0001.rst
Remove:
> (The delegate's email address is currently omitted due to a
limitation in the email address masking for reStructuredText PEPs.)
I don't know when this changed, but some 81 of 117 PEP-Delegate fields have email addresses.
----
📚 Documentation preview 📚: https://pep-previews--3622.org.readthedocs.build/
=> PEP 1: Remove outdated info about omitting delegate's email address

peps/pep-0737.rst
* Add `type.__format__()` method.
* Add more formats to `PyUnicode_FromFormat()`.
* Add `PyType_GetModuleName()` function.
----
📚 Documentation preview 📚: https://pep-previews--3589.org.readthedocs.build/
=> PEP 737: Add type.__format__() method

peps/pep-0719.rst
Update PEP 719 for 3.13.0a3's release, and adjust the future alpha's for the skipping of the Christmas alpha. Also drop the mention of "PEP-sized items" since we no longer try to keep track of PEPs for the release in the release schedule itself.
----
📚 Documentation preview 📚: https://pep-previews--3623.org.readthedocs.build/
=> PEP 719: Update for 3.13.0a3

peps/pep-0739.rst, peps/pep-9999.rst
----
📚 Documentation preview 📚: https://pep-previews--3599.org.readthedocs.build/
=> PEP 739: Static description file for Python installations

peps/pep-0011.rst
As announced in https://discuss.python.org/t/43534, I'm stepping down as the contact for powerpc64le.
This demotes the platform to Tier 3 (which is the right place for it, IMO).
----
📚 Documentation preview 📚: https://pep-previews--3632.org.readthedocs.build/
=> PEP 11: Move powerpc64le to tier 3

peps/pep-0739.rst
Just a minor visual improvement, as with raw text it becomes quite difficult to distinguish the smaller subsections.
----
📚 Documentation preview 📚: https://pep-previews--3634.org.readthedocs.build/
=> PEP 739: don't use raw text in specification titles

peps/pep-0735.rst
There are two commits here.
One is to fix some mistakes which were noted in the PEP thread.
The other adds a note to the Rationale section about designing the spec to allow for future extensions to the data.
Such "future compatibility" is an explicit goal of the PEP.
----
📚 Documentation preview 📚: https://pep-previews--3627.org.readthedocs.build/
=> PEP 735: Minor updates and fixes

peps/pep-0740.rst
Per PEP 1, I've opened a discussion thread here: https://discuss.python.org/t/pep-740-index-support-for-digital-attestations/44498.
----
📚 Documentation preview 📚: https://pep-previews--3635.org.readthedocs.build/
=> PEP 740: update discussions-to

peps/pep-0696.rst
See https://discuss.python.org/t/pep-696-type-defaults-for-typevarlikes/22569/20
=> PEP 696: Replace usages of TypeVarLike with type parameter

peps/pep-0011.rst
This loosens the statements about builds and configure needing to Break and instead changes this to a mere build/configure time warning. This is in line with how we treat platforms that are not on a support Tier (of which there are many).  Doing anything else would basically be unreasonable punshiment for anything in our support Tiers that then loses its official PEP-11 support for whatever reason.
Discuss this change in https://discuss.python.org/t/proposed-update-to-pep-11-on-unsupporting-a-platform-less-draconian-measures/44065
----
📚 Documentation preview 📚: https://pep-previews--3633.org.readthedocs.build/
=> PEP 11: Make unsupporting a platform less draconian

peps/pep-0705.rst
I think it's meant to say `Logs` instead of `UserAudit` here, as it's `Logs` that has a `timestamp` key in the example.
cc @alicederyn 
----
📚 Documentation preview 📚: https://pep-previews--3640.org.readthedocs.build/
=> PEP 705: fix typo in "Motivation" section.

peps/pep-0669.rst
----
📚 Documentation preview 📚: https://pep-previews--3615.org.readthedocs.build/
=> PEP 669: Mark final

peps/pep-0673.rst
Documented in the typing spec at https://typing.readthedocs.io/en/latest/spec/generics.html#self
----
📚 Documentation preview 📚: https://pep-previews--3644.org.readthedocs.build/
=> PEP 673: Mark as Final

peps/pep-0544.rst
----
📚 Documentation preview 📚: https://pep-previews--3646.org.readthedocs.build/
=> PEP 544: Mark as Final

peps/pep-0544.rst
Follow on from https://github.com/python/peps/pull/3646, _actually_ change the status to "Final" this time...
----
📚 Documentation preview 📚: https://pep-previews--3647.org.readthedocs.build/
=> PEP 544: Mark as Final (take 2)

peps/pep-0696.rst
I've made some suggested edits to the text for readability and fixed what I think is a typo in a code example. Feel free to reject any edits that don't make sense.
cc @Gobot1234 
----
📚 Documentation preview 📚: https://pep-previews--3641.org.readthedocs.build/
=> PEP 696: some suggestions to make the text clearer

peps/pep-0696.rst
A couple more proposed changes (likely the last ones from me):
* Consolidates discussion of usage of defaults in constraint solving in the "Function Defaults" section, to make it more obvious that this is experimental. Otherwise, I find it confusing for the abstract to mention a usage that is then not precisely specified.
* Adds a section that explicitly calls out that type parameter defaults don't affect subtyping.
cc @Gobot1234 
----
📚 Documentation preview 📚: https://pep-previews--3648.org.readthedocs.build/
=> PEP 696: consolidate discussion of constraint solving in "Function Defaults" section, add new "Subtyping" section

.github/CODEOWNERS
The https://github.com/python/peps/blob/main/.github/CODEOWNERS file is showing errors:
> This CODEOWNERS file contains errors
>
> Unknown owner on line 156: make sure @theller exists and has write access to the repository
> `peps/pep-0298.rst  @theller`
https://github.com/theller aka Thomas Heller hasn't been active on GitHub for a long time, and I presume  was removed from the https://github.com/python org as a result of requiring 2FA:
* https://github.com/python/steering-council/issues/91#issuecomment-1932716492
Thomas resigned as a committer in 2011: https://pythoninsider.blogspot.com/2011/04/thomas-heller-steps-down-as-ctypes.html. [PEP 298](https://peps.python.org/pep-0298/) was withdrawn in 2002, so it's unlikely to need updates and we don't need an explicit CODEOWNER for it. …
=> Meta: Remove theller from `CODEOWNERS`

peps/pep-0011.rst
Approved by the SC at https://github.com/python/steering-council/issues/223#issuecomment-1910376006 .
----
📚 Documentation preview 📚: https://pep-previews--3655.org.readthedocs.build/
=> PEP 11: promote `wasm32-wasi` to tier 2

peps/pep-0724.rst
----
📚 Documentation preview 📚: https://pep-previews--3656.org.readthedocs.build/
=> Withdrawing PEP 724.

peps/pep-0728.rst
I have posted the thread at https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443.
The headers have been updated. This should be ready for review, thanks! @JelleZijlstra 
----
📚 Documentation preview 📚: https://pep-previews--3658.org.readthedocs.build/
=> Add the "Discussions-To"/"Post-History" headers and fix a typo.

peps/pep-0728.rst
This update addresses @hugovk [comments](https://github.com/python/peps/pull/3441#pullrequestreview-1871689915).
----
📚 Documentation preview 📚: https://pep-previews--3659.org.readthedocs.build/
=> PEP 728: Fix formatting and code highlighting issues.

pep_sphinx_extensions/pep_processor/transforms/pep_footer.py, pep_sphinx_extensions/tests/pep_processor/transform/test_pep_footer.py
Add "peps/" to the URL.
----
📚 Documentation preview 📚: https://pep-previews--3653.org.readthedocs.build/
=> Fix HTML "Last Modified" link in the footer

peps/pep-0740.rst
Initial feedback from https://discuss.python.org/t/pep-740-index-support-for-digital-attestations/44498:
* Adds a point with the JSON API version bump (consistent with PEP 700, which bumped the minor version for a backwards-compatible change)
* Adds additional motivation/rationale context
----
📚 Documentation preview 📚: https://pep-previews--3637.org.readthedocs.build/
=> PEP 740: initial feedback

.github/CODEOWNERS, peps/pep-0483.rst, peps/pep-0742.rst
----
📚 Documentation preview 📚: https://pep-previews--3649.org.readthedocs.build/pep-0742/
=> PEP 742: TypeNarrower

peps/pep-0738.rst
Updates following [discussion on Discourse](https://discuss.python.org/t/pep-738-adding-android-as-a-supported-platform/40975):
* Reduce minimum Android API level from 23 to 21.
* Add more device information fields to `platform.android_ver`.
Other changes:
* State that a `python3.x` executable will not be officially supported on this platform. For the reasons explained in "App lifecycle", this would be of very little use.
* Add another reason why libpython must be dynamically linked.
* Add details of stdin, stdout, and stderr.
* Remove `spwd` from unsupported modules list, since it's already been removed from Python 3.13.
@freakboy3742: FYI
----
📚 Documentation preview 📚: https://pep-previews--3651.org.readthedocs.build/
=> PEP 738: Android support, draft 2

peps/pep-0586.rst
Helps https://github.com/python/peps/issues/3579 and #2872.
----
📚 Documentation preview 📚: https://pep-previews--3666.org.readthedocs.build/
=> PEP 586: Mark as Final

peps/pep-0589.rst
Helps https://github.com/python/peps/issues/3579 and #2872.
----
📚 Documentation preview 📚: https://pep-previews--3667.org.readthedocs.build/
=> PEP 589: Mark as Final

peps/pep-0591.rst
Helps https://github.com/python/peps/issues/3579 and #2872.
----
📚 Documentation preview 📚: https://pep-previews--3668.org.readthedocs.build/
=> PEP 591: Mark as Final

peps/pep-0675.rst
----
📚 Documentation preview 📚: https://pep-previews--3673.org.readthedocs.build/
=> PEP 675: Mark as Final

peps/pep-0698.rst
----
📚 Documentation preview 📚: https://pep-previews--3676.org.readthedocs.build/
=> PEP 698: Mark as Final

peps/pep-0681.rst
----
📚 Documentation preview 📚: https://pep-previews--3674.org.readthedocs.build/
=> PEP 681: Mark as Final

pep_sphinx_extensions/pep_theme/static/style.css
A "simple" list is one whose items all consist of a single paragraph, optionally followed by a nested list which is itself simple. Sphinx detects such lists and gives them the `simple` class, but does not make any other structural changes to the HTML output. 
The PEP style sheet currently does nothing with this class. As a result, when a list contains a mixture of single-paragraph and multi-paragraph items, it's common for a paragraph to appear closer to paragraphs of a different item than it is to other paragraphs of the same item. This obscures the logical structure of the text.
This PR fixes that by adding spacing between the items of "complex" (i.e. non-simple) lists, equal to the spacing between regular paragraphs. For example, in PEP 595:
<table><tr>
<td>
<a …
=> Infra: Increase spacing between complex list items

peps/pep-0655.rst
Also add green/yellow/red sidebars for the yes/okay/no codeblocks, similar to [PEP 8](https://peps.python.org/pep-0008/):
----
📚 Documentation preview 📚: https://pep-previews--3672.org.readthedocs.build/
=> PEP 655: Mark as Final

peps/pep-0613.rst
----
📚 Documentation preview 📚: https://pep-previews--3670.org.readthedocs.build/
=> PEP 613: Mark as Final

peps/pep-0688.rst
----
📚 Documentation preview 📚: https://pep-previews--3678.org.readthedocs.build/
=> PEP 688: Mark as Final

peps/pep-0692.rst
----
📚 Documentation preview 📚: https://pep-previews--3679.org.readthedocs.build/
=> PEP 692: Mark as Final

peps/pep-0604.rst
----
📚 Documentation preview 📚: https://pep-previews--3677.org.readthedocs.build/
=> PEP 604: Mark as Final

peps/pep-0695.rst
----
📚 Documentation preview 📚: https://pep-previews--3675.org.readthedocs.build/
=> PEP 695: Mark as Final

peps/pep-0718.rst
----
📚 Documentation preview 📚: https://pep-previews--3631.org.readthedocs.build/
=> PEP 718: More rationale, use-cases and expansion on monomorphisation

peps/pep-0728.rst
This updates mainly three things:
- Spec out the `closed=True` proposal and use `__extra_items__` as the special key name
- Enhance `extra=Type` discussion under the "Rejected Ideas" section
- Discuss the interaction between closed vs. non-closed TypedDict.
----
📚 Documentation preview 📚: https://pep-previews--3680.org.readthedocs.build/
=> PEP 728: Incorporate feedback from discussions

peps/pep-0664.rst, peps/pep-0693.rst, peps/pep-0719.rst
* https://www.python.org/downloads/release/python-3118/
* https://www.python.org/downloads/release/python-3122/
* https://www.python.org/downloads/release/python-3130a4/
----
📚 Documentation preview 📚: https://pep-previews--3681.org.readthedocs.build/
=> PEP 664, 694, 719: Update 3.11.8, 3.12.2 and 3.13.0a4 release dates

peps/pep-0732.rst
----
📚 Documentation preview 📚: https://pep-previews--3663.org.readthedocs.build/
=> PEP 732: Specify that the Python Wiki is not in scope

peps/pep-0742.rst
* Awaitable example changed in accordance with https://discuss.python.org/t/pep-742-narrowing-types-with-typeis/45613/22
* bool compatibility rule changed following python/typing#1637
----
📚 Documentation preview 📚: https://pep-previews--3696.org.readthedocs.build/
=> PEP 742: Allow inferring the intersection type; carry over TypeGuard spec change

peps/pep-0738.rst
This PR clarifies the following points which were [raised on Discourse](https://discuss.python.org/t/pep-738-adding-android-as-a-supported-platform/40975/19):
* The availability of buildbots and GitHub Actions resources for testing Python on Android. 
* That the supported build platforms for Android will be Linux and macOS.
----
📚 Documentation preview 📚: https://pep-previews--3700.org.readthedocs.build/
=> PEP 738: clarify Android CI availability

.github/CODEOWNERS, peps/pep-0741.rst
* Add sys.get_config_names() function.
* Add PyInitConfig_HasOption() function.
* Remove Py_ExitWithInitConfig() function.
* Add "Fully remove the preinitialization" section.
* Mention when the caller must hold the GIL.
* Add example increasing an initialization configuration option.
* "Usage of the stable ABI" section: add more quotes.
* Document that options side effects are not taken in account by PyInitConfig_Set*() functions.
----
📚 Documentation preview 📚: https://pep-previews--3686.org.readthedocs.build/
=> PEP 741: Add sys.get_config_names()

peps/pep-0736.rst
Adds a reference to the new discourse discussion.
----
📚 Documentation preview 📚: https://pep-previews--3708.org.readthedocs.build/
=> PEP 736: Add reference to new discussion

peps/pep-0737.rst
PR related to the Steering Council decision: https://discuss.python.org/t/pep-737-unify-type-name-formatting/39872/50
cc @warsaw @gpshead
----
📚 Documentation preview 📚: https://pep-previews--3704.org.readthedocs.build/
=>  PEP 737: Remove Python changes

.github/CODEOWNERS
I don't need to be specifically assigned each time someone adds a new PEP and themselves to CODEOWNERS.
----
📚 Documentation preview 📚: https://pep-previews--3716.org.readthedocs.build/
=> Meta: Reduce CODEOWNERS for hugovk

Makefile
Similar to https://github.com/python/devguide/pull/1291, announce the creation of the venv before a stream of scary package installation messages appear.
----
📚 Documentation preview 📚: https://pep-previews--3729.org.readthedocs.build/
=> docs: announce venv creation before installing packages

peps/pep-3156.rst
----
📚 Documentation preview 📚: https://pep-previews--3733.org.readthedocs.build/
=> PEP 3156: Fix a style error caused by extra spaces

peps/pep-0563.rst, peps/pep-0649.rst
According to PEP 649, which is now Accepted:
> If accepted, this PEP would supersede [PEP 563](https://peps.python.org/pep-0563/), and [PEP 563](https://peps.python.org/pep-0563/)’s behavior would be deprecated and eventually removed.
Therefore I'm updating the metadata:
* on PEP 649 to reflect that it supersedes PEP 563 and
* on PEP 563 to reflect that it is replaced by PEP 649.
----
📚 Documentation preview 📚: https://pep-previews--3701.org.readthedocs.build/
=> PEP 649 replaces 563

peps/pep-0700.rst
The new `size` and `upload-time` fields have been documented in the spec: 
* https://packaging.python.org/en/latest/specifications/simple-repository-api/#additional-file-information
And have been implemented at least in:
* PyPI: https://github.com/pypi/warehouse/pull/12727
* Bandersnatch: https://github.com/pypa/bandersnatch/pull/1557
* pypi-simple: https://github.com/jwodder/pypi-simple/issues/5
* Mousebender: https://github.com/brettcannon/mousebender/pull/93
----
📚 Documentation preview 📚: https://pep-previews--3643.org.readthedocs.build/pep-0700/
=> PEP 700: Mark as Final

peps/pep-0647.rst
Was meant to be be marked as Final in https://github.com/python/peps/pull/3577, I added the link to the canonical docs there but I forgot to actually change the status...
Take 2!
----
📚 Documentation preview 📚: https://pep-previews--3737.org.readthedocs.build/
=> PEP 647: Mark as Final (take 2)

peps/pep-0569.rst, peps/pep-0596.rst, peps/pep-0619.rst, peps/pep-0719.rst
Python 3.8.19, 3.9.19, and 3.10.14 were released on March 19, 2024:
* https://discuss.python.org/t/python-3-10-14-3-9-19-and-3-8-19-is-now-available/48993
* https://www.python.org/downloads/release/python-3819/
* https://www.python.org/downloads/release/python-3919/
* https://www.python.org/downloads/release/python-31014/
Python 3.13a5 was released on March 12, 2024:
* https://discuss.python.org/t/python-3-13-0-alpha-5/48341
* https://www.python.org/downloads/release/python-3130a5/
----
📚 Documentation preview 📚: https://pep-previews--3735.org.readthedocs.build/
=> PEPs 569, 596, 619, 719: Update release dates

peps/pep-0007.rst
* Remove the section "For C code that needs to support versions of Python older than 2.3...". I can add it back if needed.
* Highlight the example C code with C syntax instead of Python.
* Like PEP 8 (https://github.com/python/peps/pull/3567), add green and red side borders "good" and "bad" examples. For this, I split this example into two blocks:
```c
return albatross; /* correct */
return(albatross); /* incorrect */
```
* Format None as `None`, add a missing full stop. Remove some redundant PEP fields.
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
----
📚 Documentation preview 📚: https://pep-previews--3702.org.readthedocs.build/pep-0007/
=> PEP 7: Remove Python 2.2 advice, add C syntax highlighting and green/red sidebars

peps/pep-0664.rst
Similar to the others:
* https://peps.python.org/pep-0619/#bugfix-releases
* https://peps.python.org/pep-0596/#bugfix-releases
Sorry for missing in https://github.com/python/peps/pull/3745 :)
----
📚 Documentation preview 📚: https://pep-previews--3746.org.readthedocs.build/
=> PEP 664: 3.11.9 is the final regular bugfix release with binary installers

peps/pep-0101.rst
This step says:
> NOTE, check with Steve Dower about this step, it is probably obsolete.
It was added in https://github.com/python/peps/commit/f2ada91bbec53eeafeac171449e163964de6d13e.
@zooba Is it obsolete? Can it be removed, or does it need updating?
----
📚 Documentation preview 📚: https://pep-previews--3750.org.readthedocs.build/
=> PEP 101: Update Windows version bump step

.github/CODEOWNERS, peps/pep-0744.rst
----
📚 Documentation preview 📚: https://pep-previews--3751.org.readthedocs.build/pep-0744/
=> PEP 744: JIT Compilation

peps/pep-0560.rst
I was looking for this PEP on 
https://peps.python.org/topic/typing/ but because
it's missing the label, the sphinx pep_zero_generator skipped this one.
----
📚 Documentation preview 📚: https://pep-previews--3753.org.readthedocs.build/
=> PEP 560: Add Typing label

peps/pep-0003.rst, peps/pep-0009.rst, peps/pep-0042.rst, peps/pep-0103.rst, peps/pep-0204.rst, peps/pep-0211.rst, peps/pep-0216.rst, peps/pep-0224.rst, peps/pep-0225.rst, peps/pep-0239.rst, peps/pep-0242.rst, peps/pep-0363.rst, peps/pep-0426.rst
Follow on from https://github.com/python/peps/pull/3682.
Re: https://github.com/python/peps/pull/3682#issuecomment-2054071526
And remove text duplicating that inserted by the template.
Previews:
* https://pep-previews--3756.org.readthedocs.build/pep-0003/
* https://pep-previews--3756.org.readthedocs.build/pep-0009/
* https://pep-previews--3756.org.readthedocs.build/pep-0042/
* https://pep-previews--3756.org.readthedocs.build/pep-0103/
* https://pep-previews--3756.org.readthedocs.build/pep-0204/
* https://pep-previews--3756.org.readthedocs.build/pep-0206/
* https://pep-previews--3756.org.readthedocs.build/pep-0209/
* https://pep-previews--3756.org.readthedocs.build/pep-0210/
* https://pep-previews--3756.org.readthedocs.build/pep-0211/
* …
=> Infra: add newlines so admonition text is shown

peps/pep-0101.rst
Changes mainly in presentation, not in substance.
* Remove redundant PEP headers and emacs metadata
* Default to `shell` highlight, the blocks are mainly commands to run
* Remove `$` from code blocks to make commands easier to copy/paste and run
* A lot of formatting fixes, such as reducing indents to make stuff no longer blockquoted
* Add/update links
* Some typos, minor wording
----
📚 Documentation preview 📚: https://pep-previews--3755.org.readthedocs.build/pep-0101/
=> PEP 101: Formatting, links, typos

peps/pep-0257.rst
We no longer need this Python 2 advice:
> For Unicode docstrings, use``u"""Unicode triple-quoted strings"""``.
Also:
* Update links
* Remove redundant headers and emacs footer
----
📚 Documentation preview 📚: https://pep-previews--3748.org.readthedocs.build/
=> PEP 257: Remove outdated Unicode docstring advice

peps/pep-0602.rst
PEP 602 is a [Process PEP](https://peps.python.org/pep-0001/#pep-types) rather than Informational or Standards Track:
> A **Process** PEP describes a process surrounding Python, or proposes a change to (or an event in) a process. Process PEPs are like Standards Track PEPs but apply to areas other than the Python language itself. They may propose an implementation, but not to Python’s codebase; they often require community consensus; unlike Informational PEPs, they are more than recommendations, and users are typically not free to ignore them. Examples include procedures, guidelines, changes to the decision-making process, and changes to the tools or environment used in Python development. Any meta-PEP is also considered a Process PEP.
And …
=> PEP 602: Mark as Active Process

requirements.txt
[Sphinx 7.3.0-7.3.5](https://www.sphinx-doc.org/en/master/changes.html) have just been released and for some reason a lot of PEPs are now 404, for example: https://peps.python.org/pep-0719/
Here are the missing directories at https://github.com/python/peps/tree/gh-pages:
<details>
<summary>Details</summary>
```
pep-0465
pep-0466
pep-0467
pep-0468
pep-0469
pep-0470
pep-0471
pep-0472
pep-0473
pep-0474
pep-0475
pep-0476
pep-0477
pep-0478
pep-0479
pep-0480
pep-0481
pep-0482
pep-0483
pep-0484
pep-0485
pep-0486
pep-0487
pep-0488
pep-0489
pep-0490
pep-0491
pep-0492
pep-0493
pep-0494
pep-0495
pep-0496
pep-0497
pep-0498
pep-0499
pep-0500
pep-0501
pep-0502
...
pep-0565
pep-0566
pep-0567
pep-0568
pep-0569
pep-0570
pep-0571
pep-0572
pep-0573
pep-0574
pep-0575
pep-0576
pep-0577
pep-0578
pep-0579 …
```
=> Infra: Skip Sphinx 7.3 to fix missing 404s

peps/pep-0558.rst
PEP 667 no longer breaks C API compatibility and has a working reference implementation for 3.13, so switch this PEP from Deferred to Withdrawn (in favour of PEP 667)
----
📚 Documentation preview 📚: https://pep-previews--3762.org.readthedocs.build/
=> Withdraw PEP 558 in favour of PEP 667

peps/pep-0011.rst, peps/pep-0730.rst
The work to implement PEP 730 (see python/cpython#114099) is now complete. 
This PR adds details about the minor changes to the accepted PEP introduced by the review process, and formalises iOS in the PEP 11 Tier 3 list.
----
📚 Documentation preview 📚: https://pep-previews--3761.org.readthedocs.build/
=> Finalize PEP 730, and add iOS to PEP 11

.github/workflows/render.yml, pep_sphinx_extensions/__init__.py, requirements.txt
This seems to fix things -- see https://aa-turner.github.io/peps/pep-0465/
A
xref:
* #3759 
* #3758
----
📚 Documentation preview 📚: https://pep-previews--3760.org.readthedocs.build/
=> Infra: Fix 404s

.github/workflows/test.yml
Fixes https://github.com/python/peps/pull/3760#issuecomment-2071968850.
Re: https://github.com/actions/setup-python/issues/696#issuecomment-1637587760.
There's a couple of similar ways to do this, for this workflow the difference is mostly cosmetic.
Any preferences?
---
This PR: keep 3.9 in the matrix (it adds Windows, Ubuntu and `macos-latest`), then remove 3.9/`macos-latest` and include 3.9/`macos-13`:
<details>
<summary>diff</summary>
```diff
diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
index 70a62762..5fef7979 100644
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -39,6 +39,13 @@ jobs:
- "windows-latest"
- "macos-latest"
- "ubuntu-latest"
+        # Python 3.9 is on macos-13 but not macos-latest (macos-14-arm64)
+        # …
```
=> Infra: Fix Python 3.9 on CI

.github/CODEOWNERS, peps/pep-0745.rst
Tentative schedule based on the initial 3.13 schedule ([PEP 719](https://peps.python.org/pep-0719/)).
----
📚 Documentation preview 📚: https://pep-previews--3764.org.readthedocs.build/
=> PEP 745: Python 3.14 release schedule

peps/pep-0639.rst, peps/pep-0639/appendix-examples.rst, peps/pep-0639/appendix-license-survey.rst, peps/pep-0639/appendix-rejected-ideas.rst, peps/pep-0639/appendix-user-scenarios.rst
To be rebased on #3727 once merged.
It's best to review section by section rather than by commits.
=> PEP 639: Post-split edits (language simplification, deeper edits of sections)

peps/pep-0723.rst
- Documented: https://packaging.python.org/en/latest/specifications/inline-script-metadata/
- Implemented:
- Hatch: https://hatch.pypa.io/latest/how-to/run/python-scripts/
- pip-run: https://github.com/jaraco/pip-run/tree/v12.6.1#script-declared-dependencies
----
📚 Documentation preview 📚: https://pep-previews--3772.org.readthedocs.build/
=> PEP 723: Mark as final

peps/pep-0668.rst
This commit updates the the link from the former, unofficial nixos wiki page to the new https://wiki.nixos.org
ref: NixOS/foundation#113
----
📚 Documentation preview 📚: https://pep-previews--3775.org.readthedocs.build/
=> PEP 668: Update link to official NixOS wiki

peps/pep-0667.rst
----
📚 Documentation preview 📚: https://pep-previews--3784.org.readthedocs.build/pep-0667/
=> PEP 667: Mark as Accepted

peps/pep-0741.rst
* Remove string types other than UTF-8.
* Exclude the API from the limited C API.
* Remove the explicit preconfiguration.
* Remove the rationale about the limited C API / stable ABI.
----
📚 Documentation preview 📚: https://pep-previews--3789.org.readthedocs.build/
=> PEP 741: Address Steering Council's review

Makefile, peps/conf.py, peps/pep-0594.rst
When Python 3.13 is released in October, the links to the removed batteries in the main docs will be broken.
Let's link to the last version they were included, 3.11 or 3.12.
Also:
* Add `pypi` extlink role
* Use roles for linking to modules and PyPI packages
* Fix make linkcheck target
* Fix some broken links
* Remove redundant PEP fields
----
📚 Documentation preview 📚: https://pep-previews--3778.org.readthedocs.build/
=> PEP 594: Re-link removed batteries to last included version

Makefile, requirements.txt
The 3.13-dev CI build has started failing: https://github.com/python/peps/actions/runs/9256853760/job/25463759359
The reason and fix is the same as https://github.com/python/cpython/pull/119607.
----
📚 Documentation preview 📚: https://pep-previews--3796.org.readthedocs.build/
=> Infra: Only install sphinx-autobuild for `make htmllive`

Makefile
It's not unusual that I might run `make htmllive` for a pair of CPython docs, devguide and PEPs at the same time.
To avoid clashes, use a randomly-chosen ["ephemeral port"](https://en.wikipedia.org/wiki/Ephemeral_port) between 49152–65535 for the local server for each of devguide and PEPs.
```python
python -c "import random; print(random.randint(49152, 65535))"
```
Also use the more descriptive Sphinx long options (added in [7.3.0](https://www.sphinx-doc.org/en/master/changes.html#release-7-3-0-released-apr-16-2024)) for the Makefile. 
See also https://github.com/python/devguide/pull/1327.
----
📚 Documentation preview 📚: https://pep-previews--3792.org.readthedocs.build/
=> Infra: Define port for htmllive to avoid collisions

peps/pep-0741.rst
* Soft deprecate the PyConfig API.
* Remove PyInitConfig_CreatePython().
* Rename PyInitConfig_CreateIsolated() to PyInitConfig_Create().
* Rejected Ideas: locale encoding and wide strings.
----
📚 Documentation preview 📚: https://pep-previews--3800.org.readthedocs.build/
=> PEP 741: Update

peps/pep-0667.rst
Fixed an editorial issue in the accepted PEP 667: redundancy in the phrase "will be always be visible.".
----
📚 Documentation preview 📚: https://pep-previews--3803.org.readthedocs.build/
=> PEP 667: Fix word duplication

.readthedocs.yaml, Makefile
Like https://github.com/python/devguide/pull/1320.
Using uv to install dependencies is quicker than pip.
On Read the Docs, it adds 1 second to install uv, and then cuts the docs build time from 134s -> 115s, overall reduces the time from 146s -> 129s.
pip: https://beta.readthedocs.org/projects/hugovk-peps/builds/24491058/
uv: https://beta.readthedocs.org/projects/hugovk-peps/builds/24491059/
Locally, running `make clean; time make venv` with a warm cache goes from 8.6s -> 0.5s:
* pip: `make venv  4.49s user 0.94s system 63% cpu 8.586 total`
* uv: `make venv  0.04s user 0.12s system 34% cpu 0.461 total`
`make html` is the same for both.
Overall, `make clean html` goes from 1m26s -> 1m09s.
----
📚 Documentation preview 📚: https://pep-previews--3791.org.readthedocs.build/
=> Infra: makefile/RTD: Use uv if installed

peps/pep-0667.rst
PyFrame_GetLocals was already added back in Python 3.11, so PEP 667 is changing it rather than adding it.
(Discrepancy picked up while writing the C API docs update)
----
📚 Documentation preview 📚: https://pep-previews--3793.org.readthedocs.build/
=> PEP 667: PyFrame_GetLocals is no longer new

peps/pep-0590.rst
This is still listed under "[Accepted PEPs (accepted; may not be implemented yet)](https://peps.python.org/#accepted-peps-accepted-may-not-be-implemented-yet)".
If it's fully implemented, let's mark it as Final and add a banner linking to the canonical docs at https://docs.python.org/3/c-api/call.html#vectorcall.
Also remove a redundant header and footer.
----
📚 Documentation preview 📚: https://pep-previews--3598.org.readthedocs.build/
=> PEP 590: Mark as Final

peps/pep-8104.rst, peps/pep-8105.rst
The 2023 and 2024 SC elections are complete.
Also remove the redundant `Content-Type: text/x-rst` header and fix a typo.
----
📚 Documentation preview 📚: https://pep-previews--3808.org.readthedocs.build/
=> PEPs 8104, 8105: Mark as Final

peps/pep-0581.rst
Helps https://github.com/python/peps/issues/2872, which says:
> [PEP-581](https://peps.python.org/581) _Using GitHub Issues for CPython_: Since the PEP's content is tightly focused on the rationale for choosing GitHub rather than the current, active process for using it and is thus now of historical rather than procedural value, it should be marked Final (rather than Active) like other transition-oriented Process PEPs have.
Also remove some redundant fields.
----
📚 Documentation preview 📚: https://pep-previews--3807.org.readthedocs.build/
=> PEP 581: Mark as Final

peps/pep-0578.rst
Fixes https://github.com/python/peps/issues/2872.
Also:
* Fix broken licence link. http://www.opencontent.org/openpub/ has a 500 internal server error. Looks like the whole site is down. https://web.archive.org/web/20190228180246/https://www.opencontent.org/openpub/ is an archive from around the time the PEP was published, and I've verified the body text matches https://spdx.org/licenses/OPUBL-1.0.html (other than whitespace) which I've used as a replacement.
* Update a couple of redirecting links.
* Replace some non-breaking spaces with real spaces.
This is the last unchecked PEP in https://github.com/python/peps/issues/2872. Let's close it now, and use new issues such as …
=> PEP 578: Mark as Final

peps/pep-0684.rst
Also remove redundant ``Content-Type`` field.
I guess this PEP doesn't need a ``canonical-doc`` directive
----
📚 Documentation preview 📚: https://pep-previews--3810.org.readthedocs.build/
=> PEP 684: Mark as Final

Makefile
Follow on from https://github.com/python/peps/pull/3791 and https://github.com/python/peps/pull/3796. 
Before:
```console
❯ make clean htmllive
rm -rf .venv
rm -rf build topic
Creating venv in .venv
Using Python 3.12.3 interpreter at: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3
Creating virtualenv at: .venv
Activate with: source .venv/bin/activate
Resolved 26 packages in 67ms
Installed 26 packages in 57ms
+ alabaster==0.7.16
+ babel==2.15.0
+ certifi==2024.6.2
+ charset-normalizer==3.3.2
+ coverage==7.5.3
+ docutils==0.21.2
+ idna==3.7
+ imagesize==1.4.1
+ iniconfig==2.0.0
+ jinja2==3.1.4
+ markupsafe==2.1.5
+ packaging==24.0
+ pluggy==1.5.0
+ pygments==2.18.0
+ pytest==8.2.1
+ pytest-cov==5.0.0
+ requests==2.32.3
+ snowballstemmer==2.2.0
+ sphinx==7.3.7
+ …
```
=> Infra: Fix `make clean htmllive`

peps/pep-0749.rst
- Reject "make it a no-op forever"
- Use the name "annotationlib"
----
📚 Documentation preview 📚: https://pep-previews--3823.org.readthedocs.build/
=> PEP 749: Updates from discussion

peps/pep-0745.rst
I've had this email address for a year, and I think this is the only public place it's been posted. I only started getting spam to it a couple of weeks after publishing it here.
[PEP 1 says it's optional](https://peps.python.org/pep-0001/#pep-header-preamble), let's see if removing it makes any difference or if it's too late now!
----
📚 Documentation preview 📚: https://pep-previews--3820.org.readthedocs.build/
=> PEP 745: Remove my email

peps/pep-0749.rst
The name `annotationlib` is mentioned through, but the examples use `annotations` instead. This commit fixes that.
----
📚 Documentation preview 📚: https://pep-previews--3833.org.readthedocs.build/
=> PEP 749: use `annotationlib` as the proposed module name throughout

pep_sphinx_extensions/__init__.py, pep_sphinx_extensions/generate_rss.py, pep_sphinx_extensions/pep_theme/templates/page.html
Fixes https://github.com/python/peps/issues/2919.
Use the PEP abstract for `<meta property="og:description">` and `<meta name="description">`.
If the abstract is not found, use the introduction. If that's not found, use the current default of "Python Enhancement Proposals (PEPs)".
The abstract and intros cover 631 / 652 PEPs, which is good enough.
(The abstract alone covers 594 / 652, which might be enough to remove a few extra lines here?)
Trim the description to 256 characters, and escape things like double quotes.
----
📚 Documentation preview 📚: https://pep-previews--3801.org.readthedocs.build/
=> Infra: Use PEP abstract/introduction as HTML and OG description

pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py, peps/pep-0012.rst, peps/pep-0526.rst, peps/pep-0544.rst, peps/pep-0560.rst, peps/pep-0585.rst, peps/pep-0586.rst, peps/pep-0589.rst, peps/pep-0591.rst, peps/pep-0593.rst, peps/pep-0612.rst, peps/pep-0613.rst, peps/pep-0647.rst, peps/pep-0655.rst, peps/pep-0673.rst, peps/pep-0675.rst, peps/pep-0681.rst, peps/pep-0698.rst
The new banners we have the top of many of the typing PEPs, taking people to the typing spec, are great. The typing spec generally only details how these special forms, decorators or classes should be interpreted by _type checkers_, however. Lots of these PEPs also introduced objects that were added to the runtime typing module, and if you're interested in how these objects behave at runtime, the docs at CPython are still usually the best place to go for details.
This PR adds additional links to the CPython docs for many of these typing PEPs. It also updates the wording of the banner, so that it's clear that the typing spec is not necessarily the sole source of documentation on these objects. Lastly, there are a couple of typing PEPs that don't yet have a "canonical banner" at the top; I …
=> Many typing PEPs: add more links to canonical docs

peps/pep-0746.rst
Rewords part of the specification, to make it clearer what type checkers should be validating and what should happen when `__supports_type__` has the wrong type.
cc @adriangb 
----
📚 Documentation preview 📚: https://pep-previews--3828.org.readthedocs.build/
=> PEP 746: small clarification to specification.

peps/pep-0683.rst
Helps #3817
----
📚 Documentation preview 📚: https://pep-previews--3824.org.readthedocs.build/
=> PEP 683: Mark Final

.github/CODEOWNERS, peps/pep-2026.rst
----
📚 Documentation preview 📚: https://pep-previews--3834.org.readthedocs.build/pep-2026/
=> PEP 2026: Calendar versioning for Python

peps/pep-0735.rst
This changes the key used in PEP 735 Dependency Group Includes to be 'include-group'. Per feedback, and related to discussions about the future direction of the PEP, this key will be less ambiguous when Dependency Group Includes appear in other contexts and tables.
----
📚 Documentation preview 📚: https://pep-previews--3836.org.readthedocs.build/
=> PEP 735: rename 'include' to 'include-group'

peps/pep-0012.rst
----
📚 Documentation preview 📚: https://pep-previews--3827.org.readthedocs.build/
=> PEP 12: Extract Intersphinx section. Add example of Intersphinx reference.

peps/pep-0592.rst
----
📚 Documentation preview 📚: https://pep-previews--3844.org.readthedocs.build/
=> PEP 0592: typo "awhile ago" → "a while ago"

peps/pep-0646.rst
Fixes python/cpython#115528.
----
📚 Documentation preview 📚: https://pep-previews--3832.org.readthedocs.build/
=> PEP 646: Mark Final

peps/pep-0719.rst
* https://discuss.python.org/t/python-3-13-0-beta-3-now-available/56847
* https://www.python.org/downloads/release/python-3130b3/
----
📚 Documentation preview 📚: https://pep-previews--3854.org.readthedocs.build/
=> PEP 719: Update 3.13.0b3 release date

peps/pep-0639.rst, peps/pep-0639/appendix-rejected-ideas.rst
The most significant changes:
- allowing custom SPDX identifiers per SPDX specification
- making `License-Expression` and `License` fields mutually exclusive
- not recommending a single reference library for expression parsing and validation
----
📚 Documentation preview 📚: https://pep-previews--3835.org.readthedocs.build/
=> PEP 639: Apply changes to the draft based on the Discourse thread

peps/pep-0667.rst
Changed __slots__ in FrameLocalsProxy
----
📚 Documentation preview 📚: https://pep-previews--3805.org.readthedocs.build/
=> PEP 667: Change slots in FrameLocalsProxy

peps/pep-0744.rst
After going through the themes in the [discussion thread](https://discuss.python.org/t/pep-744-jit-compilation/50756), the biggest warranted update was to clarify the LLVM build time dependency. Some topics discussed go beyond the scope of the informational PEP (e.g., going more into how the inner workings of the JIT, details about tier 1 and 2 interpreters, existing/expired patents, comparison with PyPy) or are, in my opinion, sufficiently covered (e.g., copy-and-patch compilation) by linked content. 
I've also added a link to the slides for the first talk covering the JIT for easier reading. I found a few different versions on your GitHub @brandtbucher but chose to link the slides from when the talk was originally given. Let me know if you'd like to update the links to reflect the most …
=> PEP 744: Add link to slides and clarification about LLVM dependency

peps/pep-0747.rst
---
In particular:
* Implicit Annotation Expression Values: Delete section
* Alter unparameterized TypeExpr to mean TypeExpr[Any]
----
📚 Documentation preview 📚: https://pep-previews--3856.org.readthedocs.build/
=> PEP 747: Fix rules related to UnionType (T1 | T2). Contrast TypeExpr with TypeAlias. Apply other feedback.

peps/pep-0694.rst
----
📚 Documentation preview 📚: https://pep-previews--3859.org.readthedocs.build/
=> Fix one small typo in PEP 694

.github/CODEOWNERS, peps/pep-0101.rst
* A Tex installation is no longer needed, the docs are built on CI: https://github.com/python/release-tools/actions/workflows/source-and-docs-release.yml
* Remove old note about asking Ewa for website access
* Note new RMs should be added to PSRT
* Add me to list of RMs
* The `make testall` command is now `make buildbottest`: https://github.com/python/cpython/pull/110122
* Replace MLs with Discord/Discourse
=> PEP 101: Remove outdated info and add new info

.pre-commit-config.yaml, pep_sphinx_extensions/pep_zero_generator/writer.py, peps/api/index.rst, peps/conf.py, peps/contents.rst
Fixes #2584.
----
📚 Documentation preview 📚: https://pep-previews--3864.org.readthedocs.build/
=> Meta: Document the PEPs API

peps/pep-0740.rst
~~Changing the status here to provisional, per the PyPA PEP policy: https://www.pypa.io/en/latest/specifications/#provisional-acceptance~~
I opened this prematurely last month, but reopening now that @dstufft has provisionally accepted: https://discuss.python.org/t/pep-740-index-support-for-digital-attestations/44498/26
CC @dstufft 🙂 
----
📚 Documentation preview 📚: https://pep-previews--3848.org.readthedocs.build/
=> PEP 740: Mark as Provisional

peps/pep-0749.rst
Deriving from https://discuss.python.org/t/pep-749-implementing-pep-649/54974/28 and offline discussion with Alex.
----
📚 Documentation preview 📚: https://pep-previews--3847.org.readthedocs.build/
=> PEP 749: Add section on metaclasses

peps/pep-0635.rst
Looks like an unclosed f-string.
----
📚 Documentation preview 📚: https://pep-previews--3871.org.readthedocs.build/
=> PEP 635: Minor typo fix in code sample.

.github/CODEOWNERS, peps/pep-0743.rst
Here's a rewritten version of PEP 743, focusing on hiding soft-deprecated API.
----
📚 Documentation preview 📚: https://pep-previews--3869.org.readthedocs.build/
=> PEP 743: Rewrite to hide (soft-)deprecated API

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3872.org.readthedocs.build/
=> PEP 751: Add Discussions-To and Post-History

peps/pep-0639.rst, peps/pep-0639/appendix-examples.rst, peps/pep-0639/appendix-rejected-ideas.rst
Included changes:
- remove the default glob values expected from build tools to match license-files (build backends can still define them if they wish, the standard just doesn't make any recommendation about them)
- change the error policy around deprecated license classifiers - tools MAY -- not MUST -- raise an error if they encounter them
- flatten the value of `license-files` key - expect glob patterns, specify the glob characters supported
- rework Rejected ideas to reflect the above changes, ideally reducing them in size during the process
----
📚 Documentation preview 📚: https://pep-previews--3866.org.readthedocs.build/
=> PEP 639: Incorporate the latest discussion feedback

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3873.org.readthedocs.build/
=> PEP 715: clarify what `[package.tool]` is

peps/pep-0665.rst
Fixes https://github.com/python/peps/issues/3874.
----
📚 Documentation preview 📚: https://pep-previews--3875.org.readthedocs.build/
=> PEP 665: Superseded-By: 751

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3877.org.readthedocs.build/
=> PEP 751: update based on feedback

peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3878.org.readthedocs.build/
=> PEP 710: remove index_url and state why it was removed

peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3887.org.readthedocs.build/
=> PEP 710: link specifications instead of PEP 610

peps/pep-0745.rst
Commit where `main` became 3.14: https://github.com/python/cpython/commit/7768ff1e414d8fa4aa02b888b9370c34f5e62de1
----
📚 Documentation preview 📚: https://pep-previews--3890.org.readthedocs.build/
=> PEP 745: 3.14 development has begun

peps/pep-0101.rst
Follow up to https://github.com/python/release-tools/pull/146 which renamed this script with underscores to make it importable and testable.
----
📚 Documentation preview 📚: https://pep-previews--3889.org.readthedocs.build/
=> PEP 101: Rename to `add_to_pydotorg.py`

Makefile
Like https://github.com/python/cpython/pull/122662.
This is mostly to keep the `Makefile`s similar in each repo to ease maintenance.
Also promote the `make check-links` deprecation warning (added in November 2023 in https://github.com/python/peps/pull/3514) to an error, although we could probably remove it already?
----
📚 Documentation preview 📚: https://pep-previews--3891.org.readthedocs.build/
=> Infra: Remove GNU make-specific directive from Makefile

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--3894.org.readthedocs.build/
=> PEP 751: make `packages.multiple-entries` optional

peps/pep-0558.rst
Splitting out historical rationale details for `locals()` snapshots from https://github.com/python/peps/pull/3845
=> PEP 558: Clarify rationale for locals() snapshots

.github/CODEOWNERS, peps/pep-0744.rst
This PR addresses some additional comments from https://github.com/python/peps/pull/3850#pullrequestreview-2157965764. I've chosen to address the comment around the JIT environment variable in the JIT's README (see https://github.com/python/cpython/pull/121635) since I think that's maybe valuable to contributors and that file is linked from the PEP.
I've also added myself to CODEOWNERS for this file.
----
📚 Documentation preview 📚: https://pep-previews--3861.org.readthedocs.build/
=> PEP 744: Additional updates from discussion thread

peps/pep-0750.rst
In one of the examples, the explanation appears to name the conversion and format-spec specifiers incorrectly.
This proposal fixes the specifiers so they are consistent to what the example code says.
---
----
📚 Documentation preview 📚: https://pep-previews--3900.org.readthedocs.build/
=> PEP 750: fix specifier mixup

peps/pep-0746.rst
----
📚 Documentation preview 📚: https://pep-previews--3892.org.readthedocs.build/
=> PEP 746: Use an attribute instead of a method

peps/pep-0747.rst
----
📚 Documentation preview 📚: https://pep-previews--3893.org.readthedocs.build/
=> PEP 747: Require TypeExpr(X | Y) syntax to spell value of type TypeExpr[X | Y]

peps/pep-0708.rst
Upon reading PEP 708 in detail, I found a small typo.  Here's a fix.
----
📚 Documentation preview 📚: https://pep-previews--3907.org.readthedocs.build/
=> Fix a small typo

peps/pep-0639.rst
Changes made based on the recent development of https://discuss.python.org/t/pep-639-round-3-improving-license-clarity-with-better-package-metadata/53020
----
📚 Documentation preview 📚: https://pep-previews--3913.org.readthedocs.build/
=> PEP 639: Make the policy around globs tighter

peps/pep-0752.rst
Added:
- Django
- pytest
- Sphinx
- Apache Airflow
----
📚 Documentation preview 📚: https://pep-previews--3912.org.readthedocs.build/
=> PEP 752: Add more examples

peps/pep-0639.rst
----
📚 Documentation preview 📚: https://pep-previews--3914.org.readthedocs.build/
=> PEP 639: Character ranges are treated locale-agnostic

peps/pep-0752.rst
1. Changed most uses of the word "package" to "project".
2. Explicitly state that PEP 708 does not offer protection against these types of dependency confusion attacks.
3. Changed the semantics to be based on the project rather than individual artifacts. It appears it's more useful to consider the current namespace permissions rather than if a version was part of the namespace at the time of release.
4. As a consequence of 2, removed recommended fields in the Simple API.
5. Added optional top-level `owner` and `namespace` keys to the JSON API.
6. Added NPM-style scoping explicitly as a rejected idea and enumerate all of the rationale.
7. Rather than giving permission to users, made it clear that authorization for uploads is about identical project and grant owners.
8. Made it clear that …
=> PEP 752: Address feedback, round 1

peps/pep-0752.rst
----
📚 Documentation preview 📚: https://pep-previews--3918.org.readthedocs.build/
=> PEP 752: Add terminology section

peps/pep-0740.rst
This tweaks PEP 740 a bit to clear up an ambiguity: like in the simple HTML index, the JSON Simple Index may choose to emit `provenance: null` when a distribution file has no provenance, rather than omitting the key entirely.
CC @di @darkamaul
----
📚 Documentation preview 📚: https://pep-previews--3906.org.readthedocs.build/
=> PEP 740: clarify that provenance is nullable

peps/pep-0752.rst
1. Changed the Delegate from Donald Stufft to Dustin Ingram.
2. Renamed private/public terminology to private/shared.
3. Allowed community projects the ability to have private namespaces but still _should_ be shared-only. The determination is at the discretion of reviewers.
4. Added a separate visual indicator for projects that are part of a shared namespace and are not owned by a grant holder.
5. Added a separate visual indicator for projects matching a private namespace that existed before the grant.
6. Made it explicit that root grants cannot overlap e.g. if there is a grant for `foo-bar` then one cannot apply for `foo`.
7. Adjusted language about the application review prioritization of corporate organizations.
8. Clarified that it is forbidden to replicate namespace configuration …
=> PEP 752: Address feedback, round 2

peps/pep-0741.rst
----
📚 Documentation preview 📚: https://pep-previews--3924.org.readthedocs.build/
=> PEP 741: Fix typos

peps/pep-0639.rst
Inspired by https://github.com/python/peps/pull/3913/files#r1722968974 .
----
📚 Documentation preview 📚: https://pep-previews--3926.org.readthedocs.build/
=> PEP 639: consuming tools SHOULD reject invalid glob patterns

peps/pep-0741.rst
* Remove read-only options:
* "module_search_paths_set": not useful, always true.
* "pythonpath_env": get os.environ['PYTHONPATH'] directly.
* "sys_path_0": only make sense during Python initialization.
* "_install_importlib", "_init_main", "_is_python_build": private options which only make sense during Python initialization.
* Fix related sys API for base_executable and exec_prefix.
* legacy_windows_fs_encoding is Windows only.
* Fix sorting.
----
📚 Documentation preview 📚: https://pep-previews--3927.org.readthedocs.build/
=> PEP 741: Update options

peps/pep-0705.rst
Seems to be a typo. `impl()` is not expected to have `self` parameter, I believe.
----
📚 Documentation preview 📚: https://pep-previews--3934.org.readthedocs.build/
=> PEP 705: Remove extra `self` parameter from example

peps/pep-0742.rst
Helps https://github.com/python/peps/issues/3781.
----
📚 Documentation preview 📚: https://pep-previews--3937.org.readthedocs.build/
=> PEP 742: Mark as Final

peps/pep-0705.rst
Helps https://github.com/python/peps/issues/3781, cc @alicederyn.
The spec link goes to:
https://typing.readthedocs.io/en/latest/spec/typeddict.html#typing-readonly-type-qualifier
Or do we want to link to the header just above it? We'll need to add an extra ref to the spec, if so.
https://typing.readthedocs.io/en/latest/spec/typeddict.html#read-only-items
----
📚 Documentation preview 📚: https://pep-previews--3938.org.readthedocs.build/
=> PEP 705: Mark as Final

peps/pep-0702.rst
Helps https://github.com/python/peps/issues/3781.
----
📚 Documentation preview 📚: https://pep-previews--3940.org.readthedocs.build/
=> PEP 702: Mark as Final

peps/pep-0696.rst
Helps https://github.com/python/peps/issues/3781, cc @Gobot1234.
This is documented in the typing spec at https://typing.readthedocs.io/en/latest/spec/generics.html#type-parameter-defaults.
Is it documented at https://docs.python.org/3.13/? Should it be?
=> PEP 696: Mark as Final

peps/pep-0752.rst
1. Extracted all policy, operational and UI recommendations into a separate PEP (PR incoming) and renamed to `Implicit namespaces for package repositories`.
1. Removed the concept of grants types; root grants are now just grants. Repositories may add the concept of child grants but that is not discussed.
2. Switched the shared/private terminology to open/restricted; this is final.
3. Officially specified the concept of organizations as `entities that own projects and have various users associated with them`.
4. Made it explicit that this proposal is for repositories that allow creation of projects e.g. non-mirrors.
5. Replaced the ``namespace.owners`` key in the API with ``namespace.authorized`` to eliminate client-side logic.
6. Made it explicit that packages starting with a prefix that …
=> PEP 752: Address feedback, round 3

peps/pep-0735.rst
PEP 735 is expanded here to allow `project.dependencies` and
`project.optional-dependencies` to use Dependency Group Includes. This
allows for includes which help satisfy the use-cases described by the
`--only-deps` pip use-cases.
The changes are various:
- support for these includes is added to the rationale section
- a new use case is added, aligned with the `--only-deps` use case
- the spec section is updated to list changes to the `project` table
- backwards compatibility is extended significantly to address
repackaging concerns as well as dependency analyzers[^1]
- "how to teach this" is also extended to note compatibility and
repackaging issues
- rejected ideas has added an item on `[build-system.requires]`
[^1]: It may be overstatement to say these concerns are addressed.
They are …
=> PEP 735: allow core metadata to include groups

peps/pep-0735.rst
With the addition of `project.dependencies` includes from Dependency
Groups, additions are warranted in the "How to Teach This" section of
the PEP.
Firstly, it is now useful to mention the similarity between a
dependency group and an old-style `setup.py` which reads either as
setup(install_requires=_read_helper("requirements.txt"), ...)
or else as
requirements = ["foo", ...]
...
setup(install_requires=requirements, ...)
Secondly, discussion of the interfaces for Dependency Groups adds a
dimension to the document. For tool authors, this clarifies that
allowing `project.dependencies` to use includes is necessary for
build backends to declare support, but that there are no other formal
requirements for tools. They will have to decide on interfaces -- and
therefore what it means to support …
=> PEP 735: expand "How to Teach This"

peps/pep-0007.rst, peps/pep-0008.rst
As discussed in: https://discuss.python.org/t/pep-7-break-lines-before-operators-like-pep-8/62402
It doesn't make much sense for C and Python to be different here, and the reasons for "Knuth's style" in PEP 8 apply to C code as well.
----
📚 Documentation preview 📚: https://pep-previews--3931.org.readthedocs.build/
=> PEP 7: Break lines before operators ("Knuth's style")

peps/pep-2026.rst
---
Spotted two instances where a word is repeated twice:
* "how long you have **to to** take action"
* "maps to **the the** latest Python 3+ version."
----
📚 Documentation preview 📚: https://pep-previews--3957.org.readthedocs.build/
=> PEP 2026: Fix repeated word typos

peps/pep-0744.rst
----
📚 Documentation preview 📚: https://pep-previews--3953.org.readthedocs.build/
=> PEP 744: fix broken links to benchmarking-public images

peps/pep-0501.rst
Also fixes an incorrect comment about the impact
a CPython operand precedence bug will have on the
way template literals interact with regular strings.
----
📚 Documentation preview 📚: https://pep-previews--3946.org.readthedocs.build/
=> PEP 501: Minor editing fixes

peps/pep-0756.rst
Use the native encoding. "=I" size is 4 bytes on all platforms.
----
📚 Documentation preview 📚: https://pep-previews--3967.org.readthedocs.build/
=> PEP 756: Fix buffer format

peps/pep-0752.rst
1. Expressed the use case for open/restricted namespaces in the motivation section.
2. Made it clear that the current automatic protection against typosquatting used by PyPI is insufficient.
3. Added examples of attacks to the appendix.
4. Fixed versioning of the JSON API.
5. Rejected the idea of encouraging projects to maintain their own package repositories.
6. Rejected the idea of fixed top-level prefixes used for reservations.
7. Rejected the idea of using DNS.
8. Expressed in the rationale that using PEP 541 requests in addition to this proposal would minimize risk to users.
9. Added a community buy-in section enumerating feedback from relevant projects and communities.
----
📚 Documentation preview 📚: https://pep-previews--3955.org.readthedocs.build/
=> PEP 752: Address feedback, round 4

peps/pep-0755.rst
1. Improved wording in the rationale to make it clear that community organizations can reserve namespaces.
2. Used "paid" organization over "corporate" organization to ease understanding for non-native speakers and reduce concern among those who consider the word corporate to have a negative connotation.
3. Removed expectation that grants for communities should be open.
4. Improved language around why reviews for paid organizations are prioritized.
5. Included PEP 541 in the expected teaching process.
----
📚 Documentation preview 📚: https://pep-previews--3959.org.readthedocs.build/
=> PEP 755: Address feedback, round 1

peps/pep-0757.rst
This change export API to Antoine Pitrou -like proposal.
* I'm unsure if we should use signed type for ``value`` or store here absolute value.
* Right now, we probably can put compact value to this field, but using PyLong_AsLongAndOverflow first seems to be faster.  So, we might just reserve ``value`` field for future use.
----
📚 Documentation preview 📚: https://pep-previews--3970.org.readthedocs.build/
=> PEP 757: use PyLong_Export

peps/pep-0757.rst
* endian => endianness
* Move text to function documentations
* Discussions: add link to the PEP discussion
----
📚 Documentation preview 📚: https://pep-previews--3979.org.readthedocs.build/
=> PEP 757: Cleanup

Makefile
Update `htmllive` target to match CPython (https://github.com/python/cpython/pull/124219).
The `ensure-sphinx-autobuild` target isn't used, it was refactored into `_ensure-sphinx-autobuild`.
Re-use variables for `make` and `build`.
Fix `make spellcheck` to match `make lint` (missed in https://github.com/python/peps/pull/3891).
----
📚 Documentation preview 📚: https://pep-previews--3985.org.readthedocs.build/
=> Infra: Update `Makefile`to match CPython/Docs and devguide

pep_sphinx_extensions/generate_rss.py
The RSS feed https://peps.python.org/peps.rss starts:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
<channel>
<title>Newest Python PEPs</title>
<link>https://peps.python.org/peps.rss</link>
<description>Newest Python Enhancement Proposals (PEPs): Information on new language features and some meta-information like release procedure and schedules.</description>
<atom:link href="https://peps.python.org/peps.rss" rel="self"/>
<docs>https://cyber.harvard.edu/rss/rss.html</docs>
<language>en</language>
<lastBuildDate>Wed, 18 Sep 2024 12:01:25 GMT</lastBuildDate>
<item>
<title>PEP 757: C API to import-export Python integers</title>
<link>https://peps.python.org/pep-0757/</link> …
```
=> Infra: Link RSS to website not feed

peps/pep-0740.rst
Opening this up for discussion: @di observed that the current provisional requirement (that the provenance be pinned by SHA-256) has no security impact, since the provenance contains digitally signatures objects that will fail to verify if tampered with.
At the same time, the index APIs still need *some* way to signal that the provenance object is actually present. This tweaks the provisional language to have the index serve a URL to the provenance object.
----
📚 Documentation preview 📚: https://pep-previews--3971.org.readthedocs.build/
=> PEP 740: ``data-provenance`` attribute value tweaks

peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--3988.org.readthedocs.build/
=> PEP 756: Add PyUnicode_EXPORT_ALLOW_COPY flag

peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--3994.org.readthedocs.build/
=> PEP 749: Move dataclass field types out of open issues

peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--3998.org.readthedocs.build/
=> PEP 749: Add annotations_to_source, value_to_source

peps/pep-0749.rst
This is a first round of changes as a result of feedback by @larryhastings; I may make some more changes, but need to think about them more first.
----
📚 Documentation preview 📚: https://pep-previews--3991.org.readthedocs.build/
=> PEP 749: Add a FAKE_GLOBALS_VALUE format

peps/pep-2026.rst
Mention `PY_VERSION_HEX`, re:
* https://discuss.python.org/t/pep-2026-calendar-versioning-for-python/55782/79
* https://discuss.python.org/t/pep-2026-calendar-versioning-for-python/55782/80
----
📚 Documentation preview 📚: https://pep-previews--3995.org.readthedocs.build/
=> PEP 2026: Note `PY_VERSION_HEX` changes needed for 3.YYYY

peps/pep-0756.rst
----
📚 Documentation preview 📚: https://pep-previews--3999.org.readthedocs.build/
=> PEP 756: Give up on copying memory

peps/pep-0749.rst
----
📚 Documentation preview 📚: https://pep-previews--4000.org.readthedocs.build/
=> PEP 749: Rename SOURCE to STRING, go back on __annotations__ setting

pep_sphinx_extensions/pep_theme/static/style.css, pep_sphinx_extensions/pep_theme/templates/page.html, pep_sphinx_extensions/pep_zero_generator/pep_index_generator.py, pep_sphinx_extensions/pep_zero_generator/writer.py, peps/contents.rst
Fixes https://github.com/python/peps/issues/2044.
Re: https://github.com/python/peps/issues/2044#issuecomment-1074914852
The frontpage index (PEP 0) is very long, and starts the PEPs grouped by category, followed by a big table sorted by number.
This duplicates the PEP list (there's 655 right now), and can make searching in the page a bit confusing.
This PR creates a new `numerical.html` page with the numerical index.
I've kept the "Numerical Index" header on the frontpage and added a link to the new page. I moved the header up, before the remaining groups, but don't have a strong opinion on where this should be.
----
📚 Documentation preview 📚: https://pep-previews--3992.org.readthedocs.build/numerical/
=> Infra: Move numerical index to own page

peps/pep-0740.rst
Both PEP 740 and [PEP 708](https://peps.python.org/pep-0708/) stipulated API version 1.2 as the next JSON API version, but PEP 708 was finished first! So this just bumps to the next unused API version.
CC @di 
----
📚 Documentation preview 📚: https://pep-previews--4001.org.readthedocs.build/
=> PEP 740: Update api-version

peps/pep-0101.rst
----
📚 Documentation preview 📚: https://pep-previews--4003.org.readthedocs.build/
=> PEP 101: Minor updates to major version bump procedure

peps/pep-0747.rst
This causes a mis-rendering on https://peps.python.org/pep-0747/
----
📚 Documentation preview 📚: https://pep-previews--4004.org.readthedocs.build/
=> PEP 747: fix rst syntax

peps/pep-0719.rst
Re: https://discuss.python.org/t/incremental-gc-and-pushing-back-the-3-13-0-release/65285
* Release 3.13.0rc3 this Monday, September 30th.
* Release 3.13.0 final a week later, on Monday, October 7th (probably starting the release process on Sunday).
----
📚 Documentation preview 📚: https://pep-previews--4005.org.readthedocs.build/
=> PEP 719: Add 3.13.0rc3, postpone 3.13.0 final

peps/pep-0735.rst
This PR applies several changes in response to community feedback and my having been convinced by these arguments that modifications to the `[project]` table are a mistake within the scope of this PEP.
The commits here each addresses a separate piece of feedback:
- Remove [project] changes from Dependency Groups.
This is the largest change, removing text about changing the `[project]` table and making several adjustments for correctness in response to this.
- Typing fix to PEP 735 reference implementation
- PEP735: Add clarification on 'requirements.in'
This adds a small blurb to "How to Teach This" on `requirements.txt` vs `requirements.in`.[^1]
- More strongly discourage overlapping extras
This changes a `SHOULD NOT` to a `MAY`, thereby widening the PEP's allowance for tools to reject …
=> PEP 735: apply community feedback, including reversion of [project] table changes

peps/pep-0703.rst
Pretty self-explanatory, this PR updates a typo.
----
📚 Documentation preview 📚: https://pep-previews--3956.org.readthedocs.build/
=> PEP 703: Fix typo 

.github/CODEOWNERS
We forgot it in https://github.com/python/peps/pull/3947.
Plus a little tidy-up of the `CODEOWNERS` file.
----
📚 Documentation preview 📚: https://pep-previews--4014.org.readthedocs.build/
=> PEP 755: Add missing CODEOWNERS entry

peps/pep-0735.rst
This is a fairly simple addition -- writing up an idea which surfaced
in the discourse thread as Deferred. The rationale given here, which
is the primary one for deferral, is that this would be obviated by
(and therefore create a confusing situation in combination with) Path
Dependencies.
----
📚 Documentation preview 📚: https://pep-previews--4012.org.readthedocs.build/
=> PEP 735: Add include-project to Deferred Ideas

peps/pep-0757.rst
1. ~~drop endianness field of the PyLongLayout struct~~
2. keep PyLong_GetNativeLayout() function (was: open question)
3. reject mpz_import/export-like API
I would appreciate also @zooba opinion on (1).  Personally I see no reasons to use non-native endianness for implementation of big integers.
(2) was taken from #3980; it seems nobody from C-API WG objected on extra API call added, so lets keep this as a more convenient interface.
----
📚 Documentation preview 📚: https://pep-previews--4017.org.readthedocs.build/
=> PEP 757: reject more ideas

peps/pep-0241.rst, peps/pep-0314.rst, peps/pep-0345.rst, peps/pep-0426.rst
----
📚 Documentation preview 📚: https://pep-previews--4020.org.readthedocs.build/
=> Add canonical refs to old package specs

peps/pep-0011.rst, peps/pep-0738.rst
~~The Android x86_64 buildbot is not yet up and running, so this is not quite ready to be merged.~~ The aarch64 and x86_64 buildbots are both now stable.
@freakboy3742: I assume you're OK with being added as a second core team contact for Android?
* https://github.com/python/cpython/pull/124259
* https://github.com/python/cpython/pull/124304
* There were no substantial changes, only minor adjustments to the `android_ver` function, as discussed [here](https://github.com/python/cpython/pull/116674).
* Closes https://github.com/python/cpython/issues/116622
----
📚 Documentation preview 📚: https://pep-previews--3982.org.readthedocs.build/
=> PEP 738: Mark as Final

peps/pep-0753.rst
Per https://discuss.python.org/t/pep-753-uniform-project-urls-in-core-metadata/62792/15:
* Removes the prescription that producers emit normalized labels, and clarifies that normalization should occur during processing on the metadata consumer side.
* Clarifies that normalized labels are not necessarily unique, per the pre-existing `Project-URL` spec.
* Adds an appendix with examples of normalization.
* Adjusts the proposed living standard location (PyPA specifications instead of PyPI's docs).
CC @pfmoore 
Signed-off-by: William Woodruff <william@yossarian.net>
----
📚 Documentation preview 📚: https://pep-previews--4010.org.readthedocs.build/
=> PEP 753: Updates

peps/pep-0730.rst
Many people will follow the link from [today's release announcement](https://www.python.org/downloads/release/python-3130/) to this PEP, so we should forward them to [the live documentation](https://docs.python.org/3/using/ios.html#using-ios) for more actionable advice.
----
📚 Documentation preview 📚: https://pep-previews--4023.org.readthedocs.build/
=> PEP 730: Add canonical-doc link

peps/pep-0719.rst
https://discuss.python.org/t/python-3-13-0-final-has-been-released/66972
----
📚 Documentation preview 📚: https://pep-previews--4028.org.readthedocs.build/
=> PEP 719: Python 3.13.0 final has been released

peps/pep-0735.rst
----
📚 Documentation preview 📚: https://pep-previews--4042.org.readthedocs.build/
=> PEP 735: Mark as Accepted

requirements.txt
The Sphinx 8.1 release added a new check for unreferenced footnotes, which causes CI to fail.
A
----
📚 Documentation preview 📚: https://pep-previews--4044.org.readthedocs.build/
=> Pin Sphinx to <8.1

pep_sphinx_extensions/pep_zero_generator/writer.py
missing initial slash broke the link
making this after discussion on a `pythondotorg` [issue](https://github.com/python/pythondotorg/issues/2643)
----
📚 Documentation preview 📚: https://pep-previews--4045.org.readthedocs.build/
=> PEP 0: Use an absolute link to `peps.json`

peps/pep-0291.rst, peps/pep-0387.rst
Re: https://github.com/python/peps/issues/4030
PEP 291 is the Python 2 stdlib policy. 
It's been superseded by [PEP 387](https://peps.python.org/pep-0387/), 
cc @ncoghlan 
----
📚 Documentation preview 📚: https://pep-previews--4032.org.readthedocs.build/
=> PEP 291: Superseded by PEP 387

peps/pep-0735.rst
This line of text was not removed when the relevant behaviors were
removed from the PEP. It is therefore inaccurate.
---
I am not sure what this change qualifies as, based on the list below:
It's an Accepted PEP, but this is definitely an oversight.
I assume, since it's a packaging PEP, that if we get Paul's approval as the PEP delegate, it becomes the middle case?
----
📚 Documentation preview 📚: https://pep-previews--4047.org.readthedocs.build/
=> PEP 735: Fix a minor mistake

peps/pep-0735.rst
Found 2 minor typos while reading the PEP.
Second commit is not about a typo, but I find that having `.`. is a bit hard to read:
For comparison:
----
📚 Documentation preview 📚: https://pep-previews--4049.org.readthedocs.build/
=> PEP 735: Fix a few typos and improve readability

peps/pep-0757.rst, peps/pep-0777.rst
Changes in this PEP update:
- Added post-history and discussions-to
- clarified behavior around `Wheel-Version` and rewrote parts to be more formal about its specification
- clarified that the `x` in `.whlx` is the letter x
- clarified that future versions of the wheel format should also use `.whlx`
- Added a paragraph about the impact of needing to read wheel contents when resolving packages
- Added several rejected ideas:
a. store the wheel major version in the file extension (i.e. `.whl2`)
b. wheel 2 should change the outer wheel container format
c. This PEP should define Wheel 2.0
----
📚 Documentation preview 📚: https://pep-previews--4056.org.readthedocs.build/
=> PEP 777: Address discussion and feedback

.pre-commit-config.yaml, check-peps.py, pep_sphinx_extensions/pep_processor/transforms/pep_headers.py, pep_sphinx_extensions/tests/pep_lint/test_pep_lint.py, pep_sphinx_extensions/tests/pep_lint/test_post_url.py, peps/pep-0001.rst, peps/pep-0702.rst, peps/pep-0735.rst
Fixes #4054.
----
📚 Documentation preview 📚: https://pep-previews--4061.org.readthedocs.build/
=> Meta: Allow adding date to Resolution header

peps/pep-0649.rst, peps/pep-0688.rst, peps/pep-0700.rst, peps/pep-0701.rst, peps/pep-0703.rst, peps/pep-0705.rst, peps/pep-0714.rst, peps/pep-0715.rst, peps/pep-0721.rst, peps/pep-0723.rst, peps/pep-0729.rst, peps/pep-0742.rst, peps/pep-0753.rst
Continuing #4054. I added acceptance dates to all PEPs in the packaging
and typing topics with numbers over 700, and then to a few other recent PEPs
where it seemed useful.
----
📚 Documentation preview 📚: https://pep-previews--4064.org.readthedocs.build/
=> Various PEPs: Add acceptance dates

peps/pep-0761.rst
A small update to make this explicit after I received a question about it.
----
📚 Documentation preview 📚: https://pep-previews--4069.org.readthedocs.build/
=> PEP 761: Deprecation doesn't affect previous signatures

peps/pep-0728.rst
- Move away from `__extra_items__: T` to `extra_items=T`
- Repurpose the 'closed' class parameter to make 'closed=True' an alias of 'extra_items=Never'
- Include references to the typing spec
- Normalize terms like "assignability" and "consistent" to match the typing glossary (https://typing.readthedocs.io/en/latest/spec/glossary.html)
- Update sections that contain documentation quotes to match the up-to-date version
- Add new sections about other ideas
- Bump the target version to 3.14
----
📚 Documentation preview 📚: https://pep-previews--4066.org.readthedocs.build/
=> PEP 728: Revise proposal to spec the 'extra_items=T' idea

peps/pep-0501.rst
----
📚 Documentation preview 📚: https://pep-previews--4070.org.readthedocs.build/
=> PEP 501: Withdraw in favour of PEP 750

peps/pep-0758.rst
----
📚 Documentation preview 📚: https://pep-previews--4073.org.readthedocs.build/
=> PEP 758: Force parentheses when using 'as'

pep_sphinx_extensions/pep_zero_generator/writer.py
Fixes #4030.
----
📚 Documentation preview 📚: https://pep-previews--4033.org.readthedocs.build/
=> Infra: update header to 'Process and Meta-PEPs'

peps/pep-0396.rst
The ``__version__`` runtime convention hasn't been rejected, as it's still a good way to version import packages instead of (or in addition to) distribution packages.
We just concluded that this PEP wasn't the right vehicle for documenting it, which is better reflected as a withdrawal rather than as a rejection.
----
📚 Documentation preview 📚: https://pep-previews--4074.org.readthedocs.build/
=> PEP 396: Reclassify as Withdrawn

peps/pep-0733.rst
This is an Informational PEP.
----
📚 Documentation preview 📚: https://pep-previews--4085.org.readthedocs.build/
=> PEP 733: Mark as Final

peps/pep-0588.rst
Fixes https://github.com/python/peps/issues/2497.
The migration was carried out in April 2022. This Informational PEP can be marked as Final, and we can link to the actual plan https://github.com/psf/gh-migration/issues/13.
----
📚 Documentation preview 📚: https://pep-previews--4086.org.readthedocs.build/
=> PEP 588: Mark as Final

peps/pep-0763.rst
Follows https://github.com/python/peps/pull/4080 by adding an appendix comparing different ecosystems' support for deletion and yanking, per @JelleZijlstra's request 🙂 
----
📚 Documentation preview 📚: https://pep-previews--4091.org.readthedocs.build/
=> PEP 763: add an appendix comparing ecosystems

peps/pep-0763.rst
Adds two more ecosystems for comparison, thanks to @JelleZijlstra.
----
📚 Documentation preview 📚: https://pep-previews--4092.org.readthedocs.build/
=> PEP 763: add Hackage and OPAM

peps/pep-0545.rst
PEP 545 covers the governance procedures for the
python.org hosted documentation translations,
it was just written and accepted before the separate topic pages existed.
----
📚 Documentation preview 📚: https://pep-previews--4093.org.readthedocs.build/
=> PEP 545: Include translations in the Governance topic

peps/pep-0659.rst
This is an informational PEP for the Specializing Adaptive Interpreter that went into 3.11, so could be marked as Final now.
I added "canonical docs" pointing to the long [3.11 what's new entry](https://docs.python.org/3/whatsnew/3.11.html#pep-659-specializing-adaptive-interpreter), unless there a better place to link to?
----
📚 Documentation preview 📚: https://pep-previews--4090.org.readthedocs.build/
=> PEP 659: Mark as Final

peps/pep-0753.rst
The equivalent PyPI page is now live at https://packaging.python.org/en/latest/specifications/well-known-project-urls/, so this adds the appropriate banner.
----
📚 Documentation preview 📚: https://pep-previews--4095.org.readthedocs.build/
=> PEP 753: link to PyPA spec

peps/pep-0691.rst
Fixes https://github.com/python/peps/issues/4088.
----
📚 Documentation preview 📚: https://pep-previews--4098.org.readthedocs.build/
=> PEP 691: Fix wrong reference to PEP 529

peps/pep-0562.rst
Closes #4068 
----
📚 Documentation preview 📚: https://pep-previews--4099.org.readthedocs.build/
=> PEP 562: Add canonical reference link

.github/workflows/lint.yml, .github/workflows/test.yml
Like https://github.com/python/blurb/pull/32.
We can also now test Python 3.9 on macos-latest, so can remove its restriction to macos-13: https://github.com/actions/setup-python/issues/696#issuecomment-2302006143
----
📚 Documentation preview 📚: https://pep-previews--4102.org.readthedocs.build/
=> Infra: Lint and test via uv

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4104.org.readthedocs.build/
=> PEP 751: address some feedback

peps/pep-0739.rst, peps/pep-0739/example.json, peps/pep-0739/python-build-info-v1.schema.json
Signed-off-by: Filipe Laíns <lains@riseup.net>
----
📚 Documentation preview 📚: https://pep-previews--4100.org.readthedocs.build/
=> PEP 739: add language.version_info and libpython.dynamic_stableabi

.github/CODEOWNERS
core-dev membership is restored
----
📚 Documentation preview 📚: https://pep-previews--4106.org.readthedocs.build/
=> Revert gh-3899

Makefile
To reproduce:
```console
$ make htmllive
...
The HTML pages are in build.
[sphinx-autobuild] Serving on http://127.0.0.1:55302
[sphinx-autobuild] Waiting to detect changes...
```
Then edit a file, for example `peps/pep-0101.rst` and it will rebuild it. So far, so good.
But then because `peps/numerical.rst` is regenerated, `sphinx-autobuild` detects a change and begins an infinite rebuild loop:
```console
[sphinx-autobuild] Detected changes (peps/pep-0101.rst)
[sphinx-autobuild] Rebuilding...
...
The HTML pages are in build.
[sphinx-autobuild] Serving on http://127.0.0.1:55302
[sphinx-autobuild] Detected changes (peps/numerical.rst)
[sphinx-autobuild] Rebuilding...
...
The HTML pages are in build.
[sphinx-autobuild] Serving on http://127.0.0.1:55302
[sphinx-autobuild] Detected changes …
```
=> Infra: don't let generated `numerical.rst` trigger rebuild loop

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4108.org.readthedocs.build/
=> PEP 751: make `path`/`url` optional

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4109.org.readthedocs.build/
=> PEP 751: provide explanation for why `path` and `url` are optional

peps/pep-0739.rst, peps/pep-0739/example.json, peps/pep-0739/python-build-info-v1.0.schema.json
----
📚 Documentation preview 📚: https://pep-previews--4112.org.readthedocs.build/
=> PEP 739: add version specification to schema_version

peps/pep-0752.rst
1. Added more instances of documented feedback.
2. Rejected the idea of exclusively relying on digital attestations.
3. Rejected the idea of adding new dependency syntax for asserting the name of project owners.
4. Made explicit the earlier rejected the idea of artifact-level namespace association.
5. Removed part of a footnote upon request.
----
📚 Documentation preview 📚: https://pep-previews--4018.org.readthedocs.build/
=> PEP 752: Address feedback, round 5

.github/CODEOWNERS, peps/pep-0765.rst, peps/pep-9999.rst
----
📚 Documentation preview 📚: https://pep-previews--4119.org.readthedocs.build/pep-0765/
=> PEP 765: Disallow return/break/continue that exit a finally block

peps/pep-0765.rst
----
📚 Documentation preview 📚: https://pep-previews--4120.org.readthedocs.build/
=> PEP 765: add discussion link, tweak one sentence

peps/pep-0540.rst
It's unclear what sys.output is.
----
📚 Documentation preview 📚: https://pep-previews--4122.org.readthedocs.build/
=> PEP 540: Correct `sys.output` to `sys.stdout`

peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4126.org.readthedocs.build/
=> PEP 757: edit rejected ideas (mpz_import/export-like API)

peps/pep-0601.rst, peps/pep-0765.rst
As suggested in https://discuss.python.org/t/pep-765-disallow-return-break-continue-that-exit-a-finally-block/71348/31.
----
📚 Documentation preview 📚: https://pep-previews--4128.org.readthedocs.build/
=> PEP 765: link with pep 601

.github/CODEOWNERS, peps/pep-0757.rst, peps/pep-0766.rst
----
📚 Documentation preview 📚: https://pep-previews--4123.org.readthedocs.build/pep-0766/
=> PEP 766: Explicit Priority Choices Among Multiple Indexes (index priority)

peps/pep-0765.rst
----
📚 Documentation preview 📚: https://pep-previews--4132.org.readthedocs.build/
=> PEP 765: specify when the SyntaxWarning will be emitted, and explain why

peps/pep-0101.rst
Various updates:
* python-dev@python.org has been archived:
https://www.mail-archive.com/python-dev@python.org/msg116752.html
* The new branch is created when the last one enters beta
* Move 'add label' instructions to same place
* devguide: 'Feature requests do not need version labels; it is implicit that features are added to the main branch only'
https://devguide.python.org/triage/labels/#type-labels
* Move instruction on bumping issue versions to branch retirement section
* Link to release PEPs
* We no longer need to update years in copyright notices:
https://devguide.python.org/getting-started/pull-request-lifecycle/#copyrights
* http -> https, update links, wording
----
📚 Documentation preview 📚: https://pep-previews--4136.org.readthedocs.build/
=> PEP 101: Updates

peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4140.org.readthedocs.build/
=> Set PEP 757 status to Accepted

peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4144.org.readthedocs.build/
=> PEP 757: address gpshead's review

peps/pep-0352.rst
The reference was added in https://github.com/python/peps/commit/22d5e43fa52ba6b42553917b0e423ef0ec9f1dc3 and partially removed in https://github.com/python/peps/commit/81eabf7a0d87ee4691e1b45fe81a525d59376eb4.
----
📚 Documentation preview 📚: https://pep-previews--4147.org.readthedocs.build/
=> PEP 352: Fix Sphinx reference warning

peps/pep-0740.rst
This is my first time marking a PEP as final, apologies if I've missed a step! I've gone `Provisional -> Final` based on that being a documented valid transition in PEP 1.
Supporting points:
CC @di @dstufft 🙂 
----
📚 Documentation preview 📚: https://pep-previews--4114.org.readthedocs.build/
=> PEP 740: Mark as Final

peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4153.org.readthedocs.build/
=> PEP 757: address gpshead's review (part 2, the value field)

peps/pep-0013.rst
* Because this is a process PEP, and specifically the one that defines the powers of the SC, the SC does *not* need to approve this PEP.
----
📚 Documentation preview 📚: https://pep-previews--3958.org.readthedocs.build/pep-0013/
=> PEP 13: Add STAR voting and misc tidbits

peps/pep-0765.rst
As [proposed](https://discuss.python.org/t/pep-765-disallow-return-break-continue-that-exit-a-finally-block/71348/108) by @JeffersGlass.
----
📚 Documentation preview 📚: https://pep-previews--4164.org.readthedocs.build/
=> PEP-765: rewrote two sentences as proposed by Jeff Glass

peps/pep-0013.rst
Update following the vote:
https://discuss.python.org/t/pep-13-add-deadline-for-seconding-vote-of-no-confidence/72293
----
📚 Documentation preview 📚: https://pep-previews--4163.org.readthedocs.build/pep-0013/
=> PEP 13: Add deadline of one week to second a vote of no confidence

peps/pep-0768.rst
----
📚 Documentation preview 📚: https://pep-previews--4165.org.readthedocs.build/
=> PEP 768: Add Discussions-To and Post-History headers

peps/pep-0768.rst
Switch from a buffer containing Python code to a buffer containing the path to a file containing Python code. This helps to prevent an attacker with arbitrary memory write capabilities inside a running Python process from also gaining arbitrary code execution if they don't already have the ability to write to the file system.
Also, indicate that we will send a new audit event whenever this interface is used, so that any attacker who uses it risks detection.
----
📚 Documentation preview 📚: https://pep-previews--4169.org.readthedocs.build/
=> PEP 768: Flesh out the security design

peps/pep-0376.rst
`#distutils` was added in https://github.com/python/peps/commit/c8bc9c1f233af3dc72d1200da7d0443a43c2b445 and partially removed in https://github.com/python/peps/commit/e7b6ac276c441d43f66377dadce3982a5ec9d066. 
`#distutils2` was added in https://github.com/python/peps/commit/1dfaf5580f383a862e4533da025ce3a6c1d5cc8b but never referenced.
----
📚 Documentation preview 📚: https://pep-previews--4148.org.readthedocs.build/
=> PEP 376: Fix Sphinx reference warnings

peps/pep-0386.rst
`#requires` was added in https://github.com/python/peps/commit/526ad628ce51892e4e7bd38402c74b59f8b626bd and partially removed in https://github.com/python/peps/commit/8436e4f7bb2e30c1609c9ed13b5f8149096d4fe4.
----
📚 Documentation preview 📚: https://pep-previews--4149.org.readthedocs.build/
=> PEP 386: Fix Sphinx reference warning

.pre-commit-config.yaml
Send all the files to codespell so we get the output in codespell's alphabetical order.
> `require_serial`: (optional: default false) if true this hook will execute using a single process instead of in parallel.
https://pre-commit.com/#hooks-require_serial
```console
❯ make spellcheck
...
Check for common misspellings in text files..............................Failed
- hook id: codespell
- exit code: 65
peps/pep-0728.rst:381: overriden ==> overridden
peps/pep-0728.rst:676: othere ==> other
peps/pep-0739/python-build-info-v1.0.schema.json:267: Implamentations ==> Implementations
peps/pep-0747.rst:548: alowed ==> allowed
peps/pep-0777.rst:357: introducted ==> introduced
peps/pep-0757.rst:457: bufferes ==> buffers, buffered
peps/pep-0758.rst:60: paretheses ==> parentheses …
```
=> Infra: let codespell run in parallel and output in order

pep_sphinx_extensions/__init__.py, peps/pep-0757.rst
----
📚 Documentation preview 📚: https://pep-previews--4167.org.readthedocs.build/
=> PEP 757: mark as Final

peps/pep-0745.rst
https://discuss.python.org/t/python-3-14-0-alpha-3/74542
----
📚 Documentation preview 📚: https://pep-previews--4176.org.readthedocs.build/
=> PEP 745: 3.14.0a3 was released on 2024-12-17

.readthedocs.yaml
_Not_ explicitly specifying the path to the `conf.py` is deprecated and will stop working on 20th January 2025:
https://about.readthedocs.com/blog/2024/12/deprecate-config-files-without-sphinx-or-mkdocs-config/
Let's also bump the Ubuntu version. I expect we should be fine with "latest LTS" rather than pinning a specific version.
https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
----
📚 Documentation preview 📚: https://pep-previews--4177.org.readthedocs.build/
=> Infra: Specify Sphinx config path for Read the Docs

peps/pep-0472.rst
The `keyword-X` footnotes were added in the PEP's first commit and never referenced:
https://github.com/python/peps/commit/84d82f06f22a789b7ed3923e37552daef13eba14
I've turned them into bullet points, and replaced the broken https://article.gmane.org/gmane.comp.python.ideas/ links with corresponding https://mail.python.org/archives/list/python-ideas@python.org/ ones.
I also turned the one remaining footnote into an inline link.
----
📚 Documentation preview 📚: https://pep-previews--4174.org.readthedocs.build/
=> PEP 472: Fix Sphinx reference warnings

peps/pep-0728.rst
- Specify that extra_items and closed are also supported with the
functional syntax.
- Rewrite the rules for `closed=True` and inheritance. I attempted
to make `closed=True` exactly equivalent to `extra_items=Never` in
terms of inheritance. The semantics as specified in the previous
version of the PEP felt harder to understand and less consistent.
- Fix some incorrect comments regarding expected type checker errors.
- Clarify section on assignability with Mapping
- Add section on runtime behavior. I tried to make the intended runtime
behavior simple to implement and understand. This makes the runtime
simpler but may make life more complicated for tools consuming the
metadata.
- Clean up trailing whitespace
This grew out of work on python/typing-extensions#519. cc @PIG208 
----
📚 …
=> PEP 728: Improve specification

.github/workflows/render.yml
3.14 is in alpha, let's dogfood.
* https://devguide.python.org/versions/
* https://peps.python.org/pep-0745/
----
📚 Documentation preview 📚: https://pep-previews--4183.org.readthedocs.build/
=> Infra: switch 3.13-dev to 3.14-dev

.github/workflows/render.yml, Makefile, peps/conf.py, requirements.txt
Right now if you typo a PEP (e.g. https://peps.python.org/pep-123456) you get the default GitHub Pages 404 page:
This is an attempt to use a nicer one using our own Sphinx theme:
I have this on my fork right now: https://hugovk.github.io/peps/pep-123456
The one difference is I have `notfound_urls_prefix = "/peps/"` in `conf.py` because it's using the github.io domain and a `peps/` subdir. See:
https://sphinx-notfound-page.readthedocs.io/en/latest/faq.html#does-this-extension-work-with-github-pages
We'll probably need to merge this to see if it works properly.
----
📚 Documentation preview 📚: https://pep-previews--4184.org.readthedocs.build/
=> Infra: Add nicer 404 page

pep_sphinx_extensions/pep_theme/templates/page.html
Follow on from https://github.com/python/peps/pull/4184.
We don't need the empty "Contents" and "[Page Source (GitHub)](https://github.com/python/peps/blob/main/peps/404.rst)" (itself a 404):
Let's remove those for 404 pages:
(It's also possible to adjust the title and body with config: https://sphinx-notfound-page.readthedocs.io/en/stable/configuration.html#confval-notfound_context)
----
📚 Documentation preview 📚: https://pep-previews--4185.org.readthedocs.build/
=> Infra: Remove "Contents" and source link from 404

peps/pep-0728.rst
----
📚 Documentation preview 📚: https://pep-previews--4188.org.readthedocs.build/
=> PEP 728: Fix code block syntax

peps/pep-0694.rst
----
📚 Documentation preview 📚: https://pep-previews--4190.org.readthedocs.build/
=> Fixed some external links in the RST

peps/pep-0767.rst
----
📚 Documentation preview 📚: https://pep-previews--4181.org.readthedocs.build/
=> PEP 767: Include `__init_subclass__` in initialization

peps/pep-0769.rst
Noticed a very small typo.
I did check and it wasn't picked up in #4192.
----
📚 Documentation preview 📚: https://pep-previews--4197.org.readthedocs.build/
=> PEP 769: Fix a typo

peps/pep-0769.rst
@facundobatista 
Hope you don't mind some tweaking of the wording!
----
📚 Documentation preview 📚: https://pep-previews--4192.org.readthedocs.build/
=> PEP 769: Fix some typos and provide some clarity

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4195.org.readthedocs.build/
=> PEP 770: Move SBOM data recommendations, address review comments

peps/pep-0747.rst
- Added missing generic parameter for `strip_annotated_metadata`
- Use the correct `typx` parameter name for `TypeForm` arguments in the `split_union` and `as_instance` / `as_type` examples.
- Add `from typing import TypeForm, cast` imports to make the usage of `typing` symbols consistent
----
📚 Documentation preview 📚: https://pep-previews--4193.org.readthedocs.build/
=> PEP 747: Minor fixes in code examples

peps/pep-0745.rst
* https://discuss.python.org/t/python-3-14-0-alpha-4/77112
* https://www.python.org/downloads/release/python-3140a4/
----
📚 Documentation preview 📚: https://pep-previews--4202.org.readthedocs.build/
=> PEP 745: 3.14.0a4 was released on 2024-01-14

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4201.org.readthedocs.build/
=> PEP 770: Remove MUST for JSON+UTF-8, fix typo

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4205.org.readthedocs.build/
=> PEP 751: update the post history

peps/pep-0751.rst
The foregoing text doesn't appear to describe  a `[[packages.files]]` key; the data that was labelled "files" looks appropriate for a `[[packages.wheels]]` entry instead. I suspect this was left over from a previous version of the PEP.
----
📚 Documentation preview 📚: https://pep-previews--4206.org.readthedocs.build/
=> PEP 751: Fix apparent typo in main example

peps/pep-0747.rst
…://github.com/microsoft/pyright/discussions/9397#discussioncomment-11777151).
----
📚 Documentation preview 📚: https://pep-previews--4204.org.readthedocs.build/
=> PEP 747: Updated to reflect the latest round of feedback

peps/pep-0735.rst
Now that a specification document is in place on the packaging site, it is possible to update this PEP to link to it.
---
The PR templates don't seem to fit this case exactly, so I assume it's fine to make this change like so.
----
📚 Documentation preview 📚: https://pep-previews--4209.org.readthedocs.build/
=> PEP 735: Add a canonical spec link

peps/pep-0735.rst
The canonical doc link was already merged (slightly out-of-order), but this change should "true it up".
As a packaging PEP, several of the checklist items are blank as not-applicable.
---
@pfmoore, there's only one thing which I learned during implementation and which I think is worth sharing. I do not think it's material to the PEP itself, but it is something which might impact future discussions.
There's a callout in the PEP and the spec doc about not doing more validation than you need to, in order to allow multiple tools and tool versions to coexist even if the spec evolves in the future.
In Python, this is very easy to support -- load the TOML data, but only read sections as you need them. …
=> PEP 735: Mark as Final

peps/pep-0750.rst
After merging our [big PR](https://github.com/python/peps/pull/4124) yesterday I noticed that the "Alternate layouts" section was out of date. I've updated it to reflect the correct past history of layouts for the `Template` type.
@AA-Turner Assuming the change looks good, we're happy to merge.
----
📚 Documentation preview 📚: https://pep-previews--4210.org.readthedocs.build/
=> PEP 750: Small update to 'alternate layouts' section

peps/pep-0751.rst
Several parts of the specification referred to a `[[packaging]]` array of tables, which presumably should refer to `[[packages]]` etc. (There's no attempt to describe a separate top-level `[[packaging]]`.)
Searched and replaced these mentions.
Also fixed a typo ("packages" -> "package") noticed while verifying the search-and-replace result.
----
📚 Documentation preview 📚: https://pep-previews--4212.org.readthedocs.build/
=> PEP 751: Ensure consistent "packages" table name

peps/pep-0739.rst, peps/pep-0739/example.json, peps/pep-0739/python-build-info-v1.0.schema.json
----
📚 Documentation preview 📚: https://pep-previews--4216.org.readthedocs.build/
=> PEP 739: some (hopefully final) updates

peps/pep-0739/example.json
----
📚 Documentation preview 📚: https://pep-previews--4221.org.readthedocs.build/
=> PEP 739: put base_prefix above base_interpreter

pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py
Follow-up to https://github.com/python/peps/pull/4114#issuecomment-2515273831.
Use the base class `admonition_class = nodes.important` for all.
----
📚 Documentation preview 📚: https://pep-previews--4152.org.readthedocs.build/
=> Infra: use same admonition for canonical-doc, canonical-pypa-spec and canonical-typing-spec

pep_sphinx_extensions/pep_theme/static/sticky_banner.js
Closes #4224.
A
----
📚 Documentation preview 📚: https://pep-previews--4225.org.readthedocs.build/
=> PEP Theme: Support multiple closeable admonitions

peps/pep-0561.rst, peps/pep-0759.rst, peps/pep-0777.rst
I wasn't sure whether this is classified as a meta change or an editorial change, so I just chose editorial.
----
📚 Documentation preview 📚: https://pep-previews--4229.org.readthedocs.build/
=> PEP 561, 759, 777: Update my name, email, and links

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4228.org.readthedocs.build/
=> PEP 770: Move 'Selecting a single SBOM standard' to rejected ideas

peps/pep-0639.rst, peps/pep-0639/appendix-examples.rst, peps/pep-0639/appendix-user-scenarios.rst
----
📚 Documentation preview 📚: https://pep-previews--4227.org.readthedocs.build/
=> PEP 639: Mark as Final

peps/pep-0661.rst
Simplify the suggestion further by making it more opinionated: remove the options to customize the repr and the truthiness.
Use "sentinellib" rather than "sentinels" for the proposed module name, to avoid clashing with an existing popular package on PyPI.
Also a few minor tweaks to wording.
----
📚 Documentation preview 📚: https://pep-previews--4232.org.readthedocs.build/
=> PEP 661: Some changes after submission (before SC review)

peps/pep-0387.rst
----
📚 Documentation preview 📚: https://pep-previews--4156.org.readthedocs.build/
=> PEP 387: Suggest waiting 5 years before removing a deprecated feature

peps/pep-0774.rst
----
📚 Documentation preview 📚: https://pep-previews--4236.org.readthedocs.build/
=> PEP 744: Add Discussions-To link and minor revisions

.github/CODEOWNERS, peps/conf.py, peps/pep-0764.rst, peps/pep-9995.rst
----
📚 Documentation preview 📚: https://pep-previews--4082.org.readthedocs.build/pep-0764/
=> PEP 764: Inlined typed dictionaries

peps/pep-0745.rst
I'll be attending [PyCon Estonia](https://pycon.ee/) on 2-3 October, so will be unavailable for release on Wednesday 2025-10-01, so let's move it to Tuesday 2025-10-07.
This is similar to 3.13.0 final, which went out on 2024-10-07.
As it happens, 3.13.6 is also planned for Tuesday 2025-10-07.
cc:
* @doko42 @mitya57 / Debian
* @hroncok / @befeleme / Fedora / RHEL
* @mgorny / Gentoo
* @danigm @mcepl / openSUSE
Would this cause significant problems for you? Alternatively, we may be able to move it to the end of September.
----
📚 Documentation preview 📚: https://pep-previews--4199.org.readthedocs.build/
=> PEP 745: Update 3.14.0 final release date

peps/pep-3108.rst
These references were all used at some point, then their uses were later removed but the refs left intact. We can remove them now:
* module-index: https://github.com/python/peps/commit/ea3b5e5b6413db13cbc07e350eb1214c79001701
* py-dev-summary-2004-11-01: https://github.com/python/peps/commit/6099923396b1158bb6cc2b1c832071e7d0fbfe4c
* twisted: https://github.com/python/peps/commit/6099923396b1158bb6cc2b1c832071e7d0fbfe4c
* sun-au: https://github.com/python/peps/commit/f0e39dc4ce0860284357b27a30529c70905192e1
----
📚 Documentation preview 📚: https://pep-previews--4243.org.readthedocs.build/
=> PEP 3108: Fix Sphinx reference warning

peps/pep-3126.rst
The reference here is mentioned in the text, but was missing an underscore. Also, not needed to fix the ref, editorially added a colon.
----
📚 Documentation preview 📚: https://pep-previews--4242.org.readthedocs.build/
=> PEP 3126: Fix Sphinx reference warning

peps/pep-3141.rst
The reference was added in https://github.com/python/peps/commit/66baf214a23fb052bb26527419771be9ee02e259 but never referenced in the text.
This PR turns it into a bullet point to remove the warning.
----
📚 Documentation preview 📚: https://pep-previews--4241.org.readthedocs.build/
=> PEP 3141: Fix Sphinx reference warning

peps/pep-3146.rst
The reference was added in https://github.com/python/peps/commit/b3dd94c365a3ec92501cbf5305e26709d3b49cb9 when the PEP was added, and never referenced in the text.
This PR turns it into a bullet point to remove the warning.
----
📚 Documentation preview 📚: https://pep-previews--4240.org.readthedocs.build/
=> PEP 3146: Fix Sphinx reference warning

peps/pep-0499.rst
----
📚 Documentation preview 📚: https://pep-previews--4245.org.readthedocs.build/
=> PEP 499: Fix 404 mail.python.org link

peps/pep-0759.rst
After discussion among the authors @emmatyping and myself, we have decided to withdraw PEP 759.  This PR changes the `Status` to `Withdrawn`, include a `PEP withdrawn` section for the withdrawal rationale, and and *incomplete* `Resolution` header.
I'm setting this PR to Draft to prevent merging until I have a chance to post on the DPO thread that the PEP is withdrawn.  Then I'll update the `Resolution` header with the link, and merge the PR.  However, please do review for copyediting purposes.  Thanks!
----
📚 Documentation preview 📚: https://pep-previews--4248.org.readthedocs.build/
=> Withdraw PEP 759

peps/pep-0739.rst, peps/pep-0739/python-build-info-v1.0.schema.json
https://discuss.python.org/t/pep-739-static-description-file-for-build-details-of-python-installations/44572/90
----
📚 Documentation preview 📚: https://pep-previews--4252.org.readthedocs.build/
=> PEP 739: Mark as Accepted

peps/pep-0771.rst
There has been an extensive discussion going on in this [DPO](https://discuss.python.org/t/pre-publish-pep-711-default-extras-for-python-software-packages/77892) thread while the original PR for PEP 771 was being reviewed. Rather than continuously update that PR, @pradyunsg suggested that that PEP should be published as-is initially and that changes based on the pre-publish discussion should be made in a separate PR. This is the separate PR :tada: 
The main changes are:
* Real-life examples of packages have been added in several places by popular demand
* Most of the 'How to teach this' section has been moved to a new 'Examples of usage' section, and 'How to teach this' has been filled with new content
* The backward-compatibility section has been expanded to address concerns raised …
=> PEP 771: Amendments following pre-publish discussion

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4256.org.readthedocs.build/
=> PEP 751: Fix example

peps/pep-0739.rst
Small improvements based on read through of the published PEP.
----
📚 Documentation preview 📚: https://pep-previews--4257.org.readthedocs.build/
=> Fix some typos and add some links

peps/pep-2026.rst
----
📚 Documentation preview 📚: https://pep-previews--4258.org.readthedocs.build/
=> PEP 2026: Mark as Rejected

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4259.org.readthedocs.build/
=> PEP 751: fix section order

peps/pep-0693.rst, peps/pep-0719.rst
* https://discuss.python.org/t/python-3-13-2-and-3-12-9-now-available/79509
* https://www.python.org/downloads/release/python-3129/
* https://www.python.org/downloads/release/python-3132/
----
📚 Documentation preview 📚: https://pep-previews--4265.org.readthedocs.build/
=> PEP 693, 719: 3.12.9 and 3.13.1 released 2025-02-04

peps/pep-3131.rst
---
Fixes https://github.com/python/peps/issues/4262.
* Replace a broken link with Internet Archive version
* Use https for other links
* Move reference footnotes to inline links
=> PEP 3131: Fix links

peps/pep-0745.rst
* https://discuss.python.org/t/python-3-14-0-alpha-5/80364
* https://www.python.org/downloads/release/python-3140a5/
----
📚 Documentation preview 📚: https://pep-previews--4268.org.readthedocs.build/
=> PEP 745: 3.14.0a5 was released on 2024-02-11

peps/pep-0747.rst
Updated draft PEP 747 to fix a few bugs found by reviewers and to reflect the majority consensus on assignability of `type[T]` to `TypeForm[T]`.
----
📚 Documentation preview 📚: https://pep-previews--4269.org.readthedocs.build/
=> PEP 747: Round of updates based on feedback

peps/pep-0769.rst
----
📚 Documentation preview 📚: https://pep-previews--4272.org.readthedocs.build/
=> PEP 769: Better explanation on which exceptions are captured

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4271.org.readthedocs.build/
=> PEP 770: Add build environment and reproducibility to motivation

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4278.org.readthedocs.build/
=> PEP 770: Add list of differences between PEP 725 and PEP 770

peps/pep-0693.rst
3.12.6 was an extra odd-month release between the regularly scheduled even-month releases, so we'll be going up to 10.
https://peps.python.org/pep-0693/#bugfix-releases
----
📚 Documentation preview 📚: https://pep-previews--4280.org.readthedocs.build/
=> PEP 693: 3.12.10 is final planned bugfix release

.github/CODEOWNERS
eliben and doerwalter left the core team in 2020 and 2021 respectively: 
https://devguide.python.org/core-developers/developer-log/
They are no longer members of the https://github.com/python organisation so we need to update https://github.com/python/peps/blob/main/.github/CODEOWNERS:
----
📚 Documentation preview 📚: https://pep-previews--4282.org.readthedocs.build/
=> Remove eliben and doerwalter from CODEOWNERS

.github/CODEOWNERS, peps/pep-0775.rst
----
📚 Documentation preview 📚: https://pep-previews--4281.org.readthedocs.build/pep-0775/
=> PEP 775: Make zlib required to build CPython

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4287.org.readthedocs.build/
=> PEP 751: drop `packages.direct` and add `extras` and `dependency-groups`

peps/pep-0751.rst
=> PEP 751: Fix typos

peps/pep-0770.rst
cc @rgommers 
----
📚 Documentation preview 📚: https://pep-previews--4283.org.readthedocs.build/
=> PEP 770: Add the dist-info.files table and reserve dist-info dirs

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4290.org.readthedocs.build/
=> PEP 751: mention dependency groups for services to look for

pep_sphinx_extensions/pep_processor/parsing/pep_banner_directive.py, peps/conf.py, peps/pep-0012.rst, peps/pep-0688.rst, peps/pep-0692.rst, peps/pep-0728.rst, peps/pep-0729.rst, peps/pep-0767.rst
Cf. python/typing#1924
----
📚 Documentation preview 📚: https://pep-previews--4291.org.readthedocs.build/
=> Change links from typing.readthedocs.io to typing.python.org

peps/pep-0752.rst
The PEP-0752 is important for community driven projects - such as Apache Airflow, not only because of security risks but also because of concerns with public discussions about new names of distributions following agreed and implemented pattern.
As agreed with Ofek, I am happy to become co-author of the PEP and added more motivation explaining this case.
----
📚 Documentation preview 📚: https://pep-previews--4292.org.readthedocs.build/
=> PEP 752: Updates including co-authoring of the PEP

peps/pep-0773.rst
----
📚 Documentation preview 📚: https://pep-previews--4249.org.readthedocs.build/
=> PEP 773: Textual tweaks and clarifications

peps/pep-0751.rst
This change is based on feedback from Poetry.
Also fix some typos.
----
📚 Documentation preview 📚: https://pep-previews--4300.org.readthedocs.build/
=> PEP 751: drop the requirement that installers default to not installing any extras or dependency groups

peps/pep-0745.rst
* https://discuss.python.org/t/python-3-14-0-alpha-6/84513
* https://www.python.org/downloads/release/python-3140a6/
----
📚 Documentation preview 📚: https://pep-previews--4303.org.readthedocs.build/
=> PEP 745: 3.14.0a6 was released on 2024-03-14 (π day)

peps/pep-0758.rst
----
📚 Documentation preview 📚: https://pep-previews--4304.org.readthedocs.build/
=> PEP 758: Mark as Accepted

peps/pep-0751.rst
- Make `packages.*.name` optional
- `packages.directory.editable` can be ignored at install-time
- Clarify the marker syntax changes
- Introduce `default-group`
- Clarify how this PEP does not fully replace requirements files
- Clarify how different installers can be used to install from a lock file, but different lockers could lead to different outcomes
----
📚 Documentation preview 📚: https://pep-previews--4306.org.readthedocs.build/
=> PEP 751: address feedback

peps/pep-0751.rst
Also clarify that using `extras` and `dependency_groups` outside of lock file is an error.
----
📚 Documentation preview 📚: https://pep-previews--4308.org.readthedocs.build/
=> PEP 751: Make `default-group` be `default-groups`

peps/pep-0765.rst
=> PEP 765: Mark as Final

peps/pep-0755.rst
This ambiguity came up during the [PoC](https://github.com/pypi/warehouse/pull/17691).
----
📚 Documentation preview 📚: https://pep-previews--4312.org.readthedocs.build/
=> PEP 755: Address feedback, round 2

peps/pep-0768.rst
----
📚 Documentation preview 📚: https://pep-previews--4317.org.readthedocs.build/
=> PEP 768: Mark as Accepted

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4321.org.readthedocs.build/
=> PEP 770: Remove mechanism for statically defining SBOM files

peps/pep-0776.rst
To be split into its own pep per @pfmoore's instructions.
----
📚 Documentation preview 📚: https://pep-previews--4327.org.readthedocs.build/
=> PEP 776: Remove all discussion of packaging

peps/pep-0751.rst
Made it explicit that `dependency-groups` represents the groups users are expected to be able to set via a tool's UI. Also made clear what `extras` and `dependency_groups` should be set to by default.
----
📚 Documentation preview 📚: https://pep-previews--4330.org.readthedocs.build/
=> PEP 751: address some minor user feedback

peps/pep-0752.rst
Based on feedback here: https://discuss.python.org/t/63192/86
----
📚 Documentation preview 📚: https://pep-previews--4329.org.readthedocs.build/
=> PEP 752: Address feedback, round 6

peps/pep-0782.rst
----
📚 Documentation preview 📚: https://pep-previews--4335.org.readthedocs.build/
=> PEP 782: Address Steve's review

.github/PULL_REQUEST_TEMPLATE/Mark a PEP as Accepted or Rejected.md, .github/PULL_REQUEST_TEMPLATE/Mark a PEP as Final.md
* Suggest "Mark as Final"
* Suggest including the date in the Resolution field
----
📚 Documentation preview 📚: https://pep-previews--4338.org.readthedocs.build/
=> Meta: Minor updates to PR templates

peps/pep-0751.rst
----
📚 Documentation preview 📚: https://pep-previews--4339.org.readthedocs.build/
=> PEP 751: Fix typo in `dependency_groups`

peps/pep-0748.rst
Parts of this PEP reference sections of the numbered lists and it makes it more challenging to read when the numbered list isn't actually displayed correctly 😉 .
----
📚 Documentation preview 📚: https://pep-previews--4340.org.readthedocs.build/
=> PEP 748: Fix auto-numbering syntax for RST

peps/pep-0781.rst
----
📚 Documentation preview 📚: https://pep-previews--4341.org.readthedocs.build/
=> PEP 781: Add deprecation and a rejected idea

peps/pep-0008.rst
Closes #4342.
----
📚 Documentation preview 📚: https://pep-previews--4343.org.readthedocs.build/
=> PEP 8: Remove the diamond (`<>`) inequality operator

.github/CODEOWNERS, peps/pep-0781.rst, peps/pep-0784.rst
----
📚 Documentation preview 📚: https://pep-previews--4348.org.readthedocs.build/
=> PEP 784: Adding Zstandard to the standard library

peps/pep-0784.rst
Follows on from #4348.
A
----
📚 Documentation preview 📚: https://pep-previews--4350.org.readthedocs.build/pep-0784/
=> PEP 784: Editorial review

peps/pep-0784.rst
Hopefully this is a bit clearer with regards to timeline.
----
📚 Documentation preview 📚: https://pep-previews--4352.org.readthedocs.build/
=> PEP 784: Updates to timeline and RFC reference

peps/api/index.rst
PEP 160 (listed as an example) as well as other PEPs (e.g. 0 and 3) have `post_history` as null, so it probably makes sense to document it like other nullable fields.
----
📚 Documentation preview 📚: https://pep-previews--4354.org.readthedocs.build/
=> Document peps.json post_history as nullable

peps/pep-0596.rst, peps/pep-0619.rst, peps/pep-0664.rst, peps/pep-0693.rst, peps/pep-0719.rst, peps/pep-0745.rst
Releases of 3.9-3.14:
* https://discuss.python.org/t/python-3-14-0a7-3-13-3-3-12-10-3-11-12-3-10-17-and-3-9-22-are-now-available/87580
=> PEPs 596, 619, 664, 693, 719, 745: Update release dates

peps/pep-0750.rst
----
As part of pre-acceptance of PEP 750, the [Steering Council requested four small updates](https://github.com/python/steering-council/issues/275#issuecomment-2781683333) to the PEP. I've taken a first cut at all four:
With this PR, hopefully we can all put eyes on PEP 750 and get it to a state we're excited about! :tada:
----
📚 Documentation preview 📚: https://pep-previews--4351.org.readthedocs.build/pep-0750/
=> PEP 750: Updates requested by the Steering Council

peps/pep-0589.rst
See the screenshot (from https://peps.python.org/pep-0589/#type-consistency):
----
📚 Documentation preview 📚: https://pep-previews--4358.org.readthedocs.build/
=> PEP 589: Fix indentation issue with one of the example snippets

check-peps.py, pep_sphinx_extensions/tests/pep_lint/test_pep_lint.py, pep_sphinx_extensions/tests/pep_lint/test_post_url.py, peps/pep-0012.rst, peps/pep-0012/pep-NNNN.rst
There's often confusion about whether the discussion thread should be created before or after the draft PEP has been merged.
It's often better to merge the PEP first, and the the thread can use the https://peps.python.org/ URL instead of disseminating a temporary RTD URL that will soon be outdated and later deleted.
The linter is confusing too: "Discussions-To must be a valid thread URL or mailing list" makes some think the thread must be created first to pass, it's not obvious they can omit the field to satisfy the linter.
Finally, PEP 12 says "it is okay to just list the venue name initially" but the linter requires a thread or ML URL.
Instead, I think it may improve things if authors can write ~"Discussions-To: TBA"~ "Discussions-To: Pending" without the linter complaining. We can then …
=> PEP 12: Allow "Pending" as Discussions-To

peps/pep-0661.rst
Deferred for Python 3.14 based on Steering Council recommendation.
----
📚 Documentation preview 📚: https://pep-previews--4363.org.readthedocs.build/
=> Officially defer PEP 661

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4366.org.readthedocs.build/
=> PEP 770: Fix a handful of review comments

peps/pep-0770.rst
----
📚 Documentation preview 📚: https://pep-previews--4367.org.readthedocs.build/pep-0770/
=> PEP 770: Mark as Accepted

pep_sphinx_extensions/generate_rss.py
This eliminates an AttributeError during PEP editing, if the PEP being edited has an Abstract or Introduction section but with no interior content (i.e. paragraphs) yet.
In practice this should have no effect on actual
RSS feeds, since merged PEPs should always have a proper abstract. However, this prevents a confusing error from bubbling up during local editing.
See #4355.
----
📚 Documentation preview 📚: https://pep-previews--4356.org.readthedocs.build/
=> Infra: Make PEP abstract extration more robust

.github/CODEOWNERS, peps/pep-0785.rst
I've discussed this fairly extensively with @gpshead, and we've been using related functions at work for some time now.  I'm therefore posting the PR now to get the process rolling; I also expect to polish the prose (especially the footnotes) a little further before merging.
(apologies for the intitial confusion here)
(none identified)
(none identified)
----
📚 Documentation preview 📚: https://pep-previews--4357.org.readthedocs.build/
=> PEP 785: New methods for easier handling of `ExceptionGroup`s

peps/pep-0785.rst
Per @hugovk's request in https://github.com/python/peps/pull/4357#issuecomment-2800482219 🙂 
----
📚 Documentation preview 📚: https://pep-previews--4372.org.readthedocs.build/
=> PEP 785: post-history

peps/pep-0787.rst
Adds the discussion-to and post-history to PEP 787
----
📚 Documentation preview 📚: https://pep-previews--4373.org.readthedocs.build/
=> PEP 787: Add discussion-to

peps/pep-0694.rst
https://discuss.python.org/t/pep-694-pypi-upload-api-2-0/76316/2
Summary:
* Add some error return code descriptions where they were underspecified
* Fix some misspellings and poorly worded text
* Combine the canceling and deleting of upload files sections
* Simplify the rules for replacing a staged but not yet published file
* Add open question about deferring stage previews
* Update `Post-History` header
----
📚 Documentation preview 📚: https://pep-previews--4323.org.readthedocs.build/
=> PEP 694: Several updates based on Michał Górny's feedback on DPO

peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--4374.org.readthedocs.build/
=> PEP 734: Simplify Explanations of "Shareable" Objects

peps/pep-0784.rst
Hopefully this condenses down all of the discussions that have happened so far in the discussion thread regarding naming as well as whether or not to include gzip/zipfile/tarfile.
=> PEP 784: Updates to reflect inclusion of gzip and discussed rejected ideas

peps/pep-0780.rst
The main purpose of this PR is to focus PEP 780 on its packaging impact by removing the initially proposed standard library addition.
----
📚 Documentation preview 📚: https://pep-previews--4377.org.readthedocs.build/
=> PEP 780: Remove standard library addition from PEP

peps/pep-0785.rst
Brett Canon [observed](https://discuss.python.org/t/pep-785-new-methods-for-easier-handling-of-exceptiongroups/88244/2):
> I will say the name `flat_exceptions()` confused me initially as a “flat exception” isn’t a thing.
and on reflection I agreed that this made sense, renaming the method to `.leaf_exceptions()` to match terminology from PEP-654.  If this PEP is accepted, I plan to check for appropriate places to introduce the term to the exception-group tutorial and reference documentation.
Updating [my GitHub search](https://github.com/search?q=%2F%5C.leaf_exceptions%5C%28%2F+language%3APython&type=code) for existing uses of this name still finds zero hits.  Interestingly, https://github.com/python-trio/exceptiongroup/pull/13 proposed a `leaf_exceptions()` helper for a precursor to …
=> PEP 785: rename method, and a rejected idea

peps/pep-0787.rst
Change python version to target 3.15 instead of 3.14
----
📚 Documentation preview 📚: https://pep-previews--4381.org.readthedocs.build/
=> PEP 787: Postpone to Python 3.15

peps/pep-0773.rst
----
📚 Documentation preview 📚: https://pep-previews--4378.org.readthedocs.build/
=> PEP 773: Replace open issues with decisions. Remove empty footnotes section

peps/pep-0772.rst
This will be best reviewed commit-by-commit.
----
📚 Documentation preview 📚: https://pep-previews--4320.org.readthedocs.build/
=> PEP 772: A round of updates

peps/pep-0772.rst
Follow up to #4320 
----
📚 Documentation preview 📚: https://pep-previews--4382.org.readthedocs.build/
=> PEP 772: Follow up PR to clarify a few more things

peps/pep-0728.rst
https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443/150
cc @erictraut
----
📚 Documentation preview 📚: https://pep-previews--4383.org.readthedocs.build/
=> PEP 728: Address additional feedback

peps/pep-0749.rst
* Add discussion of conditional annotations
* Add discussion of partially execute modules
* Change plans on the metaclasses issue
* Explain the motivation of the `VALUE_WITH_FAKE_GLOBALS` name
* Adjust two APIs in `annotationlib`
----
📚 Documentation preview 📚: https://pep-previews--4316.org.readthedocs.build/
=> PEP 749: Updates

peps/pep-0772.rst
As per [this discussion on DPO](https://discuss.python.org/t/pep-772-packaging-governance-process/79724/52).  The intention is to align PEP 772 with PEP 13.
----
📚 Documentation preview 📚: https://pep-previews--4384.org.readthedocs.build/
=> PEP 772: As with PEP 13, seconding a vote of no confidence should be open for one week

peps/pep-0787.rst
Note: requires approving review from @nhumrich before merging.
----
📚 Documentation preview 📚: https://pep-previews--4389.org.readthedocs.build/
=> PEP 787: defer pending PyPI library experimentation

peps/pep-0784.rst
I removed any references to removal or deprecation of the existing modules other than to say that it is left to a future decision as part of the Backwards Compatibility section.
At the behest of Barry, cc'ing @python/steering-council to review the exact language.
----
📚 Documentation preview 📚: https://pep-previews--4387.org.readthedocs.build/
=> PEP 784: Mark as Accepted

.github/CODEOWNERS, peps/pep-0790.rst
Tuesdays have been working well, with Final planned for 1st October (a Thursday).
Includes a slight rewording of the lifespan section, and state the security phase is three years. Also format as a bullet list.
----
📚 Documentation preview 📚: https://pep-previews--4388.org.readthedocs.build/pep-0790/
=> PEP 790: Python 3.15 release schedule

peps/pep-0788.rst
This doesn't change anything about the PEP, but fixes a few [clarity issues](https://discuss.python.org/t/pep-788-reimagining-native-threads/89863/2) that quickly came up. Sorry for the churn and extra PR here :(
----
📚 Documentation preview 📚: https://pep-previews--4391.org.readthedocs.build/pep-0788/
=> PEP 788: Add some minor clarifications

peps/pep-0728.rst
Discussion:
https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443/153
This mainly clarifies indexed accesses and assignments with arbitrary str keys.
cc @carljm :
Let me know if there is anything else you have in mind!
----
📚 Documentation preview 📚: https://pep-previews--4393.org.readthedocs.build/
=> PEP 728: Address feedback from Carl

.github/workflows/documentation-links.yml
If you make a fork, and then a coauthor makes a PR to that fork, a non-working docs link will get generated. This should fix this by making sure it's only being added to PRs to this repository, and not PRs to forks.
Example: https://github.com/henryiii/peps/pull/1
~~Though I need to try to test this in my fork to make sure, `pull_request_target` can be tricky.~~ I think I have to test it by PR'ing into this branch on my fork. Edit: yes, it's working: https://github.com/henryiii/peps/pull/2
----
📚 Documentation preview 📚: https://pep-previews--4399.org.readthedocs.build/
=> Infra: Only add preview links for PRs to ``python/peps``

peps/pep-0423.rst
Even though typo fixes like this are advised against -- this is pretty bad because we have a scam website right here when you open it for the first time in a browser profile.  Therefore I decided to break this rule.
Fixes #4401.
----
📚 Documentation preview 📚: https://pep-previews--4402.org.readthedocs.build/
=> PEP 423: Fix a Link that Leads to Scam Website on First Opening

peps/pep-0782.rst
----
📚 Documentation preview 📚: https://pep-previews--4407.org.readthedocs.build/
=> PEP 782: Set the Python version to 3.15

peps/pep-0749.rst
cc @warsaw 
----
📚 Documentation preview 📚: https://pep-previews--4406.org.readthedocs.build/
=> PEP 749: Mark as Accepted

peps/pep-0727.rst
@tiangolo agreed to withdraw the PEP in emails last year, but this never happened. Let's clean it up.
----
📚 Documentation preview 📚: https://pep-previews--4408.org.readthedocs.build/
=> PEP 727: Mark as Withdrawn

peps/pep-0718.rst, peps/pep-0728.rst, peps/pep-0746.rst, peps/pep-0747.rst, peps/pep-0764.rst, peps/pep-0767.rst, peps/pep-0781.rst
The ship has sailed for 3.14. cc @Gobot1234 @PIG208 @adriangb @davidfstr @Viicos @Enegg @methane 
Several of these PEPs seem pretty far along and I'd encourage you to submit them to the Typing Council for a decision.
----
📚 Documentation preview 📚: https://pep-previews--4409.org.readthedocs.build/
=> Open typing PEPs: Retarget to 3.15

peps/pep-0764.rst
- _inlined_ -> _inline_ as per https://github.com/python/typing_extensions/pull/579#issuecomment-2781631062.
- Decide on runtime implementation: inline TDs are implemented as classes.
- Explicitly allow inline TDs to be extended.
- Update runtime behavior section, not mentioning implementation details.
- Refer to mypy's and typing_extension's implementations.
To avoid yet another update, might be best to wait for the outcome of PEP 728 so that I can update this PEP with respect to the closed behavior.
cc @erictraut 
=> PEP 764: Second round of updates

peps/pep-0563.rst
Alternative to and would close #3571, cc @JelleZijlstra.
A
----
📚 Documentation preview 📚: https://pep-previews--4411.org.readthedocs.build/
=> PEP 563: Mark as Superseded

peps/pep-0745.rst
Python 3.14.0 beta 1 was released today https://www.python.org/downloads/release/python-3140b1/
----
📚 Documentation preview 📚: https://pep-previews--4415.org.readthedocs.build/
=> PEP 745: Update 3.14.0b1 release date

peps/pep-0770.rst
Links to the canonical specification for PEP 770.
----
📚 Documentation preview 📚: https://pep-previews--4418.org.readthedocs.build/
=> PEP 770: Add canonical specification

peps/pep-0719.rst
Currently, the expected PEPs are under the `Actual` subheading.  This PR puts them under their own `Expected` subheading, [following the form like that for 3.14.0.](https://github.com/python/peps/blob/61cfcda7f94fd9c477521918e9d60090d2cf0b40/peps/pep-0745.rst?plain=1#L36-L58)
----
📚 Documentation preview 📚: https://pep-previews--4425.org.readthedocs.build/
=> PEP 719: Move actual bugfix releases to their own subsection

peps/pep-0776.rst
There is some more work to be done to teach CMake and other build systems that Emscripten supports RPATH. But those are packaging problems. I think this section can be deleted.
----
📚 Documentation preview 📚: https://pep-previews--4423.org.readthedocs.build/
=> PEP 776: RPATH is fully supported as of Emscripten 4.0.8

peps/pep-0745.rst
Target beta 2 for Monday 2025-05-26 rather than Tuesday 2025-05-27. I'm off to PyCon Italia very early on Wednesday, so this also gives an extra day of buffer in case of delays.
=> PEP 745: Target 3.14.0b2 a day earlier

peps/pep-0784.rst
----
📚 Documentation preview 📚: https://pep-previews--4436.org.readthedocs.build/
=> PEP 784: Mark as Final

peps/pep-0745.rst
----
📚 Documentation preview 📚: https://pep-previews--4441.org.readthedocs.build/
=> PEP 745: 3.14.0b2 was released on 2025-05-26

peps/pep-0758.rst
=> PEP 758: Mark as Final

peps/pep-0772.rst
I noticed the discussion header was still referring to the original thread.
----
📚 Documentation preview 📚: https://pep-previews--4445.org.readthedocs.build/
=> PEP 772: Update discussion link

peps/pep-0794.rst
----
📚 Documentation preview 📚: https://pep-previews--4448.org.readthedocs.build/
=> PEP 794: Import name metadata

peps/pep-0734.rst
This includes the provision to name the module `concurrent.interpreters`.  We are still discussing
dropping that provision and sticking with just `interpreters`, but that can be addressed
in a later change if it happens.
----
📚 Documentation preview 📚: https://pep-previews--4451.org.readthedocs.build/
=> PEP 734: Mark as Accepted

peps/pep-0771.rst
Following the initial publication of PEP 771, there has been a lot of discussion in this [DPO](https://discuss.python.org/t/pep-771-default-extras-for-python-software-packages/79706) thread. This PR makes changes to PEP 771 that hopefully addresses most of the concerns there.
The main changes are:
* ``package[]`` is now considered to be the primary way to specify that a package without any default extras is being requested
* The alternative approach of splitting packages into two has now been added, and given a reasonably extensive section as it appears to be the main alternative
* Added text regarding packages that have both multiple backends and frontends and might want at least one default for each
* Added a reference to PEP 751 since that PEP in principle solves the current ``pip …
=> PEP 771: Amendments following discussion

peps/pep-0792.rst
Per procedure, I've opened <https://discuss.python.org/t/pep-792-project-status-markers-in-the-simple-index/94978> for this PEP's discussion.
----
📚 Documentation preview 📚: https://pep-previews--4455.org.readthedocs.build/
=> PEP 792: add Discussions-To link

peps/pep-0387.rst, peps/pep-0793.rst, peps/pep-0793/examplemodule.c, peps/pep-0793/shim.c
---
- Add a shim to implement the old hook in terms of the new one
- Soft-deprecate the old hook
- Allow tokens for `PyType_GetModuleByDef`
----
📚 Documentation preview 📚: https://pep-previews--4453.org.readthedocs.build/pep-0793/
=> PEP 793: Updates from discussion & implementation

peps/pep-0672.rst
I intended these to be *further reading*, but since they're specifications, people might assume that Python is conformant. It is not. (Formally, we don't even pass the [very first point](https://www.unicode.org/reports/tr55/#Conformance) of TR55's checklist -- *“An implementation claiming conformance to this specification shall identify the version of this specification.”*)
@miketheman, does this clear things up?
----
📚 Documentation preview 📚: https://pep-previews--4460.org.readthedocs.build/
=> PEP 672: Note that mentioning Unicode specs doesn't mean we follow them

peps/pep-0747.rst
---
I wanted to specially thank a number of folks who have contributed to the TypeForm PEP. 💖 **For each person that I mentioned†, please review my summary of your key contribution(s) and let me know if you'd like to modify the wording.**
This Acknowledgements section is the last major change I intend to make to this PEP before submitting it to the Typing Council for review. There are already (nearly‡) 2 implementations of the PEP available in major typecheckers and no significant further issues were discovered during the implementation process.
† Folks I mentioned in this PR, tagged for visibility:
‡ The mypy implementation is still going through PR reviews. The pyright implementation has existed for many months now.
----
📚 Documentation preview 📚: …
=> PEP 747: Add Acknowledgements section

peps/pep-0792.rst
@brettcannon points out that the current language implicitly concerns only the "project level" index responses, not the "root" response. This change hopefully clarifies that by making it explicit 🙂 
----
📚 Documentation preview 📚: https://pep-previews--4457.org.readthedocs.build/
=> PEP 792: clarify index API changes

peps/pep-0792.rst
Per discussion from https://discuss.python.org/t/pep-792-project-status-markers-in-the-simple-index/94978/7
CC @sethmlarson 
Signed-off-by: William Woodruff <william@yossarian.net>
----
📚 Documentation preview 📚: https://pep-previews--4463.org.readthedocs.build/
=> PEP 792: additional review feedback

peps/pep-0685.rst
----
📚 Documentation preview 📚: https://pep-previews--4470.org.readthedocs.build/
=> PEP 685: Mark as Final

peps/pep-0745.rst
https://discuss.python.org/t/python-3-14-0-beta-3-is-here/95843
cc @hugovk 
----
📚 Documentation preview 📚: https://pep-previews--4471.org.readthedocs.build/
=> PEP 745: 3.14.0b3 was released on 2025-06-17

peps/pep-0768.rst
- Remove the struct tag
- Add `Py_` to `MAX_SCRIPT_PATH_SIZE`
As discussed in: https://discuss.python.org/t/73969/58
---
Not *exactly* an editorial issue, but I don't think it needs a full SC vote. @pablogsal, are you OK with approving this yourself?
----
📚 Documentation preview 📚: https://pep-previews--4473.org.readthedocs.build/
=> PEP 768: Make sure C API names start with `Py_`

peps/pep-0788.rst
I've done the following here:
1. Removed the ten-year deprecation for `PyGILState` and instead leave it as undetermined.
2. Made many small changes that improve the clarity of the proposal.
3. Added an "Acknowledgements" section.
I plan to submit PEP 788 to the C API working group for feedback after this is merged.
----
📚 Documentation preview 📚: https://pep-previews--4474.org.readthedocs.build/
=> PEP 788: Minor clarity changes and improvements

peps/pep-0728.rst
Jukka pointed out the incorrect use of extra_items here:
https://discuss.python.org/t/pep-728-typeddict-with-typed-extra-items/45443/157
Also fixed a minor issue with a class missing its body.
----
📚 Documentation preview 📚: https://pep-previews--4475.org.readthedocs.build/
=> PEP 728: Fix minor issues with examples

peps/pep-0710.rst
----
📚 Documentation preview 📚: https://pep-previews--3884.org.readthedocs.build/
=> PEP 710: elaborate on storing at least one hash

peps/pep-0734.rst
----
📚 Documentation preview 📚: https://pep-previews--4479.org.readthedocs.build/
=> PEP 734: Mark as Final

peps/pep-0695.rst
Changed `template <typename>` to `template <typename T>` in the C++ generic class example.
----
📚 Documentation preview 📚: https://pep-previews--4485.org.readthedocs.build/
=> PEP 695: Fix template definition in C++ example

peps/pep-0745.rst
* https://discuss.python.org/t/python-3-14-0-beta-4-is-here/98092/1
* https://www.python.org/downloads/release/python-3140b4/
----
📚 Documentation preview 📚: https://pep-previews--4488.org.readthedocs.build/
=> PEP 745: 3.14.0b4 was released on 2025-07-08

peps/pep-0011.rst
With the restoration of an [Emscripten buildbot](https://buildbot.python.org/#/builders/1810), plus python/cpython#136230 and python/steering-council#256, we are now in a position to formally restore Emscripten to Tier 3.
----
📚 Documentation preview 📚: https://pep-previews--4490.org.readthedocs.build/
=> PEP 11: Restore Emscripten to Tier 3

peps/pep-0788.rst
---
- Add a `PyThreadRef` parameter to `PyThreadState_Ensure` and `PyThreadState_Release`.
- Rename the PEP to "Interpreter References", alongside removing the (confusing) usage of "native thread". I think this is a good short and sweet title, something like "Attaching Thread States via Interpreter References" felt too long and redundant to me.
----
📚 Documentation preview 📚: https://pep-previews--4478.org.readthedocs.build/pep-0788/
=> PEP 788: Address feedback from second round

peps/pep-0011.rst
Emscripten is no longer getting removed!
Follow-up for #4490 (commit 25cec5d07e93f7de4f42b930ec25c8d4ffbfa95b)
cc @freakboy3742 @AA-Turner
----
📚 Documentation preview 📚: https://pep-previews--4491.org.readthedocs.build/
=> PEP 11: Remove Emscripten from No-longer-supported platforms

peps/pep-0628.rst
Like https://github.com/python/cpython/issues/136122.
Vi Hart has removed intentionally removed their videos from YouTube: https://www.patreon.com/posts/vihart-channel-129842460
One is available on their Vimeo. The other is not, so use another YouTube copy. Also update other links to https.
----
📚 Documentation preview 📚: https://pep-previews--4487.org.readthedocs.build/
=> PEP 628: Fix 'Pi is [(still)] wrong' links

.github/CODEOWNERS, peps/pep-0798.rst, peps/pep-9999.rst
This PEP follows the discussion from [this thread](https://discuss.python.org/t/pre-pep-unpacking-in-comprehensions/96362) about adding support for unpacking syntax in comprehensions / genexps.
CC @JelleZijlstra, @edemaine
----
📚 Documentation preview 📚: https://pep-previews--4498.org.readthedocs.build/
=> PEP 798: Unpacking in Comprehensions

peps/pep-0798.rst
Fixes a small typo in PEP 798, a duplicate piece of code in an early example box.
----
📚 Documentation preview 📚: https://pep-previews--4500.org.readthedocs.build/
=> PEP 798: Small Typo Fix

peps/pep-0747.rst
When I was reading the PEP, it was unclear to me whether the rule on what expressions can implicitly evaluate to TypeForm applied to the rest of the PEP. This PR suggests pulling that rule out into its own section and linking to it the first time "valid type expression" is used, to make it clear that this definition applies throughout.
----
📚 Documentation preview 📚: https://pep-previews--4484.org.readthedocs.build/
=> PEP 747: Explicitly define "valid type expression".

peps/pep-0745.rst
Happy Pi Approximation Day!
https://discuss.python.org/t/python-3-14-release-candidate-1-is-go/99754
https://www.python.org/downloads/release/python-3140rc1/
----
📚 Documentation preview 📚: https://pep-previews--4506.org.readthedocs.build/
=> PEP 745: 3.14.0rc1 was released on 2025-07-22

.github/CODEOWNERS, peps/pep-0800.rst
----
📚 Documentation preview 📚: https://pep-previews--4505.org.readthedocs.build/
=> PEP 800: Solid bases in the type system

.github/CODEOWNERS, peps/pep-0799.rst
This bit wasn't too clear to me:
> The code that as the time of writing this is in `profile.sampling` module no longer exist and will only exist in the `profilers` package.
This PR suggests:
> The code that, at the time of writing, is in the `profile.sampling` module will be moved to the `profilers` package.
Is that the idea?
Alternatively:
> The code that, at the time of writing, is in the `profile.sampling` module will no longer exist and will instead only exist in the `profilers` package.
----
📚 Documentation preview 📚: https://pep-previews--4511.org.readthedocs.build/
=> PEP 799: clarifications

peps/pep-0799.rst
----
📚 Documentation preview 📚: https://pep-previews--4513.org.readthedocs.build/
=> PEP 799: Small clarifications about new sampling profiler

peps/pep-0750.rst
I moved the PEP 750 examples repository out of my personal GitHub account and into the [t-strings org](https://github.com/orgs/t-strings/repositories). This change updates the links in the PEP.
Stepping back: do we have a pattern for PEPs that link to example code? (Do we even _want_ external links like this in the PEP?)
----
📚 Documentation preview 📚: https://pep-previews--4514.org.readthedocs.build/
=> PEP 750: Update links to example code

peps/pep-0798.rst
This PR represents a few small wording changes for PEP 798 (primarily in the "How to Teach This" section) based on discussion from the Discourse thread, attempting to fix some correctness issues and to clarify some points.  It also fixes syntax highlighting for the examples from other languages.
----
📚 Documentation preview 📚: https://pep-previews--4518.org.readthedocs.build/
=> PEP 798: Fixes and Clarifications from Discourse Thread

peps/pep-0790.rst
3.14 beta 1 was released on Wednesday 7 May: https://peps.python.org/pep-0745/#schedule
A
----
📚 Documentation preview 📚: https://pep-previews--4528.org.readthedocs.build/
=> PEP 790: Record actual date for start of 3.15 development

peps/pep-0791.rst
* emphasize: no backward-incompatible changes
* expand history of the proposal
* Motivation: what people should expect about factorial() output?
* add n_div() proposal, rename ceil_div() like gmpy2
----
📚 Documentation preview 📚: https://pep-previews--4522.org.readthedocs.build/pep-0791/
=> PEP 791: address PEP review comments (part 2)

peps/pep-0802.rst
Added the reference implementation, expanded and added some rejected ideas, added a brief note to backwards compatibility.
A
----
📚 Documentation preview 📚: https://pep-previews--4537.org.readthedocs.build/
=> PEP 802: Add Reference Implementation, expand Rejected Ideas

peps/pep-0745.rst
Because of the magic number bump:
* https://discuss.python.org/t/early-3-14-0-rc2-and-extra-rc3/102151
* https://discuss.python.org/t/heads-up-pyc-magic-number-change-in-3-14-0rc2/102095
We're planning on making an early RC2 release this Thursday, and will add an extra RC3 about midway between RC2 and final (during the core sprint).
----
📚 Documentation preview 📚: https://pep-previews--4544.org.readthedocs.build/
=> PEP 745: Move RC2 earlier and add RC3

peps/pep-0794.rst
Also fix a couple critical typos.
----
📚 Documentation preview 📚: https://pep-previews--4545.org.readthedocs.build/
=> PEP 794: Clarify the default action when `Import-Name` et. al. are not specified

peps/pep-0719.rst, peps/pep-0745.rst
* https://discuss.python.org/t/python-3-14-0rc2-and-3-13-7-are-go/102403
* https://www.python.org/downloads/release/python-3140rc2/
* https://www.python.org/downloads/release/python-3137/
----
📚 Documentation preview 📚: https://pep-previews--4546.org.readthedocs.build/
=> PEP 745 & 719: Python 3.14.0rc2 and 3.13.7 were released on 2025-08-14

peps/pep-0750.rst
Part of https://github.com/python/peps/issues/4437
----
📚 Documentation preview 📚: https://pep-previews--4551.org.readthedocs.build/
=> PEP 750: Mark as Final

peps/pep-0503.rst, peps/pep-0691.rst
These PEPs have long since been canonicalized in the "Simple repository API" 🙂 
----
📚 Documentation preview 📚: https://pep-previews--4558.org.readthedocs.build/
=> PEP 503 & PEP 691: Link to PyPA specifications

pep_sphinx_extensions/pep_theme/templates/page.html
Prior art: https://github.com/python/cpython/commit/9cbf46d9920c269fe736ed689236d00223545f73
----
📚 Documentation preview 📚: https://pep-previews--4561.org.readthedocs.build/
=> Link to plain text PEPs for 'Page Source'

peps/pep-0794.rst
Also explicitly say that `Import-Name` may be empty.
----
📚 Documentation preview 📚: https://pep-previews--4567.org.readthedocs.build/
=> PEP 794: Introduce a way to specify private import names

peps/pep-0794.rst
Just clarifying a few points.
----
📚 Documentation preview 📚: https://pep-previews--4571.org.readthedocs.build/
=> PEP 794: Address comments

peps/pep-0794.rst
----
📚 Documentation preview 📚: https://pep-previews--4576.org.readthedocs.build/
=> PEP 794: Weaken the suggestion to use a project's name when `Import-Name` isn't set

peps/pep-0798.rst
The main change here is adjusting the proposed semantics of unpacking in generator expressions and adding a section briefly outlining the pros and cons of the alternatives, but I also:
* added a link to a Reddit thread I stumbled upon, which was quite positive about the PEP (not sure if this is actually worth including or not), and
* made several small wording/grammar/spelling changes.
----
📚 Documentation preview 📚: https://pep-previews--4547.org.readthedocs.build/
=> PEP 798: Add Discussion of Alternative GenExp Semantics

peps/pep-0351.rst
This PEP was originally in plaintext and when it got converted to reStructuredText format, the formatting became suboptimal.  Found by @larryhastings
For historical purposes, no substantive changes have been made.
----
📚 Documentation preview 📚: https://pep-previews--4589.org.readthedocs.build/
=> PEP 351: Fix RST formatting that got lost in translation

peps/pep-0768.rst
`Py_MAX_SCRIPT_PATH_SIZE` was made private in https://github.com/python/cpython/pull/138350. This adjusts the the PEP to match the implementation.
@pablogsal, you probably know best if this needs formal SC approval :)
----
📚 Documentation preview 📚: https://pep-previews--4591.org.readthedocs.build/
=> PEP 768: Remove Py_MAX_SCRIPT_PATH_SIZE

peps/pep-0788.rst
----
📚 Documentation preview 📚: https://pep-previews--4521.org.readthedocs.build/pep-0788/
=> PEP 788: Address feedback from the C API WG

peps/pep-0725.rst
This also references PEP 804 (see gh-4572), which address one of the most significant open issues about external dependency names needing to be curated and have canonical versions, rather than accepting everything that parses as a valid package URL. Hence these two PEPs now cross-reference each other. PEP 725 contains the packaging metadata, and PEP 804 the machinery and process around how that metadata is curated and can be queried, mapped, etc.
Cc'ing co-authors: @pradyunsg @jaimergp  
----
📚 Documentation preview 📚: https://pep-previews--4573.org.readthedocs.build/
=> PEP 725: version 3, address all feedback and open issues

peps/pep-0782.rst
----
📚 Documentation preview 📚: https://pep-previews--4590.org.readthedocs.build/
=> PEP 782: Add canonical doc link

peps/pep-0803.rst
- Use the more explicit tag `abi3.abi3t` to allow possibly expanding compatibility to 3.14
- Turn `Py_SIZE` & `Py_SET_SIZE` to functions, don't remove them
- Add a table of compatibiity between extensions & interpreters
- 2 more of the steps are now implemented. (They make sense on their own and are small enough to not need a PEP, but it does make sense to “collect” them in the PEP.)
----
📚 Documentation preview 📚: https://pep-previews--4594.org.readthedocs.build/
=> PEP 803: Updates based on Discourse discussion

peps/pep-0679.rst
----
📚 Documentation preview 📚: https://pep-previews--4600.org.readthedocs.build/
=> PEP 679: Updates based on Discourse discussion

peps/pep-0804.rst
----
📚 Documentation preview 📚: https://pep-previews--4605.org.readthedocs.build/
=> PEP 804: Add link to DPO thread

peps/pep-0806.rst
Adds a link to https://discuss.python.org/t/103971/ to discuss the draft.
----
📚 Documentation preview 📚: https://pep-previews--4609.org.readthedocs.build/
=> PEP 806: add Discuss link

peps/pep-0725.rst
----
📚 Documentation preview 📚: https://pep-previews--4604.org.readthedocs.build/
=> PEP 725: Add 2nd PEP Discussion to Post-History

peps/pep-0763.rst
As the PEP's author, I'm marking PEP 763 as withdrawn -- I think that the overall approach defined in this PEP makes sense, but I don't think there's a clear route to acceptance here that can surmount procedural problems with this being a PEP versus a matter of PyPI policy (like account management, AUPs, malware, quotas, etc.).
----
📚 Documentation preview 📚: https://pep-previews--4601.org.readthedocs.build/
=> PEP 763: Mark as Withdrawn

peps/pep-0788.rst
----
📚 Documentation preview 📚: https://pep-previews--4620.org.readthedocs.build/pep-0788/
=> PEP 788: New round based on discussion

peps/pep-0788.rst
----
📚 Documentation preview 📚: https://pep-previews--4630.org.readthedocs.build/pep-0788/
=> PEP 788: Rename functions based on discussion feedback

peps/pep-0810.rst
----
📚 Documentation preview 📚: https://pep-previews--4628.org.readthedocs.build/
=> PEP 810: Address discuss comments

peps/pep-0810.rst
It's currently rendered as a block quote, see the ordered list above for comparison:
----
📚 Documentation preview 📚: https://pep-previews--4631.org.readthedocs.build/pep-0810/#making-lazy-imports-find-the-module-without-loading-it
=> PEP 810: fix formatting

peps/pep-0810.rst
----
📚 Documentation preview 📚: https://pep-previews--4638.org.readthedocs.build/
=> PEP 810 - Fix typos

peps/pep-0810.rst
----
📚 Documentation preview 📚: https://pep-previews--4636.org.readthedocs.build/
=> PEP 810: Updates based on feedback

peps/pep-0810.rst
Add lazy objects to the spec, and also clarify what happens when reification fails and tweak some of the language.
----
📚 Documentation preview 📚: https://pep-previews--4643.org.readthedocs.build/
=> PEP 810: Add lazy objects to the spec.
